### ISSUE TITLE
support postActiv

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#10]
haven't looked into it much yet. evidently a GNU Social fork? not sure how widely used it is. the main https://postactiv.com/ site is currently down. https://www.patreon.com/postActiv has some info, including claims that it supports both OStatus and ActivityPub.

**Comment by aciccarello** [comment]
I think this project is no longer active and this issue can be closed.

**Comment by snarfed** [comment]
Confirmed, thanks!
