### ISSUE TITLE
Possible idea: Auto thread or graceful truncation with link backs of posts over 300 characters

### ISSUE THREAD

**Issue by StarrWulfe** [snarfed/bridgy-fed#1002]
Because of Bluesky's hard limit of 300 characters per post, the following idea was suggested:

>BridgyFed for the Fediverse should post as threads if the post exceeds 300 characters. Now it just truncates 500 char posts and people have no idea about the rest of it without any link or context. I know it’s early, but this would be great. -- [@rolle@mementomori.social]( https://mementomori.social/@rolle) [via fediverse](https://mementomori.social/@rolle/112387861446639752)
>>Yep! I only noticed this earlier today.
I'm also thinking, if it's not possible to thread it, a link back to the original post.
It's a good future feature! ^_^[@youronlyone@c.im](https://c.im/@youronlyone) [via fediverse](https://c.im/@youronlyone/112387871865643069)

Maybe some sort of graceful truncation/linkback or auto-threading not unlike how some of the old Twitter thread posting services or even SMS message handlers do, would be a good feature when posting to Bsky and other platforms with hard character counts. (ActivityPub doesn't have a message transmission limit; these are simply Mastodon constructs in the inputting of messages at some instances, so it's not needed there I believe.)

**Comment by revpriest** [comment]
For me, a link like:

...[Continued: boing.world/@pre/123] 

would be my preferred thing really. I don't like breaking text into threads much at the best of times even with it's planned and happens at paragraph breaks. This is why I can't follow cory. 

Robots/scripts don't break up text into threads well either, they do it badly.

**Comment by snarfed** [comment]
Yup! This is #986.
