### ISSUE TITLE
Invalid JSON-LD context in `https://bsky.brid.gy/bsky.brid.gy`

### ISSUE THREAD

**Issue by grishka** [snarfed/bridgy-fed#1003]
The JSON-LD context for the ActivityPub actor has the "security" namespace duplicated:

```json5
{
  "@context": [
    "https://www.w3.org/ns/activitystreams",
    "https://w3id.org/security/v1",
    "https://w3id.org/security/v1"
  ],
/* ... */
}
```

Since Smithereen is way too pedantic with JSON-LD processing, this causes a "recursive context inclusion" error when this object is expanded for conversion to my local context.

**Comment by snarfed** [comment]
True! Thanks for the catch.
