### ISSUE TITLE
AP => Bluesky: reply to reply didn't set root separate from parent

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#1007]
Reported by @mackuba, thanks again!

> wrong reply root uri set (it's set to the same as parent, even though parent wasn't the root)
> https://bsky.app/profile/BeAware.social.beaware.live.ap.brid.gy/post/3krjdlcvw3sh2
> notice that the second reply ("Yo" from RxBrad) is shown as having 2 replies in the status line, but there's only one direct reply visible
> there's a second reply from OP (BeAware) that's not visible on bsky.app
> root should be at://did:plc:l7l5l65nk5aogxmspxaqd5go/app.bsky.feed.post/3krjdlcvw3sh2 and not at://did:plc:zy5eyl3a7ut4vxzfjjdtysh2/app.bsky.feed.post/3krje5fbm332r

**Comment by mackuba** [comment]
I was just going to add it here :) but I have a few more 😈

**Comment by mackuba** [comment]
Another example from today: https://bsky.app/profile/shreyan.hachyderm.io.ap.brid.gy/post/3krr43qa7pzk2

**Comment by snarfed** [comment]
Fixed! Example: https://indieweb.social/@snarfed/112452723190652012 => https://bsky.app/profile/snarfed.indieweb.social.ap.brid.gy/post/3ksn3e5akcq42

...and phew, this was a project. Substantial refactoring to unify on granary's logic for populating strongRefs etc, but with our stored records. Thanks again for reporting @mackuba.
