### ISSUE TITLE
Mentions of bridged users in the fediverse sometimes link to actor id JSON

### ISSUE THREAD

**Issue by cybeardjm** [snarfed/bridgy-fed#1009]
I found & followed my bridged BS account ([@didiermary.fr@bsky.brid.gy](https://bsky.brid.gy/ap/did:plc:l2uv6ivfedhsjjmfmndx7p26)) from Pixelfed.
If I do a search for it in Pixelfed, it appears properly and I can view an empty profile (https://pixelfed.social/i/web/profile/692539545976601408).
But on this empty profile, if I click on the settings cog and select "view remote profile", I get a JSON page: https://bsky.brid.gy/ap/did:plc:l2uv6ivfedhsjjmfmndx7p26

**Comment by snarfed** [comment]
Interesting! And unfortunate. That's the ActivityPub acotr. Looks like Pixelfed is using the actor's `id` as the remote profile URL, when it should be using `url` (https://bsky.brid.gy/r/https://bsky.app/profile/didiermary.fr) instead, which works fine, and which other fediverse servers use. @dansup want us to file a Pixelfed bug?

**Comment by snarfed** [comment]
#1395 inspired me to look at this again. For a second, I thought the problem was multi-valued `url`s, but no. https://fed.brid.gy/snarfed.org has a bare string `url` value, and Pixelfed still links to its `id` instead, eg https://piconic.co/i/web/profile/505878279501544052 (requires login).

**Comment by snarfed** [comment]
Also, oddly, Mastodon does this too, but only for the bot users like @bsky.brid.gy@bsky.brid.gy? Eg https://mastodon.social/@tantek.com@tantek.com handles that fine and links you to the first value, but https://mastodon.social/@bsky.brid.gy@bsky.brid.gy links to the `id` value instead. Grr.

**Comment by snarfed** [comment]
cc @edent @jfietkau

**Comment by Tamschi** [comment]
I'll remove the `blocked` label since Bridgy Fed could work around this issue.

**Comment by snarfed** [comment]
Fixed! I think. Should be deployed in ~7m.

**Comment by Tamschi** [comment]
It works 👍
(Tested with the JSON link in the OP.)

**Comment by jfietkau** [comment]
Congrats, I've run into this problem a few times and this will help avoid confusion. 👍

With that cleared up, I believe there is something else going on in #1441 (and #1429) that might warrant another look. In both cases, the links in the posts were mentions that were supposed to lead to a local profile view on the user's server and not to the Bridgy Fed web view at all (the JSON response was just incidental). The submitter of #1429 is currently [continuing his investigation](https://hci.social/@alarith/113406854573047439) of the cause.

The local server is supposed to transform the tag into a local link, so the question is why it isn't doing that and whether anything about Bridgy Fed's AP output is the reason.

**Comment by snarfed** [comment]
@jfietkau yes! We've struggled with fediverse @-mentions in Bridgy Fed for many years #959, #493. (Hashtags were a similar years-long struggle, fwiw.) You're right, when BF bridges an @-mention into the fediverse, right now the receiving server only sometimes translates it into a local link to the profile, not always. I don't know why yet.

The next thing to try is probably #887. That seems maybe promising. However, honestly, this isn't a high priority for me right now, especially given how difficult and finicky it was to get @-mentions working in the fediverse (mainly Mastodon) at all.

Feel free to jump into #887 if you're interested though!
