### ISSUE TITLE
AP => Bluesky: hashtags that aren't in post text aren't well supported

### ISSUE THREAD

**Issue by cybeardjm** [snarfed/bridgy-fed#1010]
Posts containing hashtags, in a BS or Mastodon post, appear as inactive/passive text when bridged to the other platform.

**Comment by snarfed** [comment]
Hmm! Can you post an example? This worked for me in testing. Example: https://indieweb.social/@snarfed/112367193538259739 => https://bsky.app/profile/snarfed.indieweb.social.ap.brid.gy/post/3krh3x6wpkkv2 .

**Comment by cybeardjm** [comment]
Mastodon (original post): https://masto.ai/@cybeardjm/112389495275883834
BS (bridged): https://bsky.app/profile/cybeardjm.masto.ai.ap.brid.gy/post/3krqyth3lw6u2

**Comment by snarfed** [comment]
Ah, thanks! Yeah hashtags that aren't in the original post text, like this, aren't well supported. I'll look at those.

**Comment by mackuba** [comment]
There is actually support for "external" tags in the protocol already (a `tags` field in the `app.bsky.feed.post` lexicon), but it's still not finished in the UI so these tags don't show up even if you add them via API… but this is something that you could add once it's finished there. It's supposed to be displayed more or less like those on Mastodon. (Tags is just an array of strings like `["one", "two", "three"]`.)

There is a limit though that you can only add up to 8 of them, on Mastodon I think they're unlimited...

**Comment by AtiusAmy** [comment]
Hashtags don't seem to work for me as well.

Original post:
https://social.atiusamy.com/notes/9t24omz29sto0419

Bluesky post:
https://bsky.app/profile/AmyIsCoolz.social.atiusamy.com.ap.brid.gy/post/3krzh2wk2ljj2

**Comment by snarfed** [comment]
More sleuthing in https://github.com/snarfed/bridgy-fed/issues/980#issuecomment-2101885162

**Comment by snarfed** [comment]
This is the inverse of #1066.

**Comment by snarfed** [comment]
Fixed! Example: https://indieweb.social/@snarfed/112691845131190192 => https://bsky.app/profile/snarfed.indieweb.social.ap.brid.gy/post/3kvxbi5kjno72
