### ISSUE TITLE
ATProto => AP: second reply below reply doesn't get bridged

### ISSUE THREAD

**Issue by mackuba** [snarfed/bridgy-fed#1011]
See thread here: https://bsky.app/profile/shreyan.hachyderm.io.ap.brid.gy/post/3krr2zrynrgo2

- Shreyan posts on Masto, gets bridged to Bluesky ✅
- Laurens responds on Bluesky, is opted in => reply goes to Masto ✅ (seen here https://hachyderm.io/@shreyan/112389649962356627)
- I reply to Laurens, I'm also opted in => my reply doesn't go to Masto ⚠️
- separately, I reply to Shreyan (comment about cousin's daughters) => reply goes to Masto ✅
- I add a second reply below that comment ("Testing if this second reply goes through too") => this one doesn't appear on Masto ⚠️

**Comment by AtiusAmy** [comment]
I can say that I have experienced the same issue

**Comment by snarfed** [comment]
Thanks for filing! Heard this from someone else too. I think this is an easy one, `posts_no_replies` here should be `posts_with_replies`. If anyone's interested in trying out a small PR, just that fix plus updating tests, this is a great opportunity!

https://github.com/snarfed/bridgy-fed/blob/2cd38213f985da1d3a041b436d70cfa31ade91a7/atproto.py#L697
