### ISSUE TITLE
ATProto => AP: hashtags

### ISSUE THREAD

**Issue by mackuba** [snarfed/bridgy-fed#1013]
Here, `#atproto` is not a link:

<img width="602" alt="Screen Shot 2024-05-06 at 01 15 47" src="https://github.com/snarfed/bridgy-fed/assets/28465/d2fdd3f8-64f9-4588-ad49-a70fec4d9f07">

**Comment by snarfed** [comment]
Thanks! True. Original: https://bsky.app/profile/mackuba.eu/post/3krr7pybrf22w

I got them working AP => Bluesky in testing, https://github.com/snarfed/bridgy-fed/issues/980 , but evidently not Bluesky => AP.

**Comment by snarfed** [comment]
Fixed! Example: https://bsky.app/profile/snarfed.bsky.social => https://indieweb.social/@snarfed.bsky.social@bsky.brid.gy/112471647364648536 (requires login)
