### ISSUE TITLE
Refresh profiles when they follow bot users to opt in

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#1017]
Right now, when someone follows a bot user to opt in, if we already have a cached copy of their profile, we don't refresh it. We should, since they may have changed a setting like Bluesky's "hide from logged out views," which we interpret as opt out. Should be an easy fix.

**Comment by snarfed** [comment]
cc @ygalanter

**Comment by YuriGal** [comment]
Thanks for the quick reply!

**Comment by snarfed** [comment]
OK @ygalanter this fix should be deployed in ~5m or so, after that feel free to try unfollowing and re-following and see if it works.

**Comment by ygalanter** [comment]
Hm... Still doesn't se
![Screenshot 2024-05-06 at 3 41 18 PM](https://github.com/snarfed/bridgy-fed/assets/7891648/88f64002-59aa-40c9-a586-8a0573758329)
em to work. I am able to find Mastodon account on Bluesky, but it shows no posts, even new ones made after bridging. And I ca
![Screenshot 2024-05-06 at 3 40 25 PM](https://github.com/snarfed/bridgy-fed/assets/7891648/86122a71-120f-4c74-85e6-2e83b1418282)
n't find Bluesky account on Mastodon. Instance is https://hachyderm.io it doesn't seem to be blocking bridge servers.

**Comment by snarfed** [comment]
Ugh, ok, thanks. Reopening.

**Comment by hybridhavoc** [comment]
In this case would refreshing the account also mean updating things like display name and bio?

**Comment by snarfed** [comment]
Yup! Those kinds of profile changes should get bridged automatically, but you can also do a manual refresh with the 🔁 button on your user page.

**Comment by hybridhavoc** [comment]
> Yup! Those kinds of profile changes should get bridged automatically, but you can also do a manual refresh with the 🔁 button on your user page.

I'm not sure what you mean by user page. I went and took a look through the docs again and see some mentions of this, but most of the links don't seem to go anywhere. The one link that did took me to a form asking for my webpage, but it seems like that's intended for the web.brid.gy stuff.

I have tried unfollowing and refollowing bsky.brid.gy but that didn't seem to update the user profile on the Bluesky side to match.

**Comment by snarfed** [comment]
You're right that user pages aren't discoverable or documented well yet. Sorry! I've filed #1043 for that.

**Comment by snarfed** [comment]
Fixed the remaining bug here, and tested and confirmed. @ygalanter feel free to try again!

**Comment by YuriGal** [comment]
It works! Thanks 🙂

**Comment by yukimikudayo** [comment]
It works. Thank you.
