### ISSUE TITLE
Posts from one AP account federate to bsky, but another don't

### ISSUE THREAD

**Issue by minneyar** [snarfed/bridgy-fed#1018]
Apologies if this is the wrong place for general support, I looked around a little but didn't see any other options.

Details:
- I run a Sharkey instance at https://fuzzyfox.social/ and am testing bridging accounts with bsky.
- I have two accounts on my instance, @admin@fuzzyfox.social and @minneyar@fuzzyfox.social, both of which follow @bsky.brid.gy@bsky.brid.gy
- I have a bsky account at @minneyar.fuzzyfox.social that follows @ap.brid.gy, and it has followed both of those accounts via @admin.fuzzyfox.social.ap.brid.gy and @minneyar.fuzzyfox.social.ap.brid.gy
- Posts made from my bsky account show up on the Fediverse, and reactions to it federate across (see https://fuzzyfox.social/@minneyar.fuzzyfox.social@bsky.brid.gy)
- Posts made from @admin@fuzzyfox.social show up on bsky, and reactions to them federate across (https://bsky.app/profile/admin.fuzzyfox.social.ap.brid.gy)
   - As a side note, deleting posts seems to work fine even though bridgy-fed documentation seemed to indicate that wasn't working yet; I've made several more than federated across and then were removed when I deleted them in Sharkey

But my problem is that posts from @minneyar@fuzzyfox.social do *not* seem to federate to bsky.  The profile page exists (https://bsky.app/profile/minneyar.fuzzyfox.social.ap.brid.gy), but none of the posts I've made have appeared, even though posts from @admin@fuzzyfox.social and reactions from both accounts seem to be working.

Any ideas why posts aren't going across?

**Comment by minneyar** [comment]
Oh, interesting... it looked to me as though both counts were following each other, but I unfollowed from the bsky side and then followed again, and now posts are going through!

I forget the exact order of operations here, but I *think* I did:
1. Followed @bsky.brid.gy@bsky.brid.gy from Sharkey
2. Followed @minneyar.fuzzyfox.social.brid.gy from Bsky
3. Followed @ap.brid.gy from Bsky
4. Followed @minneyar.fuzzyfox.social@bsky.brid.gy from Sharkey

All of that would have been done in fairly quick succession, and I do think I followed from the Bsky side before opting-in from there.

**Comment by snarfed** [comment]
Glad this is working now!

**Comment by minneyar** [comment]
Hmm, it doesn't seem like it's *quite* working as expected yet; although an initial post went across, I've tried replying to it on both sides, and neither of the replies reached the other side.  For comparison:

https://bsky.app/profile/minneyar.fuzzyfox.social.ap.brid.gy/post/3krt6ht4yzpu2
https://fuzzyfox.social/notes/9sykg2gdd4j1008c

**Comment by snarfed** [comment]
Are the replies from accounts that have opted in?

Also, for Bluesky => AP, there's a delay: https://fed.brid.gy/docs#bluesky-delay => Bluesky, 

Oh btw @minneyar on an unrelated note, your instance instance fuzzyfox.social is a bit infamous on my side. A ton of other instances have been hammering `/.well-known/webfinger?resource=acct:instance.actor@fuzzyfox.social` on Bridgy Fed for weeks now, averaging 1-2qps total. Any idea why?

**Comment by minneyar** [comment]
Yep, both accounts have opted in, and the replies are both from my accounts that have followed each other.  It's been about an hour now, which I thought would've been long enough for the delay.

But that's weird, I honestly have no idea why that would be happening!  I believe the `instance.actor` account is a bot created by Misskey when joining relays; I've joined several large relays in the past, although I also left a few that I was constantly getting errors from.  Could those requests be somehow related to that?

**Comment by snarfed** [comment]
Missing replies from Bluesky is probably #1011. If that's the main outstanding problem here, I'm going to tentatively merge this into that issue.

**Comment by minneyar** [comment]
Yep, I think that is the same issue I'm seeing now, so feel free to merge it.

Other instances hammering your webfinger looking for info about my instance also seems like an issue, but this probably isn't the right place to track that...

**Comment by snarfed** [comment]
Deployed a change for this and #1011, should hopefully fix self replies and other non-notif replies. Thanks again for reporting!
