### ISSUE TITLE
AP: DM contents appear publicly in bridge's "activity" tab

### ISSUE THREAD

**Issue by qazmlp** [snarfed/bridgy-fed#1022]
See #1019. The `@bsky.bird.gy Hi bot.` text appears publicly on their bridge page in the "activity" tab.

The entry also leaks the original URL of the DM, both directly and in the timestamp link to Bridgy's log, though the Bridgy log itself appears to be missing or private.

I don't know if this is a general issue or happened because the DM was directed to a service account specifically.

**Comment by snarfed** [comment]
Great catch! Absolutely a bug, DMs should be hidden even if they're to a bot user. Will fix.

**Comment by snarfed** [comment]
Fix should be deployed in ~5m. Thanks again for reporting. Making sure we only handle public data is [part of safety and security, one of Bridgy Fed's key development values](https://fed.brid.gy/docs#values). This only happened for DMs to our own bot users, which we special cased and considered public for the purposes of handling follows (and DMs of "yes" or "ok") to opt in, but still, they shouldn't have been shown publicly. May seem minor, but still an important fix, at least for me.
