### ISSUE TITLE
Accounts not bridging

### ISSUE THREAD

**Issue by mary-ext** [snarfed/bridgy-fed#1026]
Heya! I remember opting out of the Bluesky to AP bridge a while back for `@mary.my.id` (`did:plc:ia76kvnndjutgedggx2ibrem`) and now I want to opt-in again, if it's still being respected.

This isn't all however, it seems that my fedi account, `@mary-ext@wetdry.world` isn't bridging properly? It grabbed my profile, but no posts or changes to the profile are coming through.

I wonder if it's because I had the account to require manual follower approval initially and that got it into a weird state or something. I've removed that approval now but I still haven't seen any come through, even after refollowing the bot, no confirmation via direct messages either.

Cheers!

**Comment by snarfed** [comment]
Hi Mary! I've removed the opt out for your Bluesky account, feel free to try following @ap.brid.gy to opt in.

As for https://fed.brid.gy/ap/@mary_ext@wetdry.world , your instance won't send us your posts until at least one person follows you across the bridge. We're working on fixing that in #999.

**Comment by mary-ext** [comment]
Unfollowed and followed again, let's see if it works....

**Comment by mary-ext** [comment]
Bluesky to AP bridge works, awesome!

Would me following my AP account from Bluesky fix the problem?

**Comment by mary-ext** [comment]
Oh! Looks like it's working now, thank you! I'll close this issue since everything's been resolved
