### ISSUE TITLE
Images missing when viewing Bluesky posts on Mastodon

### ISSUE THREAD

**Issue by docpop** [snarfed/bridgy-fed#1029]
It appears that images are not being displayed when viewing a bridged bluesky account on Mastodon. For example, here is the original post on Bluesky:=
<img width="590" alt="Screenshot 2024-05-06 at 5 43 37 PM" src="https://github.com/snarfed/bridgy/assets/5455256/3911303a-7e8a-4ae3-9923-88f2ed2bb01f">

And here is how it appears on the bridged account on Mastodon. 
<img width="582" alt="Screenshot 2024-05-06 at 5 43 22 PM" src="https://github.com/snarfed/bridgy/assets/5455256/886b4ee2-701f-4ab2-bad3-b906e39348ef">

**Comment by snarfed** [comment]
Yes! Sorry for the trouble. This is https://github.com/snarfed/bridgy-fed/issues/1000, merging in there.
