### ISSUE TITLE
Turn on web => Bluesky self serve

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#1034]
Very straightforward! Just need to turn it on.

**Comment by JoshuaHolme** [comment]
Very much looking forward to this 👀

**Comment by JoshuaHolme** [comment]
Is there a way to do this and you're just waiting on adding the entry point to the front page? Or is there not the functionality yet?

**Comment by snarfed** [comment]
Just waiting. I have my hands more than full triaging and bug fixing fediverse <=> Bluesky bridged accounts and content right now, I haven't had the bandwidth to add on the same triage and bug fixes for web <=> Bluesky yet. You're welcome to beta test it if you want though, as long as you don't mind rough edges? What's your web site that you want to bridge?

**Comment by JoshuaHolme** [comment]
https://electrek.co would be cool to test. Liked following their stuff on Twitter, they haven't been active on bluesky

**Comment by snarfed** [comment]
Done! @JoshuaHolme feel free to follow https://bsky.app/profile/electrek.co.web.brid.gy .

Updating docs now...

**Comment by snarfed** [comment]
...and funny, looks like Electrek was already on Bluesky:
https://bsky.app/profile/electrek.bsky.social
https://bsky.app/profile/electrek-mirror.bsky.social

**Comment by JoshuaHolme** [comment]
They have an account but aren't active on it. Also I was running that mirror but they kept posting things that would break the mirror, so I kinda gave up on that mirror 😅 . 

Any way to get the post cards to show a preview? The weird thing is if I copy the link and paste it into the post composer it will create the preview, so it seems to be using an appropriate link for it. Some posts show `Original post on electrek.co` and some just show a `more...` hyperlink

**Comment by snarfed** [comment]
The _Original post on electrek.co_ links are previews/embeds! They're just missing a picture. BF doesn't currently detect and extract OGP images for posts, which is probably what it would need to do. Feel free to file a feature request!

The _more..._ links are from Electrek's RSS feed itself. It only contains article snippets and those links. Bridgy Fed keeps it if the whole thing (snippet + more link) fits in Bluesky's 300 char limit. If it doesn't, BF truncates it and adds the _Original post..._ embed.
