### ISSUE TITLE
URL Links from BlueSky are truncated & broken on Fediverse

### ISSUE THREAD

**Issue by rxbrad** [snarfed/bridgy-fed#1039]
When a link is posted on BlueSky, the version of that link that gets bridged to the Fediverse has the http:// or https:// removed, and is also truncated for length. 

Example: https://mastodon.rxbrad.com/@jeffgerstmann.com@bsky.brid.gy/112411851554117791

Original:
https://bsky.app/profile/jeffgerstmann.com/post/3ks2wbwuqsl2k

Post text on Mastodon:
I have gone against the advice of my physicians and I have played and ranked all 52 games found on the Action 52 cart for the NES. I hope you can benefit from this research. www.youtube.com/watch?v=tEeS...

**Comment by snarfed** [comment]
Yes! Sorry for the trouble. This is #993.
