### ISSUE TITLE
Bridgy Fed Website: Form Input Text Color - A11y

### ISSUE THREAD

**Issue by miklb** [snarfed/bridgy-fed#1042]
Using Safari 17.5 when you begin to type your domain into the sign-in form the text color matches the input background color.

Setting an explicit `color: black` on `form input` in `style.css` (line 300) in dev tools resolved the issue, though I didn't investigate any other forms or browsers.

**Comment by snarfed** [comment]
Oof, embarrassing! Thanks for reporting. Fix should be deployed in ~5m!
