### ISSUE TITLE
Links don't transfer properly from Bluesky to Mastodon

### ISSUE THREAD

**Issue by nohillside** [snarfed/bridgy-fed#1044]
Looks like links don't get copied proberly from Bluesky to Mastodon:

- Original post https://bsky.app/profile/nohillside.ch/post/3ks5ylri4b226

> You can’t make this shit up!
> https://www.newsweek.com/richest-americans-pay-less-tax-working-class-1897047

- Bridged post is in @nohillside.ch@bsky.brid.gy (can't link because the link points back to Bluesky) and only shows

> You can’t make this shit up! www.newsweek.com/richest-amer...

basically only a shortened link which obviously doesn't work.

![SCR-20240511-htrk](https://github.com/snarfed/bridgy-fed/assets/873972/6d5bcb00-7a6f-4ff0-908e-c449b89c0fd9)

**Comment by snarfed** [comment]
Yes! Sorry for the trouble. This is #993.
