### ISSUE TITLE
Bad Request No web user for domain



### ISSUE THREAD

**Issue by Fauli1221** [snarfed/bridgy-fed#1045]
When trying to unfollow a Bluesky account that wasn't Bridged (managed that though an outdated cache on my instance) though [fed.brid.gy](https://fed.brid.gy/ap/@fauli1221@hooves.social/following) after logging into and authorizing with github I get redirected to https://fed.brid.gy/unfollow/start which displays ![Screenshot_20240511-131824_1.png](https://github.com/snarfed/bridgy-fed/assets/43648117/b37561b8-18f7-4d10-b09e-6ce0ed98979f)

My fedi profile is https://hooves.social/@fauli1221 
The software my instance is using is Firefish

**Comment by snarfed** [comment]
Hah, thanks for reporting. Silly bug on our end, the follow/unfollow UI on fed.brid.gy user pages is only for web users, not fediverse or Bluesky users. I'll remove it.
