### ISSUE TITLE
support Sharkey (?)

### ISSUE THREAD

**Issue by AtiusAmy** [snarfed/bridgy-fed#1050]
bsky account (That already opted in) who follows me on bsky are not shown in AP 

Followers in Bsky:
https://bsky.app/profile/AmyIsCoolz.social.atiusamy.com.ap.brid.gy/followers

However, those people are not reflected here:
https://social.atiusamy.com/@AmyIsCoolz/followers

Basically it means that I wont be notified when someone follows me-

**Comment by snarfed** [comment]
Hmm, sorry! Looks like this might be a Sharkey incompatibility. We sent AP `Follow`s for these, eg here's an example delivered to https://social.atiusamy.com/users/9pa2kavedh4b000l/inbox at 2024-05-06T10:04:55.611402467Z, which responded with HTTP 202. Maybe check your logs for that follow and see what happened?

```json
{
  "id": "https://bsky.brid.gy/convert/ap/at://did:plc:f5zr3e7halsgw656altvzvhq/app.bsky.graph.follow/3krssgj2kna23",
  "actor": "https://bsky.brid.gy/ap/did:plc:f5zr3e7halsgw656altvzvhq",
  "@context": "https://www.w3.org/ns/activitystreams",
  "type": "Follow",
  "object": "https://social.atiusamy.com/users/9pa2kavedh4b000l",
  "to": [
    "https://www.w3.org/ns/activitystreams#Public"
  ]
}
```

**Comment by AtiusAmy** [comment]
I'm gonna check the logs in a bit, but another thing I noticed is that replies don't seem to be bridged either which is weird

https://bsky.app/profile/amyiscoolz.bsky.social/post/3ksgs4ipdzd2y

Looking at the post on Fedi however, I see no such reply
https://social.atiusamy.com/notes/9t91bh90hppt0140

The Logs are quite long so I'm gonna attach it as a text file
[Uploading Sharkey.txt…]()

**Comment by qazmlp** [comment]
It seems unusual to include the `"to"` property here, but that alone really shouldn't be enough to break anything…

**Comment by AtiusAmy** [comment]
wdym by private or public

**Comment by snarfed** [comment]
I'm guessing he meant the actor's inbox vs the shared inbox. These are sent to the actor's inbox; details in https://github.com/snarfed/bridgy-fed/issues/1050#issuecomment-2109274504.

**Comment by qazmlp** [comment]
> I'm guessing he meant the actor's inbox vs the shared inbox. These are sent to the actor's inbox; details in https://github.com/snarfed/bridgy-fed/issues/1050#issuecomment-2109274504.

Sorry, 'shared inbox' yes. Thanks for the clarification.

**Comment by AtiusAmy** [comment]
![image](https://github.com/snarfed/bridgy-fed/assets/136548767/1e19af54-3909-48d1-a184-f93e148e6f07)
Not sure what happened here but the bridge begins bridging follow now? pretty goofy

**Comment by snarfed** [comment]
@AtiusAmy looks like Sharkey interop may now be working? I successfully liked https://social.atiusamy.com/notes/9vk6cxn1o1fo005k just now, and posts are flowing through to https://bsky.app/profile/AmyIsCoolz.social.atiusamy.com.ap.brid.gy

**Comment by AtiusAmy** [comment]
> @AtiusAmy looks like Sharkey interop may now be working? I successfully liked https://social.atiusamy.com/notes/9vk6cxn1o1fo005k just now, and posts are flowing through to https://bsky.app/profile/AmyIsCoolz.social.atiusamy.com.ap.brid.gy

Seems that way. Not sure what fixed it though

**Comment by snarfed** [comment]
🤷

...regardless, glad it's working!
