### ISSUE TITLE
Also bridge Bluesky accounts that have both opted in and have the "discourage visibility in logged out view" ?

### ISSUE THREAD

**Issue by DoktorZjivago** [snarfed/bridgy-fed#1052]
A fairly large portion of the Bsky accounts have checked the box to "discourage other apps to make the account visible in the logout view". But since they have actively opted in by following the bridge account, is it possible to consider bridging just those accounts anyway?

**Comment by snarfed** [comment]
Yeah this is a good point. I did this for fediverse accounts in https://github.com/snarfed/bridgy-fed/issues/974, and I should consider in it for Bluesky accounts too. Thanks for filing.

**Comment by DoktorZjivago** [comment]
Yes, I have primarily monitored the Swedish accounts signing up for the bridge and I would say about 20 to 25% maybe?

**Comment by snarfed** [comment]
Fix (I hope) for this should be deployed in ~5m, feel free to try after that!

**Comment by DoktorZjivago** [comment]
It's working! :)

**Comment by DoktorZjivago** [comment]
As an example, here are a few accounts that started to bridge after this change today (may 15)

vingadeyeliner.bsky.social@bsky.brid.gy

@missriktad.bsky.social@bsky.brid.gy

@factitia.bsky.social@bsky.brid.gy

@missomniana.bsky.social@bsky.brid.gy

@fridahylander.bsky.social@bsky.brid.gy

And here are a few bluesky accounts (including my own) still not bridging:

@frozenbride.bsky.social

@doktorzjivago.bsky.social

@camillamalm.bsky.social

@christian.internetsladd.se

@sockeranna.bsky.social

@andreaslindholm.bsky.social

**Comment by snarfed** [comment]
Thanks! And sorry, I forgot to mention, if these accounts had "hide from logged out views" on when they followed @ap.brid.gy, they'll need to unfollow and re-follow it to enable the bridge.

**Comment by DoktorZjivago** [comment]
Yes! That did the trick for my account. Thanks! 😊
