### ISSUE TITLE
Pixelfed account not bridged (didn't receive follow from bridgy account) 

### ISSUE THREAD

**Issue by TomCasavant** [snarfed/bridgy-fed#1053]
https://pixelfed.social/i/web/profile/514094858804573417

I followed the @bsky.brid.gy account and it successfully created the corresponding bluesky account (@mrpresidenttom.pixelfed.social.ap.brid.gy) but there don't appear to be any federated posts.

It looks like my pixelfed account never got followed by the bridgy account so that's probably where the issue is, unfortunately it's not my server so I don't have any logs from it.

**Comment by snarfed** [comment]
Sorry for the trouble! Pixelfed evidently still has some AP compatibility issues, we're tracking in https://github.com/snarfed/bridgy-fed/issues/39. Following up there.

**Comment by TomCasavant** [comment]
> Sorry for the trouble! In this case, you're right that your server needs to accept the bridge account's follow before it will start sending us your posts. Pixelfed evidently still has some AP compatibility issues, we're tracking in #39. Following up there.

Out of curiosity, should it still be creating the bluesky account even if the opt-in process didn't complete? (I guess the important part of the process completed w/ me following @bsky.brid.gy)

**Comment by snarfed** [comment]
Right. Not clear to me either which way is better. 🤷‍♂️
