### ISSUE TITLE
ATProto -> Bluesky reply not showing up.

### ISSUE THREAD

**Issue by enn-nafnlaus** [snarfed/bridgy-fed#1054]
From Bluesky (reply sent):

https://bsky.app/profile/nafnlaus.fosstodon.org.ap.brid.gy/post/3kshl3gchjir2
![image](https://github.com/snarfed/bridgy-fed/assets/116288799/a69f835a-9946-41a2-aa8c-258d207b5040)

From Mastodon (zero replies):

https://fosstodon.org/@nafnlaus/112440319139365705
![image](https://github.com/snarfed/bridgy-fed/assets/116288799/cba976cf-1697-4125-b4a5-9fad4e82da4e)

I'm following Bridgy from both Masto and Bluesky.  All other variants work:

* Post, from Bluesky to Masto
* Post, from Masto to Bluesky
* Reply, from Masto to Bluesky on a post that went from Bluesky to Masto

**Comment by snarfed** [comment]
Oops! Thanks for the nudge, bug on our side, missed some events. Fixed now, feel free to try again!

**Comment by enn-nafnlaus** [comment]
> Oops! Thanks for the nudge, bug on our side, missed some events. Fixed now, feel free to try again!

Seems fixed, thanks!  :)
