### ISSUE TITLE
Better handling of user handles

### ISSUE THREAD

**Issue by enn-nafnlaus** [snarfed/bridgy-fed#1056]
Note how handles are translated within the text of posts:

First, viewed from the Mastodon side - a post (parent) written on Mastodon, referencing first a Mastodon user (@nafnlaus@fosstodon.org), then their bridged Bluesky account (@nafnlaus.bsky.social@bsky.brid.gy).  The reply comes in over the bridge from Bluesky

https://fosstodon.org/@nafnlaus.bsky.social@bsky.brid.gy/112444275462951591
![image](https://github.com/snarfed/bridgy-fed/assets/116288799/4676d8eb-c465-4e47-ac5c-d948dadbb043)

Now, from the Bluesky side - the parent came in over the bridge from Mastodon, and a reply post is written on Bluesky, first referencing a Bluesky user (@nafnlaus.bsky.social), then their bridged Mastodon account (@nafnlaus.fosstodon.org.ap.brid.gy):

https://bsky.app/profile/nafnlaus.bsky.social/post/3ksjdcazrck2y
![image](https://github.com/snarfed/bridgy-fed/assets/116288799/2f3809d8-0f53-4bd5-b550-2f30edf63fed)

To sum up:

References written on Mastodon, as viewed on Bluesky:

**Reference to a native Mastodon account**: Links to the bridged Mastodon account (image #2, parent post). This is **_okay_** behavior, though even better would be, if both sides are bridged, to link to the user's normal Bluesky account.

**Reference to bridged Bluesky account on Mastodon**: Just shows up as plaintext (image #2, parent post). This is **_bad_** behavior; it should at least link to the user's bridged account on Bluesky, though ideally, their normal Bluesky account.

References written on Bluesky, as viewed on Mastodon:

**Reference to a native Bluesky account**: Just shows up as plaintext (image #1, reply post). This is **_bad_** behavior; it should at least link to the user's bridged account on Mastodon, though ideally, their normal Mastodon account.

**Reference a bridged Mastodon account on Bluesky**: Just shows up as plaintext (image #1, reply post). This is **_bad_** behavior; it should at least link to the user's bridged account on Mastodon, though ideally, their normal Mastodon account.

---

I would more to the point add that if the user links to someone's account on Mastodon or Bluesky, even if they're *not* a bridged user, it should still translate their handle as if they were - in case they were to join at a later date.

**Comment by snarfed** [comment]
Yes! Sorry, you're right, bridged @-mentions are currently buggy, those bugs are tracked in https://github.com/snarfed/bridgy-fed/issues/959 and https://github.com/snarfed/bridgy-fed/issues/957.

> I would more to the point add that if the user links to someone's account on Mastodon or Bluesky, even if they're not a bridged user, it should still translate their handle as if they were - in case they were to join at a later date.

Interesting idea! The catch is that on both sides, in the underlying data, @-mentions are more than just plaintext. In Bluesky, they're based on the bridged account's DID, which we don't know until we create it. And in the fediverse, they're HTML links and `Mention` tags, which will result in confusing UX if the mentioned account doesn't exist yet.

Regardless, Bridgy Fed can definitely do better than it does now. Feel free to follow the issues above!
