### ISSUE TITLE
Cant bridge the bluesky account to fediverse

### ISSUE THREAD

**Issue by yemyatthu-binlab** [snarfed/bridgy-fed#1057]
I have followed @ap.brid.gy Bluesky bot and wait almost 24 hr, and yet I still cant find my bridged bluesky account in fediverse (tried searching it from mastodon).I have never enabled the **hide account in logout view** and my acc name is also different from bluesky handle. Is there any thing that i have missed to do? Here is my bluesky account - `@ymt-binlab.bsky.social`.

**Comment by snarfed** [comment]
Hmm, I see your bridged account @ymt-binlab.bsky.social@bsky.brid.gy on the indieweb.social Mastodon instance. Is your instance blocking Bridgy Fed?

**Comment by yemyatthu-binlab** [comment]
Thanks sir, it appear in our instance too now, can u explain one thing to me, is bridge account instantly created after we follow the bluesky bot? or is there some sort of delay before creating bridge account? if so, what might be the average delay time?

**Comment by snarfed** [comment]
Glad to hear it! There used to be a 5-15m delay, but I got rid of that a few days ago. It should now be realtime, say, within 10s or so.
