### ISSUE TITLE
Some but not all bsky accounts bridge after including the "logout view" ones

### ISSUE THREAD

**Issue by DoktorZjivago** [snarfed/bridgy-fed#1058]
As an example, here are a few accounts that started to bridge after this change today (may 15)

@vingadeyeliner.bsky.social@bsky.brid.gy

@missriktad.bsky.social@bsky.brid.gy

@factitia.bsky.social@bsky.brid.gy

@missomniana.bsky.social@bsky.brid.gy

@fridahylander.bsky.social@bsky.brid.gy

And here are a few bluesky accounts (including my own) still not bridging:

@frozenbride.bsky.social

@doktorzjivago.bsky.social

@camillamalm.bsky.social

@christian.internetsladd.se

@sockeranna.bsky.social

@andreaslindholm.bsky.social

_Originally posted by @DoktorZjivago in https://github.com/snarfed/bridgy-fed/issues/1052#issuecomment-2113370999_

**Comment by snarfed** [comment]
Thanks! Following up in #1052.

**Comment by DoktorZjivago** [comment]
It seems as you were right, I asked all the accounts mentioned above to de-follow and follow again, then they almost immediately got bridged. So I guess this issue can be considered solved. Thanks! ☺️
