### ISSUE TITLE
Monitoring

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#1060]
We have a monitoring dashboard, https://console.cloud.google.com/monitoring/dashboards/builder/4f0ac7cc-258d-4058-8208-fafa32088378?project=bridgy-federated , but it's degraded. Time to take another pass at it!

**Comment by snarfed** [comment]
Also: alerts on task queue length.

**Comment by snarfed** [comment]
Here's a draft of what I'd like:

## Monitoring

### app
* [ ] requests
* [ ] errors
* [ ] latency, p50 90 99
* [ ] `/r`, `/convert`, webfinger requests, by domain
* [ ] outbound HTTP requests by domain
* [ ] instances

### router
* [ ] tasks by queue
* [ ] task responses, errors
* [ ] task latency
* [ ] already seen activity ids
* [ ] unsupported activity types
  * [ ] ...also in protocols like AP that short circuit them
* [ ] receive tasks by protocol, source domain
* [ ] send tasks by protocol, destination domain
* [ ] new users
* [ ] user deactivations
* [ ] activities for blocked, opted out, limited, blocklisted users
* [ ] CPU, memory

### atproto-hub
* firehose client:
  * [ ] total events
  * [ ] our events: from our users, to our users
* firehose server:
  * [ ] emitted events
  * [ ] connected clients
* [ ] CPU, memory

## Alerts

* [ ] app error rate
* [ ] app latency
* [ ] task queue length, errors, rate drops
* atproto firehose: 
  * [ ] last connection from Bluesky relay over ~75m ago
  * [ ] emitted events rate dropff
* [ ] app instances sustained spike (can we limited to billed instances?)
* [ ] router, atproto-hub serving instances sustained != `

**Comment by qazmlp** [comment]
> We have a monitoring dashboard, https://console.cloud.google.com/monitoring/dashboards/builder/4f0ac7cc-258d-4058-8208-fafa32088378?project=bridgy-federated , but it's degraded. Time to take another pass at it!

That dashboard is private, by the way.

Not sure if you're planning to have a public status page at all/if the privacy setting there is intentional, but I thought I'd mention it in case it's accidental.

**Comment by snarfed** [comment]
Hey, yes, not accidental. Not sure if I can make it public, but I'd like to!

**Comment by snarfed** [comment]
Looks like Google Cloud Monitoring dashboards can't be public 😕 

https://cloud.google.com/monitoring/access-control#predefined_roles
https://cloud.google.com/iam/docs/principal-identifiers

<img width="610" alt="image" src="https://github.com/user-attachments/assets/9a1a511f-4535-4c77-b588-308ded730192">

**Comment by snarfed** [comment]
Got a first pass at a new dashboard that I'm reasonably happy with.

<img width="1280" alt="dashboard" src="https://github.com/user-attachments/assets/e7d8630d-3438-426d-b1fe-dff97d7a2e0b">

**Comment by snarfed** [comment]
...and a first pass at alerts:
![Uploading alerts.png…]()

**Comment by snarfed** [comment]
There are a few still outstanding, but this is pretty much done!
