### ISSUE TITLE
The URL addresses in posts from Bluesky are useless

### ISSUE THREAD

**Issue by FoundOne** [snarfed/bridgy-fed#1062]
By what I've seen, any url in a Bluesky post gets shortened with ellipses and it's not converted to a link. That means I can't use any link from Bluesky. That includes links from Youtube for an example (I know it's weird such short url to be shortened, but it happens).

**Comment by snarfed** [comment]
Have you tried recently? You're right that they were broken for a while, but I fixed them a couple days ago: #993. Please post an example if they're still not working for you!

**Comment by snarfed** [comment]
Ah, sorry, never mind, that fix was just for fediverse => Bluesky. I'll look at Bluesky => fediverse.

**Comment by snarfed** [comment]
Fixed! Example: https://bsky.app/profile/snarfed.bsky.social/post/3kswfabwri32g => https://indieweb.social/@snarfed.bsky.social@bsky.brid.gy/112474267480842954 (requires login) . Thanks for the nudge!
