### ISSUE TITLE
Provide original URL as the canonical URL on posts bridged to the fediverse

### ISSUE THREAD

**Issue by mergesort** [snarfed/bridgy-fed#1077]
Apologies if I missed this request, it isn't quite #1009 but it's in the same genre of requests.

Right now when I click a link in my Mastodon clients (Ivory and Mona on iOS) to a URL in the format of `https://fed.brid.gy/r/https://bsky.app/profile/did:plc:some_identifier/post/some_other_identifier`.

While I can see how this makes sense, it creates a slightly subpar user experience. I use the Open in Browser feature to deeplink directly into Bluesky, that way I can view and interact with the post in their original context. Because fed.brid.gy is not the universal link Bluesky has registered the link instead opens in a web browser, without all of the app's functionality available to me.

I would love to instead have the canonical URL on a post be the original link, such as `https://bsky.app/profile/did:plc:some_identifier/post/some_other_identifier`, to improve the user experience of reading a Bluesky post in my Mastodon app.

Thank you so much, while I'm here I just want to say BridgyFed is an amazing idea and I am very grateful for your tireless work on it!

**Comment by snarfed** [comment]
You're right, these fed.brid.gy/r/... links are awkward and seemingly unnecessary. Sadly, they're a non-standard requirement imposed by some fediverse servers, notably Mastodon. I originally used the original link, like you describe, but Mastodon later started requiring object URLs to be on the same host as their ids: https://github.com/mastodon/mastodon/pull/6219 . This is mentioned (briefly) in the BF docs: https://fed.brid.gy/docs#web-visible-links

**Comment by mergesort** [comment]
Hey Ryan, that's a bummer but it makes sense for you to do that if that's what Mastodon is asking for. I'll close out the comment since there's not much you can do, appreciate the context and documentation.
