### ISSUE TITLE
AP: serve conneg on `/ap/...` actor URLs

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#1080]
For some reason, fediverse servers are using bridged Bluesky accounts' `id` as their "original page" link instead of `url`. Example: https://indieweb.social/@snarfed.bsky.social@bsky.brid.gy , "Open original page" goes to https://bsky.brid.gy/ap/did:plc:3ljmtyyjqcjee2kpewgsifvb , which is the actor `id` and serves the actor AS2 JSON.

So, I guess we should serve conneg on `activitypub.actor`, which serves those `/ap/...` URLs. Sigh.

Oddly, this doesn't happen for bridged web accounts, either on their own domain like https://indieweb.social/@snarfed.org@snarfed.org , or not, like https://indieweb.social/@nature.com@web.brid.gy . "Open original page" uses `url` for both of those, which is a fed.brid.gy/r/... link that (correctly) redirects to the sites themselves. Hrmph.

**Comment by snarfed** [comment]
Oddly this is inconsistent. https://bsky.app/profile/ewancroft.uk bridged themselves recently, and https://indieweb.social/@ewancroft.uk@bsky.brid.gy correctly uses to the /r/ link, not the id. 😕

**Comment by TomCasavant** [comment]
Interestingly it's also inconsistent between servers for the same profile, e.g.
 https://tomkahe.com/@snarfed.bsky.social@bsky.brid.gy -> https://bsky.brid.gy/r/https://bsky.app/profile/snarfed.bsky.social
 
 https://tomkahe.com/@globetrotters.bsky.social@bsky.brid.gy -> https://bsky.brid.gy/ap/did:plc:dzh2pohi5hgfrtf5r572zqqq
 https://mastodon.social/@globetrotters.bsky.social@bsky.brid.gy-> https://bsky.brid.gy/r/https://bsky.app/profile/globetrotters.bsky.social

**Comment by snarfed** [comment]
I think this was a historical artifact. All accounts and instances now are working ok, including https://indieweb.social/@snarfed.bsky.social@bsky.brid.gy and https://tomkahe.com/@snarfed.bsky.social@bsky.brid.gy . Tentatively closing for now.
