### ISSUE TITLE
Bridged bluesky accounts get profile but no posts get through

### ISSUE THREAD

**Issue by DoktorZjivago** [snarfed/bridgy-fed#1082]
Noticed in the last day some accounts that opted in from bluesky got a bridged account, but when they post and interact nothing gets visible on the fediverse. The profile is there, but no posts. For example @jascvakne.bsky.social@bsky.brid.gy and @knutk.bsky.social@bsky.brid.gy opted in, a mirror was created on the fediverse but their activity after the bridge was created doesn't seem to get through.

**Comment by TomCasavant** [comment]
@globetrotters.bsky.social might be experiencing a similar issue, I think it stopped bridging interactions sometime last week

**Comment by snarfed** [comment]
Ah, they need a profile picture and name. https://fed.brid.gy/docs#bluesky-cant-find

**Comment by TomCasavant** [comment]
> Ah, they need a profile picture and name. https://fed.brid.gy/docs#bluesky-cant-find

Oh sorry, didn't see that was added. Is that just spam prevention?

**Comment by snarfed** [comment]
Yes! Spam prevention, new as of a couple weeks ago.

**Comment by qazmlp** [comment]
I'd like to point out that it's very common for blind users to not have profile or header pictures.

(I'm aware of the spam incident that WeDistribute reported on, though, so I get that some filters are necessary.)

**Comment by snarfed** [comment]
Oof, great point. The current filters (display name, profile picture, at least one follower, over two weeks old if we know account age) are definitely crude, at best. Hopefully they'll do more net good than harm, but thank you for the heads up, there's clearly room for improvement.
