### ISSUE TITLE
xrpc: Wrong error type returned when repo is not found

### ISSUE THREAD

**Issue by mackuba** [snarfed/bridgy-fed#1083]
Testing on `getLatestCommit` at least - when called with a DID of a repo that doesn't exist (was deleted?), it returns:

https://atproto.brid.gy/xrpc/com.atproto.sync.getLatestCommit?did=did:plc:qwerty

```
{
    "error": "InvalidRequest",
    "message": "Repo None not found"
}
```

On Bluesky servers, it returns:

https://amanita.us-east.host.bsky.network/xrpc/com.atproto.sync.getLatestCommit?did=did:plc:qwerty

```
{
    "error": "RepoNotFound",
    "message": "Could not find root for DID: did:plc:qwerty"
}
```

The error type seems to be specified in the lexicon:

https://github.com/bluesky-social/atproto/blob/main/lexicons/com/atproto/sync/getLatestCommit.json#L30

```
"errors": [{ "name": "RepoNotFound" }]
```

**Comment by snarfed** [comment]
Good point, thanks!

**Comment by snarfed** [comment]
Done!
