### ISSUE TITLE
`web.brid.gy/r` redirection can be more useful

### ISSUE THREAD

**Issue by fishy** [snarfed/bridgy-fed#1084]
Currently, in order to get the ✅, the website must have a link to `https://web.brid.gy/r/<url>`, but that just redirects back to `<url>`, which makes it quite unuseful to be put on the website, so people would need to hide it (add `display:none;`, for example)

It would be much more useful if it redirects to `https://fed.brid.gy/web/<domain>/` instead, which the website can use it on a link says something in the line of "follow this website on the fediverse" and no longer need to hide it.

**Comment by snarfed** [comment]
I'm with you, the /r/ redirect is annoying and sometimes confusing. Sadly the way it works now is required for Mastodon interop: https://fed.brid.gy/docs#web-visible-links , https://github.com/snarfed/bridgy-fed/issues/1077

**Comment by fishy** [comment]
Sorry if I misunderstood something, but I think the requirement is just that the link is on `fed.brid.gy` domain, not that it must redirects back to the original url?

Also I'm talking about this part: https://fed.brid.gy/docs#mastodon-link-verification

**Comment by snarfed** [comment]
Yes! Sadly these URLs all come from the same place(s) under the hood, and Mastodon's semantics for them and its same-domain requirement (described in https://fed.brid.gy/docs#web-visible-links and the links there) apply to them all equally.

**Comment by snarfed** [comment]
(Sorry, to clarify, the rel-me link that you put on your web site has to point to your AP actor's `url` field, which has to be on `web.brid.gy`.)

For a _visible_ link on your site, you're definitely right that linking to your user page on fed.brid.gy is more useful! That's what I do on my own site, https://snarfed.org/ . I have the rel-me link to `/r/...` in a separate `display: none` link, like you mention, and like I recommend in the docs. Annoying, agreed, but hopefully not too much of a burden.
