### ISSUE TITLE
Document that webmentions require microformats2 

### ISSUE THREAD

**Issue by fishy** [snarfed/bridgy-fed#1085]
I just implemented webmention from my website, and sent a webmention to `https://fed.brid.gy/webmention`. I got 202 response with body:

```
Added webmention task projects/bridgy-federated/locations/us-central1/queues/webmention/tasks/0364590518903229013 : {'source': '...', 'target': 'https://fed.brid.gy/'}
```

And I saw that a request with user-agent of `Bridgy Fed (https://fed.brid.gy/)` accessing my website within 2 minutes. But after one hour I still don't see the new post appearing in the activity tab of `https://fed.brid.gy/web/<my domain>`, wondering if there are some huge delay even with webmention, or if I did something wrong.

**Comment by snarfed** [comment]
Hmm, sorry for the trouble! What was the post URL? I can take a look.

**Comment by fishy** [comment]
> Hmm, sorry for the trouble! What was the post URL? I can take a look.

https://b.yuxuan.org/fediverse

**Comment by snarfed** [comment]
Looks like we got backed up pretty badly. I'm still not sure why yet, but I'll get the backlog processed and figure out what happened.

**Comment by snarfed** [comment]
Finally got a chance to look at this. Looks like your site doesn't have microformats? If you want to use webmention to trigger BF instead of RSS/Atom, you'll need microformats. https://microformats.org/wiki/microformats2 , https://indieweb.org/microformats

**Comment by fishy** [comment]
> Finally got a chance to look at this. Looks like your site doesn't have microformats? If you want to use webmention to trigger BF instead of RSS/Atom, you'll need microformats. https://microformats.org/wiki/microformats2 , https://indieweb.org/microformats

the doc doesn't make it clear that microformats are _required_ for webmentions, and it worked without microformats before with rss feed 🫤

**Comment by snarfed** [comment]
True! Good point about the docs, sorry about that. I'll update them.

RSS and microformats both provide a predictable way to extract structured data, notably post content and optionally title, from arbitrary HTML. Without those, it's not easy for BF to determine what specifically in your HTML is the post content that you want to federate.

**Comment by fishy** [comment]
ok anyways I added microformat and looks like it works now (the webmention request now times out at 1s for some reason, but I do see the request from bridgy fed immediately after and then it's updated)
