### ISSUE TITLE
Post's are no longer synced to Bluesky

### ISSUE THREAD

**Issue by Fauli1221** [snarfed/bridgy-fed#1087]
I suspect this is my fault as I played around with some broken cache on my Firefish instance that was created back in the phase of developed where you could view Bluesky profiles on @user.domain@atproto.brid.gy and was trying out what would happen if I would @ one of those users in a post 

I posted and after it did not get synced I deleted and reposted without mentioning that account though that post was also never synced to Bluesky 

All other interactions since then have also not been seen by the bridge

My profile: https://fed.brid.gy/ap/@fauli1221@hooves.social

**Comment by hybridhavoc** [comment]
I have actually also had two posts today that were never registered on [my profile](https://fed.brid.gy/ap/@hybridhavoc@darkfriend.social).

Post 1: https://darkfriend.social/@hybridhavoc/112513318793570706
Post 2: https://darkfriend.social/@hybridhavoc/112515589460478709

I have not tried refollowing at this time. I did hit the refresh profile button on my profile. That, also, does not have an entry on my profile when I think normally it does.

**Comment by snarfed** [comment]
Sorry all! Looks like we got backed up pretty badly last night. I was mostly off the grid this weekend, so I'm only now getting to dig into this. I'm still not sure why yet, but I'll get the backlog processed and figure out what happened.
