### ISSUE TITLE
[ATProto->AP] The user's display name is overwritten with the custom feed name.

### ISSUE THREAD

**Issue by usounds** [snarfed/bridgy-fed#1096]
When I published a new custom feed on Bluesky, my username on the Fediverse side was overwritten with the new custom feed name.

My Bluesky Account is "ゆー"
<img width="245" alt="image" src="https://github.com/snarfed/bridgy-fed/assets/46260022/23c1a8a7-d4f8-499a-95db-8bcfee41b2aa">

My Account in Fediverse is "ああああ"
<img width="467" alt="image" src="https://github.com/snarfed/bridgy-fed/assets/46260022/352fb52f-7755-44f0-aaf2-252deeb4ae7c">

"ああああ" is the name of my newest custom feed.
<img width="610" alt="image" src="https://github.com/snarfed/bridgy-fed/assets/46260022/e04d6ade-e6da-48c5-8a96-3aa7dc89e1ce">

**Comment by snarfed** [comment]
Oh no! Sorry about that. Funny, I think I can guess what happened there. Custom feeds' DIDs work a bit strangely, I didn't fully understand them until recently. Hopefully should be an easy fix.

**Comment by snarfed** [comment]
I _think_ this is fixed. Your name is now back to ゆー on all three instances where you have followers - https://misskey.io/@usounds.work@bsky.brid.gy , https://mi.usounds.work/@usounds.work@bsky.brid.gy , https://shelter.moe/@usounds.work@bsky.brid.gy - and on new instances, eg https://indieweb.social/@usounds.work@bsky.brid.gy . And I think this shouldn't happen again. I'm not 100% sure though, please reopen if your bridged name in the fediverse gets set to a custom feed again!

**Comment by snarfed** [comment]
Oh no! Thanks for the heads up, glad it's not urgent. I'll look again at some point.
