### ISSUE TITLE
AT: Bridgy ignores self-applied sensitive content labels

### ISSUE THREAD

**Issue by qazmlp** [snarfed/bridgy-fed#1099]
This is the inverse of #1100.

I made this post with an image self-labelled as "Suggestive": https://bsky.app/profile/qazm.bsky.social/post/3ktwiogwras2s
(Note: You _probably_ should have nudity set to at least "Warn" if you look at my account beyond that page.)
![The post in question.](https://github.com/snarfed/bridgy-fed/assets/17500283/83f5ad59-36fa-4408-a3f8-2e593e2639fa)

This was [bridged to AP](https://bsky.brid.gy/convert/ap/at://did:plc:2shmwstgqmlu4ymg7ctjcdc7/app.bsky.feed.post/3ktwiogwras2s) with no indication of sensitive content:

```json
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "attachment": [
    {
      "name": "A truncated screenshot of a dimly-lit purple SFD-modelled abstract knot-like shape above a background grid.",
      "type": "Image",
      "url": "https://morel.us-east.host.bsky.network/xrpc/com.atproto.sync.getBlob?did=did:plc:2shmwstgqmlu4ymg7ctjcdc7&cid=bafkreiejrmrtm43o6rqtorom6pd3dwgme5apte42ebxodn2hopgdcv2ixi"
    }
  ],
  "attributedTo": "https://bsky.brid.gy/ap/did:plc:2shmwstgqmlu4ymg7ctjcdc7",
  "content": "<p>(This is a test on how self-applied sensitive content labels are bridged.)</p>",
  "contentMap": {
    "en": "<p>(This is a test on how self-applied sensitive content labels are bridged.)</p>"
  },
  "content_is_html": true,
  "id": "https://bsky.brid.gy/convert/ap/at://did:plc:2shmwstgqmlu4ymg7ctjcdc7/app.bsky.feed.post/3ktwiogwras2s",
  "image": {
    "name": "A truncated screenshot of a dimly-lit purple SFD-modelled abstract knot-like shape above a background grid.",
    "type": "Image",
    "url": "https://morel.us-east.host.bsky.network/xrpc/com.atproto.sync.getBlob?did=did:plc:2shmwstgqmlu4ymg7ctjcdc7&cid=bafkreiejrmrtm43o6rqtorom6pd3dwgme5apte42ebxodn2hopgdcv2ixi"
  },
  "published": "2024-06-02T08:04:00.537Z",
  "to": [
    "https://www.w3.org/ns/activitystreams#Public"
  ],
  "type": "Note",
  "url": "https://bsky.brid.gy/r/https://bsky.app/profile/did:plc:2shmwstgqmlu4ymg7ctjcdc7/post/3ktwiogwras2s"
}
```

Which of course means that the image isn't blurred-by-default on any ActivityPub platforms, unless the account is moderated by the receiving instance:

![The post in question.](https://github.com/snarfed/bridgy-fed/assets/17500283/0443bd2c-af60-4fb7-aa59-525d11937e09)

---

What I expected:

The post should have a sensitive content label applied like on [this native AP post I just made](https://tiggi.es/@Qazm/112546008212972221):

```json
{
    "@context": [
        "https://www.w3.org/ns/activitystreams",
        {
            "ostatus": "http://ostatus.org#",
            "atomUri": "ostatus:atomUri",
            "inReplyToAtomUri": "ostatus:inReplyToAtomUri",
            "conversation": "ostatus:conversation",
            "sensitive": "as:sensitive",
            "toot": "http://joinmastodon.org/ns#",
            "votersCount": "toot:votersCount",
            "blurhash": "toot:blurhash",
            "focalPoint": {
                "@container": "@list",
                "@id": "toot:focalPoint"
            }
        }
    ],
    "id": "https://tiggi.es/users/Qazm/statuses/112546008212972221",
    "type": "Note",
    "summary": null,
    "inReplyTo": null,
    "published": "2024-06-02T08:09:59Z",
    "url": "https://tiggi.es/@Qazm/112546008212972221",
    "attributedTo": "https://tiggi.es/users/Qazm",
    "to": [
        "https://www.w3.org/ns/activitystreams#Public"
    ],
    "cc": [
        "https://tiggi.es/users/Qazm/followers"
    ],
    "sensitive": true,
    "atomUri": "https://tiggi.es/users/Qazm/statuses/112546008212972221",
    "inReplyToAtomUri": null,
    "conversation": "tag:tiggi.es,2024-06-02:objectId=15943322:objectType=Conversation",
    "content": "<p>(This is a test on how self-applied sensitive content labels are bridged.)</p>",
    "contentMap": {
        "en": "<p>(This is a test on how self-applied sensitive content labels are bridged.)</p>"
    },
    "attachment": [
        {
            "type": "Document",
            "mediaType": "image/jpeg",
            "url": "https://tiggi.es/system/media_attachments/files/112/546/004/838/492/972/original/141e2f46f5601539.jpg",
            "name": "A truncated screenshot of a dimly-lit purple SFD-modelled abstract knot-like shape above a background grid.",
            "blurhash": "Uc7,?0axI%oNs?j[W9axaxj]ayaxoNaxWTj]",
            "focalPoint": [
                0,
                0
            ],
            "width": 3000,
            "height": 1000
        }
    ],
    "tag": [],
    "replies": {
        "id": "https://tiggi.es/users/Qazm/statuses/112546008212972221/replies",
        "type": "Collection",
        "first": {
            "type": "CollectionPage",
            "next": "https://tiggi.es/users/Qazm/statuses/112546008212972221/replies?only_other_accounts=true&page=true",
            "partOf": "https://tiggi.es/users/Qazm/statuses/112546008212972221/replies",
            "items": []
        }
    }
}
```

This results in blurring the image:
![The post in question.](https://github.com/snarfed/bridgy-fed/assets/17500283/9528d45f-880b-45e3-8ced-44a95b1c8c0b)
(I'm not sure if this is an image blur or just the blurhash… _Ideally_ Bridgy should compute the blurhash to make sure the post still looks good in AP software.)

For higher categories of labels, i.e. "Nudity" or "Porn" instead of just "Sensitive", Bridgy should **additionally** use those terms or "Label: Nudity"/"Label: Porn" as CW/CN so that users can filter on them!

**Comment by snarfed** [comment]
Great feature request! I don't know much about the `as:sensitive` AS2 extension - assuming it is an extension at all, and not just a misuse of a field like Mastodon putting CWs into `summary` - but I can learn!

**Comment by qazmlp** [comment]
> Great feature request! I don't know much about the `as:sensitive` AS2 extension - assuming it is an extension at all, and not just a misuse of a field like Mastodon putting CWs into `summary` - but I can learn!

It's namespace misuse, I'd say. The term is undefined in the core AS namespace but Mastodon puts it there: https://docs.joinmastodon.org/spec/activitypub/#as

> Also hopefully I can do this without actually calculating a real blurhash. That would be possible, but very low priority right now.

The details probably depend on the receiving instance a bit, but at worst it should result in an indistinct placeholder. Anything worse I'd file as a bug on their end.

**Comment by jfietkau** [comment]
There is [a draft report](https://swicg.github.io/miscellany/) by @evanp that aims to formally document some loose ends, including `as:sensitive`.

**Comment by qazmlp** [comment]
Just my two cents, but if you do end up adding CNs/CWs, the ones I'd most like to see are:

- Adult Content: Nudity
- Adult Content: Porn

Mirroring the "Adult Content" click-through that Bsky shows but with a bit more specificity. This would also get picked up by AP users' existing word filters for "nudity", "porn" and "adult content", but at the same time is unique enough that filtering "Adult Content: Nudity" and "Adult Content: Porn" would hit more or less only Bsky posts in case someone wants to hide those specifically.

**Comment by qazmlp** [comment]
Maybe an interesting complication: On Bluesky, "Sensitive" can also be applied to posts with link preview attachments.
Mastodon does not have this option when composing posts, so when receiving a sensitive post without (other) media, it's possible that it would still show a preview there.

If it does, it might be a good idea to suppress the preview there or apply "Adult Content: Sensitive" as CN/CW *only when there's no bridged images/videos*.

**Comment by qazmlp** [comment]
Just a small nudge that there are now a few bridged-from-Bluesky users who occasionally post adult content themselves.
*Might* become an issue if someone from a huge instance follows them and they appear on the federated feed there.

**Comment by snarfed** [comment]
^ also snarfed/granary@1b9d46b1f626b647ffd4c8a055e62e08f7116bbc

**Comment by snarfed** [comment]
ATProto => ActivityPub is working: https://bsky.app/profile/snarfed.bsky.social/post/3kxc2vlq75t2e => https://indieweb.social/@snarfed.bsky.social@bsky.brid.gy/112788210990075629 . Still working on the reverse.

**Comment by snarfed** [comment]
Never mind, ActivityPub => ATProto is working too after all: https://indieweb.social/@snarfed/112788212838236725 => https://bsky.app/profile/snarfed.indieweb.social.ap.brid.gy/post/3kxc2x4mta3l2

**Comment by qazmlp** [comment]
Mostly there (in my eyes), but this doesn't seem to apply content notes for the higher levels, which most general-purpose instances require. There are some purpose-built instances for adult content that only require the 'sensitive' label, but those are usually limited in visibility via instance moderation elsewhere.

[Example thread on Bluesky.](https://bsky.app/profile/qazm.bsky.social/post/3kxchrxboek26)
I don't know how to easily get the AP id for these. Might be neat to have a button to copy it in the event log on the bridge's account status page, eventually.

**Comment by snarfed** [comment]
Thanks! And understood.

> content notes/CWs for the higher levels, which most general-purpose instances require

Any chance you have a link with more info on this?

**Comment by qazmlp** [comment]
> Thanks! And understood.
> 
> > content notes/CWs for the higher levels, which most general-purpose instances require
> 
> Any chance you have a link with more info on this?

It's (by the nature of the network) inconsistent of course, and the remark was admittedly based on my subjective experience in it.

I can make a table of the largest instances, since this is listed publicly in their rules...

|instance (rules page)|notes|requirement for sexual content|requirement for violent content|
|-|-|-|-|
|[mastodon.social](https://mastodon.social/about)|-|sensitive or CW|sensitive or CW
|[misskey.io](https://support.misskey.io/hc/ja/articles/6564530842767-%E5%88%A9%E7%94%A8%E8%A6%8F%E7%B4%84)|In Japanese. I *think* it's similar to mastodon.social's with Japan-specific legal requirements.|sensitive is enough?|R-18G-rated violence is banned|
|[mstdn.jp](https://mstdn.jp/about) (in the About section, not Rules)|In Japanese. Something along the lines of "please use descriptive CWs according to common sense", though CWs may not be required for NSFW image-only posts while the media is flagged.|descriptive CW?|descriptive CW?|
|mastodon.cloud|Rules aren't public.|?|?|
|[mstdn.social](https://mstdn.social/about)|-|sensitive flag|sensitive flag|
|[mastodon.online](https://mastodon.online/about)|-|sensitive or CW|sensitive or CW|
|[mastodon.world](https://mastodon.world/about)|-|CW|CW, with exceptions that are banned|
|[mas.to](https://mas.to/about)|-|sensitive and/or CW|unspecific (likely the same)|
|[micro.blog](https://help.micro.blog/t/community-guidelines/39)|Nothing specific.|none?|none?|
|[lemmy.world](https://legal.lemmy.world/tos/)|Unspecific regarding sexual content.|none?|NSFW tag (which I think is "sensitive", but I'm not certain.)|

You're right, only two of the top ten require a CW specifically. "sensitive" is likely enough for threads.net too, but I assume they'll just filter out those posts completely over there.

I think furry servers are just largely more strict about this. The ones listed on [joinmastodon.org](https://joinmastodon.org/servers):

|instance (rules page)|notes|requirement for sexual content|requirement for violent content|
|-|-|-|-|
|[bark.lgbt](https://bark.lgbt/about)|-|CW|CW|
|[furry.engineer](https://furry.engineer/about)|-|CW|CW|
|[pawb.fun](https://pawb.fun/about)|-|CW|CW|
|[furries.club](https://furries.club/about)|"should"|sensitive flag + descriptive CW|sensitive flag + descriptive CW|
|[cyberfurz.social](https://cyberfurz.social/about)|Not specific regarding violence.|CW|probably CW?|
|[furry.energy](https://furry.energy/about)|-|sensitive flag, + CW for some|sensitive flag, + CW for some|

(The LGBTQ+ category is a bit more lax about this, I think only about half the servers there require CWs specifically (or ban adult content outright).)

In practice, I _personally_ don't see sexually explicit content without CW on Mastodon, which is convenient because it lets me show sensitive media by default (so suggestive stuff) while I can decide if I want to see porn or violence on a case-by-case basis, or filter it outright based on keywords. (I have a filter for "porn" on my main account.)

- - -

Something else to consider is that **the CW/`summary`-UX in AP apps is usually not obtrusive**:

|software|CW|notes|
|-|-|-|
|Mastodon|![The post content has a line with the summary text and a SHOW MORE button next to it, formatted like post text.](https://github.com/user-attachments/assets/f681efe6-969e-477f-b665-74d5ba1f8550)|The CW is formatted like text content and doesn't collapse images.<br><br>Text and images are revealed independently.|
|Pixelfed|![Pixelfed CW vs. sensitive](https://github.com/user-attachments/assets/78f0e922-29dc-4758-8a2b-4c2fb2ee7441)|The first post has a CW, the second is only marked sensitive.<br><br>The CW only replaces the "This post may contain sensitive content." copy with the `summary`.<br><br>_Either_ hides all text content unless expanded. Clicking "See Post" shows both image and text content together.|

(I don't have a Misskey account to test this with currently, but from screenshots it seems to be like Mastodon.)

I think this actually enhances the presentation compared to not applying a CW.
On Pixelfed always, of course, and on Mastodon definitely if the post has otherwise no text.

_Personally_, I would prefer a CW with the label category even for posts that have text, since if I look at the adult-flagged posts on Bluesky, the text is usually not very descriptive in that way. It's more often than not stuff like "Care to join?" (okay, that's predictable), "View", "yea" or just the character name or commissioner, which makes what I'm about to see a guessing game if the label category isn't visible.

**Comment by qazmlp** [comment]
Basically, among [the label types that Bridgy Fed understands](https://github.com/snarfed/granary/commit/48e57b7708f57152301996182ce3b76acebc39be#diff-1915ad0740506cba5b100e33d222098b9ec534f9f592b600ab55571db03296b0R136), I would like to see CWs for all _except whichever the one is that Bluesky calls 'Sensitive' in their UI_. That one seems to be used only for very tame content that I wouldn't expect a separate CW on on Mastodon even in my context, and it seems to usually be paired with a bit more useful descriptions in the text content on Bluesky.

For the other Adult Content CWs I'd prefer "Adult Content: Nudity" and "Adult Content: Porn" as mentioned [here](https://github.com/snarfed/bridgy-fed/issues/1099#issuecomment-2148442575).

The others should probably match Bluesky's warnings if you see them (so "Explicit or potentially disturbing media." for `'graphic-media'`, I think?), but I don't think Bridgy Fed can currently receive them from the Bluesky PDS since they aren't self-applicable.

I have a hunch you might want to outright filter out or `Delete` posts that end up labelled `'nsfl'` instead of just putting CW on those, but I feel strongly unmotivated to find out what that category actually is used for.

**Comment by snarfed** [comment]
Thank you for the detailed investigation and context! As always. I really appreciate it.

I'm a bit torn on adding CWs. I try hard to avoid/minimize changing users' content itself, which CWs in one sense feel like, since they're user-authored and go into the AS2 `summary` field. (Which is generally agreed now to be a misuse of that field, so maybe that's less an argument.) On the other hand, Bluesky self labels are also a form of user authoring, and they're rendered and used similarly to CWs, so maybe in this case it's the right idea.

(Btw, unrelated nit: looking at your catalog of instance rules, my interpretation is that they apply to those instances' own users, not all users on the fediverse, right? Are you saying admins generally apply those same rules to remote users and posts, ie as their moderation policies?)

**Comment by qazmlp** [comment]
> Thank you for the detailed investigation and context! As always. I really appreciate it.
> 
> I'm a bit torn on adding CWs. I try hard to avoid/minimize changing users' content itself, which CWs in one sense feel like, since they're user-authored and go into the AS2 `summary` field. (Which is generally agreed now to be a misuse of that field, so maybe that's less an argument.) On the other hand, Bluesky self labels are also a form of user authoring, and they're rendered and used similarly to CWs, so maybe in this case it's the right idea.

I think that removing them is stronger alteration, when taking into account the different filter choice mechanisms between the networks.

I can see where you're coming from in not using third-party labels, to an extent, though in the (far) future it might be nice if instance admins could "subscribe" to certain labellers through Bridgy Fed and then see the content through that lens when using authorized fetch from their instance.

> (Btw, unrelated nit: looking at your catalog of instance rules, my interpretation is that they apply to those instances' own users, not all users on the fediverse, right? Are you saying admins generally apply those same rules to remote users and posts, ie as their moderation policies?)

Yes and no, kinda. The rules _are_ generally more lenient regarding other instances, but they also influence which posts may be boosted by users on that instance (with a visibility above followers-only, at least). For example, if my instance requires as CW on nudity, then I generally shouldn't boost nudity that doesn't have one.

The rules also inform which other instances certain instances will share a relay with, since that causes the discovery feeds to be merged. Conversely, if there's a large difference, admins may remove individual users or an instance from the discovery feeds on their instance. In practice: 
![image](https://github.com/user-attachments/assets/9e1276ad-5f3b-4bb2-be7a-50f17dee8ab4)
![image](https://github.com/user-attachments/assets/4e287d29-b690-4c7d-b187-36a335973c5e)

These are from the mod lists of two instances I have accounts on.
I don't think my admin on the latter would have defederated the instance for lack of CWs alone, but it's often taken into account to some extent, in my experience with a few instances other than these two.

**Comment by snarfed** [comment]
OK! I can plan to translate Bluesky self labels to fediverse CWs. And I'll look at "Adult Content - Sensitive" and see if it's worth excluding.

**Comment by qazmlp** [comment]
I appreciate it. This will definitely make (re)connecting with friends across the bridge a much smoother experience for me, and for them also I imagine (in terms of not having to worry about small-instance Mastodon culture as much).

**Comment by snarfed** [comment]
OK, this is done. All Bluesky self labels now get translated to fediverse content warnings. No exceptions yet, let's see how it goes and what we think?

Example: https://bsky.app/profile/did:plc:3ljmtyyjqcjee2kpewgsifvb/post/3kxgt3rrroc22 => https://indieweb.social/@snarfed.bsky.social@bsky.brid.gy/112798919768121532
