### ISSUE TITLE
support MediaGoblin

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#11]
https://mediagoblin.org/ . evidently it does ActivityPub? i think spec editor @cwebber is a maintainer, even if [he hasn't done much recently](https://git.savannah.gnu.org/cgit/mediagoblin.git/log/)...?

**Comment by cwebber** [comment]
Yes the great irony is that I got into ActivityPub for MediaGoblin's sake and then ActivityPub kept me from working on MediaGoblin.

MediaGoblin will support AP in 2018 so if you have AP support, you'll have MediaGoblin support...!

**Comment by strypey** [comment]
Any update on progress with AP support in MediaGoblin?

**Comment by snarfed** [comment]
Give it a shot, see if it works!

**Comment by Ryuno-Ki** [comment]
FWIW I'm on their mailing list (and had some mail exchange last year). Let me know if I shall relay something.

**Comment by strypey** [comment]
@ Ryuno-Ki yes please. As @CWebber said, if and when MediaGoblin supports AP, this issue is well on its way to being solved. Although from my layperson's understanding, smooth interoperation and UX isn't quite as simple as "implement AP" ;)

**Comment by snarfed** [comment]
Not seeing any progress on ActivityPub in MediaGoblin. No meaningful development in over a year, and nothing on ActivityPub for much longer:

- https://mediagoblin.org/news/still-here-in-2020.html
- https://wiki.mediagoblin.org/index.php?search=activitypub&title=Special%3ASearch&go=Go
- https://git.savannah.gnu.org/cgit/mediagoblin.git/log/?qt=grep&q=activitypub
- https://git.savannah.gnu.org/cgit/mediagoblin.git/log/

Tentatively closing. Feel free to reopen!
