### ISSUE TITLE
Long posts from ActivityPub that contain images end up truncated without link

### ISSUE THREAD

**Issue by lupomancer** [snarfed/bridgy-fed#1106]
Long posts usually get truncated with a link to the original post on the fediverse like so

https://bsky.app/profile/lupomancer.furries.club.ap.brid.gy/post/3ktr4vwupiba2

but when a [long post contains images](https://furries.club/@lupomancer/112554386726301465), it ends up just truncating the post without linking to the original like the following:

https://bsky.app/profile/lupomancer.furries.club.ap.brid.gy/post/3ku2a3mdgr6o2

**Comment by snarfed** [comment]
Ooh, good catch! Thank you for filing. I think I know what's happening here, should be a straightforward fix.

**Comment by snarfed** [comment]
So the fix here is straightforward, but not ideal. Bluesky posts can have either a link embed or images, but not both. So if I "fix" this, these posts would get the link card to the original post, but lose the attached images. Hrm.

One alternative would be to link to the original post in the post text instead of an embed, so we could keep the images. That would be inconsistent with using the embed in truncated posts without images, but that may be ok.

**Comment by snarfed** [comment]
Filed https://github.com/bluesky-social/atproto/discussions/2575 for this ^

**Comment by snarfed** [comment]
Phew, this was more complicated than I expected. No matter, should be working now!

**Comment by mackuba** [comment]
It looks like the facet positions aren't calculated correctly in some cases, e.g.:

https://bsky.app/profile/aboveedxw.mastodon.social.ap.brid.gy/post/3kusqralvfqe2
https://bsky.app/profile/baoteca.mastodon.social.ap.brid.gy/post/3kurc4rv3dte2

Yeah I know this API is tricky to use :)

**Comment by snarfed** [comment]
Ugh, thanks for reporting. Reopening.

Agreed, index-based rich text APIs like this tend to be easier and safer for the rendering side (eg bsky.app) than inline markup like HTML, but they're definitely more difficult and error prone for publishers, and there are generally way more publishing implementations than rendering implementations. Afaik publishing standards communities (PDF, PostScript, DOCX, etc) have largely converged on inline markup for those reasons. 🤷‍♂️

**Comment by snarfed** [comment]
^ Should be fixed now. Thanks again for the report @mackuba!

**Comment by mackuba** [comment]
Btw, Skythread now reads the `bridgyOriginalText` property and shows the full text automatically: https://blue.mackuba.eu/skythread/?author=MilekPl.sciences.social.ap.brid.gy&post=3kuscj3txuue2

**Comment by snarfed** [comment]
Awesome! Love it. `bridgyOriginalUrl` next! 😁
