### ISSUE TITLE
AP › ATP: Long post with hashtags all over and lot's of mentions doesn't show at all on Bluesky 

### ISSUE THREAD

**Issue by zaphbbrox** [snarfed/bridgy-fed#1114]
My fellow mastodonian wanted to publish this [post](https://det.social/@HerrGuenni/112563780838075991) and a [reply](https://det.social/@HerrGuenni/112563797080531271), but nothing showed up on Bluesky.
In his user dashboard was not even a yellow check (although I'm not sure what it stands for).
After reading #980 I thought this could maybe be related and/or the groups (the last three mentions in post) interfered with the truncation process somehow?!
If he hadn't successfully delivered a post before and a repost of one of my posts after the two problematic posts, I would have thought his recent instance switch might've been the problem.

Here's the link to his Bluesky profile:
https://bsky.app/profile/HerrGuenni.det.social.ap.brid.gy

Let me know if you need anything else.

**Comment by snarfed** [comment]
Hmm! Thanks for the nudge, looks like this is #885, will follow up there.
