### ISSUE TITLE
AP > ATP: Posts with URL fail to deliver

### ISSUE THREAD

**Issue by zaphbbrox** [snarfed/bridgy-fed#1121]
Today, every post containing an URL failed to deliver from Mastodon to Bluesky.  
Example:  
https://norden.social/@zaph0d/112576819517532259

Same content other way round worked:
https://bsky.app/profile/zaph0d.bsky.social/post/3kue6snknvd2q

Result on Mastodon:  
<blockquote lang="en" cite="https://fed.brid.gy/r/https://bsky.app/profile/did:plc:n3ohxrhocxrckoa5rtwojgsi/post/3kue6snknvd2q">
  <p><a href="https://bsky.brid.gy/hashtag/bridgyfed" rel="nofollow noopener noreferrer" target="_blank">#bridgyfed</a> test if URLs work:<a href="https://libredirect.github.io/index.html" rel="nofollow noopener noreferrer" target="_blank">libredirect.github.io/index.html</a>
  <a href="https://bsky.brid.gy/hashtag/test" rel="nofollow noopener noreferrer" target="_blank">#test</a> <a href="https://bsky.brid.gy/hashtag/bridgy" rel="nofollow noopener noreferrer" target="_blank">#bridgy</a></p>
  <footer>
     — zaph0d (@zaph0d.bsky.social@bsky.brid.gy) <a href="https://fed.brid.gy/r/https://bsky.app/profile/did:plc:n3ohxrhocxrckoa5rtwojgsi/post/3kue6snknvd2q"><time datetime="2024-06-07T18:44:40.675Z">7.6.2024, 20:44:40</time></a>
  </footer>
</blockquote>

**Comment by snarfed** [comment]
Hmm, sorry about that! I looked at this briefly and I haven't yet figured out what happened. Not system-wide at least, other fediverse posts with URLs are bridging ok, eg https://bsky.app/profile/camillamalm.bsky.social/post/3kufeqm4yju2c

**Comment by snarfed** [comment]
Fixed! Thanks for reporting, this was a real bug, hidden by a bit of bad error handling ^.
