### ISSUE TITLE
No "user page" created for bridged Mastodon account

### ISSUE THREAD

**Issue by pviglucci** [snarfed/bridgy-fed#1122]
I don't have a "user page" for my bridged Mastodon account. https://fed.brid.gy/ap/@pete@wargamers.social returns 404 Not Found, ap user @pete@wargamers.social not found. The bridge appears to be working fine however. I can see my posts on Bluesky, respond, interact with them, etc.

I also bridged my Bluesky account and the user page was created correctly, https://fed.brid.gy/bsky/petev.bsky.social. The bridge appears to be working fine from Bluesky as well.

Is there something I need to do to get a user page created for my bridged Mastodon account?

**Comment by pviglucci** [comment]
Adding that the issue may be self-inflicted in that when I initially established the bridge, one setting in my Mastodon profile was not enabled:

- Include profile page in search engines

I subsequently enabled that setting and all appears to be working sans the user page.

**Comment by pviglucci** [comment]
Ugh, I just realized that the user page is case sensitive. All is working.

**Comment by snarfed** [comment]
Sorry for the confusion! Good nudge, I can try to make it case insensitive.
