### ISSUE TITLE
AT to AP - Strange link, or link applied to wrong text

### ISSUE THREAD

**Issue by hybridhavoc** [snarfed/bridgy-fed#1123]
Just ran across an odd issue I thought I would bring up here. A Bluesky post bridged over to ActivityPub has a link in a weird place. 

- Bluesky post here: https://bsky.app/profile/aielcakes.bsky.social/post/3kuiqjn63762z
- ActivityPub side here: https://darkfriend.social/@aielcakes.bsky.social@bsky.brid.gy/112587069838804943

The original Bluesky post has an @ mention for bsky.app which is displayed as a link on Bluesky. On the AP side there is no link on the @ mention, but there is a link on a different set of 9 characters.

User page on fed.brid.gy: https://fed.brid.gy/bsky/aielcakes.bsky.social

Unfortunately it doesn't look like there's a log available for that post.

**Comment by enwin** [comment]
I'm seeing the same issue with hashtags and @ mentions as well.
- Bluesky original post: https://bsky.app/profile/did:plc:6es2dmxav4uel3q67xhkgyox/post/3kuilbhibek2v
- ActivityPub side example: https://mastodon.social/@origasky.bsky.social@bsky.brid.gy/112586702973436265

The first hashtag is properly mapped to a fediverse hashtag, but not the following ones. They also display a link displacement, same for the following @ mention.

User page on fed.brid.gy: https://fed.brid.gy/bsky/origasky.bsky.social

**Comment by snarfed** [comment]
Oof, yeah. Sorry! Will fix.

**Comment by snarfed** [comment]
Background: snarfed/granary@e08550ef5b2216739d840f284a34474857d110de interacted badly with #990 and https://github.com/snarfed/bridgy-fed/commit/b4124bd23fb21f8b2ca1cc11dfe15dfaefc6f779. I'm rolling back snarfed/granary@e08550ef5b2216739d840f284a34474857d110de, which should fix this regression, but that means AP => Bluesky profile bios still won't have meaningful whitespace, ie newlines won't show up. I'll need to figure that out.

**Comment by snarfed** [comment]
Sadly Mastodon's `.status__content p { white-space: pre-wrap }` style doesn't apply to profile bios, they have class `account__header__content` instead.

https://github.com/snarfed/bridgy-fed/blob/551637f6a1091c9317446001245b5fd94d9d2680/activitypub.py#L810-L816

Good motivation, really I want to bring back the `\n` => `<br>` translation anyway instead of depending on a project-specific CSS like that to preserve whitespace.

**Comment by snarfed** [comment]
OK, the regression here should be fixed. Example: https://bsky.app/profile/snarfed.bsky.social => https://indieweb.social/@snarfed.bsky.social@bsky.brid.gy/112587591636781521

I'll leave this open to figure out the rest.

**Comment by snarfed** [comment]
OK, fixed preserving whitespace in AP => Bluesky bios. Example: https://bsky.app/profile/evan.cosocial.ca.ap.brid.gy
