### ISSUE TITLE
Mastodon to Bluesky bridges only reposts from first user reposted

### ISSUE THREAD

**Issue by turgaer** [snarfed/bridgy-fed#1124]
I am observing a very strange issue: I bridged my mastodon account [turgaer@norden.social](https://norden.social/@turgaer) to Bluesky.  The account created there is [turgaer.norden.social.ap.brid.gy](https://bsky.app/profile/did:plc:xjgcpri42vg2sqfmarbc6uwl) as expected. 

"My" first posting bridged from Mastodon to Bluesky was a repost from an account which is a Bluesky-Mirror on Mastodon ( [streetdogg.bsky.social@bsky.brid.gy](https://norden.social/@streetdogg.bsky.social@bsky.brid.gy), https://norden.social/@streetdogg.bsky.social@bsky.brid.gy/112568101916374862 ). 
The second posting bridged from Mastodon to Bluesky was a repost from a Mastodon account of the same person ( [StreetDogg@norden.social](https://norden.social/@StreetDogg), https://norden.social/@StreetDogg/112568127451982234 )

After that I posted some stuff on Mastodon by myself and I reposted stuff from the same account as above on Mastodon ( [StreetDogg@norden.social](https://norden.social/@StreetDogg) ) and from other accounts. I am observing, that the only postings, which get bridged to Bluesky from my Mastodon account, are postings from my own account and postings and repostings from the account I reposted in the first place ( [StreetDogg@norden.social](https://norden.social/@StreetDogg) ), but not things I repost from other accounts than the above one.

**Comment by qazmlp** [comment]
Are the other accounts opted into Bluesky bridging too?

Bridgy Fed requires the original author to agree to cross-network sharing first. It currently also doesn't bridge fedi posts that were created before the bridge was enabled for that account, even if self-boosted later.

**Comment by turgaer** [comment]
Ahh, thank you. That makes sense. :) Sorry for the superfluous issue. I will close it.
