### ISSUE TITLE
Bluesky -> Fediverse drops attached URLs silently

### ISSUE THREAD

**Issue by whitesided** [snarfed/bridgy-fed#1126]
I follow a few accounts on Bluesky in my Mastodon account by way of bsky.brid.gy. I noticed several had posts that seem to be referring to things not shown in the post. Upon investigation I discovered these posts had URL attachments not visible once they'd been bridged.

Example post, seen via Mastodon:
<img width="498" alt="image" src="https://github.com/snarfed/bridgy-fed/assets/17487/0d7cee02-22ff-4fe0-832b-ec11dd5605b4">

If I go view [the post](https://bsky.app/profile/radleybalko.bsky.social/post/3kulek3pcn32r) on Bluesky: 
<img width="601" alt="image" src="https://github.com/snarfed/bridgy-fed/assets/17487/96bbcc60-357f-4ab5-89fd-c0036087ca5d">

**Comment by TomCasavant** [comment]
If you're referring to the quote post, that's #461 which I think recently got marked as higher priority since bluesky uses quote posts a lot more than some of the AP alternatives.

**Comment by whitesided** [comment]
> If you're referring to the quote post, that's #461 which I think recently got marked as higher priority since bluesky uses quote posts a lot more than some of the AP alternatives.

I read the start of that but didn't go far enough; you're right - [this comment](https://github.com/snarfed/bridgy-fed/issues/461#issuecomment-2094112548) mentions it being in issue in the bsky->mast direction as well.

**Comment by snarfed** [comment]
Right! Quote posts are #461, link preview embeds are #958. Feel free to follow either of those!
