### ISSUE TITLE
Undo/Delete Boosts not being federated AP => Bluesky

### ISSUE THREAD

**Issue by TomCasavant** [snarfed/bridgy-fed#1127]
Accidentally boosted a post using mastodon, removed it and then was surprised to see it was still boosted on the bluesky side a few hours later

Tested it with a few other posts and got the same result

![Screenshot_20240610_193923_Tom-Moshidon Debug.jpg](https://github.com/snarfed/bridgy-fed/assets/7014115/f930634d-1f6b-4431-ac76-f3c853d64365)

![Screenshot_20240610_193939_Tom-Moshidon Debug.jpg](https://github.com/snarfed/bridgy-fed/assets/7014115/9bdac046-b9b3-42cb-bdec-fe28d89d7180)

![Screenshot_20240610_193900_Bluesky.jpg](https://github.com/snarfed/bridgy-fed/assets/7014115/f4287f69-38ec-4705-a3be-75eb33434da0)

![Screenshot_20240610_193910_Bluesky.jpg](https://github.com/snarfed/bridgy-fed/assets/7014115/a786e757-a738-415e-9034-89868ecd48dc)

Here are the links if that helps:
https://bsky.app/profile/mmasnick.bsky.social/post/3kum5klb2rk2f
https://bsky.app/profile/samuel.bsky.team/post/3kum434yavl2g

**Comment by snarfed** [comment]
Ooh, good catch! This is almost certainly because undoing a boost is an `Undo`, not a `Delete`, and I think we only handle `Undo`s of `Follow`s right now. Should be straightforward to add support.

**Comment by snarfed** [comment]
Done! Also for likes, undoing those works now too.

(Also, this was suspiciously easy.  The diff for 22d6cef is...well, there's kind of nothing to it. Doesn't happen often, but every now and then, all the parts are already in place, and all you have to do is hook them up. Feels good man.)

**Comment by snarfed** [comment]
Also confirmed that this is working the other way, Bluesky => fediverse.
