### ISSUE TITLE
Posts get truncated, even though they would fit in the character Limit

### ISSUE THREAD

**Issue by pkreissel** [snarfed/bridgy-fed#1128]
Here ist the federated post: https://bsky.app/profile/Volksverpetzer.digitalcourage.social.ap.brid.gy/post/3kuni7pap23j2
Here is the post just manually typed: https://bsky.app/profile/volksverpetzer.de/post/3kunihi65mu26

There is no reason for truncation of this post, however it did get (...) at the end.

**Comment by snarfed** [comment]
Hmm, true! Thanks for reporting, I'll look.

**Comment by snarfed** [comment]
OK! This should be fixed ^ now. Thanks again for the report!

**Comment by qazmlp** [comment]
I just had this happen with a reply, not sure if it's the same issue: https://bsky.app/profile/Qazm.tiggi.es.ap.brid.gy/post/3kyk4fkwegxn2

**Comment by snarfed** [comment]
@qazmlp hmm, the character counting on that one looks right to me. I see 305 chars in your original Mastodon post.

One confusing bit here may be that the Mastodon and Bluesky web clients ellipsize the URL, but that's only for display. The underlying post objects themselves both have the full URL. eg in Bluesky: https://api.bsky.app/xrpc/com.atproto.repo.getRecord?repo=Qazm.tiggi.es.ap.brid.gy&collection=app.bsky.feed.post&rkey=3kyk4fkwegxn2

**Comment by snarfed** [comment]
> I see 305 chars in your original Mastodon post.

Sorry, I oversimplified. The Mastodon post object's `content` is HTML, so it's more than 305 chars. When we convert it to plain text for Bluesky - and keep the URL whole and intact, so that it's clickable and goes to the right place - the resulting text is 305 chars.

**Comment by qazmlp** [comment]
> > I see 305 chars in your original Mastodon post.
> 
> Sorry, I oversimplified. The Mastodon post object's `content` is HTML, so it's more than 305 chars. When we convert it to plain text for Bluesky - and keep the URL whole and intact, so that it's clickable and goes to the right place - the resulting text is 305 chars.

I see, but that doesn't actually match Bluesky's calculations - the character count caps at 27 for each URL. I was able to post this just fine: https://bsky.app/profile/qazm.bsky.social/post/3kyngslzfp22v
(The URL is 35741 characters.)

**Comment by snarfed** [comment]
Hah, funny. I was confused that I'd never heard of this 27 number before...turns out it's specific to the bsky.app client, not part of ATProto or the Bluesky AppView: https://github.com/bluesky-social/social-app/issues/3244 . When you include a URL in a post on bsky.app, it gets ellipsized in the post text and linked to the full URL in a facet. BF doesn't do that yet, but it could!

**Comment by qazmlp** [comment]
> Hah, funny. I was confused that I'd never heard of this 27 number before...turns out it's specific to the bsky.app client, not part of ATProto or the Bluesky AppView: https://github.com/bluesky-social/social-app/issues/3244 . When you include a URL in a post on bsky.app, it gets ellipsized in the post text and linked to the full URL in a facet. BF doesn't do that yet, but it could!

That would be helpful. Mastodon counts them as flat 23 characters instead (even shorter ones), but that's an implementation detail and remembering to count 4 extra per URL is easy enough.

**Comment by snarfed** [comment]
^ Filed a new issue, #1228
