### ISSUE TITLE
Post language should federate

### ISSUE THREAD

**Issue by simardcasanova** [snarfed/bridgy-fed#1134]
Both Bluesky and Mastodon support post languages, i.e., the user can set the language(s) in which a post is written.

Bridgy should federate this metadata, as not federating the language may greatly impact the visibility of posts that are not written in English.

From this conversation on Bluesky: https://bsky.app/profile/o.simardcasanova.net/post/3kuvhhogdp22x

**Comment by ikke-t** [comment]
In addition to visibility, also transalte button in mastodon clients don't work properly due getting wrong language from post metadata.

**Comment by snarfed** [comment]
In Bluesky, looks like this is the top-level `langs` array in `app.bsky.feed.post`, which has two-letter [ISO_639-1](https://en.wikipedia.org/wiki/ISO_639-1) language codes:

```json
          "langs": {
            "type": "array",
            "description": "Indicates human language of post primary text content.",
            "maxLength": 3,
            "items": { "type": "string", "format": "language" }
          }
```

Example posts:

https://bsky.app/profile/o.simardcasanova.net/post/3kwkeewu26s22
https://bsky.app/profile/o.simardcasanova.net/post/3kwkeewu26s22

In AS2, it's the top-level `contentMap` field, a mapping from ISO 639-1 language code to full `content`. We added that in #681.

**Comment by snarfed** [comment]
Done! Examples:
* https://indieweb.social/@snarfed.bsky.social@bsky.brid.gy/112764486613536842 => https://bsky.app/profile/snarfed.bsky.social/post/3kwxjrbrgb22q
* https://indieweb.social/@snarfed/112764489851370785 => ...bsky.app isn't showing it yet due to a Bluesky outage, I'll check back to confirm

**Comment by snarfed** [comment]
Thanks for the nudge here, all! Very good idea.

**Comment by pinage404** [comment]
The documentation doesn't mention language https://fed.brid.gy/docs (there is one mention but unrelated)

Does it support `xml:lang` with Atom feed ?
https://en.wikipedia.org/wiki/Atom_(web_standard)#Internationalization

**Comment by snarfed** [comment]
@pinage404 good idea! We don't handle `xml:lang` right now, but it would be a good feature request.
