### ISSUE TITLE
Reply to my own post is doubled?

### ISSUE THREAD

**Issue by AtiusAmy** [snarfed/bridgy-fed#1139]
The reply to my own post are doubled 

https://bsky.app/profile/AmyIsCoolz.social.atiusamy.com.ap.brid.gy/post/3kvax76tavjq2

https://bsky.app/profile/AmyIsCoolz.social.atiusamy.com.ap.brid.gy/post/3kvakcgs4jbq2

The AP side:

https://social.atiusamy.com/notes/9uoy23bt7fdf00zc

https://social.atiusamy.com/notes/9uopt8277fdf00mo

**Comment by snarfed** [comment]
Huh, that's not good. Thanks for the nudge, will look.

**Comment by AtiusAmy** [comment]
I'm closing this as it seemed to not happen outside of those two post.

**Comment by snarfed** [comment]
Hmm! OK. Thanks again for reporting, please do reopen if you see it again. Glad it's not ongoing, but still ideally we shouldn't do this at all.

**Comment by AtiusAmy** [comment]
I'll keep that in mind! Good work you're doing!
