### ISSUE TITLE
Docs: more FAQs on why profiles, follows, posts don't get bridged

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#1140]
Lots of possible reasons these happen, and it's one of the things I get pinged about most often. We have many of these FAQs in https://fed.brid.gy/docs already, but they're a bit scattered, might be worth gathering them all together in one place that's easy to point people to.

**Comment by TomCasavant** [comment]
You have an issue for sending a dm when someone opts in #1024, would it be possible to make it DM the user the reason it didn't work if it fails?

**Comment by snarfed** [comment]
Yes! Also a good idea. DMs are only partially supported across the fediverse, though, and whether people will actually receive or see them depends on a number of platform-specific settings in both the fediverse and Bluesky, so I want to do this too, and probably prioritize it, since only a subset of users will ever see any DM I send, on any platform.
