### ISSUE TITLE
The mirror from FGC.Network to Bluesky doesn't seem to work

### ISSUE THREAD

**Issue by Wolfy76700** [snarfed/bridgy-fed#1142]
Hi, I tried setting up the bridge between my [FGC.Network account](https://fgc.network/@MathiasWolfbrok) and [Bluesky](https://bsky.app/profile/did:plc:zfweyrpxwcdkb6o255ebzuk4) but so far it's not really doing much, I did follow [@bsky.brid.gy@bsky.brid.gy](https://fgc.network/@bsky.brid.gy@bsky.brid.gy) on the Fediverse but it states that the follow is "Awaiting approval". Any idea what the issue could be?

**Comment by snarfed** [comment]
Hmm, looks like the fgc.network server is unhappy. We're getting HTTP 500s for every AP activity we try to deliver to https://fgc.network/users/MathiasWolfbrok/inbox, including the `Accept` for that follow, our own `Follow` from @bsky.brid.gy@bsky.brid.gy, and bridged posts from Bluesky. Maybe have your admin check the server logs and see what's going on?

It's possible this is an interop issue between Bridgy Fed and Soapbox; cc @alexgleason? 500 makes me guess it's a server issue more than project interop, but not sure.

**Comment by alexgleason** [comment]
@Wolfy76700 If @snarfed is getting 500 errors from your server, you can run `journalctl -eu pleroma` to see what those errors are.

**Comment by Wolfy76700** [comment]
@alexgleason We’re thinking it might be Cloudfare blocking the requests, the admin has temporarily disabled it but if that didn’t work then I won’t try to go further into the issue and just close it as apparently no error was reported on our side.

**Comment by snarfed** [comment]
Hmm. Cloudflare can indeed be tricky sometimes for fronting fediverse servers, but it wouldn't return HTTP 500 responses. That symptom still makes me think something's up with your server.

**Comment by alexgleason** [comment]
@Wolfy76700 Try: `journalctl -u pleroma --since "3 days ago" | grep "error"`

**Comment by Wolfy76700** [comment]
Closing this issue as I am not the server admin and cannot do debug operations on said server.
