### ISSUE TITLE
[Request] return account link after follow of bridgy

### ISSUE THREAD

**Issue by fabiscafe** [snarfed/bridgy-fed#1143]
The hardest part was to get the account of the other side after follow. I don't know anything about bluesky, so the setup of the account over there was completely unknown to me and it took someone to point this out to me.

So I'd suggest to "answer" with an link to the account on the other side, after you followed bridgy.
In more detail: 
* If you are on bluesky, following bridgy should respond with a DM that tells you the account link on the fediverse
* If you are on the fediverse, following bridgy should respond with a DM that tell you the account link on bluesky

Something like "Hey :wave: , thanks for following. Your account is ready to use: https://… and will mirror your postings from now on"

**Comment by qazmlp** [comment]
Bridgy Fed only creates these network-agnostic status pages for bridged accounts, not web pages on the respective destination network: https://fed.brid.gy/ap/@Qazm@tiggi.es

I suppose ATProto is centralised enough in practice to provide a Bluesky link there, though.

**Comment by snarfed** [comment]
@fabiscafe yes! Great idea, this is https://github.com/snarfed/bridgy-fed/issues/1024 , I'll merge in there. Especially now that Bluesky supports DMs (and yes, including programmatically), we should start using those more as UI like this for the bridge.

@qazmlp is right, the user pages on fed.brid.gy are based on the source network, and generally also have links and handles for everywhere they're bridged.
