### ISSUE TITLE
AP => AT Bridged AP accounts when replying to another bridged AP accounts aren't bridged to BSKY

### ISSUE THREAD

**Issue by AtiusAmy** [snarfed/bridgy-fed#1147]
Says what it says on the tin. I replicated it here:

AP side:
https://social.atiusamy.com/notes/9uuxrld97fdf07fi

AT side:
https://bsky.app/profile/atiusamy.social.atiusamy.com.ap.brid.gy/post/3kvlimtstgb72

As you can see here, there's no reply on the BSKY side of things.

**Comment by snarfed** [comment]
Yes! This sounds like https://github.com/snarfed/bridgy-fed/issues/1047 ...?

**Comment by AtiusAmy** [comment]
Woops, I don't know the right terms for it and couldn't find that issue! closing as duplicated
