### ISSUE TITLE
ATProto Quote Posts => AP: RE link has reverted to bsky.brid.gy/convert URL

### ISSUE THREAD

**Issue by hybridhavoc** [snarfed/bridgy-fed#1154]
This was working correctly before, but this afternoon I started noticing the links were back to the bsky.brid.gy/convert URL which just leads to some JSON.

Sample on Mastodon: https://darkfriend.social/@mmasnick.bsky.social@bsky.brid.gy/112679870992024030

![image](https://github.com/snarfed/bridgy-fed/assets/53440374/50fdccb5-e031-4c09-9eee-960d6c2c69c0)

**Comment by snarfed** [comment]
Argh, thanks for reporting! This may be due to https://github.com/snarfed/bridgy-fed/issues/1047#issuecomment-2190063293. I'll look.

**Comment by snarfed** [comment]
Ok, should be fixed now. Thanks again for filing the issue!

**Comment by snarfed** [comment]
Had to roll this back, will look again tomorrow.

**Comment by snarfed** [comment]
OK, I've updated and re-deployed, this should be fixed. Let me know if you see bad quote links on new posts!
