### ISSUE TITLE
Bridged account halted

### ISSUE THREAD

**Issue by lupomancer** [snarfed/bridgy-fed#1157]
I think I may have broken my connection to the Bridger bot by reposting too many things in too short a timespan.

[@sig.furries.club.ap.brid.gy ](https://bsky.app/profile/sig.furries.club.ap.brid.gy) which is bridged from [@sig@furries.club](https://furries.club/@sig) has completely halted mirroring, just showing that the account exists.

I (maybe stupidly) followed the bridge before reposting all my posts from my previous mastodon account [@lupomancer@furries.club](https://furries.club/@lupomancer). Now my follow status for the Mastodon end of the bridge is stuck “pending” along with all bridged users.

**Comment by snarfed** [comment]
Hi! Sorry for the trouble. Looks like https://furries.club/@sig is a new account that was just created. One of BF's spam filters is account age: [it only bridges accounts that are at least two weeks old](https://fed.brid.gy/docs#fediverse-cant-find). Feel free to check again after that!

**Comment by lupomancer** [comment]
The account is a couple days over two weeks old and it still doesn’t appear to be updating on BSKY. Is there summering that needs to be done to kick off the bridging?

**Comment by snarfed** [comment]
@lupomancer try unfollowing and re-following @bsky.brid.gy@bsky.brid.gy ?

**Comment by lupomancer** [comment]
I’ve tried doing it over a matter of a couple seconds, but I’ll try unfollowing and leaving it for a while before refollowing

**Comment by snarfed** [comment]
Yup, it definitely is "up and running even though it isn't": https://fed.brid.gy/ap/@sig@furries.club It has an ATProto repo internally, it's committing to that repo and serving those commits to the Bluesky relay. I'm not sure yet why the relay isn't ingesting them. 😕

**Comment by snarfed** [comment]
Think I figured it out. Bluesky made some networking changes on their end yesterday and their relay may have stopped reconnecting from BF after it disconnects. That happened yesterday evening (PT), and it happened again early this morning. I'm (hopefully) talking with them about it: https://discord.com/channels/1097580399187738645/1097580399187738648/1261015863998550037

**Comment by snarfed** [comment]
Yup, you're up and running now. Sorry for the trouble!
