### ISSUE TITLE
Replies from mastodon to bluesky doubles on bluesky

### ISSUE THREAD

**Issue by DoktorZjivago** [snarfed/bridgy-fed#1161]
Seen several replies from mastodon where the reply gets double posted on bluesky; like here for example: https://bsky.app/profile/KarroH.mastodon.nu.ap.brid.gy/post/3kw7oadyfwg62

**Comment by snarfed** [comment]
Yes! Sorry, looks like there's an occasional race condition. Merging into #1063.
