### ISSUE TITLE
Translate blocks

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#1162]
When we first looked at blocks in #713, we concluded that the main effect of a block, on either side of the bridge, was handled natively within that network. The blocker would no longer see the blockee, and the blockee's interactions wouldn't reach the blocker. So, we didn't necessarily need to translate blocks.

This is true, but the blockee still gets to interact with the blocker's content on the blockee's side of the bridge. We can prevent that by translating blocks. We should do that!

**Comment by qazmlp** [comment]
Oh, that's surprising. I had (mis)interpreted the "just like with native users" in the docs to mean that the block would be visible to them too.

**Comment by snarfed** [comment]
Got this mostly working, fediverse => Bluesky block and unblock and Bluesky => fediverse block.

* fediverse => Bluesky
  * https://indieweb.social/1fae4aa8-7eb2-48a4-a881-53ef6ab7ec1b => at://did:plc:bg5udl25mvzg3rt7l5n2hzet/app.bsky.graph.block/3kwn775xutjb2
  * https://indieweb.social/users/snarfed#blocks/15669/undo
* Bluesky => fediverse
  * at://did:plc:3ljmtyyjqcjee2kpewgsifvb/app.bsky.graph.block/3kwn7no3i3h2h => https://bsky.brid.gy/convert/ap/at://did:plc:3ljmtyyjqcjee2kpewgsifvb/app.bsky.graph.block/3kwn7no3i3h2h

**Comment by snarfed** [comment]
Got Bluesky => fediverse undo block working!
