### ISSUE TITLE
Several accounts not bridged bsky > masto

### ISSUE THREAD

**Issue by DoktorZjivago** [snarfed/bridgy-fed#1164]
Several Swedish accounts tried to bridge from bsky > mastodon the last two days, however several accounts didn't get bridged, although some did, cannot really see a pattern. Accounts that didn't get bridged:

@matsgz.bsky.social
@hardcorebibblo.bsky.social
@gravadersdagar.bsky.social
@ramscoop.bsky.social
@allalleriall.bsky.social
@larsa66.bsky.social
@solflickan.bsky.social
@barbromaria.bsky.social
@linbro.bsky.social
@huldabianca.bsky.social

**Comment by snarfed** [comment]
@qazmlp is right: for Bluesky accounts that followed @ap.brid.gy yesterday, roughly 7/3 17:00 - 7/4 07:00 GMT, those follows probably didn't enable the bridge. Please ask them to unfollow and refollow the bridge, hopefully that should fix it.

Sorry for the trouble!

**Comment by snarfed** [comment]
Tentatively closing. Feel free to reopen!
