### ISSUE TITLE
Bluesky replies by author creating a thread are not propagated to mastodon

### ISSUE THREAD

**Issue by stepheneb** [snarfed/bridgy-fed#1179]
Replies by the original author on Bluesky don't appear to end up on mastodon.

I follow user @kenwhite on bluesky via bridgy-fed: @kenwhite.bsky.social@bsky.brid.gy

A recent post by @kenwhite had an original post and two replies from the author: https://bsky.app/profile/kenwhite.bsky.social/post/3kx6hnlq3ek2k

On my mastodon account only the initial post appears.

https://ruby.social/deck/@kenwhite.bsky.social@bsky.brid.gy/112780101582901819

<img width="588" alt="image" src="https://github.com/user-attachments/assets/90a5125b-d48f-4c90-9419-22dbb9055097">

**Comment by snarfed** [comment]
Something's going on with either his handle or Bluesky's infrastructure or both right now, not sure which. https://bsky-debug.app/handle?handle=%E2%80%AAkenwhite.bsky.social%E2%80%AC

**Comment by snarfed** [comment]
Oh never mind, that was an odd copy paste with some invisible Unicode chars, https://bsky-debug.app/handle?handle=kenwhite.bsky.social and https://web.plc.directory/did/did:plc:s6j27rxb3ic2rxw73ixgqv2p look ok. Will look.

**Comment by snarfed** [comment]
Looks like this is a bug. Thank you for reporting!

**Comment by snarfed** [comment]
Fixed. Thanks again!
