### ISSUE TITLE
AP -> AT Some replies become post?

### ISSUE THREAD

**Issue by AtiusAmy** [snarfed/bridgy-fed#1181]
I just noticed this, but some of my replies became their own post. For ex:

https://social.atiusamy.com/notes/9vdetlseu2g408ox

https://bsky.app/profile/AmyIsCoolz.social.atiusamy.com.ap.brid.gy/post/3kwlyx3xhl7b2

**Comment by snarfed** [comment]
Oops, yes! Thanks for reporting. Looks like we're not quite smart enough about self replies where the upstream thread isn't bridged. Will fix.

**Comment by snarfed** [comment]
I think this was fixed by #1166; the fix there went out on 7/9, a few days after your example. But I'm also adding another layer that will help with snarfed/granary@9bf7cb7.
