### ISSUE TITLE
Bridgy control panel monitoring fediverse account after blocking, then refollowing bridge

### ISSUE THREAD

**Issue by lupomancer** [snarfed/bridgy-fed#1183]
This is likely related to #1130, but I'm not entirely sure so I don't want to pollute the main thread.

It looks like bridgy is monitoring my fediverse account after I've blocked, then refollowed it.
The [control panel is still monitoring updates](https://fed.brid.gy/ap/@spotty@cubhub.social).

Would there be any way to manually re-allow the bridging to BSKY? Is there any useful information here that might help with the automated process?

**Comment by snarfed** [comment]
Hi @lupomancer! Yup, it's expected that Bridgy Fed still receives activities from your fediverse account after you block the Bluesky bot user. Followed up in https://github.com/snarfed/bridgy-fed/issues/1130#issuecomment-2229901486.

**Comment by snarfed** [comment]
Merging into #1130.
