### ISSUE TITLE
web <=> Bluesky: Allow specifying `rkey` for Bluesky posts

### ISSUE THREAD

**Issue by imax9000** [snarfed/bridgy-fed#1189]
Having a predictable or manually specified `rkey` would allow a much smoother integration for things like https://github.com/aendra-rininsland/blue-comments

Right now one has to first create a post, then wait for Bridgy to relay it to Bluesky, get the `rkey` of the created post, and only then add it to the page. If `rkey` was known in advance, that would remove the need for this round-trip.

**Comment by snarfed** [comment]
Apologies @imax9000, I'm going to close this as not planned. This is just too low-level of an operation for Bridgy Fed to realistically support. Sorry!
