### ISSUE TITLE
AP -> AT Quotes don't get bridged if the post is long

### ISSUE THREAD

**Issue by AtiusAmy** [snarfed/bridgy-fed#1197]
I'm not sure whats going on here:

https://bsky.app/profile/AmyIsCoolz.social.atiusamy.com.ap.brid.gy/post/3kxtqc2uxwse2

https://social.atiusamy.com/notes/9vzzkc3q8efj00e3

**Comment by snarfed** [comment]
Huh, interesting! Thanks for filing.

**Comment by snarfed** [comment]
Hey @AtiusAmy, have you seen any other instances of this? I'm sure it's a real bug, not a one-time-only glitch, but I'm still curious.

**Comment by AtiusAmy** [comment]
> Hey @AtiusAmy, have you seen any other instances of this? I'm sure it's a real bug, not a one-time-only glitch, but I'm still curious.

Not at the moment but lemme try

**Comment by AtiusAmy** [comment]
https://bsky.app/profile/atiusamy.social.atiusamy.com.ap.brid.gy/post/3ky33z6lpozb2

Just posted the same message and it appeared like this

I can also do the same with messages that are very long

https://bsky.app/profile/atiusamy.social.atiusamy.com.ap.brid.gy/post/3ky342wonbfk2

**Comment by snarfed** [comment]
Thanks!

**Comment by snarfed** [comment]
snarfed/granary@86fd3c9fa5fb576a8cace22401866aae0fc1e1aa. I think this is fixed, shold be deployed in ~5m, feel free to try again then.
