### ISSUE TITLE
Web feed polling: better error handling

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#1202]
Right now, when we fetch and process an RSS/Atom feed, there are a number of classes of errors that will stop us from polling it in the future. We also don't create a poll task if we have trouble creating a user object and then later create it ok. We need to be better about adding the next poll-feed task in those cases.

**Comment by snarfed** [comment]
Sure! Just let me know which site here, I can kick it.

**Comment by ZipMartini** [comment]
> Sure! Just let me know which site here, I can kick it.

https://zipmartini.photography

I apologize, I didn't realize a path couldn't be set; the application/rss+xml tag I set on the index.html should do the trick.
It would be nice if these errors were transparent so a user could self-diagnose a failure and confirm that everything is well-formed before switching everything on.

**Comment by snarfed** [comment]
@ZipMartini sure! And agreed!

Next step is to switch your Atom `id`s to URIs, which Bridgy Fed needs. http://www.atomenabled.org/developers/syndication/#requiredEntryElements

**Comment by snarfed** [comment]
Also I've made the web site form at https://fed.brid.gy/#enter-web-site now re-poll, so feel free to use that to test once you've updated your feed!

**Comment by ZipMartini** [comment]
> Also I've made the web site form at https://fed.brid.gy/#enter-web-site now re-poll, so feel free to use that to test once you've updated your feed!

That seemed to work!  Well, at least on the Bluesky end; there are no posts going out to the Fediverse.  I'm sure I screwed something up [setting up that .htaccess](https://fed.brid.gy/docs#fediverse-enhanced) file (although it's pretty much verbatim what's in the Apache example).  I notice that every time I pull up my Fediverse profile, it then redirects back to my website.  I probably shouldn't be trying anything this advanced... just wait until I try selfhosting a PixelFed instance on this thing.

**Comment by snarfed** [comment]
Bridgy Fed only delivers posts to fediverse instances where you have at least one follower: https://fed.brid.gy/docs#only+delivers

> I notice that every time I pull up my Fediverse profile, it then redirects back to my website.

If you're loading a remote URL directly on an instance where you're not logged in, https://mastodon.social/@z@zipmartini.photography , then yeah, that's just what many fediverse servers do. Try searching for @z@zipmartini.photography on an instance where you're logged in and then click on the profile in the search results.

**Comment by ZipMartini** [comment]
Ah, I should have read the docs more closely, my bad.
I don't want to turn this issue into my private tech support -- the re-polling seems to have worked -- but is it expected behavior that the Fediverse bridge only shows what's contained in the `title` tag and then the `id` tag, but not what's in the `content` tag? The Bluesky mirror _does_ show the contents of the `content` tag.  I couldn't find any documentation about exactly which elements of the RSS are published out, or if there are differences if `entry` or `item` tags are used as the enclosure, or if there's differences between RSS and Atom.

![Screenshot_20241119-230446](https://github.com/user-attachments/assets/6918db47-4fdf-4935-81f9-a6909f005a28)

**Comment by snarfed** [comment]
> is it expected behavior that the Fediverse bridge only shows what's contained in the `title` tag and then the `id` tag, but not what's in the `content` tag?

Depends on the fediverse server, but often sadly yes: https://fed.brid.gy/docs#Mastodon+currently+shows

**Comment by snarfed** [comment]
This is largely fixed, and also if a site isn't polling, entering it into https://fed.brid.gy/web-site now recreates the poll task.
