### ISSUE TITLE
web.brid.gy internal server error

### ISSUE THREAD

**Issue by TomCasavant** [snarfed/bridgy-fed#1203]
Not a huge issue, I was just trying to bridge an RSS feed from a local news site (https://abc6onyourside.com/) it said something about being unable to find a referenced image file (sorry, didn't think to copy the message) and then I got an internal server error:
![image](https://github.com/user-attachments/assets/096d3f33-ce0f-4887-a97b-a5047aa98e00)

Plugged in the same site again and it just takes me directly to the internal server error.

**Comment by snarfed** [comment]
Lol, that site itself is 500ing: https://abc6onyourside.com/

Not an excuse for BF itself to 500, of course!

**Comment by snarfed** [comment]
Ah, their 500 is due to Firefox's tracking protection feature. They load ok in Chrome, and in Firefox with that turned off.
