### ISSUE TITLE
WebFinger should ignore stored users with status != None

### ISSUE THREAD

**Issue by DoktorZjivago** [snarfed/bridgy-fed#1215]
Still seeing several accounts on bluesky who follows ap.brid.gy, and gets followed by the account, but no mirror gets created on the fediverse. Latest a fellow Swede on bluesky bassesbasta.bsky.social who have no bridged account and doesn't really find a reason why. Anything they can do to try to make it work?

**Comment by snarfed** [comment]
Hmm! Have they checked everything on https://fed.brid.gy/docs#troubleshooting ?

**Comment by snarfed** [comment]
If so, the next thing they can try is unfollow and re-follow ap.brid.gy.

**Comment by DoktorZjivago** [comment]
Thanks! Yes they tried to re-follow but still no effect. Is it still that "hide account from logged out view" makes the bridge not working? If so, that might be the case.

**Comment by snarfed** [comment]
Interesting. That account used to have a different DID, https://web.plc.directory/did/did:plc:nxgbz3zl3dfad7ghyvwroiwi , which no longer has an ATProto repo. They switched to a new one, https://web.plc.directory/did/did:plc:onlmd532kfzrtqb3w2r4mfre , which is serving fine, and working ok in BF, https://fed.brid.gy/bsky/did:plc:onlmd532kfzrtqb3w2r4mfre , but our WebFinger is still trying to use the old one. Hopefully an easy fix. Thanks for reporting!

**Comment by DoktorZjivago** [comment]
Oh yeah that's right! He deleted his old account a while back, but created a new account recently, with the same username since it was available again.

**Comment by snarfed** [comment]
^ Fix should be deployed in ~10m.
