### ISSUE TITLE
Enable following of users, even if they did not consent to bridge

### ISSUE THREAD

**Issue by pkreissel** [snarfed/bridgy-fed#1217]
The question about consent is about federating the POSTS of a user. 
Even if this consent is not given, we could federate only the profile. The profile could show a description like: "This user is not yet available for federation". We dont need to federate the profile picture. So just an empty profile. 

But when the user then does decide to federate, his social graph would already be ready. 

The advantage of this would be: I could just follow all people I already follow on Bluesky. Then - whenever they enable federation - I would already follow them. 

Currently the problem is, that I would have to check weekly, whether or not my following already federates.

**Comment by snarfed** [comment]
I definitely feel your pain! Waiting for and checking whether people have enabled the bridge is inconvenient.

One big catch here is that unlike search in most fediverse servers, Bluesky search only uses its own index. It doesn't make any external requests to see if a new federated user exists. So to do what you want, Bridgy Fed would effectively need to crawl the _entire_ fediverse, ongoing, and push every new user it finds into Bluesky. That's not really feasible, or at least, it's not something I personally plan to to build and run.

Apart from that...

> The question about consent is about federating the POSTS of a user.

This is one interpretation, but many people who wanted consent for bridging wouldn't agree. Many of those people expect consent before bridging any part of their account, including name, handle, etc.
