### ISSUE TITLE
log status is `complete`, but no reply was received

### ISSUE THREAD

**Issue by kwaa** [snarfed/bridgy-fed#122]
Hello! since the Discord `#indieweb-dev` channel doesn't seem to be bridging my messages correctly, I'm trying to ask question here.
My blog has been configured with Atom(WebSub), `/.well-known/` redirection, published a reply post and sent Webmention to fed.brid.gy, with log status of complete, but the instance did not receive any reply.

I can try to provide more information on instances if needed. :)

- Source: https://kwaa.dev/indieweb/test
- Target (Pleroma 2.3.0 / Soapbox BE 1.1.1 / Soapbox FE 1.3.0): https://kwaa.moe/@kwa/posts/AHrkHdpeS5r6Snvwoq
- Log: https://fed.brid.gy/log?key=https%3A%2F%2Fkwaa.dev%2Findieweb%2Ftest+https%3A%2F%2Fkwaa.moe%2Fobjects%2Fcbe6d8d5-11e5-4b1e-b8ac-56be764dd773&start_time=1648456557

**Comment by snarfed** [comment]
Thanks for the detailed report! Bridgy Fed's support for Pleroma is unclear right now. Details in https://github.com/snarfed/bridgy-fed/issues/12 . It seems close, but it's probably not all the way there yet. In this case, Bridgy Fed sent the correct AP request to your instance's inbox, and it returned 200, so I don't know why the reply isn't showing up. Let me know if you debug and figure anything out!

**Comment by kwaa** [comment]
I made a third attempt at.
Source: https://kwaa.dev/indieweb/fed
Target: https://kwaa.moe/notice/AHrkHdpeS5r6Snvwoq
Log: https://fed.brid.gy/log?key=https%3A%2F%2Fkwaa.dev%2Findieweb%2Ffed+https%3A%2F%2Fkwaa.moe%2Fobjects%2Fcbe6d8d5-11e5-4b1e- b8ac-56be764dd773&start_time=1648562734

But the difference is that this time I have the full instance debug logs, and some of them are of great concern to me:

```
Mar 29 10:05:32 mix[1425178]: 10:05:32.559 request_id=FuDfEh__XeO_Al0AAorB [debug] No signature header!
Mar 29 10:05:32 mix[1425178]: 10:05:32.622 request_id=FuDfEiPew-pNNNEAAorR [debug] No signature header!
Mar 29 10:05:33 mix[1425178]: 10:05:33.049 request_id=FuDfEj1GXrJlldUAAorh [debug] No signature header!
Mar 29 10:05:34 mix[1425178]: 10:05:34.026 request_id=FuDfEmMQTXhdwgkAAorx [debug] Could not validate against known public keys: {:error, {:error, "acct:kwaa.dev@kwaa.dev"}}
Mar 29 10:05:34 mix[1425178]: 10:05:34.026 request_id=FuDfEmMQTXhdwgkAAorx [debug] Signature missing or not from author, relayed Create message, fetching object from source
```

Unfortunately I don't really understand how activitypub/pleroma works, so I uploaded the logs to [pastebin](https://pastebin.com/9VJxs7hb).

**Comment by snarfed** [comment]
Thanks! I don't have much experience with Pleroma, and I don't have my own instance to test against, but I'll look at some point and see if I can find anything.

**Comment by snarfed** [comment]
Ah, I do see one issue. kwaa.dev is currently redirecting `/.well-known/*` to Bridgy Fed with HTTP 308, which is unusual, and based on the pastebin log, Pleroma may not support it. Try 302 or 301 instead?

Key snippet from the log:
```
Mar 29 10:05:34 mix[1425178]: 10:05:34.024 request_id=FuDfEmMQTXhdwgkAAorx [debug] Couldn't finger acct:kwaa.dev@kwaa.dev
Mar 29 10:05:34 mix[1425178]: 10:05:34.025 request_id=FuDfEmMQTXhdwgkAAorx [debug] {:ok, ..., query: [], status: 308, url: "https://kwaa.dev/.well-known/webfinger?resource=acct:acct:kwaa.dev@kwaa.dev"}}
```

**Comment by kwaa** [comment]
Ok, looking forward to good news! in addition, I can provide an idle VPS for running Pleroma instances for testing if needed.

**Comment by kwaa** [comment]
> Ah, I do see one issue. kwaa.dev is currently redirecting `/.well-known/*` to Bridgy Fed with HTTP 308, which is unusual, and based on the pastebin log, Pleroma may not support it. Try 302 or 301 instead?
> 
> Key snippet from the log:
> 
> ```
> Mar 29 10:05:34 mix[1425178]: 10:05:34.024 request_id=FuDfEmMQTXhdwgkAAorx [debug] Couldn't finger acct:kwaa.dev@kwaa.dev
> Mar 29 10:05:34 mix[1425178]: 10:05:34.025 request_id=FuDfEmMQTXhdwgkAAorx [debug] {:ok, ..., query: [], status: 308, url: "https://kwaa.dev/.well-known/webfinger?resource=acct:acct:kwaa.dev@kwaa.dev"}}
> ```

ok i will try it

**Comment by kwaa** [comment]
🤔 It no longer appears as `Couldn't finger acct:kwaa.dev@kwaa.dev` now, but still no reply is received.

[Source](https://kwaa.dev/indieweb/tomoe)
[Target](https://kwaa.moe/notice/AHrkHdpeS5r6Snvwoq)
[Bridgy Fed Log](https://fed.brid.gy/log?key=https%3A%2F%2Fkwaa.dev%2Findieweb%2Ftomoe+https%3A%2F%2Fkwaa.moe%2Fobjects%2Fcbe6d8d5-11e5-4b1e-b8ac-56be764dd773&start_time=1648566039)
[Pleroma Log](https://pastebin.com/Q7gdAc83)

**Comment by snarfed** [comment]
Progress! And you're right, that `No signature header` from Pleroma does seem like the next problem. It's also where we ended up in https://github.com/snarfed/bridgy-fed/issues/12#issuecomment-799787738, trying to get Pleroma working there too, so this is likely the same issue. We still haven't fully gotten Pleroma working yet. We believe Bridgy Fed is sending the `Authorization` header correctly, since it's working with other AP servers like Mastodon and GNU Social, so we don't yet know why Pleroma is unhappy. Thank you for the details here, definitely keep us posted if you make any more progress!

**Comment by kwaa** [comment]
Thanks for the reply. btw, does the regular [Bridgy](https://brid.gy) work? this seems to be an alternative until the issue is solved.

**Comment by snarfed** [comment]
Yes! Normal Bridgy seems to work ok with Pleroma, as far as we can tell. More in https://github.com/snarfed/bridgy-fed/issues/12#issuecomment-973231456
