### ISSUE TITLE
atproto event stream: profile records missing from commit CAR diff

### ISSUE THREAD

**Issue by bnewbold** [snarfed/bridgy-fed#1229]
I'm seeing a trickle of errors on the Relay firehose where a record is missing from the commit event CAR diff. They seem to be coming from the bridgy-fed PDS. I haven't confirmed if this issue is coming from the PDS, or could be an internal thing in the Relay, but i'm pretty confident it is coming from the PDS event stream.

These are all either profile records (`app.bsky.actor.profile/self`) or chat declarations (`chat.bsky.actor.declaration/self`). There is a mix of "update" and "create" events.

There are on the order of hundreds of these a day. A weird thing is that a few accounts (DIDs) have dozens or hundreds of the same event error daily.

A common pattern we've seen with this specific error is the record block not being included in the CAR because it was previously included in a previous CAR file. For example, a profile was edited, then edited again returning the record to the exact state it was previously. We don't have the semantics totally formalized, but the current expectation is that any record which "changed" in a commit should be included in the CAR diff, along with all intermediate MST nodes referencing such records.

**Comment by snarfed** [comment]
Hmm, sorry for the trouble, thanks for filing! I thought we fixed this a bit ago in https://github.com/snarfed/bridgy-fed/issues/1016#issuecomment-2118868137 / snarfed/arroba@e4d832b by always emitting records in every firehose event...but I guess not? Interesting that it's always `self` records too, that's probably a clue. I'll look!

**Comment by snarfed** [comment]
Think I found it. Looks like snarfed/arroba@615acb181001e5af6d8593f3d8e6eb4e70774b02 was the culprit, that commit is wrong in at least a couple ways, both the content and the message. 😆 I've undone it, deploy should be done in ~5m, let's see if that stops the missing records.

**Comment by snarfed** [comment]
Related: https://github.com/bluesky-social/atproto/discussions/2165

**Comment by snarfed** [comment]
Tentatively closing, I think this is fixed. @bnewbold feel free to reopen!
