### ISSUE TITLE
Bluesky => AP: Private posts in Bsky become public in the Fediverse

### ISSUE THREAD

**Issue by last-partizan** [snarfed/bridgy-fed#1240]
Hello

I'm following a bsky user with private profile, but enabled Fediverse bridging by following https://bsky.app/profile/ap.brid.gy

But, these posts does not appear as "Followes only" in Fediverse, and i can repost them even without knowing they were supposed to be private.

Looking at the docs: https://fed.brid.gy/docs

> Who can see me and my stuff?  
> Only the people who can already see you and your stuff, without bridging. Bridgy Fed only bridges fully public data, so if your account is private or protected or followers-only, it won't (can't!) bridge your account at all.

That's probably outdated info, as it can bridge followers-only posts, but forgets to set appropriate privacy level.

**Comment by snarfed** [comment]
Hi! Thanks for asking, this probably does deserve more documenting.

Bluesky doesn't really have private profiles or posts. From https://bsky.social/about/blog/5-19-2023-user-faq :

> Bluesky is a public social network. Think of your posts as blog posts – anyone on the web can see them, even those without an [account]. An [account] simply grants access to the service we’re running that lets you publish a post yourself. (Developers familiar with the API can view all posts regardless of whether they have an account themselves.)

For this account, I'm guessing you mean they turned on the setting to show their profile only to logged in users. Even so, anyone can create a Bluesky account and see them and their posts. People can also see them in third party Bluesky clients without creating an account at all.

This is very different from followers-only posts in the fediverse, which actually are restricted to only followers.

I'll add more detail on this to the docs!

**Comment by TomCasavant** [comment]
Maybe off topic but do the Bluesky RSS feeds include the logged-in only posts?

**Comment by snarfed** [comment]
Got me, that would be interesting to find out.

**Comment by TomCasavant** [comment]
hm, it looks like they don't generate any RSS feed for logged-in only users (it's also much more difficult to find the DID of the accounts who are marked as logged-in only because the page source doesn't show it anywhere, had to find it through the API)

**Comment by snarfed** [comment]
Thanks! Also https://internect.info/ is useful for finding DIDs
