### ISSUE TITLE
Bug: infinite redirects on my user page `www.jvt.me`

### ISSUE THREAD

**Issue by jamietanna** [snarfed/bridgy-fed#1244]
Hey! As per the `#dev` chat I noticed today that my Bridgy Fed Feed hasn't been loading since Tuesday - https://fed.brid.gy/web/www.jvt.me shows "page isn't redirecting correctly" in Firefox and a similar issue for Chrome

**Comment by jamietanna** [comment]
It looks like it's redirecting from `/www.jvt.me` to `/jvt.me` and back

**Comment by jamietanna** [comment]
https://github.com/snarfed/bridgy-fed/commit/479acea6576dceee9e2993e04daa2b250ead4b44 could be a candidate for what's introduced this?

**Comment by snarfed** [comment]
Fixed! Oddly a bit of metadata on your account got set wrong. Not sure how, but I fixed that, and the code itself seems ok, so 🤷

**Comment by jamietanna** [comment]
Thanks @snarfed 🚀
