### ISSUE TITLE
Blocked ap.brid.gy from bsky, still getting self-notifications

### ISSUE THREAD

**Issue by fluffy-critter** [snarfed/bridgy-fed#1253]
I use brid.gy publish to post links to my bluesky profile at `@fluffy.beesbuzz.biz`. Said profile has blocked `@ap.brid.gy`, but even then I am still receiving webmentions from it back to the original page, and I would like not to.

I do still want mentions from *other* profiles on bsky, just not from my own. Technically I'd also like the ability to send mentions to other sites when I post from bsky so if I could only have ap.brid.gy not post mentions back to myself that'd be great, but I don't use bsky much directly so this is a lower priority than simply not having these spurious mentions come in.

On https://fed.brid.gy/web/beesbuzz.biz/notifications it looks as if the notifications are being registered to a deprecated bsky username (they're supposedly coming from `@beesbuzz.biz` rather than from `@fluffy.beesbuzz.biz`) so perhaps that has something to do with it.

**Comment by snarfed** [comment]
> I use brid.gy publish to post links to my bluesky profile at `@fluffy.beesbuzz.biz`. Said profile has blocked `@ap.brid.gy`, but even then I am still receiving webmentions from it back to the original page, and I would like not to.

Sorry for the trouble! Can you give me an example webmention?

(Also fwiw I deal with this too, I routinely have to delete my own self-webmentions like this. Yours may be a different root cause, but regardless, BF may not currently have a way to prevent them.)

> On https://fed.brid.gy/web/beesbuzz.biz/notifications it looks as if the notifications are being registered to a deprecated bsky username (they're supposedly coming from `@beesbuzz.biz` rather than from `@fluffy.beesbuzz.biz`) so perhaps that has something to do with it.

Yeah that's #1074, BF doesn't handle Bluesky handle changes well yet, but should be unrelated to this.

**Comment by fluffy-critter** [comment]
I've deleted most of the ones I received, but an example one is at https://bsky.brid.gy/convert/web/at://did:plc:gvyalihuzofyntqt2sp5bdjw/app.bsky.feed.post/3ky3ioykubh2l%23bridgy-fed-create

**Comment by snarfed** [comment]
I've tweaked your account, BF shouldn't send you webmentions from your Bluesky account any more.

You may hit other rough edges using Bridgy Fed and Bridgy classic together, that's not a scenario I've fully planned for or tested much. We can see!

**Comment by fluffy-critter** [comment]
Thanks.

What is your recommendation for crossposting my blog posts to bluesky while also receiving webmentions from other people posting on bluesky?

**Comment by snarfed** [comment]
@fluffy-critter I guess it depends. Bridgy classic uses your Bluesky account that you control, and it backfeeds [replies, likes, and reposts](https://brid.gy/about#which). Bridgy Fed uses its own Bluesky account for your site that you can't control, and it backfeeds replies, likes, reposts, quote posts, and @-mentions. Neither one backfeeds links to your site in other people's posts.
