### ISSUE TITLE
Request AP > BSKY account deleted

### ISSUE THREAD

**Issue by lupomancer** [snarfed/bridgy-fed#1256]
I was doing some testing for if an account can be bridged on day 14 of mastodon account age (turns out no)

both of the following accounts can be deleted. I’ve tried deleting one account and blocking the bridge in the other and they’re both still sticking around so I think they just need to be manually handled unfortunately (sorry!)

https://bsky.app/profile/soggy.cubhub.social.ap.brid.gy
https://bsky.app/profile/siggy.cubhub.social.ap.brid.gy

**Comment by snarfed** [comment]
Done!
