### ISSUE TITLE
BSKY => AP account halted

### ISSUE THREAD

**Issue by lupomancer** [snarfed/bridgy-fed#1260]
Looks like [this account](https://fed.brid.gy/bsky/hansfaffing.bsky.social) isn't sending over actions properly, by guess is the user (a friend of mine) followed, unfollowed, then refollowed the bridge.

Additionally, thanks for always taking time for these little one-off issues <3 I know you've got bigger fish to fry so I appreciate it!

**Comment by lupomancer** [comment]
Okay, interesting, thanks for looking at that. 

I just notice there's a ton of non-bridged posts and replies in the past, but I suppose that could be from the period where the user wasn't following the bridge. 
I'm not familiar with what happens during the period where a user has unfollowed the bridge. Does it just monitor the account and resume bridging when they re-follow?

**Comment by snarfed** [comment]
Un-following the bridge account doesn't do anything, but *blocking* it disables bridging, https://fed.brid.gy/docs#opt-out . If they did that, then un-blocked it and re-followed it, then yes, it would just resume from then.

**Comment by lupomancer** [comment]
Awesome, thanks for the info!
