### ISSUE TITLE
follow request response "{error: …}"

### ISSUE THREAD

**Issue by mro** [snarfed/bridgy-fed#1269]
```
{
  "error": "Invalid activity, probably due to id: Protocol activitypub does not own id https://fed.brid.gy/tantek.com#subscribe"
}
```

more details at https://seppo.social/issues/37

What should I do for successful follow requests?

**Comment by snarfed** [comment]
Sorry for the trouble! Looks like the problem is that this activity's id was on fed.brid.gy. Following up in https://seppo.social/issues/37
