### ISSUE TITLE
Ignore/exclude specific posts from bridge

### ISSUE THREAD

**Issue by TheEssem** [snarfed/bridgy-fed#1275]
Hi there! I was wondering if it would be possible to add a way to exclude specific posts from being bridged (e.g. via a hashtag or specific character in the post itself). Some ActivityPub software has the option to make "local-only" posts that are limited to a single instance; this would act somewhat similarly to that, allowing people who have opted into the bridge to limit certain posts to a single protocol (e.g. for posts that would only make sense on one side of the bridge).

**Comment by snarfed** [comment]
Yes! This is #831

**Comment by TheEssem** [comment]
I see; didn't catch that when looking at existing issues, thanks!

I might suggest having some sort of setting to toggle between full bridging and selective bridging, like some old crossposters offered, but I'd imagine a settings system in general would need to be implemented first.
