### ISSUE TITLE
Public key not found for key `https://fed.brid.gy/fed.brid.gy#key`

### ISSUE THREAD

**Issue by martymcguire** [snarfed/bridgy-fed#1292]
Encountered when sending a webmention for [this like on my site](https://martymcgui.re/2024/08/30/123558/) to [this Mastodon post on hackers.town](https://hackers.town/@lmorchard/113051863182636511)

From the logs here: https://fed.brid.gy/log?path=%2Fqueue%2Fwebmention%2C%2Finbox&start_time=1725035870&key=https%3A%2F%2Fmartymcgui.re%2F2024%2F08%2F30%2F123558%2F

```
I 2024-08-30 16:37:51.074124+00:00 Finding recipients and their targets
I 2024-08-30 16:37:51.074566+00:00 Raw targets: ['https://hackers.town/@lmorchard/113051863182636511']
I 2024-08-30 16:37:51.091055+00:00 Signing with [fed.brid.gy](http://fed.brid.gy/) 's key
I 2024-08-30 16:37:54.967304+00:00 [requests.get](http://requests.get/) https://hackers.town/@lmorchard/113051863182636511 {'data': None}
I 2024-08-30 16:37:55.204413+00:00 Received 403: {"error":"Public key not found for key https://fed.brid.gy/fed.brid.gy#key"}
W 2024-08-30 16:37:55.204678+00:00 403 Client Error: Forbidden for url: https://hackers.town/@lmorchard/113051863182636511 ; {"error":"Public key not found for key https://fed.brid.gy/fed.brid.gy#key"}
W 2024-08-30 16:37:55.205511+00:00   File "/layers/[google.python.pip/pip/lib/python3.11/site-packages/oauth_dropins/webutil/util.py](http://google.python.pip/pip/lib/python3.11/site-packages/oauth_dropins/webutil/util.py)", line 1698, in call
    resp.raise_for_status()

  File "/layers/[google.python.pip/pip/lib/python3.11/site-packages/requests/models.py](http://google.python.pip/pip/lib/python3.11/site-packages/requests/models.py)", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)

I 2024-08-30 16:37:55.206281+00:00 Can't determine protocol for https://hackers.town/@lmorchard/113051863182636511
I 2024-08-30 16:37:55.206552+00:00 Direct (and copy) targets: dict_keys([])
```

Opening up `https://fed.brid.gy/fed.brid.gy#key` I see:

```
{
  ...
  "publicKey": {
    "id": "https://fed.brid.gy/fed.brid.gy#key",
    "owner": "https://fed.brid.gy/fed.brid.gy",
    "publicKeyPem": "-----BEGIN PUBLIC KEY----- ... \n-----END PUBLIC KEY-----"
  },
  ...
}
```

That `publicKey` entry exists and has an id of `https://fed.brid.gy/fed.brid.gy#key`, which I assume is what `hackers.town` would be looking for?

I don't want to fall down a hole of documentation, so this is a mystery to me. I do have a weird gut instinct to guess that `#key` should refer to an actual key in this JSON document, so it should be `#publicKey`? Probably way off there.

**Comment by snarfed** [comment]
Sigh, looks like hackers.town is blocking Bridgy Fed. They don't show their blocked servers on https://hackers.town/about , but when you search for @fed.brid.gy@fed.brid.gy and open the profile, it says _This user has been suspended by a moderator._ Same w/@snarfed.org@snarfed.org. @bsky.brid.gy@bsky.brid.gy doesn't even show up at all.

Feel free to ping their admin and ask them to reconsider since BF is (and has always been) opt in on the fediverse!

**Comment by martymcguire** [comment]
Oh! Thanks so much for checking! I will try to remember that bit of debugging for the future.

Closing as CANTFIX :joy:
