### ISSUE TITLE
My account seems to be in a broken state on bsky.brid.gy

### ISSUE THREAD

**Issue by leo60228** [snarfed/bridgy-fed#1294]
I experimented with Bridgy Fed on the ATProto sandbox before Bluesky publicly deployed federation. My account now seems to be in a broken state: https://bsky.brid.gy/.well-known/webfinger?resource=acct:vriska.bsky.social@bsky.brid.gy gives the error "No atproto user found for did:plc:omvdmfrh4dp36f77fuetrgjh".

**Comment by snarfed** [comment]
Hmm! Have you followed https://bsky.app/profile/ap.brid.gy on Bluesky? https://fed.brid.gy/docs#bluesky-get-started

**Comment by leo60228** [comment]
Yes. I can also follow bridged ActivityPub users, though my interactions don't get bridged back.

**Comment by leo60228** [comment]
I just got a bridged notification, the issue seems to be fixed.

**Comment by snarfed** [comment]
Great! Bluesky => fediverse bridging has been a bit backed up since yesterday, Bluesky saw a 10x sustained spike in load and new users due to Brazil shutting down X. Bridgy Fed is still catching up. Wish us luck!
