### ISSUE TITLE
AP -> ATProto: mentions not resolved

### ISSUE THREAD

**Issue by KDederichs** [snarfed/bridgy-fed#1297]
I made a mastodon post while mentioning two bridged users at the same time (https://mastodon.ladon-dragon.net/@ladon/113060576389202189)
In Mastodon the handles correctly resolve to the corresponding bridgy profiles.
On Bluesky (https://bsky.app/profile/ladon.mastodon.ladon-dragon.net.ap.brid.gy/post/3l32zhupmdzj2) the user handles are just plaintext and not resolved as they should be.
(Not sure if handle resolution works in general, just something I noticed and thought maybe it has to do with the fact that there's more than one)

**Comment by snarfed** [comment]
Huh, surprising! Thanks for reporting. We've definitely had fediverse => Bluesky mentions working in general, so I'm not sure what happened here. I can look at some point.

**Comment by KDederichs** [comment]
Thanks for looking into it!

**Comment by snarfed** [comment]
Not sure what happened here, but I tried a fedi => Bluesky post with multiple mentions just now, https://indieweb.social/@snarfed/113612141635201822 => https://bsky.app/profile/fedi.test.snarfed.org/post/3lcpxopdymld2 , and the mentions bridged fine, so I suspect we've fixed this.
