### ISSUE TITLE
Try harder to delete bridged accounts when the source account is deleted

### ISSUE THREAD

**Issue by breadguyyy** [snarfed/bridgy-fed#1304]
https://bsky.app/profile/breadguyyy.c.wtf.ap.brid.gy
the original account no longer exists for this one

**Comment by snarfed** [comment]
Ooh, thanks for reporting! Looks like we currently delete Bluesky bridged profiles when someone opts out, but not when they delete their fediverse account. We should! Should be straightforward.

Full log from this receive task:

```
Task 72965585254320164051
Params: [('authed_as', 'https://convo.casa/users/breadguyyy'), ('obj', 'ahBicmlkZ3ktZmVkZXJhdGVkcjYLEgZPYmplY3QiKmh0dHBzOi8vY29udm8uY2FzYS91c2Vycy9icmVhZGd1eXl5I2RlbGV0ZQw')]
Receiving activitypub delete https://convo.casa/users/breadguyyy#delete AS1: {
  "objectType": "activity",
  "verb": "delete",
  "id": "https://convo.casa/users/breadguyyy#delete",
  "actor": "https://convo.casa/users/breadguyyy",
  "object": "https://convo.casa/users/breadguyyy"
  "to": [{
      "id": "https://www.w3.org/ns/activitystreams#Public"
    },{
      "objectType": "group",
      "alias": "@public"
    }],
}
Marking Object https://convo.casa/users/breadguyyy deleted
Deactivating Followers from or to = https://convo.casa/users/breadguyyy
Finding recipients and their targets
Raw targets: []
Direct (and copy) targets: dict_keys([])
Delivering to followers of Key('ActivityPub', 'https://convo.casa/users/breadguyyy')
```

**Comment by breadguyyy** [comment]
MVP 🙏 cheers!

**Comment by snarfed** [comment]
Actually, I take it back. The immediate problem here was that when Bridgy Fed followed you back from @bsky.brid.gy@bsky.brid.gy, c.wtf choked on that `Follow` activity and returned 500 `"error"`. I expect this is the same Pleroma incompatibility as  #12 / https://git.pleroma.social/pleroma/pleroma/-/issues/3206.

Since c.wtf never got that follow, it never started sending Bridgy Fed your activities, including the `Delete` when you deleted your account, so Bridgy Fed never knew it should disable your bridged Bluesky account.

**Comment by snarfed** [comment]
Here's the `Follow` activity, sent at 2024-08-08 17:56:28 UTC:

```
POST https://c.wtf/users/breadguyyy/inbox
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "type": "Follow",
  "id": "https://bsky.brid.gy/r/https://bsky.brid.gy/#follow-back-https://c.wtf/users/breadguyyy-2024-08-08T17:40:53.226091+00:00",
  "actor": "https://bsky.brid.gy/bsky.brid.gy",
  "object": "https://c.wtf/users/breadguyyy",
  "to": ["https://www.w3.org/ns/activitystreams#Public"]
}
```

**Comment by cuducos** [comment]
Same issue here. I added `#nobridge` to my website and apparently, the user page does not exist: `https://fed.brid.gy/web/cuducos.me` gives me a 404. However, the [Bluesky account](https://bsky.app/profile/cuducos.me.web.brid.gy) still exists : /

It was a few minutes ago, but I was hopping not to leave the `#nobrige` live on my website for that long…

**Comment by snarfed** [comment]
OK, added an integration test for fediverse => Bluesky. If a fediverse account accepts @bsky.brid.gy@bsky.brid.gy's follow, we correctly deleted them.

@breadguyyy and @cuducos, I've deleted your bridged Bluesky accounts. Remaining work here is to add an integration test for web too.

**Comment by snarfed** [comment]
Done!

**Comment by cuducos** [comment]
Awesome ✨ Thank you so much : )

**Comment by breadguyyy** [comment]
MVP 👍
