### ISSUE TITLE
AP --> Bluesky domain username?

### ISSUE THREAD

**Issue by mmattbtw** [snarfed/bridgy-fed#1307]
I saw #1150 / #1190 but I was wondering if there was anyway to have the opposite, and to be able to have (for example) the account `@matt@social.lol` from Mastodon bridged to an account on Bluesky with the username `@mmatt.net`

I feel like this should be as simple as just DMing (or "private mentioning") the AP user to change their DNS value to one provided by Bluesky for the bridged account, but I'm unfamiliar with how Bluesky/AT Proto handles this. Or even if it would be on Bluesky's side at all.

**Comment by snarfed** [comment]
Yes! Totally doable. I think this is #826...?
