### ISSUE TITLE
Bluesky video

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#1317]
Should be straightforward, mostly just need to add translation in granary `bluesky.from_as1`/`to_as1` and enable fetching in `ATProto._convert`:

https://github.com/snarfed/bridgy-fed/blob/a8b433375986a4b342d5022d254f39cb34a00c7e/atproto.py#L739-L749

https://console.cloud.google.com/errors/detail/CLCw_IiuhNOmjAE;time=PT1H;locations=global?project=bridgy-federated

**Comment by snarfed** [comment]
Bluesky shipped video on web and in the apps today! https://bsky.social/about/blog/09-11-2024-video

**Comment by snarfed** [comment]
...and bridging video is alive! Examples: [fediverse => Bluesky](https://bsky.app/profile/snarfed.indieweb.social.ap.brid.gy/post/3l3wjjg2frwt2), [Bluesky => fediverse](https://indieweb.social/@snarfed.bsky.social@bsky.brid.gy/113122497653905131) (requires login).

...except the Bluesky => fediverse example isn't quite working. Not sure why yet. The video is < 60s and < 25MB, the record (below) looks ok, [atproto.tools says it's valid](https://atproto.tools/?did=did%3Aplc%3Abg5udl25mvzg3rt7l5n2hzet&collection=app.bsky.feed.post&rkey=3l3wjjg2frwt2), and `getBlob` redirects to it fine, with `Content-Type` and `Content-Length` that match the blob's `mimeType` and `size`.

I've asked the team in Discord, will see what they say...

**Comment by snarfed** [comment]
Evidently this is due to the phased rollout, which includes users on federated PDSes like Bridgy Fed. Hopefully they'll get to BF users soon!

**Comment by hybridhavoc** [comment]
Was coming here to ask about this. Noticed with [this post](https://bsky.app/profile/hybridhavoc.darkfriend.social.ap.brid.gy/post/3l3xrw3vgikq2) that it wasn't working, assumed it was something along those lines. Looking forward to the rollout.

**Comment by mackuba** [comment]
Wow, that was fast 😳 I was gonna add a ticket for this, but today I saw a bridged post with apparently a video in it, but I was thinking it's impossible that it's already working… 😅
