### ISSUE TITLE
Bluesky: refresh DID doc when user follows ap.brid.gy

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#1334]
Evidently we're not refreshing a user's DID doc when they first follow ap.brid.gy, which means we occasionally have a stale wrong handle.

Example: did:plc:usl4pnhyasr2moto7elbvhw6 . Changed their handle from cyrneko.codeberg.page to cyrneko.eu at 2024-09-14 12:59 PM PT, then followed ap.brid.gy at 2024-09-15 18:31:06 PT. We already had their DID doc from beforehand, with cyrneko.codeberg.page, and we didn't reload it, so we bridged them with that handle.

Related: #1017, #1201

**Comment by danielledeleo** [comment]
Seeing this for my account (should be @transpile.net, but it got picked up as @caffein.ated.io)

**Comment by snarfed** [comment]
@danielledeleo sorry for the trouble! I've refreshed your DID doc, feel free to try again.

**Comment by snarfed** [comment]
Fixed! Thanks again for reporting.
