### ISSUE TITLE
Documentation: add use case of mentioning a BluSky user from fediverse or respond to one of their posts

### ISSUE THREAD

**Issue by tuxayo** [snarfed/bridgy-fed#1342]
I tried guessing and I just @ them like if I was one BluSky (assuming that's how it works). The bridge posted the same thing that I posted on mastodon but somehow the @nicknameFooBar wasn't highlighted and not clickable. So I assume the person wasn't notified of the message.
But the same @nicknameFooBar was highlighted and clickable on another post that I saw on their timeline. So something is missing when I'm using the bridge to be able to mention someone.

Also, how about responding to a post? Like if I have more than 300 chars to say, responses allow to chain posts.

**Comment by qazmlp** [comment]
You have to mention their bridged account, which is that same user name but on the `@bsky.brid.gy` instance.

Mastodon will shorten it to only the first part in the visible post text, but attach the full mention as meta data and deliver it accordingly.

---

You can just reply with a long post when needed. Bridgy Fed truncates the text and inserts a link to the original post automatically in such cases.

It also inserts the full original (HTML, usually?) representation of the post into the Bluesky record, so alternative Bluesky clients can display the full text immediately.

On that note, @snarfed, iirc, posts can also be plaintext or Markdown internally. Do you have documentation on how that is handled?

**Comment by snarfed** [comment]
> On that note, @snarfed, iirc, posts can also be plaintext or Markdown internally. Do you have documentation on how that is handled?

Wait, what? Where? Not in either AS2 or ATProto anywhere that I'm aware of.

**Comment by qazmlp** [comment]
> > On that note, @snarfed, iirc, posts can also be plaintext or Markdown internally. Do you have documentation on how that is handled?
> 
> Wait, what? Where? Not in either AS2 or ATProto anywhere that I'm aware of.

I'll have to double-check, maybe it's just for posting through the client API…

**Comment by qazmlp** [comment]
Yeah, Peertube actually broadcasts most `"content": "…"` as `"mediaType":"text/markdown"` rather than HTML. You can find an example at `https://peertube.tv/videos/watch/0b0a87b3-5107-4100-b1c4-ffb65669cca3`, but from the source code it seems this doesn't just apply to `Video`s but also other objects. Notably, it doesn't use `contentMap`.

Pleroma appears to have a function to render these into HTML when receiving them: https://github.com/pleroma-social/pleroma/blob/f917285b72dbc770be40478e1a55973f29d5db7d/lib/pleroma/web/activity_pub/object_validators/audio_video_validator.ex#L95-L103

**Comment by snarfed** [comment]
`mediaType: text/markdown` wooowwww. Fun! And I imagine hell on interop. I wonder how many other platforms besides Pleroma handle incoming Markdown!

**Comment by tuxayo** [comment]
> You have to mention their bridged account, which is that same user name but on the @bsky.brid.gy instance.

Nice, thanks :)

Wait, so the other account needs have bridged themselves?

So it's not possible to use bridgy-fed just to mention any BluSky user? Or reply to any post there?

**Comment by qazmlp** [comment]
> > You have to mention their bridged account, which is that same user name but on the @bsky.brid.gy instance.
> 
> Nice, thanks :)
> 
> Wait, so the other account needs have bridged themselves?
> 
> So it's not possible to use bridgy-fed just to mention any BluSky user? Or reply to any post there?

Yes, the system is currently symmetric (and even if a user is opted in, it can be pretty difficult to find their post if you weren't following them when they made it, but that's more a property of ActivityPub).

*If* they have their Chat open to everyone (which is not the default on Bluesky), you can Mention-only their ATProto handle (as shown on Bluesky) to `@bsky.brid.gy@bsky.brid.gy` to request that they opt into the bridge on their end. They're only ever sent one such request, though, afaik.

Also note that your replies must be Public to be bridged to ATProto. I think the relevant issue to loosen that a little is #1036.
(I think there's _less_ of a discovery mismatch there now that Bluesky is reducing the visibility of replies in feeds if the viewer doesn't also follow the OP in that conversation.)

**Comment by snarfed** [comment]
Definitely a good idea to mention this in the docs, I've done that. Thanks for the nudge!
