### ISSUE TITLE
Some AP->Web @-mention notifications don't deliver

### ISSUE THREAD

**Issue by jamietanna** [snarfed/bridgy-fed#1345]
Ie https://hachyderm.io/@anderseknert/113191706986003922 doesn't seem to display on https://fed.brid.gy/web/www.jvt.me/notifications, but can't seem to see why - could be me being a special case with `www`?

**Comment by snarfed** [comment]
Interesting one! Thanks for filing. That activity had other targets too, notably https://eigenmagic.net/users/arichtman , which returned HTTP 444 when we tried to fetch it, which is an HTTP status we didn't understand, so it cut our processing short. Looks like we need to handle errors more aggressively. 😁

**Comment by snarfed** [comment]
I think this is a special case of #885

**Comment by jamietanna** [comment]
Oh interesting, thanks!

**Comment by snarfed** [comment]
Merging into #885
