### ISSUE TITLE
@bsky.brid.gy@bsky.brid.gy won't accept my follow request nor will it follow me back.

### ISSUE THREAD

**Issue by suflors** [snarfed/bridgy-fed#1356]
I read that the bot does not accept follow requests from accounts younger than 2 weeks old, however, I made my instance and my account on 2024.09.13, so it has now been almost 3. I thought maybe it might've been a problem with the bot not knowing when my account was made, as from my instance it says that _the bot's_ account was made on the 16th, as seen below:
![image](https://github.com/user-attachments/assets/956d23be-bb14-46c6-a514-6f40c7ed5663)
So I waited for it to be 2 weeks from the 16th under this impression. However, it is now 2 days after that, and it is still not accepting my follow request, so I am unsure what is happening. I am attempting to follow from user @kelsey@goto.tomato.pink and my instance is a private IPV4 GoToSocial 0.16.0+git-f1cbf6f instance.

**Comment by snarfed** [comment]
Hey, sorry for the trouble! Have you looked at https://fed.brid.gy/docs#troubleshooting ?

**Comment by snarfed** [comment]
Also we've had at least some reports of interop trouble w/GoToSocial before, #1033. They've hopefully fixed them, but I haven't tracked that in detail, or whether those bug fixes are all released or in which version.

**Comment by suflors** [comment]
Have indeed, and unless I'm missing something everything here should be fine. My instance isn't blocking the bot's instance, and I am able to discover the bot and see its profile, as well as send a follow request, but then nothing happens. I'm not sure if #1033 is similar to my issue as they seemed to not be able to discover the bot at all.

**Comment by snarfed** [comment]
Thanks for the info. Looking at our logs, when we fetched https://goto.tomato.pink/users/kelsey with `Accept: application/activity+json, application/ld+json; profile="https://www.w3.org/ns/activitystreams", text/html; charset=utf-8; q=0.5` and an HTTP signature with `keyId=https://fed.brid.gy/fed.brid.gy#key`, we got an HTTP 500 back with a `text/html` body.

**Comment by suflors** [comment]
`Oct 02 18:53:05 Marinette gotosocial[892]: timestamp="02/10/2024 18:53:05.983" func=server.init.func1.Logger.14.1 level=ERROR latency="562.026329ms" userAgent="Bridgy Fed (https://fed.brid.gy/)" method=GET statusCode=500 path=/users/kelsey clientIP=34.42.221.223 pubKeyID=https://fed.brid.gy/fed.brid.gy#key errors="Error #01: AuthenticateFederatedRequest: error dereferencing account https://fed.brid.gy/fed.brid.gy: enrichAccountSafely: error getting account https://fed.brid.gy/fed.brid.gy from database after race: sql: no rows in result set\n" requestID=1mm98kmj04001hp5trs0 msg="Internal Server Error: wrote 910B"`
This is what I'm seeing in the database.

**Comment by snarfed** [comment]
Thanks. Sounds like you may need to ask the GoToSocial people.

**Comment by snarfed** [comment]
Merging into #1033 to track our overall interop w/GoToSocial.
