### ISSUE TITLE
ATProto => AP: repost translated to boost of an incorrect post

### ISSUE THREAD

**Issue by mackuba** [snarfed/bridgy-fed#1357]
I reposted this post from Paul Frazee: https://bsky.app/profile/pfrazee.com/post/3l5ku5gdorg2u

This post mentions a link to a blog post in the content: https://activitypub.ghost.org/beta-plans/

I also follow my bridged account on my native Mastodon account, so I looked there, and it seems that my bridged account has boosted Ghost's post (via web.brid.gy) instead of Paul's bridged post 🤔

<img width="603" alt="Screen Shot 2024-10-03 at 01 41 30" src="https://github.com/user-attachments/assets/9adf03bc-b8a5-4621-8e17-3311a6af8354">

<img width="607" alt="Screen Shot 2024-10-03 at 01 41 44" src="https://github.com/user-attachments/assets/81c9b2ab-0f06-456f-90c4-ebb19e960aa6">

**Comment by snarfed** [comment]
Oh no, that's not good. Reminds me of #1237. I'll look.

**Comment by snarfed** [comment]
Hmm, looking at https://martianbase.net/@mackuba , it shows that you reposted Paul's bridged quote post, not Ghost's post. Is the fediverse client you're using maybe misinterpreting the AS2?

<img width="807" alt="image" src="https://github.com/user-attachments/assets/a499e89e-1686-469d-b250-f57529b27115">

**Comment by snarfed** [comment]
Hey @mackuba, friendly ping?

**Comment by mackuba** [comment]
Hey, sorry, I'll dig into that… probably tomorrow evening at the earliest since I'm driving AT->PL tomorrow

**Comment by snarfed** [comment]
Not urgent! Don't worry about it. Enjoy your trip!

**Comment by mackuba** [comment]
Ahh, I thought I was going crazy, because I looked now and I saw what you were seeing too, but we're both looking at the wrong thing ;) https://martianbase.net/@mackuba is my native Mastodon account which isn't bridged, this is about what the bridged account @mackuba.eu@bsky.brid.gy has reposted.

**Comment by snarfed** [comment]
Aha, thanks! Ok, will look.

**Comment by snarfed** [comment]
Phew, this one was complicated. TLDR, it's a bug, here 😆:

https://github.com/snarfed/bridgy-fed/blob/89e0ecda6c8e8a3ef97c8d67253d9199f5c26189/protocol.py#L1475-L1478

Not sure if I'm smart for knowing this might eventually be a problem, or dumb for shipping it anyway. Probably the latter! 😁

**Comment by snarfed** [comment]
Fixed. Thank you again for reporting!
