### ISSUE TITLE
Replies from Mastodon to Bluesky do not work anymore

### ISSUE THREAD

**Issue by FoundOne** [snarfed/bridgy-fed#1362]
I've noticed that recently any reply I sent to a Bluesky post does not go there. I can see it on my side though.
I'm not sure whether that's a software issue or some system issue with the brid.gy instance. I hope that's the correct place.

**Comment by FoundOne** [comment]
Oops wrong project.

**Comment by snarfed** [comment]
Hi! This is the right project. Sorry for the trouble! I tried a reply just now, and it bridged from Mastodon to Bluesky ok: https://bsky.app/profile/snarfed.indieweb.social.ap.brid.gy/post/3l5rh3ijfxf42

Can you give me an example reply that didn't work for you?

**Comment by FoundOne** [comment]
Yesterday it randomly started working. Now I see some comments on Bluesky which are just counted, but not shown. The worst part is that it happens at random and can't pin point the issue exactly. I need some time to make proper screenshots.

**Comment by snarfed** [comment]
Ugh, sorry. If you can send me even just one Mastodon URL for a recent reply that didn't work, I'm happy to look.

**Comment by snarfed** [comment]
Tentatively closing. @FoundOne feel free to reopen if you can provide more info!
