### ISSUE TITLE
Can't discover a Bluesky account from the fediverse

### ISSUE THREAD

**Issue by grishka** [snarfed/bridgy-fed#1363]
I'm trying to follow https://bsky.app/profile/timmarinin.net from Mastodon, but when I try searching for `@timmarinin.net@bsky.brid.gy`, I don't get any results. I also tried making a webfinger request (https://bsky.brid.gy/.well-known/webfinger?resource=acct:timmarinin.net@bsky.brid.gy) manually, but this returns a 404 with "No atproto user found for did:plc:qgljapx75sdwa2d53boqzir7".

He does follow `@ap.brid.gy`:
![Снимок экрана 2024-10-07 в 00 40 48](https://github.com/user-attachments/assets/3e7cc181-1875-4001-9aa2-b1de0157c585)

And I also follow the bridge on Mastodon. My Mastodon account is correctly bridged into Bluesky:
![Снимок экрана 2024-10-07 в 00 43 54](https://github.com/user-attachments/assets/7fc93401-f2f6-4e7e-94dd-b12e0da2cbe8)

At this point I'm out of ideas how else to try debugging this, so here's this issue ¯\\\_(ツ)_/¯

**Comment by snarfed** [comment]
Hey, sorry for the trouble! Looks like that user never got bridged. Checking whether they follow @ap.brid.gy is a good first step, but Bridgy Fed has had at least a couple bits of downtime before when it didn't catch follows. The way to be certain is to check their BF user page, http://fed.brid.gy/bsky/timmarinin.net here.

Feel free to ping them and ask them to unfollow and refollow the bot to try again!

**Comment by grishka** [comment]
He did it and it worked, thanks!
