### ISSUE TITLE
No longer receiving Mastodon @mentions via webmentions.io

### ISSUE THREAD

**Issue by candidexmedia** [snarfed/bridgy-fed#1366]
I implemented bridgy-fed on my site a while back, and was able to receive Mastodon mentions as webmentions using my webmentions.io RSS Feed:

![image](https://github.com/user-attachments/assets/c0ee3d19-9d26-4b26-bd21-a586fbbe5726)

I'm no longer able to get these mentions when I "toot" from that same Mastodon account. Here's a [test post](https://mastodon.design/@candidexmedia/113268754606525728) and here's my [bridgy profile](https://fed.brid.gy/web/candide.media).

(Also posted on the webmentions Gihub: https://github.com/aaronpk/webmention.io/issues/215)

**Comment by snarfed** [comment]
Hey, sorry for the trouble! That Mastodon post is unlisted, and Bridgy Fed only bridges fully public posts. https://docs.joinmastodon.org/user/posting/#privacy

**Comment by candidexmedia** [comment]
@snarfed Unfortunately, I've tried with a [public post](https://mastodon.design/@candidexmedia/113273177614842567) as well, and no dice...

**Comment by snarfed** [comment]
Aha. Thanks for your patience here, and for reporting this! Turned out to be a bug. I'm deploying a fix, then I'll re-send the webmention to confirm that it works.

**Comment by snarfed** [comment]
Looks like that did the trick. Thanks again! https://webmention.io/www.candide.media/webmention/7wALJWI8qg6aJliiQI0u

**Comment by candidexmedia** [comment]
Yup, I see it on my RSS feed now. Thank you for your help and for creating this bridge!
