### ISSUE TITLE
AP => Bluesky accounts not being bridged

### ISSUE THREAD

**Issue by TomCasavant** [snarfed/bridgy-fed#1377]
I assume this is potentially because of #1376, but maybe there are conditions these 2 accounts are failing to meet.

https://tomkahe.com/@surrender_index -> has profile photo, created september 26th
https://tomkahe.com/@surrender_idx90 -> Has profile photo, created sepetember 27th

I attempted to bridge them a little over 14 days after they were made and the bridgy account accepted the follow but never followed back. I attempted to unfollow/refollow with the idx90 account but it didn't change anything

**Comment by snarfed** [comment]
Hey Tom! Looks like you followed @fed.brid.gy@fed.brid.gy with those accounts, not @bsky.brid.gy@bsky.brid.gy?

I wonder if I should remove the @fed.brid.gy account to avoid this kind of confusion.

**Comment by TomCasavant** [comment]
Oh shoot you're right. Sorry for the trouble

**Comment by qazmlp** [comment]
> I wonder if I should remove the @fed.brid.gy account to avoid this kind of confusion.

You need it to centralise GET requests though, right?

If you make those through other means, I think you'd have to use a fallback chain in case a specific remote-network-domain got defederated somewhere without your knowledge. Maybe listing the network instance accounts in the bio would work already (with the caveat that some users might not read the manual and then not realise that blocking is currently irreversible towards Bsky).

**Comment by snarfed** [comment]
Hah. It's the norm that I don't necessarily know whether a given instance has defederated Bridgy Fed, and which domains. 😁

You're right that I currently use @fed.brid.gy as the BF instance actor, eg for signing GETs. If an instance defederates, even from just one or some domains, I don't try to "handle" that at all - it's not always easy to detect with any confidence - so I could easily switch the instance actor to @bsky brid.gy.
