### ISSUE TITLE
Suggestion: Replies between bridged accounts on one site should appear on the other?

### ISSUE THREAD

**Issue by jmcken1** [snarfed/bridgy-fed#1382]
I have a Bluesky account I’ve bridged over to the Fediverse. On Bsky, I post a reply to someone else who also has a bridged account. If I then find their bridged post on Mastodon, however, I don’t see my reply there from my bridged account. Could this perhaps be considered, so that anyone following my bridged account on Masto can see my full interactions there (at least with other bridged accounts)?

**Comment by ygg2** [comment]
Same side replies do get bridged, but on Mastodon replies follow normal post delivery methods which means the reply will only appear on the instance if
1) someone on the instance is following the replier
2) someone on the instance is following someone who boosts the reply
3) someone on the instance is following someone who replies to the reply
4) the reply has a tag that the instance is following via a relay
...There might be a few other cases? Some also don't apply to bridgy
Not being able to see all replies has been a source of frustration for a lot of people on Mastodon, and there's an open issue for it.

**Comment by jmcken1** [comment]
Ah, thanks for the info. (Is it just me or does Mastodon throw up a weird number of hoops to jump through to get your posts to appear …?)

**Comment by ygg2** [comment]
No problem! (I'd say replies aside, it generally works well for a network where people just want to follow other people - and the overall culture and expectations are based on somewhat scoped discoverability. Doesn't mean that's what everyone wants for the network though of course!)

**Comment by snarfed** [comment]
@ygg2 is right (thanks!), content on the fediverse is inconsistent in general, including replies, for all sorts of reasons. It's generally expected that the original instance for a profile or post will be more or less complete, and here the original instance is effectively Bluesky itself.

Tentatively closing. @jmcken1 feel free to reopen if you still have concerns!
