### ISSUE TITLE
Sometimes posts that I delete on Misskey are not deleted on Bluesky.

### ISSUE THREAD

**Issue by KyungmiAhn** [snarfed/bridgy-fed#1393]
* Misskey
![image](https://github.com/user-attachments/assets/0f7df161-c2fa-4abd-b16a-05e652b4ec21)
* Bluseky
![image](https://github.com/user-attachments/assets/ad706b4d-b3ac-4284-be70-2c41614f6572)

As you can see, the “☆” has been deleted, but it's still there in the bridge account.
(I realize now that the “음?” is actually not in the bridge account)

* Misskey
![image](https://github.com/user-attachments/assets/e8559259-035a-4cbf-b7e6-8a3b81c538be)
* Bluesky
![image](https://github.com/user-attachments/assets/6c9ea226-0f7c-4981-82f3-ef5568cdf537)

And another example. I was trying to fix a typo, and the unedited version was left in the bridge account.

If I remember correctly, I think I deleted it a few seconds after I posted it, in both cases. Then the post was not deleted from my Bluesky Bridge account.

It's understandable that deletions sometimes don't get processed, but I'm writing about it anyway because it happens.

This is my first time using something like this, so I don't know if I wrote it well.

**Comment by snarfed** [comment]
Thank you for reporting, and sorry for the trouble! If it happens when you delete a post within seconds of posting it, this is probably #1361. I'll tentatively merge into that issue; feel free to reopen if you disagree.
