### ISSUE TITLE
@bsky.brid.gy cannot be accessed on Mastodon (Masto→Bsky)

### ISSUE THREAD

**Issue by Cellosia** [snarfed/bridgy-fed#1395]
Maybe I'm just doing something wrong, but attempting to visit the Mastodon `@bsky.brid.gy@bsky.brid.gy` profile from mastodon.social (https://mastodon.social/deck/@bsky.brid.gy@bsky.brid.gy) results in "This page is not available in the requested format".

Removing "deck" or trying to access @bsky.brid.gy directly sends to https://bsky.brid.gy/bsky.brid.gy which will spit out a json object(?), not a profile page.

**Comment by snarfed** [comment]
Hey, sorry for the trouble! Some of this is just how Mastodon works. I don't know about the /deck/ URL prefix, but in general, if you're not logged in and you open a profile URL like https://mastodon.social/deck/@bsky.brid.gy@bsky.brid.gy , it redirects you to the original profile URL. If you are logged in, it renders the remote profile inside mastodon.social.

If you're just trying to get to the profile, you can search for `@bsky.brid.gy@bsky.brid.gy` and click on it in the results.

As for why it redirects to https://bsky.brid.gy/bsky.brid.gy, which serves JSON, that's #1009, it's an odd one that's been around for a while. We think Mastodon and Pixelfed aren't follow the AP and AS2 standards right, but we're not sure.
