### ISSUE TITLE
Option to bridge "quiet public" posts from fediverse to bluesky

### ISSUE THREAD

**Issue by kimbabclub** [snarfed/bridgy-fed#1396]
Due to bridged posts from Bluesky flooding on federated timelines, many fediverse instance admins decide to silence the bridge server(meaning all posts from the bridge server is posted as "quiet public").
If so, the users can only @ the bridged accounts in a "quiet public" visibility, preventing their posts to get bridged forever.
To be honest I think all public and quiet public posts can be bridged by default (if the option gets too complicated)!

Thanks for this great service! It has made all those scattered exodus from X much more connected.

**Comment by qazmlp** [comment]
I think that's #1036. (Context: 'Unlisted' was renamed to 'Quiet public' very recently in Mastodon.)

Top-level posts on Bluesky are much more visible than 'quiet public' ones in Mastodon, so this would be a bad translation.

However, as mentioned in the other issue, it would make sense to bridge quiet public replies that are in reply to a cross-network post. They'd still come up in search in Bluesky, but I think they now aren't shown to non-followers in Feeds anymore, which matches fediverse behaviour.
I think that would also solve the issue of being unable to reply to those posts.

**Comment by snarfed** [comment]
Thanks @qazmlp! Yes, sounds like this is #1036, I'll merge it in there. @kimbabclub feel free to reopen if you disagree.
