### ISSUE TITLE
Not sure what's going on with my account.

### ISSUE THREAD

**Issue by mardevour** [snarfed/bridgy-fed#1398]
Hi! First of all, sorry if this is not the palce for this but i'm not sure what is going on with my profile, I don't know if it's a bug or what it is.

so I made a new mastodon account because in the other one I have I blocked the BF bot because i wasn't sure how it worked or if it was working and not knowing this can't be undone (didn't read the docs)... so I wanted to ask here before doing anything like that again

Now in my new account what I did was: follow the BF bot, check my user page at https://fed.brid.gy/ap and check my bridged profile at https://bsky.app.

everything was there. today I tried to access my user page but [it's missing](https://fed.brid.gy/ap/@mardevour@mstdn.social). not my [birdged account](https://bsky.app/profile/mardevour.mstdn.social.ap.brid.gy), though. I did not unfollow the bot, but I checked my followed accounts and it's not there. I also checked [the bot page on mastodon](https://mstdn.social/@bsky.brid.gy@bsky.brid.gy) and it shows the `Follow back` button, which is weird since it's supposed to unfollow me if I had unfollowed it, right? If i click the button it shows a confirmation to actually UNfollow, so I don't know what's going on here.
![imagen](https://github.com/user-attachments/assets/453a9aa6-921b-4b9f-9664-2279bf729c7d)
![imagen](https://github.com/user-attachments/assets/fbae6b66-fa0e-4c9e-afd9-7850a266bcc9)

I though of actually unfollowing and following back but i didn't want to do anything weird that wouldn't allow me to bridge my account again. I also couldn't find anything on the docs. what do i do now?

**Comment by snarfed** [comment]
Hi! Account age is one of our spam filters, the bridge doesn't bridge accounts less than two weeks old: https://fed.brid.gy/docs#troubleshooting . Try again on 11/1!

**Comment by mardevour** [comment]
Oh right! that makes sense, i don't know how I didn't think of that! it just seemed weird because the first day my user page was availabe and then it wasn't.
anyway, sorry for opening this 😅

**Comment by mclmt-owo** [comment]
Sorry to bump this, but I think this is something worth adding to the documentation for people wondering the same thing.

**Comment by snarfed** [comment]
@mclmt-owo it's there, and linked earlier in this issue: https://fed.brid.gy/docs#troubleshooting

**Comment by mclmt-owo** [comment]
Oh... duh! Sorry, please disregard. I haven't had my coffee yet 😅
