### ISSUE TITLE
Add support for alternatives to Firestore

### ISSUE THREAD

**Issue by ch0ccyra1n** [snarfed/bridgy-fed#1402]
Firestore unfortunately is a proprietary Google Cloud service. I would like the option to use a different database such as MariaDB/MySQL or SQLite for the purpose of self-hosting my own Bridgy-fed instance, since I don't have a Google account and would prefer to avoid them entirely when possible.

**Comment by snarfed** [comment]
Yes! Definitely understood. This is #627, merging in there.
