### ISSUE TITLE
Apply spam filters before creating bridged profiles

### ISSUE THREAD

**Issue by xne** [snarfed/bridgy-fed#1403]
Hi!

When opting-out by blocking @bsky.brid.gy on the Fediverse, or @ap.brid.gy on Bluesky, the associated bridged profile is not deleted on the other network.

For example:
- [@xne.bsky.social](https://bsky.app/profile/xne.bsky.social) has blocked @ap.brid.gy, but [@xne.bsky.social@bsky.brid.gy](https://mastodon.social/@xne.bsky.social@bsky.brid.gy) persists. 
- [@xne@mastodon.social](https://mastodon.social/@xne) has blocked @bsky.brid.gy, but [@xne.mastodon.social.ap.brid.gy](https://bsky.app/profile/xne.mastodon.social.ap.brid.gy) persists.

Thank you!

**Comment by snarfed** [comment]
Hey, sorry for the trouble! Looks like your accounts both got caught by one of our spam filters: we currently require a profile picture, https://fed.brid.gy/docs#troubleshooting . The result is awkward right now though: it does the bare minimum to create your initial profile, but nothing beyond that, including blocking to disable. Obviously not ideal.

#758 is part of the answer here, but also we should apply the spam filters earlier and not create bridged profiles at all. Hope you're ok if I track that in this issue?

**Comment by xne** [comment]
Sounds good, thanks for the quick reply!

**Comment by Tamschi** [comment]
(I'm adding the safety label here because, while not severe, the effect can still cause misunderstandings if others find the account.)

**Comment by snarfed** [comment]
Done!
