### ISSUE TITLE
Update profile not syncing with Mastodon

### ISSUE THREAD

**Issue by xne** [snarfed/bridgy-fed#1404]
Hi!

Upon updating my profile at https://fed.brid.gy/web/xne.ca, the associated profile [@xne.ca@xne.ca](https://mastodon.social/@xne.ca@xne.ca) on Mastodon is not updated. Is this on the Bridgy Fed side, or Mastodon?

Thank you!

**Comment by snarfed** [comment]
Hi again! Bridgy Fed sends `Update` AP activities to your followers' instances, but that account doesn't have any fediverse followers yet. It is serving your updated profile though, I see it when I search for your address on an instance that hadn't seen it before:
<img width="562" alt="image" src="https://github.com/user-attachments/assets/c35980bb-fd38-4d15-86a8-0294d36bb6c2">

**Comment by xne** [comment]
Oh ok, makes sense! Thank you again.
