### ISSUE TITLE
AP => Bluesky: Allow for excluding certain public posts from bridging over

### ISSUE THREAD

**Issue by The-Beebz** [snarfed/bridgy-fed#1405]
Hello! My home instance is [Aethy](https://aethy.com), which is an 18+ queer-led community with a focus on artistic freedom. Now, aethy does require specific content warnings on any NSFW content, but some of that content can be against BlueSky's Acceptable Content Policy.

I'd love to be able to have the control to be able to say "dont bridge this post", maybe via a hashtag like "dontbridge" or "bridgingdisabled".

It could also be considered to automatically exclude a post from being bridged if there are certain keywords flagged in the content warning field. This may be an easier but also more clumsy way to prevent Bluesky being inundated with posts (typically kinky nsfw artwork) but if this were to become a problem it would be a good stopgap until an exclusion can be done.

Thank you for this service. I'm excited to be able to interact with more fandom friends! (I will also preemptively ask other commenters to stay on the topic of fediverse bridging and be respectful)

**Comment by snarfed** [comment]
Hi! Glad you're thinking about this. Bluesky is very welcoming of NSFW content, there's a lot of it there, and Bridgy Fed bridges plenty of it already, in both directions. We currently translate the fediverse [`sensitive` flag](https://swicg.github.io/miscellany/#sensitive) ([Mastodon docs](https://docs.joinmastodon.org/user/posting/#cw)) and content warnings to/from the corresponnding [Bluesky labels](https://docs.bsky.app/docs/advanced-guides/moderation#global-label-values).

Having said that, per-post bridging is also a good feature request, we're currently tracking it in #831.

**Comment by The-Beebz** [comment]
Thank you for the reply! Looking forward to that feature. 🦋❤️
