### ISSUE TITLE
AP -> AT: encode animated GIF as video

### ISSUE THREAD

**Issue by Fauli1221** [snarfed/bridgy-fed#1409]
My instance uses Sharkey (Fork of Misskey) and thereby supports viewing and uploading GIF 
other fedi software like Mastodon support displaying those though Bluesky does not because of that it would be nice if bridgy would encode animated gif's to mp4 so that they can be viewed there as well

example 
on my instance:
https://hooves.social/notes/9zglk1p6o38902rr
on bluesky
https://bsky.app/profile/Ponysearch.hooves.social.ap.brid.gy/post/3l6ozkxza5ko2

**Comment by snarfed** [comment]
Feel free to follow https://github.com/snarfed/bridgy-fed/issues/1113!
