### ISSUE TITLE
Fediverse => Bluesky: auto-generate embeds (with thumbnail images) for links?

### ISSUE THREAD

**Issue by EdlReg** [snarfed/bridgy-fed#1411]
I do not know if this is a general problem between platforms or if it is strictly an issue between Mastodon -> Bluesky, but whenever I post an article (or other external link) on Mastodon the thumbnail doesn't show up on Bluesky. You can see the link and click on it, but no thumbnail. 
Would be great if this could be fixed.

**Comment by Tamschi** [comment]
This happens because in ActivityPub (Mastodon) link previews are generated by the receiver, but in Bluesky they are stored by the sender as part of the post itself. Bridgy Fed already handles this for web posts it seems (#1192).

Relevant Bluesky lexicons:

- [`app.bsky.feed.post`](https://github.com/bluesky-social/atproto/blob/main/lexicons/app/bsky/feed/post.json) (`.embed`)
- [`app.bsky.embed.external`](https://github.com/bluesky-social/atproto/blob/main/lexicons/app/bsky/embed/external.json)

**Comment by EdlReg** [comment]
Ok, my instance is Mastodon.nu if that is of any importance.

**Comment by Tamschi** [comment]
It's mainly the software and version that matters, as long as posts go through at all.

(The current Mastodon v4.3.1, in this case.)

**Comment by snarfed** [comment]
This is an interesting one! @Tamschi is broadly right: Bluesky/ATProto link previews (including thumbnail images) are explicit metadata in post objects. ActivityStreams 2 post objects _can_ have similar link preview metadata, eg in the `attachment` field, but fediverse clients and servers like Mastodon often generate them from the first link in the post instead. When they get a post with an `attachment`, they halfway honor it and render it similarly, but usually without an image, so it looks like a second class citizen.

Take https://indieweb.social/users/snarfed/statuses/112582713947140513 as an example. I authored it inside Mastodon, and included a single URL in the text. Mastodon renders a link preview embed for that URL, in both the source instance and remote instances, but it federates it as an AS2 `Note` with no `attachment` value. The user-visible link preview is handled entirely outside AP.

![image](https://github.com/user-attachments/assets/0ec97c64-babd-4f44-bc82-25a62b189b12)

I haven't done a comprehensive survey, but afaik at least some other popular fediverse servers, if not most, do the same thing.

So, the common case is that fediverse link previews are a non-standard heuristic, and I'm reluctant to bake that kind of thing into Bridgy Fed. I get that it might still be the right thing to do for UX though! So I'm torn.

(I do indeed do this for web => Bluesky, but that situation is very different, since the source post is a single specific web page.)

**Comment by snarfed** [comment]
More background on how fediverse servers, particularly Mastodon, prefer to generate their own link previews and don't really want (or trust) them in federated `attachment`s: https://github.com/snarfed/bridgy-fed/issues/958

**Comment by EdlReg** [comment]
Any progress on this issue? I think it should be a priority, since many Bluesky users are (understandably) hesitant to click on a shortened URL. See example below. 
<img width="603" alt="Skärmavbild 2024-11-10 kl  12 16 01" src="https://github.com/user-attachments/assets/07316453-b979-4248-94bd-2f537f56a783">

**Comment by snarfed** [comment]
No progress yet, sorry.

First step would be to decide that we want to apply this non-standard heuristic described above, specifically that if there are link(s) in the text and no explicit preview, we generate one automatically based on the first link. I don't love that, but I guess I'm ok with it. 

After that, it's just the implementation work. PRs are welcome!

**Comment by EdlReg** [comment]
I can see why you're hesitant/reluctant, but as long as most fediverse clients and servers like Mastodon continue to mostly generate previews from the first link in the post, it sounds like a good fix. 
Unfortunately, I'm not a coder myself, but I'm happy to give feedback on design proposals, if that is of any help.

**Comment by Tamschi** [comment]
Interestingly, there _seems_ to be ongoing work on Mastodon's end to federate link previews: https://www.theregister.com/2024/05/06/mastodon_delays_fix_ddos/

The discussion on that is here: https://github.com/mastodon/mastodon/issues/23662

**If** they go ahead with standardising a federated link preview system, even if it's just a cached version without full trust, then that's likely something that Bridgy Fed _could_ translate back and forth between the networks.

**Comment by snarfed** [comment]
> Can major platforms like Flipboard be persuaded to do anything different to make it work, or is that the wrong end to tackle the issue?

Good question! I talk with people at Flipboard and many of the other big platforms pretty regularly. There are a number of options here, discussed above, but the conclusion right now is probably just to generate the previews ourselves.

**Comment by Steviemac1** [comment]
Thanks, just to add. I now see someone has noted that the bridged posts from Flipboard look like a bot and has added to a warning list. Small scale, but could be indicative of how viewers see the posts.

**Comment by Steviemac1** [comment]
There has been a slight change. More of a text preview now appears on posts from Flipboard, but no image as yet.

**Comment by snarfed** [comment]
Good eye! Yup, I shipped a first pass at this, it works, but doesn't include images yet. Working on those.

**Comment by Steviemac1** [comment]
Sounds like a plan! Thanks.

**Comment by EmilJacobs** [comment]
I see previews now 👀

**Comment by Steviemac1** [comment]
Me too, thank you for the fix. It looks so much better now. 🙌

**Comment by snarfed** [comment]
Rolling this back temporarily due to #1575, sorry. It'll be back soon!

**Comment by popet-master** [comment]
also, you'll want to mind the hashtag (induced) links in the bridged posts. I had a post from piaille.fr Masto that had a hashtag first thing, and it displayed on Bsky with the preview of piaille.fr :grin:

**Comment by snarfed** [comment]
Updated and deployed again. Example:
* https://indieweb.social/@snarfed/113576299711842461
* https://bsky.app/profile/fedi.test.snarfed.org/post/3lca2dpcv4c32

**Comment by chaperon1234** [comment]
My bluesky account is
https://bsky.app/profile/chaperon.fedibird.com.ap.brid.gy
but these toot is not reflected in blue sky.

https://fedibird.com/web/statuses/113586347590177723
https://fedibird.com/web/statuses/113581312460836009

There are several other posts that have not been reflected in blueSky since the day the link preview feature of this issue was implemented.
It appears to be mainly Twitter and Bluesky links, but there are a few other posts that are not being reflected.
Do you know the cause?

**Comment by EdlReg** [comment]
Working great for me, toots with links showing up with previews on Bluesky (my Mastodon account is on the instance Mastodon.nu, btw). Thank you for fixing this, @snarfed !

**Comment by EmilJacobs** [comment]
Just a short addon to this: it works well for short posts that are bridged, but for posts with more than 300 characters, it doesn't. Could this still be fixed?

**Comment by snarfed** [comment]
@EmilJacobs right now, if a post is longer than 300 chars and we have to truncate it, we prioritize the link to the original post.

**Comment by popet-master** [comment]
on some posts, it seems that the image size in the mirrored post is not set as per the original, see e.g.
https://bsky.app/profile/politipet.piaille.fr.ap.brid.gy/post/3lcl3tpopwai2
vs
https://piaille.fr/@politipet/113601175324204315

**Comment by snarfed** [comment]
@popet-master yes! that's https://github.com/snarfed/bridgy-fed/issues/1571

**Comment by Steviemac1** [comment]
I don't know if it’s ok to add to a closed issue.

This was fixed and working ok, but now it’s erratic and only works sometimes with links from Flipboard as fediverse shared on Bluesky.

If you look at @Ayethatllbright.flipboard.com.ap.brid.gy only three of the last 11 Flipboard posts have had an image preview show.

**Comment by Tamschi** [comment]
That's fine, it's regarding this feature after all.

I had a look at https://bsky.app/profile/Ayethatllbright.flipboard.com.ap.brid.gy:
It seems to be consistent regarding the linked domain. I have a hunch that Bridgy Fed is getting bot-filtered by some of them.
@snarfed can likely check this in the logs, but if that is indeed the case, then it's the respective websites that have to allow-list Bridgy Fed or at least serve it a simplified page that still contains the necessary meta data.

**Comment by snarfed** [comment]
Good guess @Tamschi...but these are serving fine for us, looks like the bug here is #1615.

**Comment by EmilJacobs** [comment]
> @EmilJacobs right now, if a post is longer than 300 chars and we have to truncate it, we prioritize the link to the original post.

I get that, what I'm saying is that the link in the bridged post should get priority. If it means the text in the post get shorter, then so be it. I see a huge difference in engagement between posts where the link to the article is bridged, and those that don't. I'm sure two links - one to the article posted and one to the original post - are possible?

**Comment by EdlReg** [comment]
I am experiencing problems with link previews (including thumbnail images) again. Not always, but *very* frequently. 

Example of link preview not working: https://mastodon.nu/@erikdelareguera/114640860396594862 --> https://bsky.app/profile/erikdelareguera.mastodon.nu.ap.brid.gy/post/3lqysnpqum7t2

Exampel of link preview working: https://mastodon.nu/@erikdelareguera/114631284498656093 --> https://bsky.app/profile/erikdelareguera.mastodon.nu.ap.brid.gy/post/3lquklffr6md2

Any idea as to why this is occuring? @snarfed @Tamschi 


<img width="586" alt="Image" src="https://github.com/user-attachments/assets/46656f2b-8aa8-4966-8e24-0ceb1501d28a" />

<img width="598" alt="Image" src="https://github.com/user-attachments/assets/e273bd5c-494e-484c-b27a-d824a780af52" />

**Comment by Tamschi** [comment]
I personally can't check this (I think?), but unless link previews are failing randomly across all linked domains, the most likely explanation is that Bridgy Fed's preview crawler got blocked by the sites (perhaps as part of defensive measures against LLM crawlers).

It _is_ automated traffic after all, and it's not necessarily well-known enough to be exempt by common bot blockers.

**Comment by snarfed** [comment]
@EdlReg interesting! And sorry for the trouble! Is there a pattern to the web sites or domains that you see this trouble with? Is it usually dn.se?

For the example you gave, https://www.dn.se/sverige/unrwa-chefen-sverige-kommer-med-tomma-ursakter/ , I see that it now has OGP and Twitter etc meta tags, but when we first fetched it at 2025-06-07 05:21:48 UTC, it didn't. Is it possible that they first publish their articles without meta tags, and then add them later?

**Comment by EdlReg** [comment]
@snarfed Not sure about the meta tags (it might be that, because it seems kind of random). But it also happens when I post from other news sites:

Example 1: https://bsky.app/profile/erikdelareguera.mastodon.nu.ap.brid.gy/post/3lquyqi4buwc2 (SVT = Swedish TV, state broadcasting)
Example 2: https://bsky.app/profile/erikdelareguera.mastodon.nu.ap.brid.gy/post/3lqkddknhgsk2 (Aftonbladet, one of the largest Swedish newspapers).

**Comment by snarfed** [comment]
Thanks for the examples! Looks like the same thing happened with both of those. We fetched them both successfully - https://www.aftonbladet.se/nyheter/kolumnister/a/EyrW8G/polisen-i-orebro-ville-ha-ett-opolitiskt-massmord at 2025-06-01 11:53:51 UTC , https://www.svt.se/nyheter/inrikes/smsen-visar-ud-avfardade-sida-forslag-om-stod-till-unrwa at 2025-06-05 17:50:19 UTC - but neither had meta tags, so we didn't have any data to populate a link preview embed with.

Maybe they all use the same or similar CMSes that publish articles first, and then later populate their meta tags in the backgrounud?

**Comment by EdlReg** [comment]
Hm, don't know, but yes, maybe they use a CMS or social media editing software that provides meta tags at a later stage. Is there a way to get around this? (Btw, today all links I've posted have worked fine – which is weird). @snarfed

**Comment by snarfed** [comment]
We'd have to ask these publishers. If they don't serve Bridgy Fed any preview info when it fetches an article, I don't have many other options.

**Comment by EdlReg** [comment]
Having the same problem with Youtube-links @snarfed :

Example 1:
https://mastodon.nu/@erikdelareguera/114650692974122375
https://bsky.app/profile/erikdelareguera.mastodon.nu.ap.brid.gy/post/3lr56f6q6wtj2

Example 2:
https://mastodon.nu/@erikdelareguera/114640950173917298
https://bsky.app/profile/erikdelareguera.mastodon.nu.ap.brid.gy/post/3lqwwt6xoqkr2

**Comment by snarfed** [comment]
@EdlReg we don't generate preview for YouTube links right now.

https://github.com/snarfed/bridgy-fed/blob/95e2e3bf3e9517295db65432b6626769fb74083b/common.py#L77-L90

We could change that though!

**Comment by Tamschi** [comment]
YouTube videos are attached as embeds on Bluesky, not sure what the technical details are there.

**Comment by EdlReg** [comment]
Youtube would be very useful, especially if the embedded player works. @snarfed

**Comment by snarfed** [comment]
Looks like the embedded player is all client side in bsky.app. Here's an example, https://pdsls.dev/at://did:plc:fdme4gb7mu7zrie7peay7tst/app.bsky.feed.post/3lrc5r6zohs2s , the underlying record is just a link embed (`app.bsky.embed.external`) like normal.

**Comment by grrywlsn** [comment]
> we don't generate preview for YouTube links right now.
> We could change that though!

sorry for reviving an old thread, but I'm curious on the context for this - is there a reason YouTube is here specifically? I'd like to help get YouTube previews working when bridging ActivityPub -> Bluesky, if I can.

**Comment by snarfed** [comment]
Hi @grrywlsn! No good reason. I'll try allowing it and see how it goes!
