### ISSUE TITLE
"accepted #follow-back-ht..." is listed as waiting to be delivered, and a profile hasn't been made on Bluesky

### ISSUE THREAD

**Issue by killthealias** [snarfed/bridgy-fed#1412]
Hello!
I'm trying to have my account bridged to Bluesky, but when I check it here https://fed.brid.gy/ap/@riley@fiera.social it simply says that the follow back request is waiting to be delivered and that nothing else is synced. The account doesn't have a presence in Bluesky. Is there anything that can be done about this?
Thanks!

**Comment by Tamschi** [comment]
The software is a relatively recent vanilla Mastodon that I _think_ there aren't any known issues with.
The account fulfills the requirements and never blocked the bridge account according to the activity log.

Additionally, the DID Doc shows up in atproto-browser, but the collections can't be fetched: https://atproto-browser.vercel.app/at/riley.fiera.social.ap.brid.gy

Looks like a new bug to me. Thanks for reporting!
Is it correct that bridging this account never worked before?

**Comment by snarfed** [comment]
Looks like this account blocked @bsky.brid.gy@bsky.brid.gy back on 9/10, which tombstoned the ATProto repo, and that can't currently be undone. Background in #1130. We now disable Bluesky accounts a different way that can be undone, and we're working on a way to bring back old tombstoned accounts like this, but I don't have an ETA for that yet.

Also, #1330 would add UX that would help people understand when this has happened.

(Thanks for investigating @Tamschi! We don't currently show blocks in activity logs on user pages.)

**Comment by Tamschi** [comment]
> (Thanks for investigating @Tamschi! We don't currently show blocks in activity logs on user pages.)

Ah, sorry about the confusion! I'll keep that in mind.

**Comment by Tamschi** [comment]
@killthealias I'll close this since the underlying issue that caused this was solved elsewhere, but your account is still stuck until re-enabled manually. You can request this in #1446 or via email (see https://github.com/snarfed/bridgy-fed/issues/1446#issuecomment-2453044197).
