### ISSUE TITLE
AP: set discoverable, indexable flags on actors

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#1419]
We currently don't populate either the [`discoverable` flag](https://docs.joinmastodon.org/spec/activitypub/#discoverable), which allows searching for the user,  or the [`indexable` flag](https://codeberg.org/fediverse/fep/src/branch/main/fep/5feb/fep-5feb.md#specifying-search-indexing-consent-at-the-actor-level), which allows searching posts' full text, on actors bridged into the fediverse from elsewhere. We should! ...maybe?

Obviously this wouldn't be a blanket policy, we'd need to look at each network and its semantics separately...but web and Bluesky do seem to fit. Bridgy Fed already requires users to be fully public, eg they can't have Bluesky's "show to logged in users only" setting on. Otherwise, Bluesky allows global full text search over profiles and posts. Web does too, at least by default, unless the site has blocked some or all crawlers in `robots.txt`.

Fwiw, [both flags seem to apply](https://docs.joinmastodon.org/spec/activitypub/#discoverable) [to remote instances as well as local](https://socialhub.activitypub.rocks/t/fep-5feb-search-indexing-consent-for-actors/3550/4), ie if they're set to true, searches on any instance can return the user and their posts, not just the user's local instance.

**Comment by snarfed** [comment]
Loosely related: we have [docs on how to use `rel=alternate`](https://fed.brid.gy/docs#searchable) to make web posts searchable in the fediverse when you search for their exact URL, but obviously not the same as user or post full text search.

**Comment by Tamschi** [comment]
This is the text Mastodon uses to describe these options:

> **Feature profile and posts in discovery algorithms** [Recommended]
>
> Your public posts and profile may be featured or recommended in various areas of Mastodon and your profile may be suggested to other users.

> **Include public posts in search results**
>
> Your public posts may appear in search results on Mastodon. People who have interacted with your posts may be able to search them regardless.

Semantically speaking, both of these are currently always-on within Bluesky.

**Comment by snarfed** [comment]
Done!
