### ISSUE TITLE
Re-enable tombstoned Bluesky bridged accounts that tried to re-enable themselves

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#1446]
People can now undo deactivating their Bluesky bridged accounts, #1130, but only going forward. I need to manually fix accounts that we deactivated before that, by tombstoning: https://github.com/snarfed/bridgy-fed/issues/1130#issuecomment-2430525165.

Here's repl code that works for this, modulo https://github.com/snarfed/arroba/issues/34:

```py
a = ActivityPub.query(ActivityPub.handle == '...').get()
a.enabled_protocols = ['atproto']
a.obj.copies = []
a.obj.put()
a.copies = []
a.put()
ATProto.create_for(a)
ATProto.bot_follow(a)
```

**Comment by englut** [comment]
> ... I need to manually fix accounts that we deactivated before that, by tombstoning: https://github.com/snarfed/bridgy-fed/issues/1130#issuecomment-2430525165.

Will there be a request process for the manual fixes? 🙏

**Comment by snarfed** [comment]
Good question! I don't know. I can generally detect people who tried unsuccessfully to re-activate their Bluesky bridged accounts, but I'm not sure if I should. If someone tried many months ago and gave up, it might be an unpleasant surprise if their Bluesky bridged account suddenly reappeared even though they didn't do anything new themselves.

On the other hand, I don't really plan to put a lot of effort into a big formal process or outreach. It'd probably just be filing issues here or emailing feedback@brid.gy.

@englut want me to reactivate https://mastodon.social/@quaff 's Bluesky bridged account?

**Comment by englut** [comment]
I think that's a good approach. Best to not put too much effort into it, cause you never know people's intentions after so much time with things like this.


> @englut want me to reactivate https://mastodon.social/@quaff 's Bluesky bridged account?

Yes please! 🙏

**Comment by snarfed** [comment]
Done!

**Comment by snarfed** [comment]
@dreki48 sure! I've tried, but https://github.com/snarfed/arroba/issues/34 is making it difficult. I probably need to fix that first.

**Comment by killthealias** [comment]
May I have https://fiera.social/@riley re-enabled?

**Comment by letydoesstuff** [comment]
I love all the work being done here, was just messing around with how it all worked a few months ago and ended up tombstoning my account basically Can I please have https://doesstuff.social/@lety re-enabled?

**Comment by snarfed** [comment]
@killthealias @letydoesstuff done!

**Comment by snarfed** [comment]
@dreki48 yours should be working now too, https://bsky.app/profile/did:plc:kjsytn3xeyblnmnituhda7rr

**Comment by toi-co** [comment]
Hi, I blocked the bridge a month ago.
Can I have https://fedibird.com/@toico re-enabled?

**Comment by snarfed** [comment]
@toi-co yes! Done.

**Comment by citro-ignitiondorks** [comment]
Hello! Sorry to bother but could I have https://blorbo.social/@citro reenabled too? Thank you so much! 🥺

**Comment by snarfed** [comment]
Done! https://bsky.app/profile/citro.blorbo.social.ap.brid.gy

**Comment by citro-ignitiondorks** [comment]
Thank you!

**Comment by vicigrinberg** [comment]
Would you be able to do the same for me? I'd appreciate this a ton!

https://bsky.app/profile/vicgrinberg.mastodon.social.ap.brid.gy

**Comment by snarfed** [comment]
I'm working on automating this, that should be ready within a day or two. I'll update here when it's ready.

**Comment by snarfed** [comment]
Done! @vicigrinberg could you un-follow and re-follow @bsky.brid.gy@bsky.brid.gy and see if that works now?

**Comment by vicigrinberg** [comment]
This works! Thank you so much, really appreciate this!

**Comment by lxgr** [comment]
Hi,

could you please revive/re-bridge [lxgr.net](https://bsky.app/profile/lxgr.net) on Bluesky and [@lxgr@mastodon.net](https://mastodon.social/@lxgr) on the Fediverse? They both seem broken at the moment (https://bsky.app/profile/lxgr.mastodon.ap.brid.gy and https://mastodon.social/@lxgr.net@bsky.brid.gy respectively).

I've tried to unfollow and re-follow, but it didn't help.

Thank you!

**Comment by snarfed** [comment]
Sorry @lxgr! This is probably #1520. We should be caught up again soon!

**Comment by klarheit-git** [comment]
Could you please reactivate the following account?  About a month ago I blocked a bridge account while trying to get it to work. 😢

https://fedibird.com/@NagiSia
https://fed.brid.gy/ap/@NagiSia@fedibird.com

**Comment by snarfed** [comment]
@klarheit-git you can now do this by un-blocking and re-following the @bsky.brid.gy@bsky.brid.gy fediverse user.

...and usually this would work more or less immediately, but right now our bridging into Bluesky is paused. Sorry for the inconvenience. Feel free to follow https://github.com/bluesky-social/atproto/discussions/3094 and https://github.com/snarfed/bridgy-fed/issues/1520 for details.

**Comment by klarheit-git** [comment]
Thank you! I'll take a look at that thread too.

**Comment by Nanchohyang** [comment]
Hello, I ask for your understanding that the language may be awkward because I'm using a translator. 

I've blocked accounts that connect me to make sure it's not a spoiler to the Bluesky side. 
If I knew that blocking would lead to permanent account deletion, I would have chosen another way...
It's my fault, but is there any way I can recover that account?

Mastodon Page >> https://sharlayan.in/@nancho
Bridge Page >> https://fed.brid.gy/ap/@nancho@sharlayan.in
Bluesky Page >> https://bsky.app/profile/nancho.sharlayan.in.ap.brid.gy 

If it's a mistake to leave the corresponding post here, I'm also sorry about this. 
I'm new to Github, so I'm not sure if I should leave it here. If it's wrong, please let me know the right place to post and I'll leave it there.

Thank you!

**Comment by snarfed** [comment]
@Nanchohyang hi! Bridgy Fed now supports re-activating bridged accounts after you deactivate them. Try un-blocking @bsky.brid.gy@bsky.brid.gy and then re-follow it again.

**Comment by Nanchohyang** [comment]
@snarfed Thank you for your kind reply!

When I search the bridge account on Bluesky, it says it's the wrong handle, but can't I restore that handle to its original state?
(ex. @nancho.sharlayan.in.ap.brid.gy )

![화면 캡처 2024-12-17 143659](https://github.com/user-attachments/assets/1472a6e0-dbe6-4f47-abac-3d9498fae209)

**Comment by Nanchohyang** [comment]
I hope your day is happy!! Thank you so much for your help!

**Comment by cannedit** [comment]
Hi,

Unblocking and re-following unfortunately didn't work for me, so can you please do your magic for: @dongensis@mastodon.social

Thank you in advance!

**Comment by snarfed** [comment]
Hi @cannedit! Bridgy Fed only bridges your posts (and reposts of other bridged accounts, etc) going forward. https://fed.brid.gy/docs#troubleshooting Looks like you re-enabled the bridge about five hours ago, and you haven't posted anything new on https://mastodon.social/@dongensis since then. Try posting something new?

**Comment by cannedit** [comment]
Hi,

Ah, yes, after I posted something on my Mastodon account these posts appear on the bridged BlueSky account, but not the reposts of Mastodon users, apparently because they don't have their accounts bridged to BlueSky. 

So it's just a mirror of my Mastodon account, mainly of my own posts, not a full-blown BlueSky account, and I can't login there, post there independently nor follow BlueSky users, right? But can BlueSky users follow me there?

Thank you for the explanations.

**Comment by snarfed** [comment]
> So it's just a mirror of my Mastodon account, mainly of my own posts, not a full-blown BlueSky account, and I can't login there, post there independently nor follow BlueSky users, right? But can BlueSky users follow me there?

Yes and yes! https://fed.brid.gy/docs#use-like-normal

**Comment by cannedit** [comment]
Thanks!

One other thing I noticed and want to check: edits on Mastodon posts are not 'mirrored' by the BlueSky acount, only the first version of the Mastodon post is copied ...

**Comment by snarfed** [comment]
> One other thing I noticed and want to check: edits on Mastodon posts are not 'mirrored' by the BlueSky acount, only the first version of the Mastodon post is copied ...

Right, Bluesky itself doesn't support editing posts yet. #947

**Comment by mue2e** [comment]
Hello! I didn't know what to do, so I ended up here looking for it. I think I accidentally deleted the account that connects with Mastodon on Blue Sky due to a little lack of understanding of the features. I can't find my bridge account too because I didn't even get a message. I'm at a loss. Please help T.T)

Bluesky acc> @muese.bsky.social

**Comment by snarfed** [comment]
@mue2e sorry for the trouble! Looks like your bridged account is @muese.bsky.social@bsky.brid.gy ; also see https://fed.brid.gy/bsky/muese.bsky.social , https://planet.moe/@muese.bsky.social@bsky.brid.gy .

**Comment by mue2e** [comment]
> [@mue2e](https://github.com/mue2e) sorry for the trouble! Looks like your bridged account is @[muese.bsky.social@bsky.brid.gy](mailto:muese.bsky.social@bsky.brid.gy) ; also see https://fed.brid.gy/bsky/muese.bsky.social , https://planet.moe/@muese.bsky.social@bsky.brid.gy .

ToT) Thank you !!!!!!!!!! <3
