### ISSUE TITLE
AP -> AT: Bridge protected (non public but visible to anyone) posts

### ISSUE THREAD

**Issue by HotoRas** [snarfed/bridgy-fed#1449]
Many of the people(including [me](https://nekoplanet.xyz/@ras "My main fediverse account @ras@nekoplanet.xyz")) posts non-public postings, like 'Protected'. It's tracked, but seems like not bridging to AT.

Is there any plans to bridge them?

**Comment by HotoRas** [comment]
Something cursed found, will check if someone posted about and will reopen with updated contents if nothing there

**Comment by HotoRas** [comment]
Issue updated and re-opening

**Comment by ygg2** [comment]
This should be https://github.com/snarfed/bridgy-fed/issues/1036!
The main reason they are not bridged is a lot of software doesn't make them searchable/in discovery features, and everything on Bluesky is searchable/discoverable

**Comment by HotoRas** [comment]
Checked it out, closing as np(invalid)
