### ISSUE TITLE
Re-instated (previously deleted account) on bsky can't get the bridge working

### ISSUE THREAD

**Issue by DoktorZjivago** [snarfed/bridgy-fed#1451]
I think I’ve seen this issue before. This account on bluesky deleted his account a few months ago. 

https://bsky.app/profile/bassesbasta.bsky.social

Which meant the name was available, however, he created a new account with the same name a few days ago, and also re-followed the bridge on bsky recently. But even though he re-followed the bridgy account on bsky, his posts doesn’t get bridged to the fediverse. Is there something you can do to help? :-)

**Comment by snarfed** [comment]
Hi! Yeah we don't officially support this yet, but we should. That's tracked in #1293. For now, I've fixed this one manually.
