### ISSUE TITLE
Bluesky account, bridged, 404's in Mastodon?

### ISSUE THREAD

**Issue by city41** [snarfed/bridgy-fed#1453]
Thanks for making this!

I'm brand new to all of this stuff and trying to link my [bluesky profile](https://bsky.app/profile/retrodotcards.com) via bridgy so it shows up in Mastodon.

I first followed [ap.brid.gy](https://bsky.app/profile/ap.brid.gy) about an hour ago.

About 5 minutes ago I made [this post](https://bsky.app/profile/retrodotcards.com/post/3la5hxnceky2l)

And I do see it show up at [fed.brid.gy](https://fed.brid.gy/bsky/retrodotcards.com).

But Mastodon always 404's when I try to load my bridged account over there

https://mastodon.social/@retrodotcards.com@bsky.brid.gy

I feel like I'm missing something. I've read all the docs and also looked at other bridged accounts with no luck.

**Comment by city41** [comment]
Looks like I just wasn't patient enough. I'm now seeing some stuff in Mastodon.

https://mastodon.social/@retrodotcards.com@bsky.brid.gy

tries to redirect and I've yet to see it succeed, but that feels more in mastodon's area

Searching for my account on Mastodon does find it now though.

Thanks!

**Comment by snarfed** [comment]
Glad it's working now! Yeah loading URLs for remote actors directly in Mastodon like that isn't supported well. It doesn't really work at all if you're logged out, and it seems inconsistent at best even if you're logged in. 🤷
