### ISSUE TITLE
Incomplete event with null data replaced by a different event type when replaying the event sequence

### ISSUE THREAD

**Issue by godfrey-altmetric** [snarfed/bridgy-fed#1459]
This may be related to https://github.com/snarfed/bridgy-fed/issues/1367 but I raise this as a new issue so as to not detract attention from that issue if it is not related.

We're consuming from the bsky.network firehose, and observed a bsky repost event on 2024-11-01, which had null data (something that raised an exception in our code).

A short while later, when debugging this issue, we used the sequence id (minus 1) of the event prior as a cursor to replay the event when connecting to the firehose. When the event for that sequence id was returned, we saw that an entirely different event was returned (a create post, instead of the repost). This event was fully populated, and the only thing that was the same was the user's profile identifier (did:plc:..) and the sequence id.

We noticed that this user is using Bridgy-fed, by the inclusion of `bridgyOriginalUrl` and `bridgyOriginalText`. From what Bluesky have told us, this shouldn't be possible, as the relays are responsible for assigning sequence ids, and when subscribing with a previous event, it is retrieved from the event log. Has anyone come across this same issue?

**Comment by snarfed** [comment]
@godfrey-altmetric any thoughts here? I'm happy to help debug etc, but not sure what I can do otherwise.
