### ISSUE TITLE
AP -> Bluesky: Delivery failed on Mastodon server with limited federation mode

### ISSUE THREAD

**Issue by n-nekocha** [snarfed/bridgy-fed#1463]
I am running a Mastodon server which is set to [limited federation mode](https://docs.joinmastodon.org/admin/config/#limited_federation_mode). I have manually approved `bsky.brid.gy` domain on this server, and while some bridge accounts have shown up in search, it seems that delivery between `bsky.brid.gy` and my server is failing.

![delivery_failed](https://github.com/user-attachments/assets/703cd498-8168-4950-aeb5-eb6347c90f88)

Also when I tried following a bridge account, the follow request remained pending. This is similar to #1391 but my server's Mastodon version is up to date.
Is this related to my server being in limited federation mode? Is it possible to use Bridgy Fed with this mode?

I found this message in the log:
`Nov 10 01:09:59 bundle[795059]: I, [2024-11-10T01:09:59.372475 #795059]  INFO -- : method=GET path=/users/iretate_nekocha format=json controller=AccountsController action=show status=403 allocations=1434 duration=6.71 view=0.46 db=1.34 key=https://fed.brid.gy/fed.brid.gy#key`

**Comment by snarfed** [comment]
Hi! Looks like yes, this is due to limited federation. Could you approve fed.brid.gy also and then try again?

**Comment by snarfed** [comment]
Also, allowing bsky.brid.gy and fed.brid.gy will only allow Bluesky accounts via Bridgy Fed, not web sites. You can allow some of those by adding web.brid.gy too, but you still won't allow bridged web sites that use their own domain, like me, @snarfed.org@snarfed.org. Up to you.

**Comment by n-nekocha** [comment]
I approved fed.brid.gy too and now I can follow a bridge account! Also the delivery error is resolved as well.
Thank you so much! Bridgy Fed is really amazing, decentralized sns is more confortable with this!
