### ISSUE TITLE
Docs: fediverse admin section

### ISSUE THREAD

**Issue by Tamschi** [snarfed/bridgy-fed#1465]
This is a follow-up to  #1463.

It would be good to document specific federation requirements for remote networks, i.e. that `fed.brid.gy` must be federated with in addition to `bsky.brid.gy` or `web.brid.gy` and (or?) individual custom domains of bridge accounts.

The explanation should mention '[limited federation mode](https://docs.joinmastodon.org/admin/config/#limited_federation_mode)' to make it easier to discover for Mastodon admins.

**Comment by snarfed** [comment]
Yes! This would be part of a bigger "I'm an instance admin, what do I need to know?" section that I want to write. Will do.

**Comment by snarfed** [comment]
Other things to note here:
* Opt in
* Only fully public profiles, posts, and other data are bridged. unlisted/quiet public not included.
* Multiple subdomains: bsky, web, fed, ap, more in the future
  * Some web site actors will be on their own domains, eg @snarfed.org@snarfed.org
* Authorized fetch by instance actor `https://fed.brid.gy/fed.brid.gy`
* Spam filters, other troubleshooting info in https://fed.brid.gy/docs#troubleshooting
* DMs
* blocks are translated, both directions
* reports (`Flags`) are translated to Bluesky reports
* bot accounts are `Service`, bridged users are `Person`
* all accounts are normal AP accounts, subject to normal moderation tools, etc
