### ISSUE TITLE
Can't set domain name on BSky

### ISSUE THREAD

**Issue by edent** [snarfed/bridgy-fed#1467]
* AP Account is https://bot.viii.fi/bot
* Following the bridge
* Appearing as https://bsky.app/profile/bot.bot.viii.fi.ap.brid.gy
* DID is resolving at https://bot.viii.fi/.well-known/atproto-did
* Debug shows it working https://bsky-debug.app/handle?handle=bot.bot.viii.fi.ap.brid.gy
* Using https://fed.brid.gy/ap/@bot@bot.viii.fi and hitting 🔁 says "Updating profile from `@bot@bot.viii.fi`..."
* If I visit https://bsky.app/profile/bot.viii.fi - the account appears.
* But if I try to mention it or search for it, the request fails ![image](https://github.com/user-attachments/assets/9ea37cb0-8dd1-4cb9-99a7-bec990f94d4c)

Any pointers gratefully received!

**Comment by Tamschi** [comment]
Did you DM `username @bot.viii.fi` to `@bsky.brid.gy@bsky.brid.gy` after setting up the DID pointer on your domain?

(Just in case, here's the documentation: [Can I use my own domain as my Bluesky handle?](https://fed.brid.gy/docs#bluesky-enhanced))

**Comment by edent** [comment]
@Tamschi thanks! That did the trick.

**Comment by Tamschi** [comment]
Thanks for the PR! (I don't review those, but looks good to me.)

Hopefully adding DM support wasn't too much trouble on your end :slightly_smiling_face:
I'll close this as completed.
