### ISSUE TITLE
Bridging fediverse to Blusky: no reply when setting custom domain

### ISSUE THREAD

**Issue by jmaris** [snarfed/bridgy-fed#1474]
Hi all,

I've recently set up bridging of my fediverse account to Blusky, and gone through the process of adding a DNS record for a custom Blusky username, which blusky's DNS validator says is okay.

The final step is to inform the bridgey-fed bot. Hence I sent a private DM to the bot with:
`@bsky.brid.gy username mydomain.com` 

(with mydomain.com replaced with my domain)

Unfortunately, I haven't received a reply from the bot since, all other functions work fine, though.

What could be the reason for this?

**Comment by jmaris** [comment]
Okay, it looks like my handle on blusky has been updated, the bot just didn't tell me.

**Comment by TomCasavant** [comment]
https://github.com/snarfed/bridgy-fed/issues/826#issuecomment-2450143435

I believe that's expected behavior as of right now, if everything works you won't get a DM response

**Comment by snarfed** [comment]
Sounds like some DMs got lost somewhere. The bot definitely replies and tell you when it successfully sets your handle, but if your handle is already set to a given domain, and you try to set the same domain, the bot won't repeat the confirmation.

I tested with `help` just now and got a response, so DMs aren't broken overall. @jmaris @Fauli1221 I'm happy to look into your missing DMs if you can tell me which accounts to look at!

**Comment by Fauli1221** [comment]
My account is `@fauli1221@hooves.social`

**Comment by snarfed** [comment]
@Fauli1221 looks like BF isn't handling Sharkey's DM text format right. Should be an easy fix. Thanks for reporting!

**Comment by snarfed** [comment]
@Fauli1221 hopefully fixed, feel free to try again.

**Comment by Fauli1221** [comment]
@snarfed unfortunately it doesn't seem like it send another help command a few minutes ago and still did not get a reply

**Comment by jmaris** [comment]
for me it is @jmaris@eupolicy.social!

**Comment by snarfed** [comment]
@Fauli1221 sorry, my bad, that deploy didn't have your fix after all. I've deployed it for real now.

and @jmaris thanks for the nudge! that was a separate bug, fixed now, should be deployed in ~7m.

**Comment by Fauli1221** [comment]
It works for me again

**Comment by jmaris** [comment]
Amazing, I'll take this opportunity to say thanks for your amazing work, and close this issue :)
