### ISSUE TITLE
Various improvements to invite DMs

### ISSUE THREAD

**Issue by FurblandChannel** [snarfed/bridgy-fed#1478]
I feel like this would go hand in hand with the other task open right now about making the invite DMs simpler. When a request is sent to an already bridged user, the bot should inform them as such and send a link to their bridged profile. It would also be nice for the bot to notify the user making the request if the user being sent the invite has their DMs closed. Thirdly, if you have sent an invite to someone or requested to invite someone that has already been invited, the bot should send you a DM with the bridged profile once the invite has been accepted.

**Comment by snarfed** [comment]
Definitely good ideas! The first one is already implemented: when you request an already bridged user, the bot replies and says so and links to their profile. The second and third are https://github.com/snarfed/bridgy-fed/issues/1326 and https://github.com/snarfed/bridgy-fed/issues/1321 , respectively.

**Comment by FurblandChannel** [comment]
Got it, awesome! Closing as there is already a task for this.
