### ISSUE TITLE
Using my own Domain for my Fedi -> Bluesky Bridge Account

### ISSUE THREAD

**Issue by 343max** [snarfed/bridgy-fed#1488]
I'm trying to use a custom domain for my bridged bluesky account:
In the last step I sent a mastodon dm:

```
@bsky.brid.gy 343max.mastodon.social.ap.brid.gy mastodon.343max.de
```

this results in this response:

```
Max von Webel · @343max@mastodon.social is already bridged into the fediverse.
```

Then I tried this:

```
@bsky.brid.gy@bsky.brid.gy @343max@mastodon.social mastodon.343max.de
```

and received no response at all.

**Comment by snarfed** [comment]
Hi! Sounds like you're looking for the `username` command? https://fed.brid.gy/docs#bluesky-enhanced

**Comment by 343max** [comment]
Ahhh! So `username [domain]` literally means `username mastodon.343max.de`. I'd never had guessed that! The tool is pretty amazing, but the documentation ist very confusing. Thank you!

**Comment by 343max** [comment]
It worked fine now. Uff!
