### ISSUE TITLE
Cannot get my account to bridge (gnarlybear.mastodon.social.ap.brid.gy)

### ISSUE THREAD

**Issue by OnceAnArtifact** [snarfed/bridgy-fed#1489]
@bsky.brid.gy hello. This doesn’t seem to be working. I was able to follow my partner on Bluesky but I have followed your account on mastodon and I have still not populated for him to follow via gnarlybear.mastodon.social.ap.brid.gy which is accordance with the how to guide and documentation. 

Are you able to assist?

**Comment by snarfed** [comment]
Hey, sorry for the trouble! Have you looked at https://fed.brid.gy/docs#troubleshooting ?

**Comment by Tamschi** [comment]
The account was created yesterday according to mastodon.social, so it fails the "must be older than 14 days" test.
(There was a spam wave from Nostr through Momostr through Bridgy Fed onto Bluesky, so there's a rudimentary spam filter now.)

Bridgy Fed should be clearer about what's going on in those cases though, that's #758.

**Comment by OnceAnArtifact** [comment]
Thank you for the clarification. I will try again once my account has been
activate for the 14 day time period.
