### ISSUE TITLE
AP: Invalid `object` in `Follow` in `Accept`

### ISSUE THREAD

**Issue by Tamschi** [snarfed/bridgy-fed#1492]
> I enabled trace logging in GoToSocial and retried a follow. Looks like it's upset with this:
> 
> ```json
> {
>     "@context": "https://www.w3.org/ns/activitystreams",
>     "actor": "https://bsky.brid.gy/ap/did:plc:inze6wrmsm7pjl7yta3oig77",
>     "id": "https://bsky.brid.gy/convert/ap/did:plc:inze6wrmsm7pjl7yta3oig77/followers#accept-https://gotosocial.i.eta.st/users/eta/follow/01JYZNV5JJ9GP3QQTDJJG4HP5X",
>     "object": {
>         "actor": "https://gotosocial.i.eta.st/users/eta",
>         "id": "https://gotosocial.i.eta.st/users/eta/follow/01JYZNV5JJ9GP3QQTDJJG4HP5X",
>         "object": "did:plc:inze6wrmsm7pjl7yta3oig77",
>         "to": "https://bsky.brid.gy/ap/did:plc:inze6wrmsm7pjl7yta3oig77",
>         "type": "Follow",
>         "url": "https://gotosocial.i.eta.st/users/eta#followed-did:plc:inze6wrmsm7pjl7yta3oig77"
>     },
>     "to": "https://www.w3.org/ns/activitystreams#Public",
>     "type": "Accept"
> }
> ```
> 
> I would hazard a guess that it's looking at the `object` property, and not the `to`  (this seems to point in that direction: https://github.com/superseriousbusiness/gotosocial/blob/main/internal/typeutils/astointernal.go#L465). Putting a bsky DID in there is certainly interesting -- I'm surprised that doesn't cause more problems!
> 
> (edit: looking at the [spec](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-follow) and what mastodon does, I'm not sure that's indeed compliant)

_Originally posted by @eeeeeta in https://github.com/snarfed/bridgy-fed/issues/1033#issuecomment-2480020155_

**Comment by Tamschi** [comment]
This should have the original `Follow`'s `object`, I'll see if I can find it.

**Comment by Tamschi** [comment]
Unfortunately not, looks like it's a bit too indirect to be a really quick fix.

**Comment by snarfed** [comment]
Hah, funny! Yup, bug on our part, definitely not intentional. Will fix.

**Comment by snarfed** [comment]
Fixed! Will be deployed in ~7m.
