### ISSUE TITLE
Attempt to follow @bsky.brid.gy@bsky.brid.gy from WordPress Friends plugin fails

### ISSUE THREAD

**Issue by solarbirdy** [snarfed/bridgy-fed#1493]
Hi! Installed the Friends plugin to my selfhosted latest-WordPress instance running ActivityPub at https://solarbird.net/.

I then attempted to friend @bsky.brid.gy@bsky.brid.gy in order to allow ActivityPub follows from BlueSky. It fails with a “too many redirects” error:

Too many redirects (https://bsky.brid.gy/bsky.brid.gy)

I have filed this with the Friends plugin author as well, of course. But since following Mastodon accounts seems to work fine, it's quite possible they'll throw the ball back to me and say to ask you.

However it gets addressed, it would be very nice if I could follow @bsky.brid.gy@bsky.brid.gy from the WordPress Friends plugin with ActivityPub as I'm hoping that would work as an opt-in on the gateway, thus enabling BlueSky users to follow my Federated blog instance using standard Fediverse nomenclature.

Thank you! ^_^

**Comment by snarfed** [comment]
Hey, sorry for the trouble! I think I might see what's going on here. We don't currently serve `Vary: Accept` for AP actors like this, but we need to. I'll try that and see if it helps.

**Comment by snarfed** [comment]
Not confident that will solve your problem, though. I don't see that BF is serving multiple redirects or a loop. Guess we'll see.

**Comment by snarfed** [comment]
Not confident that will solve your problem, though. I don't see that BF is serving multiple redirects or a loop. Guess we'll see.

**Comment by solarbirdy** [comment]
I look forward to trying it! ^_^

Obviously I have no idea whether that error reflects what's actually going on or whether it's just a fallback error, so it totally could be misleading.

Will you note here when the change is in place, or otherwise, how best should I track it?

**Comment by snarfed** [comment]
Yup, I'll update here.

**Comment by snarfed** [comment]
@solarbirdy mind trying again? I give it 50/50 that this fixes your issue 😁

**Comment by solarbirdy** [comment]
Oh, already! Not at all, I'll give it a try right now...

No.

Dang.
<img width="1221" alt="Screenshot 2024-11-16 at 2 30 51 PM" src="https://github.com/user-attachments/assets/991b07b1-a33f-4e34-b9a0-d8756cc16c46">

**Comment by snarfed** [comment]
@solarbirdy the Friends plugin is evidently sending an unusual `Accept` header for AP/AS2 conneg that Bridgy Fed isn't understanding. I've added some logging, mind trying again?

**Comment by solarbirdy** [comment]
Gladly! Here we gooooo...

Done. Same result and error at the moment of course.

**Comment by snarfed** [comment]
Well that's odd. The Friends plugin isn't even trying to do AP conneg, it's fetching https://bsky.brid.gy/bsky.brid.gy with `Accept: */*`, which is wrong: https://www.w3.org/TR/activitypub/#retrieving-objects

@solarbirdy is this the latest version of the plugin? If so, you'll probably want to file a bug: https://github.com/akirk/friends/issues

**Comment by solarbirdy** [comment]
I am running the latest version. I've also already opened an issue - I contact both of you at the same time - over at [the plugin support page](https://wordpress.org/support/topic/attempting-to-follow-bridgyfed-the-fediverse-bluesky-bridge-fails/). I know that Alex responds to posts there, and I will add this to it with a link.

I'll also ask whether I should open it as an issue on the Github side, and try to keep everybody up to date.

**Comment by akirk** [comment]
Thanks for all the debugging here! The reason the plugin sends an `Accept: */*` request first is that the feed discovery also needs to work for non-ActivityPub sources. The issue was actually that I set the redirect to a too low number, [just raising it by 1 makes it work](https://github.com/akirk/friends/pull/389)!

![Screenshot 2024-11-18 at 08 49 51](https://github.com/user-attachments/assets/0e4cb268-640d-4c46-ad63-a4e3e7e69445)

**Comment by solarbirdy** [comment]
I came here to say it looked like it works and to give a link back!

https://wordpress.org/support/topic/attempting-to-follow-bridgyfed-the-fediverse-bluesky-bridge-fails/#post-18142632

Thanks to everybody, this was great :D

**Comment by snarfed** [comment]
Thank you @akirk!

**Comment by solarbirdy** [comment]
Got confirmation that it worked this morning too! :D 

Seriously this is fun xD

https://mastodon.cloud/@SarekOfVulcan/113505224593928376
