### ISSUE TITLE
Delete the profile created with bridgy-fed

### ISSUE THREAD

**Issue by frananc** [snarfed/bridgy-fed#1496]
Greetings. 
Coming from Friendica (to be more precise its Italian server, Poliverso) I created a bridgy-fed account, but unfortunately this does not post what I entered in Friendica/Poliverso. 
I would therefore like to delete this account to create a new one (with the same name) directly on Bluesky, and then use another way (that I read exists) to post from Friendica on the newly created account. 
So the question is: **how to delete a bridgy-fed account?**
Thanks,
Frananc

**Comment by Tamschi** [comment]
You can block `@bsky.brid.gy@bsky.brid.gy` [or send `stop` via DM](https://fed.brid.gy/docs#dm-commands) to deactivate the Bluesky account. This should also hide the account in search, if I'm not mistaken.

**Comment by frananc** [comment]
Thanks Maschi,
but it seems it is not possible to send DM type messages from the account I want to delete.

**Comment by Tamschi** [comment]
Are you able to block it?

Otherwise, @snarfed can deactivate or delete the bridge account manually if necessary.

**Comment by frananc** [comment]
I sent a message via Mastodon. Let's see what happens.
Thanks a lot!

**Comment by snarfed** [comment]
Feel free to reopen if that doesn't work @frananc!
