### ISSUE TITLE
fedi bot doesn't accept invite and follow back 

### ISSUE THREAD

**Issue by paczesik** [snarfed/bridgy-fed#1497]
Cannot follow fedi bot from my account @arkd.wspanialy.eu, it doesnt accept it. Tried a couple of times, looked for something in the settings, no clue.

**Comment by Tamschi** [comment]
Your account was created around six days ago. We currently require accounts to be at least 14 days old to avoid problems with spam bots. More info here: https://fed.brid.gy/docs#troubleshooting

We could communicate this better. (See #758)

For now, please cancel the follow request and re-follow once the account is older than 14 days. It should work without issue then.
