### ISSUE TITLE
Extra Trailing Slash in Nginx Redirect

### ISSUE THREAD

**Issue by miklb** [snarfed/bridgy-fed#15]
I added the nginx redirect `rewrite ^/.well-known/(host-meta|webfinger).* https://fed.brid.gy/$request_uri redirect;` to my nginx conf file

However when I try visiting that url `https://miklb.com/.well-known/webfinger` to see why I wasn't showing up in Mastodon search, I see that it gets an extra trailing slash `https://fed.brid.gy//.well-known/webfinger`

Suggestions?

**Comment by miklb** [comment]
Quick follow up I removed the trailing slash from `fed.brid.gy$request_uri` and that does remove the extra slash, but still get a `400 - Missing required parameter: resource`

**Comment by miklb** [comment]
Another follow up, now I'm seeing at `https://bridgy-federated.appspot.com/.well-known/webfinger?resource=miklb.com` that my h-card is bad. So thinking if I fix that plus removing that extra trailing slash I should be making good progress.

**Comment by snarfed** [comment]
thanks again for filing @miklb!
