### ISSUE TITLE
bsky to fedi didn't works

### ISSUE THREAD

**Issue by wbz0100** [snarfed/bridgy-fed#1500]
bsky to fedi didn't work since about 6 hours ago

**Comment by StarWolf3000** [comment]
The bot doesn't seem to follow bsky users as well, resulting in not bridging to fedi.

**Comment by excelsior091224** [comment]
Same here.
I just posted on bsky, but it doesn't seem to be bridged to Fediverse.
My bsky account:
https://bsky.app/profile/gimletmariaasamiya.bsky.social
My bsky account's bridgyfed:
https://fed.brid.gy/bsky/gimletmariaasamiya.bsky.social
The post made on November 18, 2024, 0:25 Japan time is not reflected on bridgyfed.

**Comment by StarWolf3000** [comment]
Looks like it's working again.

**Comment by snarfed** [comment]
Hey, sorry for the trouble! Yeah we had some downtime and backlogs last night, but hopefully pretty much resolved now.

**Comment by wbz0100** [comment]
![image](https://github.com/user-attachments/assets/52515a18-d902-40ab-98d7-27ff6a750546)
it delayed to much. is this normal?
