### ISSUE TITLE
Can't follow @bsky.brid.gy@bsky.brid.gy from my Mastodon account @thb_media@sueden.social - @Bluesky works

### ISSUE THREAD

**Issue by thhubm** [snarfed/bridgy-fed#1502]
I can't follow @bsky.brid.gy@bsky.brid.gy from my Mastodon account @thb_media@sueden.social 
Is underscore also a problem in the middle of the account name? I still tried some days.
My Bluesky account @thb-media.bsky.social works fine (thanks!).

**Comment by snarfed** [comment]
Sorry for the trouble! The underscore is fine. Have you looked at https://fed.brid.gy/docs#troubleshooting ?

**Comment by Tamschi** [comment]
The account was created November 10th, which is too recent to get past the spam filter.
(~8 days vs. the 14 that are necessary.)

We could be more proactively clear about this. That's #758.

You can cancel the follow-request and retry once the account is old enough.

**Comment by eloquence** [comment]
Just ran into this as well trying to bridge a couple of https://freedom.press/ accounts to Bluesky. We just set up a dedicated instance, so the accounts appear as "new" even though they're years old.

We'll try again, but it might be nice if there was some kind of human review loop to get around the spam filter. I do appreciate that this is volunteer-run infrastructure, of course!
