### ISSUE TITLE
Migrading a normal Fedi account to the bridged account.

### ISSUE THREAD

**Issue by IoIxD** [snarfed/bridgy-fed#1504]
Hi, none of the open issues on GitHub or the FAQ mention the possibility of being able to move my old Fedi account to the bridged account so that my old Fedi followers follow that one instead. Will this ever be supported?

**Comment by Tamschi** [comment]
That's #330. Notably it seems to work for accounts bridged from the web already (but not for accounts bridged from Bluesky). Migrations _off_ the bridge appear to not yet be supported in general.

**Comment by IoIxD** [comment]
Ah, yeah that should be put in the FAQ

**Comment by snarfed** [comment]
Thanks @Tamschi! @IoIxD this is in the docs here: https://fed.brid.gy/docs#migration
