### ISSUE TITLE
Website was published before, but now invalid

### ISSUE THREAD

**Issue by gbraad** [snarfed/bridgy-fed#1508]
I have been poking around in the `.well-known` folder and now for some reason my website is invalid: https://gbraad.nl. Even after restoring everything as before and clearing any cache that existed in the CDN.

**Comment by snarfed** [comment]
Hey, sorry for the trouble! I've nudged your site on Bridgy Fed's end, it should be usable again in a bit.

**Comment by gbraad** [comment]
Avail again. Was trying to use the site for AP without needing a 302 as this is a static host.
