### ISSUE TITLE
Bridged bsky account blocking bsky account

### ISSUE THREAD

**Issue by CurrentBias** [snarfed/bridgy-fed#1513]
Hey there, 

I blocked the bsky > fedi bridge from my bsky account to opt out, since I accidentally opted in. I've since unblocked it, but the bsky version of my fedi account is still blocking my bsky account. I assume this occurred when my bsky account blocked the bsky > fedi account, but is now persisting. Is there a way to get the bsky version of my fedi account to unblock my bsky account, or do I just have to wait longer for the unblock to fully propagate? 

![Screenshot_20241118-162508~2](https://github.com/user-attachments/assets/26c85a5e-b52d-4b43-afaf-578ed290eaa4)

**Comment by snarfed** [comment]
Whoa, interesting. Do you mean, you wanted to disable the bridge, so you blocked the [currentbias.zeroes.ca.ap.brid.gy](https://bsky.app/profile/currentbias.zeroes.ca.ap.brid.gy) bridged Bluesky account? Argh, sorry if so, you're actually supposed to block the [ap.brid.gy](https://bsky.app/profile/ap.brid.gy) account: https://fed.brid.gy/docs#opt-out

**Comment by snarfed** [comment]
If your native Bluesky account is bridged, you should be able to unblock it from your fediverse account, and that should bridge over and undo this.

**Comment by CurrentBias** [comment]
That's what's interesting -- I blocked the ap.brid.gy account, and this was apparently a result of that

**Comment by snarfed** [comment]
That is odd! This is the first report of this I've heard. 

Could you try unblocking yourself and see if that works?
