### ISSUE TITLE
Don't get it ...

### ISSUE THREAD

**Issue by eldijomo** [snarfed/bridgy-fed#1514]
So I thought that when bridging my accounts I could post on Mastodon and the same post would show on BlueSky, but it seems it does not. I hooked my website also, but I can't find what this should do.

BlueSky - @morpurgo.bsky.social
@morpurgo.bsky.social@bsky.brid.gy

Mastodon - @Morpurgo@mastodon.nl
@Morpurgo.mastodon.nl.ap.brid.gy

MorpurgoMedia.nl - @morpurgomedia.nl.web.brid.gy

What do I do wrong, or do I have to high expectations?

**Comment by Tamschi** [comment]
It appears to be working now.

There can be some delay sometimes before interactions show up on the other network, the bridge doesn't translate posts with a visibility lower than 'Public' to Bluesky (e.g. 'Quiet public'/'Unlisted' posts aren't bridged), and older posts won't be posted to the other network retroactively (with some exceptions, i.e. if you self-boost then iirc the older post may be bridged first).

**Comment by Tamschi** [comment]
> OK, thanks. 
> For some reason my posts on Mastodon yesterday after connecting still don't show today. 

Ah sorry, I think there was an outage in Bridgy Fed, so it's possible that the bridge was activated late. (This software is still experimental in parts.)

It should be relatively reliable overall, but there can be glitches like this.

> Quiet public'/'Unlisted what does that mean. 

It's the post visibility with the 🔓 or 🌙 icon.
(It was renamed recently, so it depends on the version of Mastodon.)

> […]
> And what does this mean, "iirc"?

It's short for 'if I remember correctly'.
I'm not entirely sure about that piece of information.

**Comment by greatquux** [comment]
@Tamschi should it be working now? i also just tried setting this up yesterday and boosted a couple things this morning from mastodon that don't show up on my bluesky profile. just wanna make sure i'm doing it right ;)

**Comment by Tamschi** [comment]
I'm not sure, since I can't see the service metrics.

That said, boosts aren't bridged if the original poster hasn't enabled the bridge.

**Comment by greatquux** [comment]
@Tamschi hmm ok, what about replies? i know mastodon doesn't support quoted replies of course but does it include a link to the thread? i just posted a reply and it didn't show up either.

**Comment by Tamschi** [comment]
Replies only get bridged if they're 'Public' and the post they're in reply to is visible on Bluesky already (bridged in either direction).

**Comment by imsodin** [comment]
This might also be due to https://github.com/snarfed/bridgy-fed/issues/1520 ?

**Comment by Tamschi** [comment]
I think so. Eveything seems to be working now, at least.

(Feel free to reopen if anything is still amiss.)
