### ISSUE TITLE
Photo and bio not synced to Bluesky on certain accounts

### ISSUE THREAD

**Issue by hturner** [snarfed/bridgy-fed#1515]
I have used Bridgy Fed to bridge my [personal account](https://fed.brid.gy/ap/@HeathrTurnr@fosstodon.org) and the organization accounts for [R_Contributors](https://fed.brid.gy/ap/@R_Contributors@hachyderm.io) and [R_Forwards](https://fed.brid.gy/ap/@R_Forwards@hachyderm.io).

For my personal account, the photo and bio were synced to Bluesky around 24 hours after one of my posts had been bridged across.

For the org accounts, the posts are syncing okay (first post ~1 week ago), but the photo and bio are still not synced. Also these bridged accounts do not appear in the search on Bluesky, not sure if that is a separate issue or the way Bluesky works (not listing accounts without a photo and/or bio). My personal bridged account appears in the search.

Maybe it is because of the underscores (that get translated to hyphens) in the handles? Can anything be done to fix this? I think people are less likely to follow accounts without profile information and not being in search certainly makes it harder, so I may have to set up Bluesky accounts rather than use bridging if this can't be fixed.

**Comment by Tamschi** [comment]
I tried to update the profiles manually just now just to make sure (using the 🔁 button), but unless they appear within a few minutes, this seems like a Bridgy Fed bug to me.

**Comment by snarfed** [comment]
@Tamschi good instinct on using the 🔁 button! We've had various profile bugs over time, and I haven't often tried to find and backfill all affected accounts, but for an account that's ok otherwise, that button should usually fix the profile.

**Comment by Tamschi** [comment]
They're both updated now! It's likely this was delayed due to #1520.

**Comment by hturner** [comment]
Brilliant, thanks everyone. I can confirm that both accounts now appear in the Bluesky search, so that issue is fixed as well.

**Comment by noamross** [comment]
I have the same issue with https://bsky.app/profile/fedi.noamross.net and it has not been resolved by hitting the  🔁 button at https://fed.brid.gy/ap/@noamross@ecoevo.social . Should I do something else to get it to sync?

**Comment by snarfed** [comment]
@noamross your profile picture is https://cdn.masto.host/ecoevosocial/accounts/avatars/109/297/431/594/357/755/original/6652e2afab6a4427.jpeg , which BunnyCDN is currently serving an HTTP 401 error for.
