### ISSUE TITLE
Possible addition of instruction on bridged accounts to follow @ap.brid.gy

### ISSUE THREAD

**Issue by ken-oh** [snarfed/bridgy-fed#1517]
Even though I gave clear instructions, I've got a 1/5 rate of follow through from friends on Bluesky in following @ap.brid.gy after following my bridged account. I wonder if changing 
[bridged from mstdn.social/@kenoh on the fediverse by fed.brid.gy ]

to something like

[bridged from mstdn.social/@kenoh on the fediverse by fed.brid.gy, to allow this account to follow you back, please follow @ap.brid.gy ]

would increase that rate.

**Comment by snarfed** [comment]
It's definitely an interesting idea! We've discussed it a bit already on https://github.com/snarfed/bridgy-fed/discussions/1347 , feel free to jump in there.

**Comment by snarfed** [comment]
Duplicate of #1347
