### ISSUE TITLE
Significant problems with bluesky to mastodon bridging

### ISSUE THREAD

**Issue by edmcman** [snarfed/bridgy-fed#1518]
First, let me say that I am brand new to bluesky, and I have not used mastodon.  But I've been trying to follow people on mastodon without success.

So my friend, who is on mastodon, and I, have been trying to debug.  Yesterday, I was able to follow the bot on bluesky, it followed me back, and I was able to request follows.  My friend received one, and thinks he followed the bot back.  He thinks he was able to follow me from mastodon on bluesky.

However, I didn't receive any notification on bluesky that he was bridged.  I can't find him if I search.  And now, the @ap.brid.gy bot is just ignoring me for about 10 minutes.

## More general impressions

The whole DM thing is really clunky.  My friend was really confused about how to "accept" the bridge request, and what it meant.    As he said:

> It's like I got a message from you saying "Follow me on Bluesky.  To do that, first follow the bridge bot and then follow  these seven pages of instructions on all things BlueSky.

This is a lot just to enable someone to watch them, when the information is already publicly available!

**Comment by snarfed** [comment]
Sorry for the trouble! The bridge got backed up badly last night: #1520 . We've almost dug ourselves out and caught up, but it's still a bit delayed right now.

And you're right! The DM prompt to ask people to bridge their accounts is absolutely clunky. Bridging itself is clunky. I'd love to see the bridge integrated natively into client apps to make the UX easier!

**Comment by edmcman** [comment]
I'm retrying to follow my friend without luck...

![image](https://github.com/user-attachments/assets/9fa89c55-d2cc-44c9-886e-5c472c751f60)

Previously it found him and DM'd him on mastodon.  Still can't see him on bluesky.

**Comment by snarfed** [comment]
That account probably doesn't pass our checks here: https://fed.brid.gy/docs#troubleshooting

We do need to improve this DM message, though! That's https://github.com/snarfed/bridgy-fed/issues/758

**Comment by edmcman** [comment]
So you can't follow people that don't have a profile picture?  That's... not great.  Or are you saying the following account -- mine -- isn't passing the checks?

The error messages are very, very confusing.  Because yesterday I got this:

![image](https://github.com/user-attachments/assets/f55648c9-2491-4b53-a486-9eb254a2379f)

**Comment by edmcman** [comment]
He added a profile picture, and now I get:

![image](https://github.com/user-attachments/assets/8467526e-0042-417c-a67e-41d8d9611414)

I don't see him in a people search yet, but hopefully that will resolve soon.

**Comment by edmcman** [comment]
Yep, I see him now.  But that seems like a pretty big problem/limitation if you can only follow people with profile images :(

**Comment by snarfed** [comment]
Yup, spam filtering is always a tradeoff. Glad you can see him now!
