### ISSUE TITLE
Can't find fediverse user

### ISSUE THREAD

**Issue by edmcman** [snarfed/bridgy-fed#1519]
I'm trying to follow my friend from bluesky on mastodon.  I get:

![image](https://github.com/user-attachments/assets/7d9b04d3-fc3b-45ab-9ee3-e33db2a70aae)

I was able to request to follow other users on infosec.exchange though.  Any ideas why this would happen?

**Comment by Tamschi** [comment]
This user appears to not have set up their profile at all. I wonder if the spam filter also applies in this situation.

**Comment by snarfed** [comment]
@Tamschi good instinct! Looks like that's the problem. I'll add this to #758.
