### ISSUE TITLE
fediverse => Bluesky bridging currently paused

### ISSUE THREAD

**Issue by wbz0100** [snarfed/bridgy-fed#1520]
![image](https://github.com/user-attachments/assets/27862098-e7e0-4629-b6ee-720a158ced00)
Its delayed so much. Is this normal?
I think it's been lagging a lot since the last time it was disconnected.

Instead of being posted sequentially. And In severe cases, there is a delay of up to 10 hours.

**Comment by snarfed** [comment]
Yes! Not normal, we're badly backed up right now. Started around midnight PT last night, send task queue peaked at over 3M tasks (!). Sorry for the trouble. It's with to 2.5M ish more, but still. 😕

I'm not sure what's going on yet. Coincidentally, I got pretty sick last night, and I'm still out of it, so I haven't been able to look yet. Hopefully soon.

**Comment by snarfed** [comment]
For my own notes, here's the repl code I'm using to clear out the send queue:

```py
from google.cloud import tasks_v2
tasks_client = tasks_v2.CloudTasksClient()

from common import TASKS_LOCATION
from google.cloud.tasks_v2.types import Task

request = tasks_v2.ListTasksRequest(
    parent=tasks_client.queue_path(appengine_info.APP_ID, TASKS_LOCATION, 'send'),
    response_view=Task.View.FULL,
)

deleted = 0
for resp in tasks_client.list_tasks(request=request):
  if urllib.parse.parse_qs(resp.app_engine_http_request.body).get(b'user') == [b'ahBicmlkZ3ktZmVkZXJhdGVkci0LEgdBVFByb3RvIiBkaWQ6cGxjOm92eWFqYm5lZ3JpcjJkZHR3ZmhpamlvYgw']:
    deleted += 1
    print(deleted)
    tasks_client.delete_task(request=tasks_v2.DeleteTaskRequest(name=resp.name))
```

**Comment by snarfed** [comment]
We're almost entirely caught up, send task queue is under 10k now. Thanks for your patience all!

**Comment by imsodin** [comment]
Thanks for dealing with this so quickly!

> For my own notes, here's the repl code I'm using to clear out the send queue:

Does that mean some posts during the incident were not replicated?  
I am just asking to get an idea if some problems I just heared about might be related or not. I had a chat with someone who unfortunately started trying out the bridge more or less at the same time as these troubles happened.

**Comment by snarfed** [comment]
Hopefully we didn't drop any posts. Let me know if you see any that are missing and pass the checks in https://fed.brid.gy/docs#troubleshooting , happy to look.

**Comment by fadookie** [comment]
@snarfed thanks for handling this. Is it possible this is happening again? In my fedi -> bsky bridged profile I haven't seen any posts updating in over 9 hours (I'm not sure what the usual delay is): https://bsky.app/profile/Eliot-L.social.coop.ap.brid.gy

**Comment by wbz0100** [comment]
Hmm... Looks like it's happening now.
A post from about 2 hours ago is publishing now.

**Comment by EmilJacobs** [comment]
Can confirm, this issue isn't resolved.

**Comment by avocado1969** [comment]
I’m also not seeing fedi actions populate onto bsky since yesterday evening, even though my profile on fed.brid.gy shows the changes going though with the green check

**Comment by Ralph1798** [comment]
I followed a newly bridged account and posts from 350d+ started to appear in my Mastodon-timeline.
Interesting enough: no current posts, just the old ones.

**Comment by snarfed** [comment]
> Not to pile on, but I can confirm this is still happening aswell. I have severl public posts and replies that all seem to have the green check, but are not appearing on the Bluesky account.
> 
> I actually haven't had anything sync over since I bridged my account like 24 hours ago

Yes! Sorry, reopening. The curren tBluesky => fediverse delay is on us, fediverse => Bluesky delay is on Bluesky team. We're (all) working on it. 😬

**Comment by wbz0100** [comment]
I know you've been sick, so please take it easy and work slowly.

I think one of the causes may have been a delay in moving posts from X (formerly Twitter) to Bluesky.

**Comment by dakota-marshall** [comment]
> > Not to pile on, but I can confirm this is still happening aswell. I have severl public posts and replies that all seem to have the green check, but are not appearing on the Bluesky account.
> > I actually haven't had anything sync over since I bridged my account like 24 hours ago
> 
> Yes! Sorry, reopening. The current Bluesky => fediverse delay is on us, fediverse => Bluesky delay is on Bluesky team. We're (all) working on it. 😬

Thanks for the response! No one is dying, so this is such a non-issue in the grand scheme of things. Hope you feel better :) Thanks for such a cool tool :D

**Comment by Daft-Freak** [comment]
How much delay should I be expecting on the bluesky side? (I haven't seen a post I've made get through in the last 24 hours and am wondering if I have an actual problem...)

**Comment by snarfed** [comment]
@Daft-Freak you mean fediverse => Bluesky? They're doing a lot of work on their relay, https://github.com/bluesky-social/atproto/discussions/3036 , and they've temporarily paused ingesting commits from federated PDSes like Bridgy Fed. I don't have an ETA for when that will be lifted, sadly.

**Comment by Daft-Freak** [comment]
Ah okay, good to know!

**Comment by snarfed** [comment]
https://bsky.app/profile/bnewbold.net/post/3lbimsarmw22g
https://bsky.app/profile/bnewbold.net/post/3lbipqvij7k2m
https://bsky.app/profile/bnewbold.net/post/3lbirrqme2s2w

**Comment by wbz0100** [comment]
Maybe bsky to fedi has been normalized.
I think, but I don't think the reverse is yet, but I think they've blocked it.

**Comment by wbz0100** [comment]
Pause again. I don't know what the problem is.

**Comment by snarfed** [comment]
Bluesky => fediverse has had a couple bumps here and there, but should still be working. Fedi => Bluesky is still paused, sadly, I'm still waiting to hear more from the Bluesky team.

**Comment by moyitpro** [comment]
> Bluesky => fediverse has had a couple bumps here and there, but should still be working. Fedi => Bluesky is still paused, sadly, I'm still waiting to hear more from the Bluesky team.

Just wondering, does this decision also affect self-hosted PDS as well?

**Comment by lucajet** [comment]
> > Bluesky => fediverse has had a couple bumps here and there, but should still be working. Fedi => Bluesky is still paused, sadly, I'm still waiting to hear more from the Bluesky team.
> 
> Just wondering, whatever Bluesky is doing also affect self-hosted PDS as well?

I asked a friend with a selfhosted PDS and he said his new posts are seen from bsky.social users.
How is different ?

**Comment by snarfed** [comment]
Heard from the Bluesky team today, they hope to get this sorted out and fediverse => Bluesky bridging working again sometime this weekend.

Sorry for the downtime, everyone. Thank you for your patience!

**Comment by wbz0100** [comment]
That's great news! On a slightly different note, it would be nice to have a page that we could monitor to make sure it's working properly... But that would probably be too complicated, right?

**Comment by snarfed** [comment]
> I asked a friend with a selfhosted PDS and he said his new posts are seen from bsky.social users.

True! Some (maybe most?) self-hosted PDSes are indeed working ok. Bridgy Fed is the largest self-hosted PDS, though, and it's over 200x the size of the next largest one: https://blue.mackuba.eu/directory/pdses

In general, the Bluesky team has been firefighting a lot this past week, I can't claim to know exactly what's working or not for them at any given moment.

**Comment by snarfed** [comment]
@wbz0100 I would love that! I already have decent observability and a dashboard, https://github.com/snarfed/bridgy-fed/issues/1060#issuecomment-2241182523 , but sadly it can't be exposed publicly, https://issuetracker.google.com/issues/354101899 . Maybe someday!

Feel free to follow #1546

**Comment by jlahtela** [comment]
I just set up this bridge and my account is not created for Bluesky yet... Just wondering will it "retry" or so once it starts work again?

**Comment by lucajet** [comment]
i just saw a 2 days old message of mine published on bsky side.
interesting with a small note

"Archived post
This post claims to have been created on 22 novembre 2024 alle ore 15:48, but was first seen by Bluesky on 24 novembre 2024 alle ore 08:39.
Bluesky cannot confirm the authenticity of the claimed date."

**Comment by wbz0100** [comment]
Sometimes I'll get one or two, but then I don't hear from them again. I guess they're not collecting them yet.

**Comment by lucajet** [comment]
> Sometimes I'll get one or two, but then I don't hear from them again. I guess they're not collecting them yet.

yeah, thx, i kinda stopped interacting two days ago, no need to grow the queue when i can just pretend i was busy doing something else 🙂

**Comment by snarfed** [comment]
@jlahtela hopefully, once this is fixed on Bluesky's side, everything that's happened over the last four days will show up in Bluesky, including bridging new accounts. 🤞

**Comment by snarfed** [comment]
Filed https://github.com/bluesky-social/atproto/discussions/3094 to track on Bluesky's side.

**Comment by andrewrgross** [comment]
This is very interesting to read. I was wondering why I was seeing posts from a few days ago but nothing since. And this makes sense. I think a lot of stuff is popping right  now (in a good way!), and I'm not surprised that troubleshooting will be needed.

Thanks for running this and the communication! I honestly feel like this could be a big step on the way to a less crappy internet.

**Comment by AtiusAmy** [comment]
One weird thing that's happening. My boyfriend runs a bot that posts Bangkok rainstorm every hour (It should've been 3 hours, but that's going off on a tangent). 

https://bsky.app/profile/bkkraindarbot.misskey.winscloud.net.ap.brid.gy

If you look at the time (22.00 or 18.00) you'll see it has been repeating for a while now, not sure what's going on, if this is the reason I'll tell him to unplug from the bridge (and change it to 3 hours damnit!)

**Comment by snarfed** [comment]
Hmm! I don't see that...? I see a gap between 11/21 03:52 and 11/22 13:02, but otherwise it looks ok...?

**Comment by dos1** [comment]
@AtiusAmy It's just old posts from the queue finally being processed - look inside the posts and see their "archived" times. It's actually a brilliant account to look at to assess where were are in the queue right now (looks like we're 24h behind and progressing at about 1h per 2-3 minutes) :smile:

**Comment by AtiusAmy** [comment]
I think it works now!

http://bsky.app/profile/amyiscoolz.atiusamy.com

Also my username now changes to the custom domain I set yay!! (Now, I just wish I could interact with more bsky account 😔)

**Comment by wbz0100** [comment]
There's still a delay, but it seems to be decreasing, up to about 5 minutes (maybe because it's processing the backlog?).

**Comment by lucajet** [comment]
@snarfed 

i think you can remove the red alert warning 🙂

**Comment by foamplugger** [comment]
This might be related to the recent pause, but posts on Mastodon that were boosted and then unboosted still appear on the bridged Bluesky account.

**Comment by snarfed** [comment]
Thanks all!

Afaict Bluesky hasn't yet backfilled all activity that happened during their outage, there's still a period of time when bridged activities didn't take effect, and I don't know yet whether they will or not. Still trying to track that down so I know what to tell peope. https://github.com/bluesky-social/atproto/discussions/3094#discussioncomment-11376697

**Comment by dos1** [comment]
It's normal for new posts to show up after a few minutes.

**Comment by wbz0100** [comment]
It used to post within seconds before the bridge broke, so it's not normal yet.

**Comment by wbz0100** [comment]
I know there's no other way to do it at this point!

Before it stopped, I had quite a few records where I was replying to my opponents within 20 seconds or so of each other, so it's possible that it could be faster, but I'll have to wait and see.

**Comment by AtiusAmy** [comment]
Perhaps it would be better to use a messaging platform you two can agree on to communicate live instead, social media in general just wasn't made for that

**Comment by lucajet** [comment]
I greatly appreciated the effort they put to help fix the issue.
Now if we can just convince them to increase up to 500 characters 🙂

There's no other way but to report the link of the full message, but each time i write a 301 char post, i feel like i'm 'advertising' mastodon, while i just want to talk with the people there.

**Comment by AtiusAmy** [comment]
> I greatly appreciated the effort they put to help fix the issue. Now if we can just convince them to increase up to 500 characters 🙂
> 
> There's no other way but to report the link of the full message, but each time i write a 301 char post, i feel like i'm 'advertising' mastodon, while i just want to talk with the people there.

500 character is still far too little, there should be like 5000 character limits, reading threads is jarring as hell. Markdown + 5000 character support (at least just rendering it, so it bridges properly (vanilla masto renders it properly despite not being able to do it))

**Comment by lucajet** [comment]
Coming from pleroma, when i post on fediverse, i always have 5000 char and, occasionally markdown (which i thought is rendered fine on bs, isn't it ?)
Most of mastodon instances default to 500, so i think is a compromise.

I don't write long essays all the time though, my practical point is that once in a while, an external link is accepted by a normie.
If it happens most of the time, maybe not.

We don't have control on this, but kinda surprised me that many paid engineers worked so hard to fix this interoperability issue, and they keep insisting with this extremely low limit, that harm their users

**Comment by snarfed** [comment]
Re-closing. Feel free to open new issues for individual accounts or posts!
