### ISSUE TITLE
fedi account federated to bsky "invalid handle"

### ISSUE THREAD

**Issue by siljelb** [snarfed/bridgy-fed#1521]
My new-yesterday federated account now shows as "invalid handle" on bsky, and posts take forever to be federated, if they get there at all. Currently 42 minutes.

https://bsky-debug.app/handle?handle=%40siljelb.snabelen.no.ap.brid.gy says both dns and https verification methods failed.

**Comment by snarfed** [comment]
Invalid handle is a Bluesky bug, it happens occasionally when they're overloaded: https://github.com/bluesky-social/atproto/issues/3004 . Looks like your handle is fine now:

![image](https://github.com/user-attachments/assets/601ed6f4-0fa3-4e07-a15a-58ccc7419bee)

(bsky-debug.app is great! but you need to remove the leading `@`: https://bsky-debug.app/handle?handle=siljelb.snabelen.no.ap.brid.gy)
