### ISSUE TITLE
Fedi bridge to Bluesky not taking up new domain name

### ISSUE THREAD

**Issue by noamross** [snarfed/bridgy-fed#1523]
I attempted to follow the documentation to set my bridge Mastodon account on Bluesky to my own domain, but the bridge does not appear to up updating my handle.  

- I created a DNS record for my desired handle:
> <img width="607" alt="Screenshot 2024-11-19 at 7 02 40 PM" src="https://github.com/user-attachments/assets/8324d910-35a9-40f7-a493-58b8b7e81e35">

 - I checked it in the debug page:
> <img width="300" alt="Screenshot 2024-11-19 at 7 04 49 PM" src="https://github.com/user-attachments/assets/223c7c0a-9b45-49d3-a91c-28684cbaf582">

 - I sent a DM to the bridgy account from Mastodon:
 > <img width="307" alt="Screenshot 2024-11-19 at 7 06 23 PM" src="https://github.com/user-attachments/assets/1ad3e9bf-a4c5-45dd-bb63-67668536cd4f">

 - Now, I can reached my bridged account on Bluesky by including the domain in the URL, but the account handle itself is still the long Bridgy name:
> <img width="310" alt="Screenshot 2024-11-19 at 7 06 02 PM" src="https://github.com/user-attachments/assets/4c275b95-2815-4775-869c-e61e38cd4fe1">

Should the Bridgy account bot respond when I send it the command? It responded when I ran the `did` command.

**Comment by snarfed** [comment]
Sorry! We got badly backed up last night, #1520. We've almost dug ourselves out of the backlog, you should get a response when we're caught up.

**Comment by yurukov** [comment]
Same issue again now but with @GovAlertEu@m.govalert.eu and a number of other ones in the same domain. All the verifications mentioned above are green. I send a message, but no update. The bridge seems to be working though.

**Comment by snarfed** [comment]
Sorry for the trouble @yurukov! I'm seeing a timeout from your DNS server on GovAlertEu.m.govalert.eu: https://bsky-debug.app/handle?handle=GovAlertEu.m.govalert.eu

![image](https://github.com/user-attachments/assets/ef217e07-7cf4-41c6-b295-92ac4848c84e)

**Comment by yurukov** [comment]
That's strange. It works fine here and it actually worked to transfer the account. The issue turned out to be that the first word of the DM should literally be "username" followed by "govalerteu.m.govalert.eu". Resolved it here https://github.com/snarfed/bridgy-fed/issues/1616
