### ISSUE TITLE
Bot doesnt follow back on Bsky

### ISSUE THREAD

**Issue by semmelkaizer** [snarfed/bridgy-fed#1524]
The bot does not like me! What did I do to them :(

**Comment by Fauli1221** [comment]
can you send a link to your profile?

**Comment by Tamschi** [comment]
There are a few requirements: https://fed.brid.gy/docs#troubleshooting
Make sure you have a profile picture and that your account isn't hidden from guests (since that property can't be translated into ActivityPub).

**Comment by semmelkaizer** [comment]
> can you send a link to your profile?

I sent you an email

**Comment by semmelkaizer** [comment]
> There are a few requirements: https://fed.brid.gy/docs#troubleshooting Make sure you have a profile picture and that your account isn't hidden from guests (since that property can't be translated into ActivityPub).

Thank you! The missing profile picture was the issue.
