### ISSUE TITLE
Bluesky feed of dr.dk and tv2.dk has no content

### ISSUE THREAD

**Issue by D-Melhede** [snarfed/bridgy-fed#1527]
As title says, the BlueSky feed of dr.dk and tv2.dk has no content.

**Comment by snarfed** [comment]
Hi! Bridgy Fed gets posts from RSS/Atom feeds and webmentions, and I don't see that either of those sites publish those feeds or send webmentions. https://fed.brid.gy/docs#web-how-post

In the future, we'll try to avoid this confusion by requiring feeds or mf2 before we bridge a site at all: #1458

**Comment by D-Melhede** [comment]
The site actually does have an RSS feed, but I am not allowed to enter an URL.
How can I add a feed for:
https://www.dr.dk/nyheder/service/feeds/senestenyt
