### ISSUE TITLE
A bsky > fedi reply was delivered successfully, but not the deletion of that reply

### ISSUE THREAD

**Issue by CurrentBias** [snarfed/bridgy-fed#1530]
Hey, I appreciate you getting back to me so quickly regarding the [blocking issue](https://github.com/snarfed/bridgy-fed/issues/1513) I had. I've got another weird one that I'm hoping isn't the result of me overlooking something:

From the [feed](https://fed.brid.gy/bsky/currentbias.bsky.social) for my bluesky account, you can see that I replied to a post from the bridged version of my fedi account, and then deleted it. The reply says it was delivered successfully, but the deletion was not, and as a result, the reply from the bridged version of my bluesky account is still in the fedi thread 17 hours later. I am wondering if this has to do with the unfollow and refollow activity before and after. Currently, the bluesky account is following the bsky > fedi bridge.

Thanks again

**Comment by Tamschi** [comment]
This is likely #1361. Deletions can currently be missed too easily if they happen quickly after making the post.
Does that seem like it would fit or was there a longer delay between your actions?
