### ISSUE TITLE
Webfinger for bridged Bluesky account returns 404 ("No atproto user found for did:plc")

### ISSUE THREAD

**Issue by temtemy** [snarfed/bridgy-fed#1532]
I've told the bridge bot to ask a friend in Bluesky ([@scarristo.bsky.social](https://scarristo.bsky.social)) to opt-in to the bridge, and thankfully they accepted. However, I cannot look them up from any instance in the fediverse, nor look up any of their posts.. I investigated and it seems like the posts themselves do get bridged fine (they get their own ActivityPub JSON objects), but the Webfinger doesn't return the expected XRD. If you go to https://bsky.brid.gy/.well-known/webfinger?resource=acct:@scarristo.bsky.social@bsky.brid.gy, it returns a 404 with the body:

> No atproto user found for did:plc:ebqlm3q42nocrrbcfip2tj7u

Which doesn't make sense because there is an atproto user in that DID.. And I've also checked whether the account has hidden themselves from logged-out view, but they don't (and if they did then the BridgyFed bot shouldn't have been able to DM them in the first place anyway).

**Comment by snarfed** [comment]
We were backed up, we're working through the backlog now, details in #1520. Sorry!

**Comment by temtemy** [comment]
Since Bluesky ==> fediverse bridging seems to be working now, can you look at this again @snarfed? The Webfinger above is still returning a 404.

**Comment by snarfed** [comment]
@temtemy sure! I'm not sure what's going on with that user, but they're not bridged. Could you ask them to un-follow and then re-follow https://bsky.app/profile/ap.brid.gy to try again?

**Comment by temtemy** [comment]
Just asked them, and it worked. Thanks :)

**Comment by temtemy** [comment]
Same issue with [@chibi-oimomushi.bsky.social](https://chibi-oimomushi.bsky.social) (webfinger: https://bsky.brid.gy/.well-known/webfinger?resource=acct:@chibi-oimomushi.bsky.social@bsky.brid.gy).. I think it would be better if Bridgy Fed itself tries to check regularly on its own list of followers if they're actually being properly bridged; what do you think @snarfed? I'm suspecting that there might be plenty of Bluesky users that have tried to opt-in to the bridge during the downtime last week, and are not being picked up. Trying to message them all to unfollow and refollow would be unrealistic IMO.

**Comment by snarfed** [comment]
@temtemy agreed! That's #1314
