### ISSUE TITLE
Echo Account For Unbridged Comments

### ISSUE THREAD

**Issue by shiribailem** [snarfed/bridgy-fed#1535]
A suggestion for cases where an unbridged user comments on a bridged post or tries to DM someone who is bridged.

Instead of silently failing or sending them errors, what about a special account? Instead of bridging the whole account it would basically just quote the user.

The idea of how I imagine it:

* post gets made on AP
* user @test.usr comments on other side of the bridge with "test comment"
* original post gets a comment from echo@bsky.brid.gy: "Unbridged https://bsky.app/profile/test.usr commented: test comment"

With the obvious translation for the other direction too.

And a user with a hard opt out like the profile tag might instead just get an automatic reply of "Comment rejected as your profile explicitly prohibits being bridged. Remove the #NoBridge tag from your profile if you wish to comment.". (Honestly I think they should just be bridged anyways since they're the ones who explicitly commented on a bridged post and most of them have blocked brid.gy anyways... but we all know how they'll freak out over something that doesn't even affect them)

Obviously this is only relevant so long as at least one side remains opt-in, and of course is not super trivial to implement.

**Comment by snarfed** [comment]
Hmm. This kind of defeats the purpose of opt-in, right?

**Comment by shiribailem** [comment]
In this case it's implicit opt-in for that singular item because they're replying to a bridged account. Echo user would allow it to happen for that specific message without having to bridge their whole account.

ie. if someone on the bridge on bluesky's side makes a post, and 10 people comment but only one of them is bridged, that's 9 comments that are invisible.

But also, those users won't have their whole feed sent, just the single message being sent to the person it's addressed to. Especially given that every bridged account is labeled such automatically and the username blatantly gives it away.

There needs to be a solution to users commenting on bridged posts without bridging themselves, it opens up so many potential problems for people to comment on your posts and not being able to see them.

So, the 3 ways I see to reasonably handle this:
* the echo suggested to send just that one message over
* sending notifications to both the commenter and the bridged account to tell them it's not sent and they should either bridge, block, or shut up.
* using various protocol tools to just delete the comment if possible

The echo method is seamless and the fault is clear on their end if they get upset over it, they explicitly sent a message to a bridged account and are upset that the message got delivered?

There's only two ways I can think of for getting mad in that case:
1) they're deflecting responsibility because they didn't pay attention and think it's the end of the world when their reply of "cool socks" (and nothing else) to your picture lands on bluesky's server
2) they're trying to harass people and this shields them

**Comment by shiribailem** [comment]
To be clear, the purpose of opt-in is that they won't have their data sent over the bridge without them doing something first to trigger it.

An echo account wouldn't give the ability to follow their profile or do anything other than read the reply and reply back to that specific comment.

**Comment by snarfed** [comment]
Understood! It's an interesting idea, and an interesting interpretation of opt in and the different mechanics at play here.  #1406 also seems somewhat related.

I use a simpler, stricter interpretation in Bridgy Fed though. If you haven't opted in (on fediverse or Bluesky), or you opt out (on web), we don't bridge your profile or activity at all. Full stop. Bridging is already complicated enough for people to understand, so I try to make things as simple as possible, especially when they're safety relevant, like opt in/out.

Specifically here, the difficulty is that many people who reply to a bridged user _won't know that that user is bridged_. They often won't even know that the bridge exists, or what it does.

**Comment by Shanesan** [comment]
Yes, I was confused when I didn't recieve at least a DM from Brid.gy when I got a reply on Bluesky from one of my posts.

A user is trying to start a conversation with a bridged user, which to me, as @shiribailem said, is "implied opt-in" as they are initiating the conversation, which is a _very human_ form of consent, probably the first forms of consent ever.

But yes, the alternative would be to turn off comments, which kind of defeats the purpose to a social network.

To rewrite @shiribailem's DM:

> Hey there! You tried to reply to <user>'s post, and since they are Bridged from <Bridged Service>, we don't want to just Bridge your reply without your specific OK!

> Want to join the conversation? Just follow [Bridgy link to Follow] and be able to respond to all <number of users> users Bridging to <Local Service>!

> [Link to more information about Bridgy]

**Comment by snarfed** [comment]
Agreed! Thanks again for all the ideas and motivations here, all.

Notifying non-bridged users when they reply is #1205. We already do it now, just not consistently, due to cost. See https://github.com/snarfed/bridgy-fed/issues/1205#issuecomment-2510285268.

Blocking non-bridged users is #1406. We obviously can't delete other people's replies in either the fediverse or Bluesky, but we can let you block them.

Otherwise, I don't currently plan use echo or placeholder accounts to re-broadcast replies or other interactions from non-bridged accounts. My goal is to keep both opting in and opting out as simple, explicit, and black-and-white as possible. 

Given that, and the open issues above, I'm inclined to close this issue. @shiribailem @Shanesan feel free to weigh in if you disagree!

**Comment by shiribailem** [comment]
While I disagree with your decision, I'd say all the points here are addressed.

**Comment by snarfed** [comment]
Understood! Thanks again for the discussion, I do appreciate it.

**Comment by Shanesan** [comment]
Weighing in, obviously late @snarfed. 

Will https://github.com/snarfed/bridgy-fed/issues/1471 inevitably change this stance?

I would really, really like to receive a DM from Brid.gy so I don't have to make a BlueSky account to reply to people asking me a question. A DM is as secret/separate as you can get from forcing a user to opt-in to a service, instead driving the comment directly to you (and only you) for you to reply.

I think this is different from OP but gets the same point across.

**Comment by snarfed** [comment]
DM is definitely another option! And yeah we're thinking about this wrt #1471...but the core issues here haven't really changed. If a platform or network like the fediverse is opt in, and someone has explicitly chosen not to opt in, they'd generally expect that bridge not to deliver their content or profile or interactions anywhere. DMing a reply would violate that less than actually bridging the reply, but it would still arguably violate it.

**Comment by Shanesan** [comment]
Sure, that makes sense, so let’s assume that we want this transaction to go one way and one way only, with the goal of not doing something someone would consider “opting in”. 

We have a URL that has a Bsky reply, let’s use [this one](https://bsky.app/profile/zagush.bsky.social/post/3lgxp5k3nak2t) as a real example.

If the goal is solely to reply to people, even if arduous, and ONLY be one-way, could Bridgy utilize this URL to act as a means to reply to that comment?

**Comment by snarfed** [comment]
So you're saying, if we didn't notify the OP, but they looked for replies themselves manually and found one like this?

At that point, if they really want to interact with Bluesky users who haven't opted into the bridge, I'd have to recommend that they just make a Bluesky account, even if only for those kinds of replies.

**Comment by snarfed** [comment]
Let's continue the conversatioon in #1200? I closed this isssue primarily because I wouldn't plan to use "echo"/placeholder accounts for this, but I'm definitely open to considering and discussing this kind of thing somehow else.
