### ISSUE TITLE
Boost to Quote, limited user settings?

### ISSUE THREAD

**Issue by shiribailem** [snarfed/bridgy-fed#1536]
This is a touchy one especially with all the nonsense of people crying over opt-in etc.

I can obviously manually quote posts all day instead of boosting, but what I'd love is if boosts on one side got translated into quotes on the other.

ie. if I boost a post, it'll be sent over to bsky as a quote post or even just an embedded link to the original post (maybe an automatic tag or two to identify what's going on and allow easy filtering if this annoys people on the receiving end).

Ideally there would be some level of user configuration available for the bridge so that this could be optionally turned on/off for the account. That way it's a bit more on the user than the bridge and *maybe* it'll avoid their outrage?

**Comment by snarfed** [comment]
Hmm, I don't quite follow. Boosts (ie reposts) are bridged as reposts right now. Is there a reason you'd want them to be bridged as quotes instead of reposts?

**Comment by mapto** [comment]
Not sure if this was the original idea, bit it does seem fully aligned:

My understanding is that currently if the original account is not bridged, the boost would also not show up over the bridge.

If that is correct, and given that original posts are public and viewable without user registration, a way to bridge such content would be to convert the boost to a post of the public link. Of course, if the boost is with a comment (masto is currently adding this feature, bksy has it) this becomes a quote post.

The idea is that this would expose much more content over the bridge. That is content that was willingly made public, thus with granted consent to bridge.
