### ISSUE TITLE
Mastodon -> Bluesky

### ISSUE THREAD

**Issue by poyoyoyoyo** [snarfed/bridgy-fed#1540]
Mastodon users' postings to Bluesky do not seem to have been reflected since the night of November 20.
Are you currently experiencing problems?

**Comment by snarfed** [comment]
Sorry, yes, Bluesky themselves are: #1520

**Comment by snarfed** [comment]
Duplicate of #1520

**Comment by poyoyoyoyo** [comment]
Thanks for your time. I will wait patiently.
