### ISSUE TITLE
No BS account sync

### ISSUE THREAD

**Issue by DanieruOtakuBoy** [snarfed/bridgy-fed#1541]
I have read the documentation at least two or three times, but I don't understand what I am doing wrong, all my interactions in the Fediverse are successfully reflected in Bridgy Fed, however, these interactions are not synchronized with BlueSky, am I doing something wrong or is it just a delay in synchronization?

Pls, help me.
![Captura de pantalla de 2024-11-21 21-30-51](https://github.com/user-attachments/assets/43cc3fdd-f456-4f4b-a8d5-21ecbc5f8aff)
![Captura de pantalla de 2024-11-21 21-31-05](https://github.com/user-attachments/assets/4f99feac-73be-46fa-8292-abbf043a4d8d)

**Comment by snarfed** [comment]
See https://github.com/snarfed/bridgy-fed/issues/1520#issuecomment-2492534380

**Comment by juanro49** [comment]
is it known how long it will take Bluesky to resume indexing?

**Comment by snarfed** [comment]
No, not yet, sorry.
