### ISSUE TITLE
"Couldn't find Bluesky user" when user exists

### ISSUE THREAD

**Issue by agharbeia** [snarfed/bridgy-fed#1544]
What does it mean when Bridgy replies with "Couldn't find Bluesky user foo", while the user does exist, and the option to discourage logged-out access is not enabled?

For example: [@0xa1ef.bsky.social](https://bsky.app/profile/0xa1ef.bsky.social)

**Comment by snarfed** [comment]
Sorry for the trouble! Looks like this account doesn't pass our spam filters: https://fed.brid.gy/docs#troubleshooting

We should definitely make this message more clear though! That's https://github.com/snarfed/bridgy-fed/issues/758#issuecomment-2487042651. Thanks for the nudge.

**Comment by agharbeia** [comment]
It would be useful to amend the documentation in order to cover:

- what happens when a Bluesky account that is the target of a bridging request is set to receiving only messages from accounts they follows, AND they are not following the robot.
- what actions are expected from the owner of the target account, if any.

Additionally, a follow-up message from the robot to the initiator of the bridging request is needed, after the bridging has been successful. Its content should cite the bridged account on the respective platform, similar to the message received when requesting the bridging of an account that's already bridged.

**Comment by snarfed** [comment]
Agreed on all counts!

> It's a duplicate of #758, correct?

Correct, specifically this one part: https://github.com/snarfed/bridgy-fed/issues/758#issuecomment-2487042651

>     * [rimaanabtawi.bsky.social](https://bsky.app/profile/rimaanabtawi.bsky.social)
>     * [ahmadelnemr.bsky.social](https://bsky.app/profile/ahmadelnemr.bsky.social)

These accounts both have the ["hide account in logged out view"](https://bsky.app/profile/safety.bsky.app/post/3khhw7s3rtx2s) setting enabled, as mentioned in https://fed.brid.gy/docs#troubleshooting .

> * what happens when a Bluesky account that is the target of a bridging request is set to receiving messages only from accounts they follows, AND they are not following the robot.

This is #1326 

> Additionally, a follow-up message from the robot to the initiator of the bridging request is needed, after the bridging has been successful.

This is #1024

**Comment by agharbeia** [comment]
Great. Thanks for this great work. It's very useful.

I've also read your post about institutionalizing this, and I hope it is realized one way or the other.

**Comment by agharbeia** [comment]
> > * what happens when a Bluesky account that is the target of a bridging request is set to receiving messages only from accounts they follows, AND they are not following the robot.
> 
> This is #1326

Friends helping me understand/debug the process reported having received/seen the robot's message after following the robot's account.

But I must say I don't understand how Bluesky messaging works, and whether there's a retry window, or whether the relevant setting is just a filter on the view.

In all cases, it would be great, in addition to the DM, to mention the case in the docs.

**Comment by Tamschi** [comment]
Bluesky has slightly strange behaviour if someone tries to DM without permission (at the protocol level): The DM is apparently still received, but just hidden from the recipient until the sender is allowed to send it.

Bridgy Fed probably sends the DM without checking for permission first, so #1326 should help with this too.

**Comment by audunmb** [comment]
While the underlying issue is difficult to solve, I think this issue should be resolved trough a more clear message. Something like:
"Couldn't find user foo on Bluesky, or the user couldn't be reached" would make more sense.
