### ISSUE TITLE
Misskey => Bluesky: Convert `_misskey_requireSigninToViewContents` flag to `!no-unauthenticated` label

### ISSUE THREAD

**Issue by vyv03354** [snarfed/bridgy-fed#1549]
Misskey 2024.11.0 added a new option to hide notes from logged-out view that is very similar to Bluesky's one. Let's convert this option between these nodes.

Misskey added a `_misskey_requireSigninToViewContents` flag to AP Actors:
https://github.com/misskey-dev/misskey/pull/14799/files#diff-e69e0203183c3337ff7ea11c3e9219e5591e32f92de33cee1f7fbffeb96d8363

Note that Misskey has a distinct "no-federate" option. Misskey will federate notes even if the "require sign-in to view contents" option is enabled and Misskey devs [intentionally chose that behavior](https://github.com/misskey-dev/misskey/issues/14473#issuecomment-2314133461). So `_misskey_requireSigninToViewContents` should not be considered as an opt-out signal.

**Comment by snarfed** [comment]
Oh wow, interesting idea! Thanks for the idea and details.

> Note that Misskey has a distinct "no-federate" option. Misskey will federate notes even if the "require sign-in to view contents" option is enabled and Misskey devs [intentionally chose that behavior](https://github.com/misskey-dev/misskey/issues/14473#issuecomment-2314133461). So `_misskey_requireSigninToViewContents` should not be considered as an opt-out signal.

I appreciate the thought here. However, I'm probably still inclined to interpret Misskey's "require sign-in" setting as opting out, like Bluesky's. I understand the difference from Misskey's "no-federate" option, but I generally prefer to handle only fully public data and accounts in both Bridgy classic and Bridgy Fed.

**Comment by vyv03354** [comment]
> I appreciate the thought here. However, I'm probably still inclined to interpret Misskey's "require sign-in" setting as opting out, like Bluesky's. I understand the difference from Misskey's "no-federate" option, but I generally prefer to handle only fully public data and accounts in both Bridgy classic and Bridgy Fed.

Makes sense, it’s your call.
