### ISSUE TITLE
Custom emoji shortcode should render as tofu instead

### ISSUE THREAD

**Issue by letydoesstuff** [snarfed/bridgy-fed#1553]
ActivityPub supports custom emoji while ATProto does not. Given that and character limits on Bluesky, I feel `:custom_emoji_shortcodes:` would be better served as `�` tofu replacement characters instead.

**CW: Marked Sensitive Media Below**

But that [this post](https://doesstuff.social/@lety/113541183145762153) currently bridges over like [this silliness](https://bsky.app/profile/lety.doesstuff.social.ap.brid.gy/post/3lbqhclxres32) seems less than ideal.

**Comment by niklaskorz** [comment]
While I agree � may be the semantically correct solution, I wonder if just removing custom emojis from the bridged post might be a more user friendly solution, so readers don't think the bridge is broken.

**Comment by snarfed** [comment]
Other people disagree 😁 https://github.com/snarfed/bridgy-fed/issues/1104#issuecomment-2165822565

**Comment by snarfed** [comment]
Merging this into #1104

**Comment by snarfed** [comment]
Duplicate of #1104
