### ISSUE TITLE
"Graphic media" label automatically added to CW-tagged media, even stuff not graphic at all

### ISSUE THREAD

**Issue by gigirassy** [snarfed/bridgy-fed#1554]
I'm assuming you people don't care for Transformers Animated so the content warning doesn't matter here. But if you do care for it, I am sorry in regards.

My Sharkey (Misskey fork) instance, showcasing a content warning for stuff that isn't shock material:

![image](https://github.com/user-attachments/assets/39370234-b3cf-48a0-82a4-1a817d64e5ac)

My account, bridged to Bluesky:

![image](https://github.com/user-attachments/assets/f9d4f550-89e7-4d8e-a80d-32fefaaf7752)

Really don't want my Bluesky followers to think I posted real, actual gore when I absolutely didn't. That's all I got to say.

**Comment by snarfed** [comment]
Definitely understood! Sadly the fediverse doesn't have a structured taxonomy for content warning types, even a shallow one like Bluesky's. It's just the `sensitive` flag, which is either true or false. So, we translate that flag to the most generic Bluesky label available, which is "Graphic media."

I could try to use some kind of machine learning model on the content warning text, but that's pretty unlikely.
