### ISSUE TITLE
Marmot.fr Not Valid Server?

### ISSUE THREAD

**Issue by shiribailem** [snarfed/bridgy-fed#1558]
This is second hand so I can provide very little, one of my favorite authors mentioned that they tried to use the bridge and got some error about "marmot.fr not a valid server". I checked and brid.gy is not listed as blocked and it is a Mastodon server...

Thread with author: https://mamot.fr/@pluralistic/113552285632090125

I don't have much to offer here, but it might bear looking into at least on a cursory level to see what might be happening.

**Comment by snarfed** [comment]
Funny. mamot.fr is fine, we have plenty of bridged users there, eg https://bsky.app/profile/Ccalvez.mamot.fr.ap.brid.gy . Looks like Cory was confused and entered mamot.fr into the web site form at https://fed.brid.gy/#enter-web-site . He should instead follow @bsky.brid.gy@bsky.brid.gy, as described immediately below that form.

(I love Cory btw! I'd love it if he tried Bridgy Fed.)

**Comment by shiribailem** [comment]
Thanks for the follow up there! I passed along the info, offering more help, and tagged you in the thread as well just because I figure you'd both appreciate it
