### ISSUE TITLE
I wish this was opt out!

### ISSUE THREAD

**Issue by tbodt** [snarfed/bridgy-fed#1560]
I wish I could just have one account on the fediverse, and from that follow all the people I know on Bluesky, and have everyone be able to reply to my posts. But this doesn't work out because the people I want to follow and the people who would reply to my posts are probably not opted into the bridge!

I'm sure this was done for a reason, but it severely limits the utility of the service. I also couldn't find an explanation of the reasoning on the FAQ page.

**Comment by tbodt** [comment]
I found it! https://github.com/snarfed/bridgy-fed/issues/835

Maybe there's something to be said about default allowing bridging *onto* the fediverse, but not *off* of it...

**Comment by snarfed** [comment]
Yeah this was a pretty big controversy. Lots of people felt strongly, on both sides but especially on the opt in side, and they told me so pretty colorfully.

Also see #1471 and https://snarfed.org/2024-01-21_moderate-people-not-code#Metcalfe , where I discussed the same point:

> Having said all that, for services like bridges that live and die by network effects, opt-out seems like the only way to be broadly useful. If a Bluesky/fediverse bridge is opt in, and Alice opts into bridging her Bluesky account, people in the fediverse will see her and her posts, but she won’t see their replies or other interactions unless they’ve also opted in. More importantly, people in the fediverse won’t see anyone else on Bluesky either.

**Comment by tbodt** [comment]
Yes, dupe of #1471 tbh
