### ISSUE TITLE
glitch.me subdomain not working with BF via RSS

### ISSUE THREAD

**Issue by gRegorLove** [snarfed/bridgy-fed#1564]
During HWC tonight we were helping @fractalkitty debug federating via RSS feed. The account `@outgoing-pentagonal-line.glitch.me@web.brid.gy` was set up and followed on mathstodon.xyz, though hasn't been posting from the RSS feed. 

During debugging we tried https://web.brid.gy/r/https://outgoing-pentagonal-line.glitch.me/ which we got the error `No web user found for any of {'outgoing-pentagonal-line.glitch.me'}`

Perhaps complicating things a bit, the site now has a domain https://www.sohaiku.art/, which she might prefer to use. We tried to put it into https://fed.brid.gy/web-site and it said the site wasn't supported.

**Comment by snarfed** [comment]
Ooh, sorry, and thanks for reporting! Bug on our side, fixing now.

...incidentally though, this site's RSS feed https://outgoing-pentagonal-line.glitch.me/rss is 5.6M, and BF's limit is 2M, @fractalkitty you'll need to prune that down so that BF can bridge your posts.

**Comment by snarfed** [comment]
Fixed! https://fed.brid.gy/web/outgoing-pentagonal-line.glitch.me

**Comment by fractalkitty** [comment]
Thank you so much everyone! I had a disk space issue on glitch and was able to edit today to fix the size of the feed. It should start working here soon for the site.
