### ISSUE TITLE
After following @bsky.brid.gy@bsky.brid.gy from Mastodon, the @bsky.brid.gy never follows back

### ISSUE THREAD

**Issue by Anthrazit68** [snarfed/bridgy-fed#1569]
I do have the same problem on my account as well, hosted on mastodon.social.

Account is verified, profile picture and header picture and more than 2 weeks old.

In addition I do not see the Bridgy Fed in the list of accounts I am following. 

A newer account which I have just created for our company on mstdn.business however seems to work nice with the bridge.

_Originally posted by @Anthrazit68 in https://github.com/snarfed/bridgy-fed/issues/1479#issuecomment-2506681818_

**Comment by snarfed** [comment]
@Anthrazit68 sory for the trouble! Which account is this?

**Comment by Anthrazit68** [comment]
https://mastodon.social/deck/@anthrazit

**Comment by snarfed** [comment]
Did you follow @bsky.brid.gy@bsky.brid.gy a few days ago? Bluesky had a bit of an outage ingesting Bridgy Fed records: https://github.com/bluesky-social/atproto/discussions/3094 . Try unfollowing and then follow again?

**Comment by Anthrazit68** [comment]
It worked!

Just have to add that I have tried a couple of times during the last week. But apparently it previously didn't work due to the same problem that was mentioned in #1479 (profile image missing), and then probably I managed to get into the outage some days ago.

Nevertheless - thanks for the quick response.
