### ISSUE TITLE
From fediverse to bluesky: can't interact with someone on bluesky

### ISSUE THREAD

**Issue by frzysk** [snarfed/bridgy-fed#1572]
hi hello

I have a bridged fediverse account, they have a bridged bluesky account, but my interactions (replies and likes) with them doesn't appear on bluesky. On https://fed.brid.gy/ap/@me@my.account, my interactions appear with a green check, but still aren't visible from bluesky. Reposting works.

I prefer not to give the real link because that's their personal account.

thanks for helping :3

**Comment by snarfed** [comment]
Hmm, https://fed.brid.gy/ap/@me@my.account shows that your account isn't bridged. Did you disable it?

**Comment by snarfed** [comment]
Sorry for the trouble! I'd need more information to help though...

**Comment by frzysk** [comment]
ok it worked? i think sending the like and replies took more time than the other things? but i think i checked even a long time after some replies?
Anyway it might be my fault, i'll check in the future if it works

**Comment by snarfed** [comment]
Ah, yes, we see delays a bit more often now that Bluesky has switched to their non-archival relay. Sorry!
