### ISSUE TITLE
Fedi -> BSKY: Flipped Block State for single account

### ISSUE THREAD

**Issue by lupomancer** [snarfed/bridgy-fed#1576]
A friend notified me today that the bridged BSKY version (@sig.dog) of my Mastodon account (@sig@furries.club) is blocking their BSKY account (@likoclave.com).

The strange thing is my Mastodon account is following their bridged BSKY account and definitely is not blocking them. I've tried blocking, then unblocking them to see if I could get it to "release" the block but that didn't seem to work. 

The bridge monitor page shows weird events for my Mastodon account, including actions like "None" and "Undid", linking to weird links on my Mastodon instance that don't seem to go anywhere.

**Comment by snarfed** [comment]
Huh, odd. Sorry for the trouble!

I do see you in the list of accounts blocking likoclave.com: https://clearsky.app/likoclave.com/blocked-by

...and I also see that your bridged account is blocking one user, but oddly clearsky doesn't show who: https://clearsky.app/sig.dog/blocking

...and when I look in your ATProto repo in Bridgy Fed, it currently has no `app.bsky.graph.block` records, only `app.bsky.actor.profile`, `app.bsky.feed.like`, `app.bsky.feed.post`, `app.bsky.feed.repost`, `app.bsky.graph.follow`, `chat.bsky.actor.declaration`. 

Clearsky says that block was created 2024-08-18. We only keep logs for 30d, so unfortunately I don't have logs for what happened or how that block was created. I don't even have the rkey or CID or `at://` URI for the block record in the appview. Argh. Not sure what I can do here.

**Comment by snarfed** [comment]
(Fwiw, Clearky now seems unhappy. Clicking on the https://clearsky.app/sig.dog/blocking link behaves weirdly, and I can't search for sig.dog any more. 🤷 )

**Comment by Tamschi** [comment]
> (Fwiw, Clearky now seems unhappy. Clicking on the https://clearsky.app/sig.dog/blocking link behaves weirdly, and I can't search for sig.dog any more. 🤷 )

I think that relies on collection enumeration, which may not be working in arroba.
atproto-browser has a very similar issue: https://atproto-browser.vercel.app/at/sig.dog

I think this may prevent Bluesky from properly re-synchronising after outages on their end, too, but I'm not sure.

**Comment by snarfed** [comment]
> I think that relies on collection enumeration, which may not be working in arroba. atproto-browser has a very similar issue: https://atproto-browser.vercel.app/at/sig.dog

Ah, thanks! It's behaving differently now than it did a few min ago, but yeah that's still possible.
 
> I think this may prevent Bluesky from properly re-synchronising after outages on their end, too, but I'm not sure.

Fortunately last I talked to them, they used getRepo for this, not enumerating anything individually.

**Comment by lupomancer** [comment]
So is this an issue that lies in Bridgey's records for my account?

Is there any kind of garbage collection or cleanup that would clear this up, do you think?

Very strange indeed!

**Comment by snarfed** [comment]
@lupomancer no, as mentioned in https://github.com/snarfed/bridgy-fed/issues/1576#issuecomment-2509472541, Bridgy Fed currently has no block records in your bridged ATProto repo, ie it doesn't think you're blocking anyone. I don't know yet what happened, or what I can do about it. Sorry I don't have better news yet. 😕

**Comment by snarfed** [comment]
OK, some progress here. I got a bit more info on this block out of the appview:

```py
from arroba.util import service_jwt

repo = arroba.server.storage.load_repo('did:plc:5la6ffruzawwik4m5n36zfiw')
token = service_jwt(host='api.bsky.app',
                        aud='did:web:api.bsky.app',
                        repo_did=repo.did,
                        privkey=repo.signing_key,
                        lxm='app.bsky.graph.getBlocks')
client = Client(f'https://api.bsky.app', headers={'Authorization': f'Bearer {token}'})
client.app.bsky.graph.getBlocks()

{
  "blocks": [{
      "did": "did:plc:puwv76g3bsmdxg46yylq3rw5",
      "handle": "likoclave.com",
      "createdAt": "2023-07-24T00:08:14.584Z",
      "indexedAt": "2024-12-02T01:57:21.446Z"
      "..."
    }]
}
```

Interestingly `createdAt` is back in July, but `indexedAt` is 12/2.

**Comment by snarfed** [comment]
Nothing in our logs for your bridged DID during the few hours before `indexedAt` here, 2024-12-02 01:57:21 UTC.

**Comment by snarfed** [comment]
...and nothing in our logs for the last 30d for both your and their DIDs together, did:plc:5la6ffruzawwik4m5n36zfiw and did:plc:puwv76g3bsmdxg46yylq3rw5.

**Comment by snarfed** [comment]
@lupomancer I may be out of ideas here. Let me know if you have any others! Otherwise I don't know if I can do anything to fix this. Ugh.

**Comment by lupomancer** [comment]
Yeah, I've got no ideas here. Definitely very strange

**Comment by snarfed** [comment]
Strange indeed.

Closing for now since we don't have any leads on what I can do here, but please reopen if you come up with any new ideas. Really sorry about this!
