### ISSUE TITLE
Web -> Bsky: account appears to be in limbo

### ISSUE THREAD

**Issue by gerbenjacobs** [snarfed/bridgy-fed#1579]
Created my fed.brid.gy account 8 days ago (https://fed.brid.gy/web/gerben.dev), so the BlueSky delay/infra troubles could be a part of it.

But I've been browsing the issues for similar topics and as such found this checker, that says that my fed.brid.gy BSKY account is borked: https://atproto-browser.vercel.app/at/did:plc:6rq2kp3tcu3hsvdpdu2k3ln2

## Problem

It has never bridged anything to the account, while the fediverse account works. I have a follower on bluesky.
I managed to follow the 'set up custom domain' instructions, and the account name changed. None of the 'Profile updates' are working though.

I recently created a custom bsky.social account (did:plc:w4kjz4to56r7hk35hsw76jsf) to a) follow my account b) checkout what the situation was like 'on the ground'. I have changed my DNS TXT to point to that account (but now _that's_ not working on bsky.app; similar problem: https://github.com/bluesky-social/social-app/issues/6493)

## Ideal state

I would like to use the web->bsky bridge if it works, including the custom domain DNS record, but my account seems to be in limbo.

**Comment by snarfed** [comment]
Ugh. Sorry for the trouble! Occasionally the Bluesky appview gets stuck on a repo like this and doesn't ingest anything, even though we're emitting records for it, and we don't have much visibility into what's happening on their end.

I've recreated your bridged account with a new DID and repo, https://bsky.app/profile/gerben.dev.web.brid.gy / did:plc:dcrsapklvvin5uztwdnwqa5u . Hopefully posts should bridge now!

**Comment by gerbenjacobs** [comment]
It works now, thanks for your help!

**Comment by gerbenjacobs** [comment]
@snarfed Sorry to bother you again. 

The new account worked (profile update) and I managed to bridge a post.

However after that I followed the docs again to use a custom domain and now neither **profile updates** or **post syndication** is working.
I can't however see much information/debugging on fed.brid.gy w.r.t to AT proto. So I need your help once again 🥹

**Comment by snarfed** [comment]
Damn. Same thing is happening with your ATProto repo as before. eg for your latest post https://gerben.dev/notes/501a40a03cebb59ce5aca43c411d167d , we got your webmention, stored it in your repo as the commit below with seq 5112420, and emitted that seq to the Bluesky relay, but they haven't ingested and displayed it, or any of your other recent records. 😕 

```
Storing ATProto Action.CREATE app.bsky.feed.post 3lcfpgv4wbg42 b'{"$type":"app.bsky.feed.post","bridgyOriginalText":"This is a really simple note to test Bluesky bridging","bridgyOriginalUrl":"https://gerben.dev/notes/501a40a03cebb59ce5aca43c411d167d","createdAt":"2024-12-03T13:06:12.000Z","text":"This is a really simple note to test Bluesky bridging"}'
```
