### ISSUE TITLE
AP => AT: Generated link preview causes link to original post to be omitted in truncated posts.

### ISSUE THREAD

**Issue by Tamschi** [snarfed/bridgy-fed#1580]
Example: https://bsky.app/profile/kelson.notes.kvibber.com.ap.brid.gy/post/3lc7f5ngdf5d2

Most likely a regression due to #1411.

There are two options here, I think:

a) Don't generate a link preview, use the attachment to link to the original post.
a) Put the link to the original post as fragment onto the "[…]" at the end of the post.

**Comment by snarfed** [comment]
Ugh yes, exactly right on all counts, thanks for raising.

**Comment by snarfed** [comment]
Looks like this post was bridged by the first, buggy deploy of this feature, and the final deploy doesn't have this bug. Phew! Example: https://bsky.app/profile/fedi.test.snarfed.org/post/3lcbyl35456e2
