### ISSUE TITLE
Posts from Bluesky don't get delivered to the fediverse until they're boosted/reposted by an opted-in Bluesky account

### ISSUE THREAD

**Issue by temtemy** [snarfed/bridgy-fed#1584]
Example: https://bsky.app/profile/makai.chaotic.ninja/post/3lccx2f7dss2k

I can't manually look it up (whether it's via Mastodon, Misskey, or Pleroma) either via https://fed.brid.gy/r/https://bsky.app/profile/makai.chaotic.ninja/post/3lccx2f7dss2k. I have to repost it just to see it in my Misskey's home feed.

**Comment by snarfed** [comment]
Looking at a Misskey inbox delivery, we posted the `Create` activity below for this post to https://makai.chaotic.ninja/inbox at 2024-12-02 10:45:55 UTC, and it returned HTTP 202.

```json
{
  "@context": ["https://www.w3.org/ns/activitystreams"],
  "type": "Create",
  "id": "https://bsky.brid.gy/convert/ap/at://did:plc:cu33jkvtkoxyfd45wg7hrhra/app.bsky.feed.post/3lccx2f7dss2k#bridgy-fed-create",
  "actor": "https://bsky.brid.gy/ap/did:plc:cu33jkvtkoxyfd45wg7hrhra",
  "published": "2024-12-02T10:45:54.633923+00:00",
  "object": {
    "type": "Note",
    "id": "https://bsky.brid.gy/convert/ap/at://did:plc:cu33jkvtkoxyfd45wg7hrhra/app.bsky.feed.post/3lccx2f7dss2k",
    "url": "https://fed.brid.gy/r/https://bsky.app/profile/did:plc:cu33jkvtkoxyfd45wg7hrhra/post/3lccx2f7dss2k",
    "attributedTo": "https://bsky.brid.gy/ap/did:plc:cu33jkvtkoxyfd45wg7hrhra",
    "content": "<p>Test post for <a href=\"https://bsky.brid.gy/hashtag/BridgyFed\">#BridgyFed</a> GitHub issue, please don't repost (except if you're <a class=\"mention\" href=\"https://bsky.app/profile/snarfed.org\">@snarfed.org</a>)</p>",
    "contentMap": {
      "en": "Test post for #BridgyFed GitHub issue, please don't repost (except if you're @snarfed.org)"
    },
    "published": "2024-12-02T10:45:53.503Z",
    "tag": [
      {
        "type": "Hashtag",
        "name": "#BridgyFed",
        "href": "https://bsky.brid.gy/hashtag/BridgyFed"
      },
      {
        "type": "Mention",
        "name": "@snarfed.org",
        "href": "https://bsky.app/profile/snarfed.org"
      }
    ],
    "content_is_html": true,
    "to": ["https://www.w3.org/ns/activitystreams#Public"]
    "cc": ["https://bsky.app/profile/snarfed.org"],
  },
  "to": ["https://www.w3.org/ns/activitystreams#Public"],
  "cc": ["https://bsky.app/profile/snarfed.org"]
}
```

**Comment by Tamschi** [comment]
Where is the `content_is_html` from? That's not defined in the Activity Streams vocabulary.

**Comment by snarfed** [comment]
Hah, good eye. It's Bridgy Fed internal, very non-standard, not really intended for external consumption. Ideally we should remove it before sending activities.

**Comment by Tamschi** [comment]
I think that would be a good idea. It's a validation error in "safe mode" JSON-LD processing, so it could well cause issues like this.

That aside, the code you pasted isn't valid JSON either. There's a misplaced comma between lines 31 and 32.
Maybe that's the issue? (I didn't notice at first either, but https://json-ld.org/playground/ flagged it.)

**Comment by snarfed** [comment]
Ah, sorry, that's just me, I rearrange and clean up JSON activities a bit before I add them to issues here. Will fix.

**Comment by temtemy** [comment]
I still can't do the manual look up (and for Mastodon I test from `yamabi.co` and `mastodon.social`), however I did [another test post](https://bsky.app/profile/makai.chaotic.ninja/post/3lceki7odok2e) in my bsky and I can see it delivered now to the fediverse (both Mastodon and Misskey) without any need for reposts. Seems like the fix worked!

**Comment by temtemy** [comment]
Another Bluesky example, this time a reply to another opted-in account (and boosting doesn't seem to be working?): https://bsky.app/profile/makai.chaotic.ninja/post/3ldhsucuy722u

**Comment by ygg2** [comment]
Not sure if it's this issue but my friend's account miseru.bsky.social stopped bridging about 4 weeks ago. I thought it might be because of "Discourage apps from showing my account to logged-out users" but https://github.com/snarfed/bridgy-fed/issues/974 suggests it would have continued bridging?

**Comment by snarfed** [comment]
@temtemy sorry for any confusion in https://github.com/snarfed/bridgy-fed/issues/1584#issuecomment-2547689257! Sounds like it turned out to be mainly Misskey interop?

@ygg2 looking at https://fed.brid.gy/bsky/miseru.bsky.social , we're seeing their recent posts, so I'm guessing they got hit by #1595 😢

**Comment by temtemy** [comment]
> @temtemy sorry for any confusion in [#1584 (comment)](https://github.com/snarfed/bridgy-fed/issues/1584#issuecomment-2547689257)! Sounds like it turned out to be mainly Misskey interop?

@snarfed Yes it seems to be just Misskey interop this time, sorry for not making it clear.

**Comment by snarfed** [comment]
@temtemy np! Feel free to reopen if you have any details on what Misskey specifically is having trouble with.

**Comment by saschanaz** [comment]
I believe this corresponds to https://github.com/misskey-dev/misskey/issues/15039. Misskey started to reject when URLs have different hosts, and thus having https://fed.brid.gy/ and https://bsky.brid.gy/ together causes rejection.

**Comment by snarfed** [comment]
THank you @saschanaz! And ugh. I get requiring that activity, object, actor, and `attributedTo` ids are all on the same domain, but `url` isn't really relevant to authorization or other security contexts in AP, this new Misskey requirement is unfortunate and doesn't make a lot of sense to me.

**Comment by snarfed** [comment]
Will follow up in #1570
