### ISSUE TITLE
Verified BlueSky accounts should be auto bridged to Mastodon

### ISSUE THREAD

**Issue by vmazi** [snarfed/bridgy-fed#1602]
Verified on BlueSky means public figure willing to broadcast their content.

Be nice to be able to have them auto linked into masto

**Comment by vmazi** [comment]
Specifically only for verified accounts, let the rest of us opt in

**Comment by Tamschi** [comment]
(Just putting this as not "completed" so that it's clear from the issue list that we don't have this feature.)
