### ISSUE TITLE
Please document how one sets a userpic

### ISSUE THREAD

**Issue by fluffy-critter** [snarfed/bridgy-fed#1604]
It's not clear to me which things on my sites map to the user icons on the bridged service.

On https://beesbuzz.biz, bridged to https://bsky.app/profile/beesbuzz.biz, it seems to be using my h-card u-image.

On https://sockpuppet.band, bridged to https://bsky.app/profile/sockpuppet.band, it seems to be using a  low-resolution `link rel="icon"`.

On https://novembeat.com, bridged to https://bsky.app/profile/novembeat.com, no icon is appearing at all, even though it provides a `link rel="icon"` (albeit without a specified resolution).

I assume that the recommendation is to provide an h-card with a u-image in some way, or that there will be a fallback to a `link rel="icon"` using some particular logic, but it would be really nice if this were in the docs.

**Comment by snarfed** [comment]
@fluffy-critter https://fed.brid.gy/docs#web-profile ?

**Comment by fluffy-critter** [comment]
Ah, thanks, I searched all over but couldn't find that for some reason.

**Comment by fluffy-critter** [comment]
Oh wait there's another issue related to this, though: with novembeat.com, fed.brid.gy was showing the icon on [the user page](https://fed.brid.gy/web/novembeat.com), but it isn't coming through to the [bsky profile](https://bsky.app/profile/novembeat.com). I also can't figure out how to refresh the others with correct icons. Will that happen eventually on its own or is that a thing that can be prodded somehow?

**Comment by snarfed** [comment]
Ugh yeah, this is a separate problem. ATProto repos sometimes get "stuck" in the Bluesky appview and new records don't show up. I haven't yet found a consistent way to debug or fix this, sigh.

Eg your profile record for that account https://atproto-browser.vercel.app/at/novembeat.com/app.bsky.actor.profile/self looks fine, but it's not currently reflected on https://bsky.app/profile/novembeat.com
