### ISSUE TITLE
Posts in a thread appear out of order in Mastodon

### ISSUE THREAD

**Issue by TheRealAdamKemp** [snarfed/bridgy-fed#1614]
When I see threads in my Mastodon feed that have been bridged from Bluesky the posts are always out of order. It looks like the original first post (top of thread) always becomes the second, and the first post I see in my Mastodon feed is usually the LAST post from the original thread.

**Comment by snarfed** [comment]
Whoa, that's odd, and unexpected. Can you give us an example?

**Comment by TheRealAdamKemp** [comment]
I’m not sure how to link to a Mastodon feed so you can see the bad ordering. If I follow a link to a particular post it takes me straight to Bluesky, and obviously that shows the right order.

This is one of the threads from Bluesky that appeared in the wrong order:

https://bsky.app/profile/did:plc:m65ifh7vn5zdgs7izcmht4gy/post/3ld26ivk7xk2x

If it helps, my Mastodon server is oliphaunt.social.

**Comment by snarfed** [comment]
Hmm, ok. I'm not sure this is Bridgy Fed specific, I see this pretty regularly with native fediverse accounts in Mastodon feeds and profile timelines. Here's an example from your server on https://oliphaunt.social/@matt 's profile:

<img width="400" alt="image" src="https://github.com/user-attachments/assets/93bf9229-c6cf-4d7b-b059-d0cf34fdced8" />


When I open any of the posts in the thread itself, eg the second one here, Mastodon shows them in the correct order:

<img width="410" alt="image" src="https://github.com/user-attachments/assets/98828e5e-a601-46a9-aabc-46a8df0d2fbe" />


Here's a similar example from a Mastodon home feed:

<img width="400" alt="image" src="https://github.com/user-attachments/assets/553f5392-03e2-442e-b877-547626a71ed3" />


...and opening the thread itself:

<img width="310" alt="image" src="https://github.com/user-attachments/assets/723e7265-bbbd-42bb-952b-53b0a8f318cf" />

**Comment by TheRealAdamKemp** [comment]
Sorry, that’s not the issue I’m reporting. I understand and expect that in feeds the posts should appear in reverse chronological order. So if a user posts (in order) “A”, “B”, “C” then I should see on my timeline:

“C”
“B”
“A”

What I’m saying is that often for Bluesky threads I see this on my feed:

“B”
“A”
“C”

They're not reverse chronological. They’re just misordered. But only one of the posts is misplaced. All of the other posts are in the right order. At first I thought it was the first post that was in the wrong place, but I think it may actually be the last one, which gets moved to the opposite end. For instance:

AB -> BA
ABC -> CAB
ABCD -> DABC

There may be exceptions (or I could just be wrong), but definitely the order is not correct in the feeds. 
 
I could still believe that this is a Mastodon bug, but I’ve only noticed it with threads from Bluesky users so far.

**Comment by snarfed** [comment]
Ah, thanks for the explanation! Got it.

Bluesky has a widely thread composer that lets users compose a multi-post thread and publish them all at once. When that happens, those posts probably all have the same timestamp, which I suspect is what Mastodon is using to order feeds.

I don't know for sure though. This is pretty squarely on Mastodon's side afaict, we may not be able to do much about it. Sorry I don't have better news.

**Comment by Tamschi** [comment]
> I don't know for sure though. This is pretty squarely on Mastodon's side afaict, we may not be able to do much about it. Sorry I don't have better news.

I think it's a quirk of pushing activities in parallel to the same inbox. Most ActivityPub software doesn't do that, if I'm not mistaken.

(_Afaik_ Mastodon doesn't order the feed by time but by order of receipt in the inbox, but I could be mistaken about that.)

**Comment by snarfed** [comment]
Tentatively closing, feel free to open if you disagree @TheRealAdamKemp.

**Comment by TheRealAdamKemp** [comment]
Sorry, I meant to respond sooner. That seems fair. I’ll let you know if I learn otherwise.
