### ISSUE TITLE
Fedi bridge to Bluesky not taking up new domain name

### ISSUE THREAD

**Issue by yurukov** [snarfed/bridgy-fed#1616]
This is similar to https://github.com/snarfed/bridgy-fed/issues/1523 where the bridge stopped working, but this time it works and my domain is still not picked up. 

This is about @GovAlertEu@m.govalert.eu. DNS is good for GovAlertEu.m.govalert.eu. I've sent the DM with "GovAlertEu m.govalert.eu" and have refreshed the profile a couple of times. No changes on the Bluesky side. I have about 8 accounts on that domain and it doesn't work for any of the, 

![Screenshot from 2024-12-12 12-44-52](https://github.com/user-attachments/assets/35587c79-0496-46f4-ac6a-adc9e5bc9552)
![Screenshot from 2024-12-12 12-44-02](https://github.com/user-attachments/assets/a025cff0-5864-472a-824b-98908870d6c0)

**Comment by Tamschi** [comment]
I wonder if it's hitting this: https://github.com/bluesky-social/atproto/blob/a940c3fceff7a03e434b12b4dc9ce71ceb3bb419/packages/pds/src/handle/reserved.ts#L400

Though, if I'm not mistaken then the associated check shouldn't be applicable here.

**Comment by yurukov** [comment]
I did not know about that. Let me check with another domain.

**Comment by Tamschi** [comment]
Side-note, the "username" in the DM is literal. You may want to send "username GovAlertEu.m.govalert.eu" instead if you're aiming to get that full handle.

**Comment by yurukov** [comment]
That did the trick. I guess if I was confused by the documentation, then others would be too. Thank you. 
![Screenshot from 2024-12-12 15-52-34](https://github.com/user-attachments/assets/079ce536-e987-430c-b326-10978eda4553)

**Comment by snarfed** [comment]
Oops, replied in #1523 before I saw this: 

> Sorry for the trouble @yurukov! I'm seeing a timeout from your DNS server on GovAlertEu.m.govalert.eu: https://bsky-debug.app/handle?handle=GovAlertEu.m.govalert.eu
> 
> ![image](https://github.com/user-attachments/assets/ef217e07-7cf4-41c6-b295-92ac4848c84e)

https://github.com/bluesky-social/atproto/blob/a940c3fceff7a03e434b12b4dc9ce71ceb3bb419/packages/pds/src/handle/reserved.ts#L400 is interesting, but I suspect it only applies to usernames on instances of that PDS codebase, not custom domain handles. Not sure though.

**Comment by yurukov** [comment]
It may be some temporary issue. I'll run diagnostic tomorrow to see if my server has stop time.
