### ISSUE TITLE
Support(web->fed): reset my Bluesky account

### ISSUE THREAD

**Issue by gerbenjacobs** [snarfed/bridgy-fed#1618]
Hi,

I'm still having trouble with my Bluesky bridging (since #1579). 

Bsky.app is now saying my account is an "invalid handle", so since posting to the relay is working (according to you) but none of the posts show up, we can maybe **nuke** the account and try again (without domains).

Current bsky DID: did:plc:dcrsapklvvin5uztwdnwqa5u ([debug](https://atproto-browser.vercel.app/at/did:plc:dcrsapklvvin5uztwdnwqa5u))
Brid.gy account: https://fed.brid.gy/web/gerben.dev

As an aside; I've removed the domain verification a couple of days ago and today I noticed that bsky cache has taken that into account.
However on Brid.gy it still shows my Bsky account is the domain version, even after "Refreshing profile".

**Comment by snarfed** [comment]
Hey, sorry for the trouble! Looks like your domain lost its DNS record or HTTPS file: https://bsky-debug.app/handle?handle=gerben.dev

**Comment by snarfed** [comment]
I've recreated your bridged Bluesky account with a new DID, `did:plc:6hwz342xdspgtmu6hun36emg`, https://bsky.app/profile/did:plc:6hwz342xdspgtmu6hun36emg. Hopefully this will get it working again.

**Comment by gerbenjacobs** [comment]
> I've recreated your bridged Bluesky account with a new DID, `did:plc:6hwz342xdspgtmu6hun36emg`, https://bsky.app/profile/did:plc:6hwz342xdspgtmu6hun36emg. Hopefully this will get it working again.

Thanks, looks like that's valid. However it's not linked (yet) to my brid.gy account, so it doesn't seem to work yet.

**Comment by snarfed** [comment]
Hmm! By linked, if you mean visible on https://fed.brid.gy/web/gerben.dev , you're right, sorry, it was cached there for a bit. It's updated now!

**Comment by gerbenjacobs** [comment]
Yep, I saw it today. Also bridging is working now. 

I'll keep it like this for a while, to test out different content types and when I feel brave I'll try the 'verify your domain' again.

Thanks!
