### ISSUE TITLE
No longer posting to bluesky

### ISSUE THREAD

**Issue by benjifs** [snarfed/bridgy-fed#1620]
I'm trying out a separate site that automatically posts to bsky and mastodon a few times a day. I only just noticed that while it has been successfully posting to AP, it stopped posting to bsky after the first few days.

https://fed.brid.gy/web/haiku.oom9.xyz
https://bsky.app/profile/haiku.oom9.xyz

Any suggestion on what to do to get posts to show up on bluesky?

**Comment by snarfed** [comment]
Hey, sorry for the trouble! I've nudged your account, it may start working again now. If not, you may have fallen victim to #1595.

**Comment by snarfed** [comment]
Looks like this didn't work. Sigh, sorry, #1595 it is.

**Comment by snarfed** [comment]
Duplicate of #1595
