### ISSUE TITLE
missing profile

### ISSUE THREAD

**Issue by adamdjbrett** [snarfed/bridgy-fed#1622]
I'm really enjoying Bridgy you did something incredible here. It works great on mastodon however its not working on bsk.app

* domain [rs-rss.com](https://rs-rss.com)
* [repo](https://github.com/adamdjbrett/rs-rss.com/)
* broken bluesky [bsk.app](https://bsky.app/profile/rs-rss.com.web.brid.gy)
* [invalid handle on bsk](https://bsky.app/profile/did:plc:h353sfvxl3wovtqhd2f6vtjt)

**Comment by adamdjbrett** [comment]
I kept reading through the documentation and I fixed the issue by switching to [bluesky enhanced](https://fed.brid.gy/docs#bluesky-enhanced). Adding the DNS records steps 5&6 really helped. thanks for a great service and super detailed documentation.

**Comment by adamdjbrett** [comment]
I kept reading through the documentation and I fixed the issue by switching to [bluesky enhanced](https://fed.brid.gy/docs#bluesky-enhanced). Adding the DNS records steps 5&6 really helped. thanks for a great service and super detailed documentation.

**Comment by snarfed** [comment]
Hey @adamdjbrett, sorry for the trouble, and thanks for the kind words. Glad you got it working!
