### ISSUE TITLE
"Invalid Handle" on Bluesky due to incorrect DID in DNS

### ISSUE THREAD

**Issue by tasquatch** [snarfed/bridgy-fed#1623]
[Bridging from kiwiblog.co.nz](https://fed.brid.gy/web/kiwiblog.co.nz) shows up as ["Invalid Handle" on Bluesky](https://bsky.app/profile/did:plc:fy4tkhgytkw7uvv5eklenzbi).

If I run `nslookup -q=txt _atproto.kiwiblog.co.nz.web.brid.gy`, I get `did=did:plc:oupl6uo54qgf4rzbpbnvdyyi`. This does not match `did:plc:fy4tkhgytkw7uvv5eklenzbi`, which is the DID of [the Bluesky profile where the bridged posts appear](https://bsky.app/profile/did:plc:fy4tkhgytkw7uvv5eklenzbi)  and also the DID on [the fed.brid.gy page](https://fed.brid.gy/web/kiwiblog.co.nz).

**Comment by snarfed** [comment]
Oof, sorry for the trouble, and thanks for the sleuthing! Not sure what happened here, but you're right about the DIDs. I've poked this manually for now, the handle should hopefully show up soon.

**Comment by tasquatch** [comment]
Looks good now. Thanks for fixing this (and for running this service in general)!
