### ISSUE TITLE
@bsky.brid.gy@bsky.brid.gy isn't accepting my follow request, nor following back

### ISSUE THREAD

**Issue by egerlach** [snarfed/bridgy-fed#1630]
I tried following @bsky.brid.gy@bsky.brid.gy in order to bridge my Mastodon account to Bluesky, but my follow request isn't being accepted, nor am I being followed back.

My account is @egerlach@hachyderm.io. Let me know if there's other data I can provide or debugging I can do at my end.

**Comment by Tamschi** [comment]
Your account doesn't have a profile picture, which means it's getting caught in the spam filter.
Add one, cancel the request and retry and it should work.

See also https://fed.brid.gy/docs#troubleshooting.
