### ISSUE TITLE
Not looking up webfinger URI template?

### ISSUE THREAD

**Issue by singpolyma** [snarfed/bridgy-fed#1636]
when I ask about @conservancy@sfconservancy.org as a fediverse address, the bluesky bridgy fed bot tells me it can't find that. I'm wondering if maybe it's not looking up https://sfconservancy.org/.well-known/host-meta to find the webfinger url pattern?

**Comment by snarfed** [comment]
Hi @singpolyma! Good guess, yes, looks like that's #1031. Any chance I could talk you into a PR? 😁
