### ISSUE TITLE
Links are removed from bridged bsky posts

### ISSUE THREAD

**Issue by papuass** [snarfed/bridgy-fed#1637]
This started happening a little bit more than day ago:

Here is bsky account: https://bsky.app/profile/lsm.lv
Here is bridged account: https://toot.lv/@lsmlv.bsky.social@bsky.brid.gy

The last bridged post that **has link**: https://toot.lv/@lsmlv.bsky.social@bsky.brid.gy/113669517942993218
Matching bsky post: https://bsky.app/profile/lsm.lv/post/3ldjgwiklys26

The first bridged post that is **missing the link**: https://toot.lv/@lsmlv.bsky.social@bsky.brid.gy/113672485889270723
Matching bsky post: https://bsky.app/profile/lsm.lv/post/3ldkr7iuros2s

The account moved from @lsmlv.bsky.social to @lsm.lv on BSKY some time ago, the bridge was made with the old identifier.

**Comment by snarfed** [comment]
Whoops, thank you for reporting! Looks like a bug we introduced indirectly in snarfed/granary@14c965340fdd75424f682d1bdb22168a9b9e07c0. Will fix.

**Comment by snarfed** [comment]
Fixed, should be deployed in ~10m. Thanks again!

**Comment by papuass** [comment]
All is working now correctly, thanks! 🎄
