### ISSUE TITLE
'No web user found for domain' error when trying to follow at 'fed.brid.gy/bsky/{custom_domain}'

### ISSUE THREAD

**Issue by mistrk7** [snarfed/bridgy-fed#1640]
I'm trying to follow my bsky-to-fedi bridgy account that uses a custom domain with a mastodon account.
It uses a custom domain but it is not run there.
![image](https://github.com/user-attachments/assets/3a28ae15-9c1c-4df7-82ad-f761ad4b8f71)
When I click the follow button, an error shows up complaining it hasn't found a web user.
But it shouldn't be, right? Why is it going through the domain? I'm not sure what I am doing wrong.
![image](https://github.com/user-attachments/assets/c66b541f-6a40-4103-be15-025de6fb7ae0)

**Comment by Tamschi** [comment]
As a workaround, you should be able to search for `@misterk.in@bsky.brid.gy` while logged into Mastodon to find the account.

**Comment by mistrk7** [comment]
> As a workaround, you should be able to search for `@misterk.in@bsky.brid.gy` while logged into Mastodon to find the account.

Thanks, this works to let me discover and follow the account. But now, the request to follow is just stuck on pending.

**Comment by Tamschi** [comment]
That could be #1135. The spam filter is currently too strict regarding just following an account.
If that is the issue, I _think_ you can retry once once the Mastodon account fulfils the requirements.

**Comment by snarfed** [comment]
Sorry for the trouble @mistrk7! The web UI is brittle and parts of it like this still don't support Bluesky yet. I'll see if this is a quick fix.

**Comment by mistrk7** [comment]
Well possibly but like @Tamschi has said, I've made the mastodon account fit the requirements, but i'm still getting the pending error so it's still not allowing it. I suppose the account age another factor as well (made yesterday). 

Otherwise could someone follow it so that posts show up on mastodon, if i'm correct in how that works? Thanks for your help.

**Comment by snarfed** [comment]
Right, age is another factor: https://fed.brid.gy/docs#troubleshooting

**Comment by snarfed** [comment]
^ Fixed the web remote follow UI, should be deployed in 10-15m. Thanks again for reporting @mistrk7!
