### ISSUE TITLE
Retroactively resend past follows by a newly bridged user

### ISSUE THREAD

**Issue by sayunuh** [snarfed/bridgy-fed#1651]
As far as I understand, if a Bluesky user follows a bridged Mastodon account before they bridge their own account in the reverse direction, the follow notification is never received even after the mutual bridge is made (unless they manually unfollow & refollow), retaining discrepancy. I wish this situation could be “retconned” automatically by resending follows to currently followed accounts once their account is bridged. Is that feasible?

**Comment by Tamschi** [comment]
This was filed a while ago, in #1102.

(In theory it's feasible, and Bridgy Fed does track the necessary data to do this already, but it doesn't seem to be a high priority.)
