### ISSUE TITLE
Potential overlap with Wordpress-ostatus

### ISSUE THREAD

**Issue by chrisaldrich** [snarfed/bridgy-fed#17]
Not really an issue, but I just saw this in [#wordpress chat](https://chat.indieweb.org/wordpress/2017-10-17#t1508233670313000), and wasn't sure if you knew about it: https://github.com/pfefferle/wordpress-ostatus

Curious how bridgy-fed may dovetail with it? I'm hoping to try to get time to test them both this weekend...

**Comment by snarfed** [comment]
thanks for the nudge! yup, i'm familiar with it. great work by @pfefferle!

bridgy fed differs in that it's not OStatus- or WordPress-specific. regardless, i'm all for people using that plugin instead if it works for them!
