### ISSUE TITLE
Replies out?

### ISSUE THREAD

**Issue by singpolyma** [snarfed/bridgy-fed#2]
I know this whole thing is WIP, just filing this :)

So far, focus seems to be on inbound salmon, etc. Outbound salmon based on my in-reply-to posts would be amazing :)

**Comment by snarfed** [comment]
yes! i'm actually trying to focus equally on both directions. as of today, it supports AP replies both in and out, tested on mastodon 1.6, and Salmon at least out, tested on hubzilla. examples:
* https://snarfed.org/2017-10-01_mastodon-for-tech-folks <=> https://mastodon.technology/@snarfed/3194674
* https://snarfed.org/reply5.html <=> https://lastauth.com/channel/snarfed/?mid=7cfa12e54cf97aaed3b0bb185651ae37a1e24027fbf3e845fab261e108392707@lastauth.com  (but lastauth.com is down right now 😢)

apologies for the delay btw, i just now noticed i wasn't watching this project. (heh.)

**Comment by snarfed** [comment]
docs on this are up, feel free to try it out!
