### ISSUE TITLE
default u-url to webmention source url

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#20]
discovered by @khurtwilliams today: if an incoming webmention doesn't have a `u-url`, we happily convert it to an AS2 object without `id`, which mastodon accepts and returns HTTP 202, but never actually displays. i *think* the lack of `id` is the root cause.

example log: https://fed.brid.gy/log?start_time=1513114805&key=https%3A%2F%2Fislandinthenet.com%2Ftest-2-2%2F+https%3A%2F%2Fmastodon.social%2F%40khurtwilliams%2F99163372007448652

**Comment by snarfed** [comment]
fixed! thanks again for reporting, @khurtwilliams. your reply shows up on https://mastodon.social/@khurtwilliams/99163372007448652 now.

**Comment by khurtwilliams** [comment]
Thank you.

https://islandinthenet.com

"Those that prosper consistently will think deeply, reevaluate, adapt,
and continually
evolve”. ~ Farnam Street

Schedule some time to chat! <http://calendly.com/monkeyhill>

From: Ryan Barrett <notifications@github.com> <notifications@github.com>
Reply: snarfed/bridgy-fed
<reply@reply.github.com>
<reply@reply.github.com>
Date: December 12, 2017 at 21:21:08
To: snarfed/bridgy-fed <bridgy-fed@noreply.github.com>
<bridgy-fed@noreply.github.com>
CC: Khürt Williams <khurtwilliams@gmail.com> <khurtwilliams@gmail.com>,
Mention <mention@noreply.github.com> <mention@noreply.github.com>
Subject:  Re: [snarfed/bridgy-fed] default u-url to webmention source url
(#20)

fixed! thanks again for reporting, @khurtwilliams
