### ISSUE TITLE
What's the difference between Bridgy-Fed and Bridgy?

### ISSUE THREAD

**Issue by kajmagnus** [snarfed/bridgy-fed#22]
Hi, I've had a look at https://fed.brid.gy/ and https://brid.gy/, and to me it's unclear what's the difference between Bridgy-Fed and Bridgy?

When would I use one of them but not the other? Why did the Bridgy-Fed people proceed with creating Bridgy-Fed although Bridgy already exists?

Why are they hosted on the same 2nd level domain? Feels as if the same person is competing with him/herself about making both projects popular. Hmm and you (@snarfed ) own both projects here in GitHub too :- )  such a mystery (to me).

**Comment by snarfed** [comment]
hi @kajmagnus! thanks for asking, and apologies for the confusion. you're right, it may not be ideal that they have similar names, branding, and domains, and do things that are related...but they are different, and don't actually overlap in functionality.

bridgy handles traditional social networks like facebook and twitter. bridgy fed, on the other hand, handles _federated_ social networks like mastodon and gnu social. that's the main difference. (bridgy fed also requires more involve setup, and its interactions are somewhat different than bridgy's.)

i'm open to ideas on how to make that distinction clearer!

**Comment by kajmagnus** [comment]
Thanks for explaining :- )

As to how to make this distinction clearer, maybe you could just copy paste roughly the sentence you wrote above to the two homepages:

1) _"Bridgy handles traditional social networks like facebook and twitter. There's also Bridgy Fed, which handles federated social networks like mastodon and gnu social"_

2) _"Bridgy Fed handles federated social networks like mastodon and gnu social. There's also "Bridgy" (without Fed in the name) which handles traditional social networks like facebook and twitter"_
