### ISSUE TITLE
rel="salmon" for my Atom feed?

### ISSUE THREAD

**Issue by singpolyma** [snarfed/bridgy-fed#24]
What should I use if I want fed.brid.gy to deliver slaps to me as webmention?

**Comment by snarfed** [comment]
salmon senders will actually look it up via webfinger, so you don't actually need it in your atom feed. e.g. https://fed.brid.gy/.well-known/webfinger?resource=singpolyma.net includes this in its response:

```json
  "links": [
    "..."
    {
      "href": "https://fed.brid.gy/singpolyma.net/salmon",
      "rel": "salmon"
    }
```

looks like you don't currently have the redirect from https://singpolyma.net/.well-known/host-meta to https://fed.brid.gy/.well-known/host-meta set up, but that should be all you need: https://fed.brid.gy/#setup

**Comment by singpolyma** [comment]
I'm in the middle of a rewrite (moving from wordpress to static) so that's why you don't see it enabled *yet*.

That looks like the link I'm looking for :)  I know webfinger-enabled people will see it there, but it can't hurt to put things in more places to support anyone who comes in some other way.

**Comment by snarfed** [comment]
i'm really glad you're going to try this! it's definitely had some usage, but not a ton, so expect more hiccoughs. AP and OStatus interop are both really finicky in practice, for a variety of reasons. e.g. Mastodon will happily accept and 202/204 incoming replies, and then proceed to not show them. i've only figured out [some of the reasons](https://fed.brid.gy/#troubleshooting). others are still mysteries. (moderation? sig verification differences? sigh.)

**Comment by singpolyma** [comment]
Yeah, I've never tried with Mastodon yet with my current stuff because they're known for not caring about the specs or common practise and just doing whatever they want.  That it works at all will be a step up for me :)
