### ISSUE TITLE
default home page URLs to https?

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#269]
When we generate wrapped home page URLs for @-@ ids like @snarfed.org@snarfed.org, we don't know the site's scheme, so we default to http, eg https://fed.brid.gy/r/http://snarfed.org/. This is fine, I don't worry about security specifically, but pretty much all current users serve on https and redirect http to https, so maybe we should switch to defaulting to https?

Discussion: https://chat.indieweb.org/2022-11-08#t1667936602382900

cc @tantek @barnabywalters

**Comment by barnabywalters** [comment]
Given the audience for BF and the (presumably 100%?) current usage of https, I would be fine with BF assuming HTTPS, at least until someone complains about it.

**Comment by snarfed** [comment]
Done!
