### ISSUE TITLE
Monitoring dashboard

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#273]
I should put together basic app-level monitoring and a dashboard, like I already have for Bridgy, granary, etc.

**Comment by snarfed** [comment]
Good progress on this in https://console.cloud.google.com/monitoring/dashboards/builder/4f0ac7cc-258d-4058-8208-fafa32088378?project=bridgy-federated , sadly can't make it public

<img width="1255" alt="image" src="https://user-images.githubusercontent.com/778068/204947357-8e0089aa-4f4b-4ed3-b640-145fd11675bf.png">
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/778068/204947412-143d6383-d52a-4a14-bb31-c21b490839c2.png">
<img width="1240" alt="image" src="https://user-images.githubusercontent.com/778068/204947460-b28483da-6848-413c-aa66-92649051ba25.png">

**Comment by snarfed** [comment]
Improved these some. Closing out!

**Comment by snarfed** [comment]
Entertaining side effect of Bridgy Fed's new monitoring, I can see mastodon.technology suddenly start sending out Delete activities for all of its users (I assume) since it's shutting down, cc @ashfurrow
![mastodon-technology](https://user-images.githubusercontent.com/778068/205171982-65b2b88e-7620-4993-8ca5-9291215ecd37.png)
![image](https://user-images.githubusercontent.com/778068/205172271-89597de6-8560-407c-857c-d98ac0808085.png)

**Comment by ashfurrow** [comment]
That is really cool! I like how you can see the dips and spikes as I reboot and scale up 😄
