### ISSUE TITLE
fed.brid.gy ignores me ;-)

### ISSUE THREAD

**Issue by iamwebrocker** [snarfed/bridgy-fed#278]
Hi Ryan, 

sorry to bother here now … after I tried and [failed](https://github.com/snarfed/bridgy/issues/1342#issuecomment-1305154039) to get brid.gy/publish/mastodon to work (b/c mastodon.social returns with an error from their side) I now set up my blog according to the hints on fed.brid.gy:

I have a atom feed in place: https://webrocker.de/?feed=atom
I have set up the redirects to webfinger etc: https://webrocker.de/.well-known/webfinger?resource=webrocker.de
I published this post with webmentions: https://webrocker.de/2022/11/12/run-to-the-hills/

```
(...)
<a class="u-in-reply-to" href="https://mastodon.social/@webrocker/109330296122499841"></a>
<a href="https://brid.gy/publish/twitter"></a>
<a href="https://fed.brid.gy"></a> 
```

But this post is not published in the fediverse, and under fed.brid.gy/responses I don't find it. 

Strangly, I had this working some day/weeks ago, but I didn't like the @www.webrocker.de@www.webrocker.de Account it "produced". So I changed the domain for my blog to webrocker.de (without the www.). As far as I can see, this worked, redirects are in place etc…
Under https://brid.gy/users/@webrocker.de and https://mastodon.social/@webrocker.de@webrocker.de my blog is found, but no post are listed.

Webmentions do work; I receive the "reactions" for instance from mastodon.social via https://brid.gy/mastodon/@webrocker@mastodon.social, and the brid.gy/publish/twitter nudge also worked, the post published on twitter: https://twitter.com/webrocker/status/1591371929470275584

But I cannot "post" via fed.brid.gy. Do have an idea what goes wrong here?

thanks once again for your work,
Tom

**Comment by iamwebrocker** [comment]
okay… now, with a delay of ca 4hrs, the post is visible! :-))

https://mastodon.social/@webrocker.de@webrocker.de/109331429489664518

cool :-)

**Comment by snarfed** [comment]
Thanks for reporting this! This was actually a bug, not just a delay. You were faster than me here to notice it! It's fixed now. Let me know if you see anything else wrong!

**Comment by iamwebrocker** [comment]
Is there a way to add a profile picture and infos for that virtual profile in the fediverse?

**Comment by snarfed** [comment]
Yes! It uses whatever's in your h-card on your web site home page.

**Comment by iamwebrocker** [comment]
according to https://indiewebify.me/validate-h-card/?url=https%3A%2F%2Fwebrocker.de the h-card works and has an image, but 
the fediverse virtual profile shows only the placeholder image. 

looking at the html source of my index page I see that there are several h-card a hrefs, because each post in the recent posts list has its own author info (which is identical since there all from the same author - me ;)
so maybe it would be smarter to create a dedicated h-card (vcard?) element for the index/profile? but how would I convey that this h-card is the one for the (profile)page, and that the h-card links in the post list are not relevant for this "profile" use?

**Comment by snarfed** [comment]
Interesting! You're right about the multiple h-cards, one inside each h-entry (post). The way you convey that an h-card is for the page, not just a single post, is to put it outside an h-entry. Your home page actually already has an h-card like that, item index 12 in https://pin13.net/mf2/?url=https://webrocker.de/ , you just need to add a u-photo to it like the h-cards inside your post already have.

(It looks like this is arguably also a bug in https://indiewebify.me/ . It should show the top-level h-card, but instead it's showing one the first one it finds, inside an h-entry, which isn't the representative one. cc @barnabywalters, will file an issue.)

**Comment by iamwebrocker** [comment]
ha. :) thanks for catching this. I remember now that during several indie web camps I fiddled with the placement of the h-card links and info… must have overlooked the u-photo outside of the entries. changed it right now, lets see if it will update the virtual profile. :-)

**Comment by iamwebrocker** [comment]
(currently under fed.brid.gy/recent the are "no log found" behind the log-links at the date strings)

**Comment by snarfed** [comment]
Argh, thanks for the catch! Will fix
