### ISSUE TITLE
Show custom username on account page

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#281]
If someone has set a custom AP username with an `acct:` `rel-me`, we should show it on their user page somehow.

(Related: #272)

**Comment by snarfed** [comment]
Done! Example: https://fed.brid.gy/user/www.ciccarello.me, cc @aciccarello

**Comment by aciccarello** [comment]
Looks great!

**Comment by datakurre** [comment]
@snarfed Could there be regression? Right now it shows domain again for me https://fed.brid.gy/user/www.ciccarello.me

Found this, when I was trying to get username work for https://fed.brid.gy/user/datakurre.pandala.org without success.

**Comment by snarfed** [comment]
Ruh roh! Thanks for the nudge, will look.

**Comment by snarfed** [comment]
Fixed, thanks again!
