### ISSUE TITLE
Drop OStatus?

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#282]
Bridgy Fed currently supports both ActivityPub and OStatus, but AP seems to be the future, OStatus the past. Do any meaningful fediverse implementations still use OStatus? Should we drop it?

Supporting both doesn't cost much maintenance, and it wouldn't be a big win to drop OStatus, but no sense in keeping the code around if it's unused.

**Comment by aciccarello** [comment]
I'm not active in these communities but judging from the projects listed on [wikipedia](https://en.wikipedia.org/wiki/OStatus) the most significant ostatus implementations have all enabled ActivityPub

- [gnusocial](https://gnusocial.network/#) ([supports ActivityPub](https://notabug.org/diogo/gnu-social#about))
- [frendica](https://friendi.ca/) ([supports ActivityPub](https://friendi.ca/about/features/))
- [Pleroma](https://pleroma.social/) ([supports ActivityPub](https://pleroma.social/blog/2021/01/13/the-big-pleroma-and-fediverse-faq/))
- [postActiv](http://www.postactiv.com/) (abandoned?)

**Comment by aciccarello** [comment]
Some interesting stats from https://the-federation.info/protocol/ostatus

    Nodes: 528
    Users: 215783
    Last 6 months users: 16129
    Last month users: 6827
    Posts: 19537041
    Comments: 523717

Looks like most activity is on mastodon (old servers), frendica, and gnusocial. Also a few hubzilla, pleroma, and even some wordpress sites.

**Comment by snarfed** [comment]
No OStatus activity on Bridgy Fed in the last month, so I'm calling it. 🫡 OStatus!
