### ISSUE TITLE
Actually delete followers

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#284]
We get a ton of `Delete` activities for deleted accounts on other servers right now. We don't currently try to find and disable the matching `Follower` entities, but we should, especially now that they're indexed appropriately.

Related, it's disappointing how overly chatty Mastodon's `Delete` activities are. As a representative example, we got 51 of them today in the span of just ~700ms, at 2022-11-15 23:25:54 UTC, for the same account on mastodon.social, which has never followed or been followed by any Bridgy Fed user. 😐

Each one got sent to a different BF user's inbox, which...ok...but it still seems like they could de-dupe by host and expect that hosts handle it instance-wide, not per user? 🤷

**Comment by snarfed** [comment]
Ah! Sounds like an AP [shared inbox](https://www.w3.org/TR/activitypub/#shared-inbox-delivery) could reduce this from one per BF user to one (?) total: https://github.com/mastodon/mastodon/issues/10476#issuecomment-508489781

**Comment by aaronpk** [comment]
Yes, the shared inbox would be a good idea to implement for a multi-user inbox, Mastodon uses it for deletes as well as other activities sent to everyone on an instance. I also wrote code in my implementation to dedupe by shared inbox when I'm sending out my own posts to cut down on the number of requests.

**Comment by snarfed** [comment]
Original: #63
