### ISSUE TITLE
allow users to choose their own username

### ISSUE THREAD

**Issue by 00dani** [snarfed/bridgy-fed#3]
I know it's standard IndieWeb practice to have only one user on the domain, but that doesn't necessarily mean their name is "me", and it's misleading to return (for example) WebFinger data that claims it's for `acct:me@example.com` when that address doesn't exist.

For example, on my site, I've provided an email address in [my representative h-card](https://indiewebify.me/validate-h-card/?url=https%3A%2F%2F00dani.me). When this is done, I think it would be appropriate for Bridgy Fed to use that email address to construct the `acct:` identifier for the user.

**Comment by snarfed** [comment]
sure! understood.

a few thoughts:
* OStatus/ActivityPub addresses only _look_ like email addresses. they're not actually email addresses, nor do they interact with email at all, so technically it doesn't matter whether the corresponding email address exists.
* the username in an OStatus/ActivityPub address is part of its identity, so if it ever changes, your identity on federated social networks will change, which will surprise other users, and maybe you too.
* `me` is intended to imply that you're the site `example.com` itself, not just a single user on `example.com`, which another username might imply. (that also means that we'd need to figure something out for multi-user sites. ¯\\\_(ツ)\_/¯)
* on a related note, what should we do if your representative h-card's email address isn't on `00dani.me`? we need an `@00dani.me` AP/OStatus address. should we still extract and use the username from the email address? unclear.
* how should conflicts be resolved? e.g. if your representative h-card has `u-email` `abc@00dani.me` and `p-nickname` `xyz` (generally interpreted as preferred username), which should we choose?

having said all that, this still is reasonable, at least for email addresses on the same domain. i can definitely consider it.

**Comment by 00dani** [comment]
Hmm, good points.

* I *did* know that OStatus/AP subjects aren't necessarily email addresses - none of my six (!) Mastodon handles are email addresses for example - but sources like https://webfinger.net seem to assume they might be? That client expects you to enter an "Email or URL", and if given an email address it uses the `acct:` scheme to look it up. It might just be that https://webfinger.net is misleading though. :wink:
* If the username changes under this suggestion, it'd be because your email address changed, which is already part of your identity, right? Although, if Bridgy Fed's behaviour changed, that'd change existing users' identities as perceived from the fediverse. Hmm.
* Using `me@example.com` to convey "I'm the site `example.com`" is really good actually. I'm starting to think I should set up `me@00dani.me`, at least as an alias. Still, that won't work for multi-user sites, which still need another solution.
* The representative h-card's email address should only be taken as the username if it's on the same domain, I think. More specifically, I think it should work like this:
* If your representative h-card has a `u-email` on the correct domain, use that. If it doesn't, use `p-nickname`. If it has neither, fall back on `me@domain`.

Thoughts?

**Comment by snarfed** [comment]
thanks! good feedback.

another argument against `me` is that mastodon largely prioritizes username over domain when rendering remote users, just like local users, so you'll often see just `me` in toots, notifications, etc. not so useful. :/

<img width="307" alt="image" src="https://user-images.githubusercontent.com/778068/31188527-0f1a014a-a8ea-11e7-8893-0cc97c68526e.png">

**Comment by snarfed** [comment]
@aaronpk out of curiosity, how would you ideally want to tell bridgy fed to use `aaronpk@aaronpk.com`? `p-nickname` in representative h-card, which wouldn't include domain? `u-email`, which is overloaded and would have false positives? other?

**Comment by snarfed** [comment]
i'm tentatively changing the username from `me` to the source site's domain. we can still consider more sophisticated approaches like `p-nickname` etc, but this fixes an interop bug with mastodon and also improves username rendering there.

**Comment by tantek** [comment]
The site's domain is an excellent default and I think mostly mitigates this issue in a very appropriate way. Want a different username? use a different domain. E.g. if @aaronpk wants something like "aaronpk" as his user name, he can choose to use his aaronpk.com domain as the domain he federates from to Mastodon. 

Given this point from @snarfed:
* username in an OStatus/ActivityPub address is part of its identity, so if it ever changes, your identity on federated social networks will change, which will surprise other users, and maybe you too.

It may be the right answer to "wont fix" the rest of this issue, or rather, close as "fixed" by being domain@domain centric and pushing the "choose your username" question to "choose your domain", since frankly, it's about "choose your identity" (per the point above) more than "choose your username" and that's your domain on IndieWeb anyway.

**Comment by 00dani** [comment]
domain@domain works for me. 👍

**Comment by 00dani** [comment]
Ooh, wait, idea: the AP/OStatus identity could be customised on your `h-card` by adding a `u-url` property *that uses the `acct:` protocol*. False positives are unlikely, and the identifier that Bridgy Fed outputs would simply exactly match the appropriate `u-url`, if one's provided. Thoughts?

**Comment by 00dani** [comment]
Alternatively, a specialised property could be devised, like `u-bridgy-fed-acct`, but I think matching the `u-url` values against `acct:` would be just as reliable.

**Comment by singpolyma** [comment]
+1 for hcard url (or rel=me ?) of `acct:` to set username

**Comment by snarfed** [comment]
fyi all, @singpolyma's #27 implements this by looking for an `acct:` `u-url` in the representative h-card, as descibed earlier here, which seems pretty safe and likely to only be used by people who know what they're doing.

i'm still a bit reluctant, but i think it addresses all the main concerns, so i'm ok with merging it. feel free to weigh in if you disagree.

**Comment by snarfed** [comment]
@singpolyma true! agreed, no user-visible impact of this right now afaik, but it could definitely use the `acct:` value too, or instead.

**Comment by damianbrown** [comment]
I know we can use u-url to change the fediverse username by setting it to acct:user1@example.com and then presumably the fediverse ID would be @user1@example.com but is it possible to have multiple "users" and so havr a fediverse user as @user1@example.com and another as @user2@example.com and so on.

**Comment by snarfed** [comment]
@damianbrown no, sorry, and I don't expect that any time soon. That would require #491, which wouldn't be easy, since "one account per domain" for web sites is pretty baked into BF's current design.
