### ISSUE TITLE
Add retry buttons on user page warnings

### ISSUE THREAD

**Issue by iamwebrocker** [snarfed/bridgy-fed#300]
I see "your site doesn't have a representative h-card" 
… when indeed it has one.

Did I messed up this section on my site?

```
<div class="widget widget-me h-card" id="about">
	<h2 class="widget-header">Me, taking care of</h2>
	<figure class="portrait">
		<a href="/impressum/"><span><img src="https://webrocker.de/blog/wp-content/uploads/2020/04/profile-300x300.png" class="u-photo" alt="Webrocker" decoding="async" loading="lazy" id="portrait" srcset="https://webrocker.de/blog/wp-content/uploads/2020/04/profile-300x300.png 300w, https://webrocker.de/blog/wp-content/uploads/2020/04/profile-210x210.png 210w, https://webrocker.de/blog/wp-content/uploads/2020/04/profile.png 500w" sizes="(max-width: 300px) 91vw,300px" width="300" height="300"></span></a>
	</figure>
	<ul class="vh">
		<li class="p-name">Tom</li>
		<li class="p-note">my blog, my personal home page, my castle in the www</li>
		<li><a rel="me" class="u-url" href="https://webrocker.de"><span class="p-nickname">Webrocker</span></a></li>
	</ul>
	<ul>
		<li><a href="http://www.wondertom.de/">Illustration &amp; Grafikdesign</a></li>
		<li><a href="http://www.bnt.de/">Webdesign &amp; Webdevelopment</a></li>
		<li><a href="http://www.popsicle.de/">Gitarre</a> &amp; <a href="http://www.motoerblock.com/">Bass</a> &amp; <a href="https://corduroy.rocks">Acoustic</a></li>
		<li><a href="https://offset.guitars">Jaguar &amp; Jazzmaster</a></li>
		<li class="contact">Kontakt: <a rel="me" href="https://mastodon.social/@webrocker">Mastodon</a> | <a href="https://twitter.com/webrocker">Twitter</a> | <a rel="me" class="u-email" href="mailto:blog@webrocker.de">E-Mail</a></li>
		<li class="elsewhere">Und sonst so: <a rel="me" href="https://codepen.io/webrocker">Codepen</a> | <a href="https://github.com/iamwebrocker" rel="me">github</a></li>
		<li class="">Find my blog on the Fediverse: <a rel="me" href="https://mastodon.social/@webrocker.de@webrocker.de">@webrocker.de@webrocker.de</a></li>
	</ul>
</div>
```

(too many me on the dancefloor?)

![Bildschirmfoto 2022-11-21 um 12 24 01](https://user-images.githubusercontent.com/1223080/203038987-a7b1872b-f1e7-4859-9f61-b8b577a951d8.png)
![grafik](https://user-images.githubusercontent.com/1223080/203043379-b771b365-88dc-4937-b6c6-90562245a39a.png)

https://indiewebify.me/validate-h-card/?url=https%3A%2F%2Fwebrocker.de

finds the right one (checks the p-note):

![grafik](https://user-images.githubusercontent.com/1223080/203044898-b11e33dd-e1dc-44c3-acb1-74de272bfd65.png)

btw, the intro site on fed.brid.gy is much clearer now, thank you :-)

**Comment by snarfed** [comment]
Hah, sorry! Looks like this was an artifact of my early testing. I entered `webrocker.de` on https://fed.brid.gy/web-site and it re-checked your site and says it's all good now.

I should add "retry" buttons in those yellow warnings. I'll track that here.

**Comment by iamwebrocker** [comment]
Heheh, thank you! :-) now hopefully the "profile" (what should we call the fediverse pseudo profile? projection? pseudo profile?) anyway, I hope this thing in the fediverse will update with the note and profile picture.
