### ISSUE TITLE
Webfinger error, returns 502

### ISSUE THREAD

**Issue by fancypantalons** [snarfed/bridgy-fed#302]
It's odd because I feel like this was working just a couple of days ago, but check out this log [this log](
https://fed.brid.gy/log?start_time=1669014155&key=https://b-ark.ca/2022/11/21/an-activitypub-feed-for-a.html%20https://indieweb.social/@tomcritchlow/109379842452147942&module=) and you'll find:

```
Webfinger error when resolving brettk@fed.brid.gy: Request for acct:brettk@fed.brid.gy returned HTTP 502
```

Oddly, issue #77 sounds eerily familiar to the one I'm experiencing.  Is it possible there was a recent regression?

**Comment by snarfed** [comment]
Hmm, your webfinger address should be b-ark@b-ark.ca or brettk@b-ark.ca, not brettk@fed.brid.gy. Any idea why it's looking for that? Weird. I'll look.

**Comment by fancypantalons** [comment]
I think I found the commit where this broke.  If we look at [this commit](https://github.com/snarfed/bridgy-fed/commit/65f3ef3cc71b4a5dea56f47ba61736a5b44f1fdf), in common.py we see this change:

>481 -         'preferredUsername': domain,
>484 +        'preferredUsername': username,

This is an accidental reversion of the fix for issue #77 (you can see in [this commit](https://github.com/snarfed/bridgy-fed/commit/fdd42ad1d4d072dd185914fa9d4caf5a2341749b) where the original change was made).

My guess is this was an accidental regression?

**Comment by snarfed** [comment]
Wow, great sleuthing! Yeah I'm sure that's the cause. I'll revert that right now.

...and you're right, I probably changed this recently thinking about custom usernames. But I expect Mastodon etc only use WebFinger for initial discovery, and then get `preferredUsername` and other info from the AS2 actor, eg the one we serve at `/b-ark.ca`, since custom usernames were still working before this regression.

**Comment by snarfed** [comment]
Argh, never mind, this is the actor code, not Webfinger. I misread. Hrmph.

**Comment by snarfed** [comment]
Confirmed, this fixes the 502 bug here. Thanks again for the sleuthing!

**Comment by fancypantalons** [comment]
Glad I was able to help, and thanks for the quick fix!
