### ISSUE TITLE
Site saying .well-known not setup, but looks like redirects are funcitonal.

### ISSUE THREAD

**Issue by Kongaloosh** [snarfed/bridgy-fed#303]
The user site says that I don't have re-directs and that I need to setup `.well-known`. Looking at the test in `models.py`, I think the test should pass.

When I `get` `host-meta` it returns

```
<?xml version='1.0' encoding='UTF-8'?>
<XRD xmlns='http://docs.oasis-open.org/ns/xri/xrd-1.0'>
  <Link rel='lrdd' type='application/json'
        template='https://fed.brid.gy/.well-known/webfinger?resource={uri}' />
</XRD>

```

Which looks correct to me.

When I request `https://kongaloosh.com/.well-known/webfinger?resource=acct:kongaloosh.com@kongaloosh.com` it returns:

```
<?xml version='1.0' encoding='UTF-8'?>
<XRD xmlns='http://docs.oasis-open.org/ns/xri/xrd-1.0'>

    <Subject>acct:kongaloosh.com@kongaloosh.com</Subject>
    
    <Alias>https://kongaloosh.com/</Alias>
    
    <Alias>https://twitter.com/kongaloosh</Alias>
    
    <Alias>https://www.facebook.com/alex.k.kearney</Alias>
    
    <Alias>https://github.com/Kongaloosh</Alias>
    
    <Alias>https://instagram.com/kongaloosh</Alias>
    
    <Alias>https://ca.linkedin.com/in/alexandrakearney</Alias>
    
    <Link rel='http://webfinger.net/rel/profile-page' type='text/html' href='https://kongaloosh.com/' />
    
    <Link rel='http://webfinger.net/rel/profile-page' type='text/html' href='https://twitter.com/kongaloosh' />
    
    <Link rel='http://webfinger.net/rel/profile-page' type='text/html' href='https://www.facebook.com/alex.k.kearney' />
    
    <Link rel='http://webfinger.net/rel/profile-page' type='text/html' href='https://github.com/Kongaloosh' />
    
    <Link rel='http://webfinger.net/rel/profile-page' type='text/html' href='https://instagram.com/kongaloosh' />
    
    <Link rel='http://webfinger.net/rel/profile-page' type='text/html' href='https://ca.linkedin.com/in/alexandrakearney' />
    
    <Link rel='http://webfinger.net/rel/avatar' type='' href='https://kongaloosh.com/static/img/profile.jpg' />
    

..... etc 
</XRD>
```

All of the links on `https://fed.brid.gy/user/kongaloosh.com` seem functional.

If the issue persists, I'll take a look in the evening MST and see if I can fix it.

**Comment by snarfed** [comment]
Ah, funny. Your redirects are duplicating the query params. eg `https://kongaloosh.com/.well-known/webfinger?resource=acct:kongaloosh.com@kongaloosh.com` currently redirects to `https://fed.brid.gy/.well-known/webfinger?resource=acct:kongaloosh.com@kongaloosh.com?resource=acct:kongaloosh.com@kongaloosh.com`.

You're right though, everything still seems functional. I'm inclined to keep the check strict, but maybe I should relax it?

**Comment by Kongaloosh** [comment]
Oh, good catch! I’ll take a look at the redirect in my config and see if
that fixes the problem.

**Comment by Kongaloosh** [comment]
This isn’t an issue, so I’m closing it.
