### ISSUE TITLE
Question: Does the link to fed.brid.gy have to appear in the post?

### ISSUE THREAD

**Issue by fluffy-critter** [snarfed/bridgy-fed#31]
Let's say I configure my WebMention publishing script to always send a WebMention to fed.brid.gy regardless of whether an actual link to it appears there. Will it work, or does fed.brid.gy's webmention endpoint require that the entry contain a link to it?

Context: I am writing a [simple WebMention conduit for Atom feeds](http://github.com/PlaidWeb/Pushl) and was hoping to make it possible to configure fed.brid.gy as an always-notify endpoint without requiring users to add a link to their template (or manually to entries with a Fediverse link or whatever).

**Comment by snarfed** [comment]
good question! bridgy fed doesn't actually verify that the webmention source page links to it, so you can omit the link.

(this technically violates the webmention spec, but this usage as a trigger instead of a normal mention is pretty unusual anyway, so I'm not worried.)

**Comment by fluffy-critter** [comment]
Thanks! That’s what I figured but I thought I’d make sure first. :)

**Comment by fluffy-critter** [comment]
So, I tried sending synthetic fed.brid.gy pings to entries without a link to it and I got an error 400. Some examples from my logs:

```
INFO:pushl.webmentions:https://webmention.io/beesbuzz.biz/webmention: ping of http://beesbuzz.biz/blog/6287-Webmention-is-here-ActivityPub-maybe-next -> http://publ.beesbuzz.biz/ successful (201)
WARNING:pushl.webmentions:https://fed.brid.gy/webmention: ping of http://beesbuzz.biz/blog/4450-The-Legend-of-Korok-Breath-of-the-Orcastraw -> https://fed.brid.gy/ failed (400)
WARNING:pushl.webmentions:https://fed.brid.gy/webmention: ping of http://beesbuzz.biz/blog/7502-Linus-empathy-and-growth -> https://fed.brid.gy/ failed (400)
WARNING:pushl.webmentions:https://fed.brid.gy/webmention: ping of http://beesbuzz.biz/blog/6796-My-useless-thoughts-on-Microsoft-GitHub -> https://fed.brid.gy/ failed (400)
```

The first one succeeded since it specifically linked to fed.brid.gy but the others did not.

I would rather not require people to add fed.brid.gy links to their templates, although I guess that's not the worst thing to require either.

**Comment by fluffy-critter** [comment]
Hm, actually, I think something else is going on, because even when I add the link to my template and do it on fresh entries it still fails:

```
WARNING:pushl.webmentions:https://fed.brid.gy/webmention: ping of http://beesbuzz.biz/art/drawings/inktober/7953-2018-2-Tranquil -> https://fed.brid.gy/ failed (400)
WARNING:pushl.webmentions:https://fed.brid.gy/webmention: ping of http://beesbuzz.biz/art/drawings/inktober/1533-2016-29-Surprise -> https://fed.brid.gy/ failed (400)
WARNING:pushl.webmentions:https://fed.brid.gy/webmention: ping of http://beesbuzz.biz/art/drawings/inktober/405-2016-27-Creepy -> https://fed.brid.gy/ failed (400)
WARNING:pushl.webmentions:https://fed.brid.gy/webmention: ping of http://beesbuzz.biz/art/drawings/inktober/1011-2017-4-Creatures -> https://fed.brid.gy/ failed (400)
WARNING:pushl.webmentions:https://fed.brid.gy/webmention: ping of http://beesbuzz.biz/art/drawings/inktober/3706-2018-1-Poisonous -> https://fed.brid.gy/ failed (400)
```

Any chance I could find out what's going on here?

**Comment by snarfed** [comment]
hey, glad you're still working on this!

be sure to look at the body of HTTP responses from bridgy fed, especially errors. it will generally tell you what happened. in this case: `No u-in-reply-to, u-like-of, or u-repost-of found in http://beesbuzz.biz/art/drawings/inktober/3706-2018-1-Poisonous`

bridgy fed currently only handles replies and other interactions, not original posts: https://fed.brid.gy/#use . original posts theoretically shouldn't need a bridge like bridgy fed to federate into Mastodon... but in practice that's still finicky at best. details in #18.

**Comment by fluffy-critter** [comment]
Ah, thanks. I hadn’t thought to log the response bodies. What’s puzzling to me, then, is that one of the posts was accepted. :)

My use case for this is less about sending replies on mastodon and more providing a way for folks to subscribe and rely to my blog posts there. Also markdown doesn’t provide a means to (easily) insert a link `rel` and I don’t think that’s the sort of thing most users are going to care about in the first place? So I’m wondering what exactly is the point to this (I mean, for my usage). 

But mostly it was easy for me to add support to fed.bridgy after I already did the work of supporting basic webmentions so it was a good exercise anyway.

**Comment by snarfed** [comment]
right! the initial hope was that original posts could be federated back and forth with just atom and maybe websub, so they wouldn't need an activitypub proxy like bridgy fed. we still _think_ that should be true, but again, it's been very finicky in practice. #18 etc.

on the other hand, replies, likes, boosts, etc do require actual activitypub, so they need a proxy like bridgy fed.

(as for authoring, users clearly do want to reply, like, etc, across many platforms. we don't generally expect or want them to have to hand author markup, via markdown or otherwise. we generally expect dedicated UI support, just like mastodon and the silos.)

**Comment by fluffy-critter** [comment]
If fed.brid.gy is only proxying replies and notifications with the intention that original posts get federated separately (as I do to my normal mastodon account via IFTTT -> twitter -> moa.party, because I love having as many fragile, proprietary links as possible between my data and my data), doesn't that imply that replies/boosts/favorites will come from a different ActivityPub user than original posts?

Oh well, as I wrote in my [ActivityPub rant](https://beesbuzz.biz/blog/2535-ActivityPub-hot-take) I'm not particularly keen on the idea of mixing long-form content up with immediate posts in the first place. :) My primary reason for doing this work was to support WebSub and webmention, and since people keep asking me about ActivityPub support in Publ I thought I could use this to quickly check off a checkbox.

Maybe down the road I'll come up with a more useful means for putting ActivityPub/fed.brid.gy-compatible markup into Publ posts, but for now I think I'll just call it a day.

Anyway, thanks for your help!
