### ISSUE TITLE
When fetching fed.brid.gy/{domain} as get, redirect to user site

### ISSUE THREAD

**Issue by swentel** [snarfed/bridgy-fed#32]
Now you'll get a json file, which is kind of weird.

It might also help with #16 where, if we append the 'source' url of a post as a get parameter in the url property, it would allow us to redirect a post to the right place on the web.
 
So 

- https://fed.brid.gy/realize.be -> redirect to https://realize.be
- https://fed.brid.gy/realize.be?post=https://realize.be/notes/1582 -> https://realize.be/notes/1582

I have some time this week to see if I could experiment with this.

Another option is that we open a request at mastodon to drop the validation of the property url, but I'm not so sure if they will remove it again.

**Comment by snarfed** [comment]
the JSON file that's currently returned is actually the AS2 translation of the site's representative h-card, which is necessary for activitypub.

i don't think i ever found anywhere in the spec(s) that say this explicitly, but AP servers use content negotiation to fetch objects at their `id` and/or` url` with `application/activity+json` (https://www.w3.org/TR/activitystreams-core/#media-type ).

we could probably check `Accept` and redirect requests that _don't_ include `application/activity+json`. are you interested in doing this just for usability? to reduce confusion?

i do think you're right about the approach to #16 of wrapping post object `id`s. i'll go add more there.

**Comment by swentel** [comment]
So, the case would be usability indeed. For instance: 

https://mastodon.social/@swentel/100776214865184909
My reply on there with "Welcome to the club!" If you hover on my nickname 'swentel', the link goes to https://fed.brid.gy/realize.be which would be confusing for people. If you hover over Aaron's link, it goes to a html page on this site.

![mastodon](https://user-images.githubusercontent.com/168466/46786120-37070300-cd34-11e8-9d22-408b4fab92b2.png)

I've been wondering whether we could change that the actual site url, but my guess is that won't be possible, or would require another thing to setup on the user's site, which would be fine for me since you already need to do some steps anyway.

**Comment by snarfed** [comment]
got it. we definitely have made that link point to users' own sites in the past, eg the bridgy fed replies from both me and greg on https://mastodon.technology/@snarfed/3194674 .

i'm hoping we can wrap `id`, but leave `url` pointing to the user's site, and mastodon will use `url`. i'll follow up on #16.

**Comment by swentel** [comment]
So I checked aaron's site. If you fetch https://aaronparecki.com/aaronpk with application/activity+json, then you'll get the AS2 translation. If not, you get the page.

Now, from the comments from that pull request in mastodon, we're 'stuck' with not being able to use a different host for the url, which has another consequence, at least I think so: once you use fed.bridgy to get on the fediverse with your site, you're 'stuck' with that id, and with the fed.bridgy service. 

If for some reason, you decide to shut down the service one day, we won't be able to easily switch that account to another implementation, whether it's an external service, or writing an implementation ourselves.

So, the only way I think to get around that is that the id should be a URL you need to setup at your site. Since fed.bridgy requires a few things already to setup, another step seems fine imho. 

I can think of two options:

1. adding a redirect from domain.tld/fediverse/hello to fed.brid.gy/domain. The name of the url is the brittle part here. 
2. two step phase: you need a url, e.g. /bridgy-fed-discovery-id which returns your fediverse url which you can choose yourself - and where the host of that id matches the host domain - and you set this url as a redirect then

In this case, I can remove that redirect and switch to a different service somewhere else, or even write my own implementation one day.

I hope it makes sense what I'm saying, thinking out loud here :)

this comment also hijacks a bit the original issue request. However, as the url would now live on the user's domain, the user can decide what to respond when a request comes in on that url and fed.brid.gy doesn't have to care at all about redirects for domains or posts.

**Comment by snarfed** [comment]
@swentel this absolutely makes sense! i really appreciate that you've stuck with this for so long, given how much work and research it's taken. thank you!

you're right, if we want to support account migration, we probably need to do something like what you've described. bridgy fed doesn't really support migration right now though, and even mastodon and activitypub themselves don't either, so i don't know that it's a strict requirement.

i'm inclined to start by just wrapping the actor and post ids in fed.brid.gy. we can try that for a while, see what people think, and then maybe revisit migration?

**Comment by swentel** [comment]
> see what people think, and then maybe revisit migration?

Oh yes. I'm totally fine with that. In the end, replies and follows - and also posts as that's a variant of replies, are more important than account migration. Mastodon already allows moving from one instance to another, so, it might probably just become a feature request at mastodon at some point to make it very easy there.

**Comment by snarfed** [comment]
it's up and running! tested with a reply on https://mastodon.social/@swentel/100776214865184909 .

**Comment by swentel** [comment]
confirmed, on same thread, awesome! :)
++
