### ISSUE TITLE
Show photos in HTML feed

### ISSUE THREAD

**Issue by gRegorLove** [snarfed/bridgy-fed#328]
Some posts in [my HTML feed](https://fed.brid.gy/user/gregorlove.com/feed) don't include the photo from the Mastodon post, e.g [this original post](https://kolektiva.social/@chadloder/109441305426576934). The Atom version appears to strip the `<img>` and show the alt text.

**Comment by snarfed** [comment]
Thanks for reporting! We're probably not converting AS2 attachments, eg:

```json
    "attachment": [
      {
        "type": "Document",
        "mediaType": "image/jpeg",
        "url": "https://assets.tech.lgbt/media_attachments/files/109/427/909/055/512/486/original/59cb07fb414c709c.jpg",
        "name": null,
        "blurhash": "ULE3C*j[IUt700WBofRjxuIURjt7Rjt7xuay",
        "width": 500,
        "height": 653
      }
    ],
```

**Comment by snarfed** [comment]
Why are Mastodon's AS2 images type `Document` and not type `Image`?! https://www.w3.org/TR/activitystreams-vocabulary/#dfn-attachment

**Comment by snarfed** [comment]
OK fine, I'll sniff `mediaType` and override `objectType`.

**Comment by snarfed** [comment]
Fixed. Thanks again!
