### ISSUE TITLE
Redirect follow mf2 rendered pages to follower profiles

### ISSUE THREAD

**Issue by aciccarello** [snarfed/bridgy-fed#336]
I'm seeing webmentions from activity Bridgy Fed is handling. However I'm struggling to understand what the activity was. I think I've seen some discussion of the confusing URLs from Mastodon but I'm not sure how to translate it to see what was the activity that happened.

The mention shows up as: 
> fed.brid.gy mentioned / ()
https://fed.brid.gy/render?source=https%3A%2F%2Ftoot.cafe%2F7d9f6700-754e-4596-af3f-3f55768c9764&target=https%3A%2F%2Fwww.ciccarello.me%2F mentioned https://www.ciccarello.me/

The linked URL references my toot.cafe account but has a http-equiv="refresh" to go to the mastodon activity permalink (which I think doesn't actually exist). However I don't see any activity on https://fed.brid.gy/user/ciccarello.me and I don't think I made any explicit interactions.

What was this interaction that bridgy fed is sending a webmention about? Is it a delivery notification? Is there some way to make the webmention more helpful or perhaps not send a webmention at all?

**Comment by snarfed** [comment]
Looks like this was the follow from @aciccarello@toot.cafe. You're right, the redirect target isn't browser-visible, but I think the mf2 on the BF page is correct, it has `u-follow-of` `https://www.ciccarello.me/` and an actor with the profile info from https://toot.cafe/@aciccarello.

It's possible there's another www/no-www bug here, maybe in BF's mf2 rendering, I'll take a look. I resent this one manually to no-www after BF originally (incorrectly) handled it for www, so it may just be that. Will see.

**Comment by aciccarello** [comment]
Ah, I see the u-follow-of now. Thanks for helping me understand. Maybe I would be better off plugging the URL into a microformats parser when I am looking at those. I also think the timing of you manually triggering the mention also threw me off. 😁 

I wonder if activities without an actual target shouldn't have the http-equiv="refresh"

**Comment by snarfed** [comment]
Maybe! Or I should just always find a reasonable, human-visible URL to redirect to, maybe the follower profile in this case.

**Comment by snarfed** [comment]
Done!
