### ISSUE TITLE
Add mention tags in replies

### ISSUE THREAD

**Issue by swentel** [snarfed/bridgy-fed#34]
[note, last issue I open, all other things are fine ;)]

I mentioned this in https://github.com/snarfed/bridgy-fed/issues/16#issuecomment-424803380 already. When you reply to a post on mastodon, this post can optionally show up in your notifications column (it's a setting). You need to add a mention tag in the object property, e.g.

```
[tag] => Array
                (
                    [0] => stdClass Object
                        (
                            [type] => Mention
                            [href] => https://mastodon.social/users/swentel
                            [name] => @swentel
                        )

                )
```

I guess we can just automatically add the user you're replying to as a mention tag as a first step.
I think I should be able to get that coded, so give a few days first :)

(edit - removed the code example, since that's for salmon, ignore that part)

**Comment by snarfed** [comment]
huh, interesting. so for AP, if we deliver a reply to a user's inbox, and its `inReplyTo` is a post from that user, the reply still doesn't show up in their notifications? adding a mention of their username seems...wrong somehow, if it's not actually there, right? if this is the expected way with AP, i'm ok with it, but i'm surprised it's necessary.

**Comment by swentel** [comment]
So the post shows up in the timeline, that's good at least. 
I'll do some research if this Mention tag is specific to mastodon or not, if so, then this will be a won't fix sadly enough. ikes and reposts do show up in your notifications column, so it potentially looks bad :)

**Comment by swentel** [comment]
So this is all too confusing. There is a thread on w3c to add it, see https://github.com/w3c/activitypub/issues/235. 

If you go to https://www.w3.org/TR/activitystreams-vocabulary/#microsyntaxes and scroll a bit down, you will find following.

> In the case a publisher wishes to indicate a mention without an associated notification, the publisher can use the Mention object type as a value of the tag property. 

With an example underneath.

There's also an explicit Mention type as well, but that's too silly to send imo, see https://www.w3.org/TR/activitystreams-vocabulary/#dfn-mention (and I'm pretty sure Mastodon ignores it)

And that same section, above the previous quote, there's also this (with an example)

> The to property indicates that the user "@sally" is to be considered part of the primary audience of the note and should therefore receive notification

This is something I saw in the request that fed.brid.gy does: it uses cc, but not to. So maybe mastodon will send a notification if the the 'primary' user (basically, the main user of the inbox) is in the 'to' property. I'm going to check that one out, that would probably make the change a bit easier.

**Comment by swentel** [comment]
So tested a lot of variations to get a notification (and skimmed mastodon code as well), but there doesn't seem to be another way of getting a mention in the notifications timeline, except for the Mention tag.

I'm fine if you don't want to implement it though :)

**Comment by snarfed** [comment]
thank you for the investigation! i'm totally ok with it if it's necessary, especially if we include a comment in the code saying as much and linking to this issue.

**Comment by swentel** [comment]
So, I gave it a shot. I'm entirely not sure whether mention['href'] = target.get('attributedTo') is right, but I think the rest should be fine. Didn't want to create a pull request, because I couldn't even run it (at least, all the code in webmention, tested the other lines in a separate python file heh.

```
diff --git a/common.py b/common.py
index 0059271..daee7a1 100644
--- a/common.py
+++ b/common.py
@@ -254,6 +254,13 @@ def postprocess_as2(activity, target=None, key=None):
                     'Only using the first: %s' % in_reply_tos[0])
             activity['inReplyTo'] = in_reply_to[0]
 
+       tags = []
+       mention = {}
+       mention['href'] = target.get('attributedTo')
+       mention['type'] = 'Mention'
+       tags.append(mention)
+       activity['tag'] = tags
+
     # activity objects (for Like, Announce, etc): prefer id over url
     obj = activity.get('object', {})
     if obj:
```

**Comment by snarfed** [comment]
Tested this again just now, 5y later, it's still true, Mastodon still requires an explicit `Mention` to make a reply show up in the original post's author's notifications. 🤷
