### ISSUE TITLE
Post HTML

### ISSUE THREAD

**Issue by tmichellemoore** [snarfed/bridgy-fed#342]
Hello,
What is the proper format of a post? I have been using the model from the documentation here:  [https://fed.brid.gy/docs#how-post](https://fed.brid.gy/docs#how-post) and using my own data. When I do this, the link on the Brid.gy feed page points to Brid.gy and not the original post. I am using WordPress and saw one hit here that seems to relate. It mentioned that the u-url is not explicitly listed. I experimented with adding this to the entry and that didn't work either. Can you provide an example if the following is not sufficient? 
Thank you!
 
<div class="h-entry">
  <p class="e-content">Sample text</p>
  <a href="https://fed.brid.gy/"></a>
</div>

**Comment by snarfed** [comment]
Hmm! What do you mean by "on the Brid.gy feed page"? Do you mean https://mastodon.social/@tmichellemoore.com@tmichellemoore.com ? Could you post a link to an example?

**Comment by tmichellemoore** [comment]
Hello, It is this page: [https://fed.brid.gy/user/tmichellemoore.com](https://fed.brid.gy/user/tmichellemoore.com). That link is pointing to https://fed.brid.gy/user/Testing%20–%20Fediverse%207.10.2. (Note: I turned off the redirection after I saw this.)
![brid-gy](https://user-images.githubusercontent.com/7757648/206914793-d573b8e4-e22b-447b-93d4-2ef6b7287014.jpg)

**Comment by snarfed** [comment]
Thanks! And ugh, sorry, this is due to the [implied u-url property](https://microformats.org/wiki/microformats2-implied-properties#hyperlink_and_url_property) behavior of microformats2 parsers, which is usually fine but sometimes confusing, like here.

Specifically, your posts don't have a `u-url` permalink, which is unusual, and when microformats parsers see that, they default to assuming the first link in the `h-entry` is the `u-url`. That usually works ok because most posts do have permalinks, even if they don't have the `u-url` class on them, but yours don't.

As a short term workaround, if you turn on permalinks in your WordPress theme, that should fix this!

**Comment by snarfed** [comment]
Looks like this was discussed and improved in https://github.com/microformats/microformats2-parsing/issues/36, which is good, but not quite enough to prevent/fix this case.

**Comment by tmichellemoore** [comment]
One more question. Can you place a sample of the html for a plan post, not a reply or like, plus  the solution above here? I see the one on the Help page, but that’s a reply.

**Comment by snarfed** [comment]
Oh sorry! That was supposed to be https://fed.brid.gy/docs#how-post, I didn't mean for it to be a reply. I'll fix that now, thanks for the catch.

**Comment by tmichellemoore** [comment]
I have set the permalinks to what I want, but don’t understand what “turning on permalinks in your WordPress theme” means. Can you point me to a reference for this? Thank you!

**Comment by snarfed** [comment]
Ah sorry, I just meant links to the current post on posts themselves. For example, the "December 6, 2022" link on https://snarfed.org/2022-12-06_48532

**Comment by tmichellemoore** [comment]
Thank you! I will work with all of these tips.

**Comment by snarfed** [comment]
For posterity for us debugging this, example problematic HTML and mf2 here from https://enchantchristmas.com/san-jose-ca-paypal-park/ :

```html
<div class="h-entry">
  <p class="e-content">Testing 7.18.1</p>
  <a href="https://fed.brid.gy/"></a>
</div>
```

```json
{
    "type": [
        "h-entry"
    ],
    "properties": {
        "content": [
            {
                "html": "Testing 7.18.1",
                "value": "Testing 7.18.1",
                "lang": "en-US"
            }
        ],
        "url": [
            "https://fed.brid.gy/"
        ]
    },
    "lang": "en-US"
}
```

**Comment by tmichellemoore** [comment]
Designating the u-url fixed the issue. I will now try to use the block editor blocks instead of HTML, which is my ultimate goal. In the link above, can you use this URL instead - https://tmichellemoore.com/blog/testing/testing-7-18/
I am cleaning up my feed from all of this testing. :-)

**Comment by snarfed** [comment]
@tmichellemoore I've updated the docs with another workaround for preventing this problem: add a `u-bridgy-fed` class to the link. https://fed.brid.gy/docs#how-post

**Comment by tmichellemoore** [comment]
@snarfed I will try that in the link later. Thank you!
