### ISSUE TITLE
Validated Content with Fed.Brid.gy Link Won't Publish

### ISSUE THREAD

**Issue by tmichellemoore** [snarfed/bridgy-fed#343]
Hello,
Yesterday, I successfully published a post to Mastodon using Bridge Fed and the updated HTML example from [https://github.com/snarfed/bridgy-fed/issues/342](https://github.com/snarfed/bridgy-fed/issues/342) in WordPress.  I then went back to WordPress to try to create a post with blocks with the proper microformat classes  and a custom html link to Brid.gy. 

- The post - [https://tmichellemoore.com/blog/testing/testing-blocks-with-divs-and-classes-with-brid-gy-2-0/](https://tmichellemoore.com/blog/testing/testing-blocks-with-divs-and-classes-with-brid-gy-2-0/)
- The Validator seems to indicate this is Valid  - https://indiewebify.me/validate-h-entry/?url=https%3A%2F%2Ftmichellemoore.com%2Fblog%2Ftesting%2Ftesting-blocks-with-divs-and-classes-with-brid-gy-2-0%2F
-  Bridgy Fed - Does not detect the post. - [https://fed.brid.gy/user/tmichellemoore.com](https://fed.brid.gy/user/tmichellemoore.com)

Do I have to use HTML all of the time or can you see anything that might prevent Bridgy Fed from detecting this post?

**Comment by snarfed** [comment]
Hi! I don't see that your site ever sent Bridgy Fed a webmention for this post to trigger publishing it. I do see that the post has a link to https://fed.brid.gy/ . Did you maybe turn off your webmention plugin, or something similar?

**Comment by tmichellemoore** [comment]
No, it’s on. The only difference in this post that didn’t work is that I used blocks and added the classes on the div. It worked fine with adding the custom HTML block and the sample from 342. I tested it a few times.

**Comment by tmichellemoore** [comment]
Sorry, let me clarify. I started from scratch. It wasn’t after. I try to make a new post for each test. But just to make sure I am going to test it again from scratch. I will report back in a bit.

**Comment by tmichellemoore** [comment]
I introduced my own error, I setup a custom post type to test these items, turned on support for them in each plugin and they don't publish in Brid.gy. My mistake. After going back in and testing with the regular Post type, Brid.gy Fed works with my blocks in this post > [https://tmichellemoore.com/blog/testing-2022-12-12-1047-testing-brid-gy-with-blocks-divs-and-classes/](https://tmichellemoore.com/blog/testing-2022-12-12-1047-testing-brid-gy-with-blocks-divs-and-classes/ )

I also tested adding the e-content to one paragraph in this post and it publishes the post title with the link, not the content inside - [https://tmichellemoore.com/blog/testing-2022-12-12-1056-testing-brid-gy-with-blocks-divs-and-classes-para-e-content/](https://tmichellemoore.com/blog/testing-2022-12-12-1056-testing-brid-gy-with-blocks-divs-and-classes-para-e-content/)

So this gets back to the original question before I introduce the error which is - Is the post supposed to look like this in Mastodon with the post title and a link to fed.brid.gy or should it have the content also?
![2022-12-12_10-47-a](https://user-images.githubusercontent.com/7757648/207091794-1d00f472-0409-4f1d-a4d5-eaef0300c375.jpg)

**Comment by snarfed** [comment]
You're right, this is somewhat surprising behavior, and a somewhat open question.

We think about two broad types of text-based posts, [notes](https://indieweb.org/note) and [articles](https://indieweb.org/article). Notes are short, eg tweets and mastodon toots; articles are blog posts. The main way we differentiate is whether there's a title: articles generally have titles, notes don't. (See [post type discovery](https://indieweb.org/post-type-discovery) for the gory details.)

Fediverse posts are primarily notes, not articles and fediverse apps like Mastodon are primarily designed to display notes. Given that, Bridgy Fed currently posts the full contents of notes into the fediverse, but only the title and link for articles. (Normal Bridgy does the same thing; details [in the docs](https://brid.gy/about#microformats).)

**Comment by snarfed** [comment]
More ancient background in https://github.com/snarfed/bridgy/issues/228

**Comment by datakurre** [comment]
@snarfed Did I understand correctly: if h-entry has only e-content, but no p-name, it is a note?

**Comment by snarfed** [comment]
@datakurre yes! Steps 10 through 15 in https://indieweb.org/post-type-discovery#Algorithm

**Comment by tmichellemoore** [comment]
@snarfed I believe I added a p-name. I will remove it and see what the behavior is.

**Comment by snarfed** [comment]
Hi Michelle! In general, this all looks like expected Bridgy Fed behavior. Key points:

- If your post has a `p-name`, BF currently published the title and link to the post, as discussed earlier. The visible "fed.brid.gy" link redirects to your site, but I can look into dropping that redirect and linking directly instead!
- If your post _doesn't_ have a `p-name`, BF posts everything inside `e-content`, and doesn't add a link. Mastodon's own permalink for the post, eg the "33m" and "5h" in the top right of these screenshots, is the link to your site.

Re custom post types, I'm not too familiar with them, I assume they're a WordPress thing? BF doesn't know anything about them, it only sees the mf2 in your HTML. #wordpress in [chat](https://indieweb.org/discuss) and @dshanske may be able to help more with WordPress!

**Comment by snarfed** [comment]
I misspoke a bit here. The article vs note distinction here is true, but a key point is that Mastodon is the one making that distinction here, not Bridgy Fed. Bridgy Fed always seds your full posts to Mastodon, with content and name/title and type (Article vs Note vs others). Mastodon then shows the full contents for Notes and most other types, eg replies, but only the title and link for Articles.

The link is taken from the underlying url field, which Mastodon currently requires to be Bridgy Fed's, ie fed.brid.gy. More background: https://github.com/tootsuite/mastodon/pull/6219#issuecomment-429142747, https://github.com/snarfed/bridgy-fed/issues/16#issuecomment-424799599. Ugly, and unfortunate, granted, and sad that we don't have much control over it after all.

**Comment by tmichellemoore** [comment]
OK, thank you @snarfed, this explains it. Can I leave this ticket open to see if my custom post type issue can be looked at or should I create a separate ticket somewhere else?

**Comment by snarfed** [comment]
Welcome! The post type issue is a WordPress thing, so you'll want to talk to other people elsewhere, maybe @dshanske or #wordpress in [chat](https://indieweb.org/discuss).
