### ISSUE TITLE
Don't send webmentions to websites that support ActivityPub

### ISSUE THREAD

**Issue by aaronpk** [snarfed/bridgy-fed#348]
Scenario:

* My website supports ActivityPub. 
* I write a post, send it to my AP followers. 
* One of my followers uses Bridgy Fed. 
* Someone on Mastodon replies, and their server sends the reply to my website's inbox, and also delivers it to the Bridgy Fed inbox.
* Bridgy Fed fetches the Mastodon post, sees that it's in reply to my post, and sends my website a webmention with a fed.brid.gy proxy URL of the Mastodon post

This causes my website to have received the same post as an ActivityPub reply and as a webmention.

I _could_ update my website to handle de-duping these, but it also seems unnecessary that Bridgy Fed is sending me a webmention when my site already supports ActivityPub.

I think the best middle ground here is to have BF try to find out if a website supports ActivityPub, and not send a webmention in that case.

**Comment by snarfed** [comment]
Thanks for filing! [Original chat discussion here.](https://chat.indieweb.org/dev/2022-12-16#t1671226563645900) Interesting point here is that aaronparecki.com isn't a direct Bridgy Fed user, but Bridgy Fed (and Bridgy classic) are _promiscuous_, ie they send webmentions liberally to any target site they come across, including this one.

The middle ground of checking for AP support via Webfinger sounds totally reasonable here. It'll take a bit of effort, but definitely doable!

**Comment by snarfed** [comment]
Closing in favor of #911, that should provide for this.
