### ISSUE TITLE
fix AP => webmention

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#35]
...for new mastodon AP activities with embedded objects, and new fed.brid.gy-wrapped ids (#16).

i attempted the first part in 2ffd10306f071bb3e013e8d7ea6bd5480d37eb33. we now need to unwrap target post URLs and use mastodon HTML URLs instead of AS2 URLs as the source.

eg the AS2 reply activity from mastodon below, for https://mastodon.social/users/swentel/statuses/100895743653130715, resulted in a bridgy fed webmention with AS2 source  https://mastodon.social/users/swentel/statuses/100895743653130715/activity and wrapped target https://fed.brid.gy/r/https://realize.be/reply/content/1594 . more details on https://webmention.io/realize.be/webmention/kfzxXXvcsK4CZAUczQii . cc @swentel.

```json
{
  "@context": "...",
  "id": "https://mastodon.social/users/swentel/statuses/100895743653130715/activity",
  "type": "Create",
  "actor": "https://mastodon.social/users/swentel",
  "published": "2018-10-14T19:54:29Z",
  "to": [
    "https://mastodon.social/users/swentel/followers"
  ],
  "cc": [
    "https://www.w3.org/ns/activitystreams#Public",
    "https://fed.brid.gy/realize.be"
  ],
  "object": {
    "id": "https://mastodon.social/users/swentel/statuses/100895743653130715",
    "type": "Note",
    "summary": null,
    "inReplyTo": "https://fed.brid.gy/r/https://realize.be/reply/content/1594",
    "published": "2018-10-14T19:54:29Z",
    "url": "https://mastodon.social/@swentel/100895743653130715",
    "attributedTo": "https://mastodon.social/users/swentel",
    "to": [
      "https://mastodon.social/users/swentel/followers"
    ],
    "cc": [
      "https://www.w3.org/ns/activitystreams#Public",
      "https://fed.brid.gy/realize.be"
    ],
    "sensitive": false,
    "atomUri": "https://mastodon.social/users/swentel/statuses/100895743653130715",
    "inReplyToAtomUri": "https://fed.brid.gy/r/https://realize.be/reply/content/1594",
    "conversation": "tag:mastodon.social,2018-09-23:objectId=55290633:objectType=Conversation",
    "content": "<p><span class=\"h-card\"><a href=\"https://fed.brid.gy/r/http://realize.be\" class=\"u-url mention\">@<span>realize.be</span></a></span> That&apos;s pretty awesome!</p>",
    "contentMap": {
      "en": "<p><span class=\"h-card\"><a href=\"https://fed.brid.gy/r/http://realize.be\" class=\"u-url mention\">@<span>realize.be</span></a></span> That&apos;s pretty awesome!</p>"
    },
    "attachment": [],
    "tag": [
      {
        "type": "Mention",
        "href": "https://fed.brid.gy/realize.be",
        "name": "@realize.be@realize.be"
      }
    ]
  },
  "signature": "...",
}
```

**Comment by snarfed** [comment]
ugh. fixing these bugs isn't enough. with the new URL wrapping, we now can't just send a webmention from a mastodon post URL directly to a user's site, since the `u-url`s are now wrapped in `fed.brid.gy`, so they don't match the original post permalink.

soooo we need to proxy the mastodon HTML, unwrap those links, and serve a proxy page with that transformed HTML ourselves, like we currently do for likes, reposts, etc. sigh.

**Comment by snarfed** [comment]
ok, looking good. example: https://webmention.io/realize.be/webmention/hG654HOgobymY54pMaNS . would show up on https://realize.be/reply/content/1594 . @swentel, does your site currently render webmentions it receives? it's not visible there yet.

**Comment by swentel** [comment]
I do render, but after moderation. I got it, awesome ! I removed that exact webmention/comment though as the toot on mastodon didn't exist anymore. 

I tested with new ones, but there might be a weird side effect still: compare https://mastodon.social/@swentel/100915134560645668 with https://realize.be/reply/content/1594

The last two comments are repeated for some reason after I replied with "Don't exaggerate now" as a mastodon user. It itsn't /that/ problematic, I should probably just add some code to the webmention webhook in the module that can detect identical webmentions.

(one other very cool fact about replying is that the conversation more or less happens in real time, that's very very awesome!)

**Comment by snarfed** [comment]
woo, good news!

do the repeated wms have the same source and target URLs? AP says inbox deliveries (and requests in general) may be repeated, so they should be idempotent and de-duped: https://www.w3.org/TR/activitypub/#inbox . webmention actually says the same thing, so you probably want to do that in your webmention receiver even independent of bridgy fed.

**Comment by snarfed** [comment]
tentatively closing!

**Comment by swentel** [comment]
Yes, the source urls and target are the same. Just added the identical checks, so it's fine! :)
