### ISSUE TITLE
outbound AP Follows from tmichellemoore.com failing inbox delivery with "Unexpected object type for key"

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#370]
We started seeing outbound AP inbox deliveries of `Follow` activities for tmichellemoore.com fail with HTTP 401 "Unexpected object type for key https://fed.brid.gy/tmichellemoore.com" recently. First instance in logs is 1/4 22:03 PT, seen from a number of instances including mstdn.social, toot.community, and masto.ai. Only for that domain, only `Follow`s. Oddly specific. Apologies @tmichellemoore!

**Comment by snarfed** [comment]
This accounts for most of @tmichellemoore's follows since 1/4, but not all. eg [here's one to mastodon.social on 1/5 that succeeded](https://fed.brid.gy/log?start_time=1672921561&key=https://tmichellemoore.com/blog/follow-of-britzmastodon-social/%20https://mastodon.social/@Britz&module=).

All of the affected instances I looked at are on 4.0.2, but mastodon.social is too. I don't know for sure that it was on 1/5, but I expect so, since it generally upgrades quickly, and 4.0.2 was released in Nov.

**Comment by snarfed** [comment]
Mastodon code, in main as of today: https://github.com/mastodon/mastodon/blob/d66dfc7b3c1b62a0d5276387ea8745da598afacc/app/services/activitypub/fetch_remote_key_service.rb#L29

**Comment by snarfed** [comment]
Well that's odd, https://fed.brid.gy/tmichellemoore.com has neither `type: Person` nor `publicKey`. That's broken.

```json
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "attachment": [
    {
      "type": "Image",
      "url": "https://tmichellemoore.com/wp-content/uploads/2022/11/DSC04496.jpg"
    }
  ],
  "attributedTo": [
    {
      "id": "https://fed.brid.gy/tmichellemoore.com",
      "name": "T Michelle Moore",
      "preferredUsername": "tmichellemoore.com",
      "type": "Person",
      "url": "https://fed.brid.gy/r/https://tmichellemoore.com/"
    }
  ],
  "endpoints": {
    "sharedInbox": "https://fed.brid.gy/inbox"
  },
  "followers": "https://fed.brid.gy/tmichellemoore.com/followers",
  "following": "https://fed.brid.gy/tmichellemoore.com/following",
  "id": "https://fed.brid.gy/tmichellemoore.com",
  "image": {
    "type": "Image",
    "url": "https://tmichellemoore.com/wp-content/uploads/2022/11/DSC04496.jpg"
  },
  "inbox": "https://fed.brid.gy/tmichellemoore.com/inbox",
  "outbox": "https://fed.brid.gy/tmichellemoore.com/outbox",
  "preferredUsername": "tmichellemoore.com",
  "summary": "Project Manager | Photographer",
  "to": [
    "https://www.w3.org/ns/activitystreams#Public"
  ],
  "url": "https://fed.brid.gy/r/https://tmichellemoore.com/"
}
```

**Comment by snarfed** [comment]
Got it. tmichellemoore.com's h-card has no `name`, so `mf2util.post_type_discovery` returns `org`, which we don't know how to handle, instead of `person`.

**Comment by tmichellemoore** [comment]
Hi @snarfed, Can you translate some of your items above? And regarding the h-cars...Mine seems to work in different ways, but on the one that I placed on my home page footer and place on my blog posts, my name is in there. I can check to make sure but I removed the org a few weeks ago. I am not sure if the IndieWeb plug-in's h-card does anything for my site since I don't use the classic editor, but it has added fields to  my User. I also have a mystery of why the h-card in the footer doesn't work on the blog posts. (I know this is a different plug-in's topic.)

**Comment by snarfed** [comment]
@tmichellemoore sorry! Everything here is just my own working notes, not anything you need to worry about. This is a BF bug, I should have it fixed soon.

**Comment by tmichellemoore** [comment]
@snarfed Got it!! Thank you!

**Comment by tmichellemoore** [comment]
@snarfed  I have a confession. I was just experimenting with my h-card and I had an organization. lol
