### ISSUE TITLE
support Misskey

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#375]
https://join.misskey.page/

**Comment by snarfed** [comment]
I federated [this like](https://snarfed.org/2023-01-18_luna-nova) of [this post](https://akko.wtf/notice/ARP7mWTNZxbJAzPTIe) on akko.wtf (running backend v[3.5.0-12-g63f2d1cb](https://akkoma.dev/AkkomaGang/akkoma/commit/63f2d1cb)), and got an HTTP 500 error with body `{"errors":{"detail":"Internal server error"}}` on inbox delivery to https://akko.wtf/users/rei/inbox. Not much help there. [Bridgy log here.](https://fed.brid.gy/log?start_time=1674082460&key=https://snarfed.org/2023-01-18_luna-nova%20https://akko.wtf/objects/8044263c-b1d3-495a-9a43-131bee571c80&module=)

Akkoma is a fork of Pleroma, and this is the same error we got from Pleroma in https://github.com/snarfed/bridgy-fed/issues/12#issuecomment-1385812088, which makes sense.

I'm guessing it choked on some part of the AS2 that's a composite object when it expects a string, maybe `actor`. Full AS2 object we sent:

```json
{
  "published": "2023-01-18T14:54:09-08:00",
  "content": "likes <a class=\"u-like u-like-of\" href=\"https://akko.wtf/notice/ARP7mWTNZxbJAzPTIe\">Luna Nova</a>",
  "url": "https://fed.brid.gy/r/https://snarfed.org/2023-01-18_luna-nova",
  "actor": {
    "url": "https://fed.brid.gy/r/https://snarfed.org/",
    "image": {
      "url": "https://secure.gravatar.com/avatar/947b5f3f323da0ef785b6f02d9c265d6?s=96&d=blank&r=g",
      "type": "Image"
    },
    "type": "Person",
    "name": "Ryan Barrett",
    "icon": {
      "url": "https://secure.gravatar.com/avatar/947b5f3f323da0ef785b6f02d9c265d6?s=96&d=blank&r=g",
      "type": "Image"
    },
    "id": "https://fed.brid.gy/snarfed.org",
    "preferredUsername": "[snarfed.org](http://snarfed.org/)"
  },
  "@context": "https://www.w3.org/ns/activitystreams",
  "type": "Like",
  "object": "https://akko.wtf/objects/8044263c-b1d3-495a-9a43-131bee571c80",
  "id": "https://fed.brid.gy/r/https://snarfed.org/2023-01-18_luna-nova",
  "cc": [
    "https://akko.wtf/users/rei",
    "https://www.w3.org/ns/activitystreams#Public",
    "https://akko.wtf/users/rei/followers"
  ],
  "to": [
    "https://www.w3.org/ns/activitystreams#Public"
  ]
}
```

**Comment by snarfed** [comment]
I federated [this like](https://snarfed.org/2023-01-18_rss-slippy) of [this post](https://slippy.xyz/notes/9a484gym1e) on slippy.xyz (running v13.0.0), and it worked. Inbox delivery to `https://slippy.xyz/users/85l270n95u/inbox` got an HTTP 202 response, [Bridgy Fed log here.](https://fed.brid.gy/log?start_time=1674083547&key=https://snarfed.org/2023-01-18_rss-slippy%20https://slippy.xyz/notes/9a484gym1e&module=)

I don't see the like on the post yet though, so I don't know for sure that it made it all the way through.

**Comment by snarfed** [comment]
Reopening, looks like this didn't work after all. Tried again with [this reply](https://snarfed.org/2023-06-05_gitea_blog_bot-slippy) on the same post just now, got the same 202 response, but it hasn't actually showed up yet.

**Comment by snarfed** [comment]
Filed with Misskey in https://github.com/misskey-dev/misskey/issues/10963

**Comment by Mirakelor** [comment]
Good News! Succeeded to display article on Misskey !!!
![image](https://github.com/snarfed/bridgy-fed/assets/63326519/a8feb393-2694-4dca-857a-837b4776cba6)
on https://submarin.online/notes/9gznv9c08u
Bad news is that i don't know how it worked...

**Comment by snarfed** [comment]
Woo, #442 fixed this! Tried another reply to that ^ original post just now and it worked.
