### ISSUE TITLE
Incoming requests from the fediverse once you're on it

### ISSUE THREAD

**Issue by swentel** [snarfed/bridgy-fed#38]
This is more of a tracking issue. Since I joined the fediverse, my site gets a lot of requests on certain paths. I want to document them here first to begin with, and then maybe eventually see if something needs to be done (e.g. more redirects from in .htaccess to bridgy fed to handle things) . A simple reference on the homepage of bridgy fed would be fine for me as well as an end result :)

https://fediverse.network/info contains some info what it crawls for and which endpoints it looks for. 

Path | Method | Example referer | Information
------------ | ------------- | ------------- | -------------
/.well-known/nodeinfo | GET | Friendica 'The Tazmans Flax-lily' 2018.12-dev-1288; https://pirati.ca / Friendica 'Asparagus' 3.5.4-1234;  | Figured out it had something todo with the fediverse while looking at pixelfed. More background on that issue: https://github.com/pixelfed/pixelfed/issues/8 What's interesting is that it's from Friendica, something I never interacted with (couple of different urls from there)
/api/v1/instance | GET | MastodonInstances (https://instances.social), Friendica 'The Tazmans Flax-lily' 2018.12-dev-1289; https://pirati.ca | Seems to be a site that allows you to 'choose' the right instance for you. But got it from friendica too
/api/gnusocial/version.json | GET | Friendica 'The Tazmans Flax-lily' 2018.12-dev-1288; https://pirati.ca | Friendica
/api/statusnet/version.json | GET | Friendica 'The Tazmans Flax-lily' 2018.12-dev-1288; https://pirati.ca | Friendica
/siteinfo.json | GET | Friendica 'The Tazmans Flax-lily' 2018.12-dev-1288; https://pirati.ca | Friendica
/statistics.json | GET | Friendica 'The Tazmans Flax-lily' 2018.12-dev-1288; https://pirati.ca | Friendica
/api/v1/timelines/tag/fail | GET | Python-urllib/3.5 | No idea if it's related with the fediverse yet, but could be.
/poco | GET | Friendica 'Asparagus' 3.5.4-1234; https://friendica.obscuritus.ca | Friendica - no clue what this would look for
/api/statusnet/config | GET | fediverse.network crawler (https://fediverse.network/info root@fediverse.network) | search enging
/api/v1/config | GET | fediverse.network crawler (https://fediverse.network/info root@fediverse.network) | crawler

This list is of requests which didn't have a referer, but feel like fediverse related.

- /api/statuses/public_timeline.json
- /api/meta (POST request)
- /nodeinfo/2.0.json
- /api/v1/instance/peers
- /api/statusnet/config.json
- .well-known/autoconfig/mail/config-v1.1.xml

**Comment by snarfed** [comment]
interesting indeed. thanks for tracking!

**Comment by snarfed** [comment]
@fluffy-critter has been seeing these on and off too. https://queer.party/@fluffy/102482645725569184

**Comment by snarfed** [comment]
I don't think we ended up with anything actionable here on Bridgy Fed's end. Tentatively closing, but feel free to reopen!
