### ISSUE TITLE
Article link should be original URL (not bridgy-fed redirect)

### ISSUE THREAD

**Issue by aciccarello** [snarfed/bridgy-fed#391]
Articles are shared as a title and a URL. Currently the URL is a fed.brid.gy redirect URL like https://fed.brid.gy/r/https://www.ciccarello.me/blog/2023/01/21/birding-in-2021/ ([post link for logged in users](https://toot.cafe/@anthony@ciccarello.me/109758431796269986]). I understand these are needed to have the same origin when sending posts via AP, but I imagine they aren't needed in the post content.

<img width="593" alt="mastodon web client screenshot showing post with blog title and fed.brid.gy link" src="https://user-images.githubusercontent.com/11273838/215243026-e168305f-1d20-4b22-8329-a69d859dc6ec.png">

Could Article posts use the original URL?

**Comment by snarfed** [comment]
Surprisingly, that whole rendering for articles is Mastodon's doing, not ours: https://fed.brid.gy/docs#which-parts

**Comment by aciccarello** [comment]
Bah, Mastodon is strange. Sorry for blaming bridgy.
