### ISSUE TITLE
Cloudflare bypass

### ISSUE THREAD

**Issue by selfagency** [snarfed/bridgy-fed#399]
I'm trying to use Bridgy Fed on my site but when I submit my URL to `https://fed.brid.gy/web-site`, it comes back with the code for the CloudFlare challenge page, which is what it throws at bots.

![CleanShot 2023-02-02 at 23 29 53](https://user-images.githubusercontent.com/2541728/216512796-83b8bc8f-bc85-413c-adaf-7a5e5e9c0e26.png)

I tried using the referrer address to bypass the challenge, but it didn't seem to work, which I assume is a result of making a request via your application's backend.

![CleanShot 2023-02-02 at 23 30 23](https://user-images.githubusercontent.com/2541728/216512848-418f0420-79f6-43bb-b496-09af800892e2.png)

Is there an origin IP or anything else I could use as a filter, and if not, could you add a referrer header or something else to make bypass possible?

**Comment by snarfed** [comment]
Oof, that error page is ugly, sorry about that. And yes! Bridgy Fed's `User-Agent` is `Bridgy Fed (https://fed.brid.gy/)`, can you allowlist that?

**Comment by selfagency** [comment]
Sadly whitelisting the user agent didn't seem to solve it.

**Comment by selfagency** [comment]
Figured it out—I had to disable bot detection.
