### ISSUE TITLE
Follow and unfollow UI don't respect User.use_instead

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#403]
Reported by @jamietanna in https://github.com/snarfed/oauth-dropins/pull/286

**Comment by snarfed** [comment]
@jamietanna I think I've fixed this, mind testing when you get a chance?

**Comment by jamietanna** [comment]
Unfortunately not, still looks the follow is being added to jvt.me

**Comment by snarfed** [comment]
Argh, sorry, ok, I'll look again.

**Comment by snarfed** [comment]
Ok @jamietanna, once more with feeling, feel free to try again.

**Comment by jamietanna** [comment]
Yes I _think_ that's done it @snarfed 👏🏽

Although https://indieweb.social/users/jamietanna hasn't received a notification /shows up as me following them in the Masto UI 🤔

**Comment by snarfed** [comment]
Thanks again for the snarfed.org signing catch! I think that was keeping these follows/unfollows from getting accepted. I've fixed th

**Comment by jamietanna** [comment]
Yep, now we're done 👏🏽 thanks for the hard work!

**Comment by snarfed** [comment]
Welcome, thanks for your patience here!
