### ISSUE TITLE
Reply webmention doesn't contain proper author h-card

### ISSUE THREAD

**Issue by EdwardHinkle** [snarfed/bridgy-fed#41]
I received a reply: https://writing.exchange/@matt/101066523112656548 this came through as a reply webmention. The author h-card has an empty photo and the name is equal to the url rather than being the username.

I know the ActivityPub to webmention isn't using the mf2 from mastodon, but looking at the mf2 on the reply page, it does contain an accurate author h-card: http://pin13.net/mf2/?url=https%3A%2F%2Fwriting.exchange%2F%40matt%2F101066523112656548

**Comment by snarfed** [comment]
hey, thanks for the report, and sorry for the trouble! looks like a straightforward bug, will fix.

**Comment by EdwardHinkle** [comment]
No worries 🙂 glad it seems like a straightforward bug!
