### ISSUE TITLE
Persist IndieAuth session when attempting to follow

### ISSUE THREAD

**Issue by jamietanna** [snarfed/bridgy-fed#416]
Right now, to try and backfill (ahead of #355 being completed) the follows from other platforms, or even to add a few follows, we need to re-authorize on each request.

I wonder if creating i.e. a 10 minute session cookie (but preferably a bit longer, maybe a day?) to capture this would be handy, then someone going through a few follows doesn't have to re-authorize.

**Comment by snarfed** [comment]
Yeah this is totally reasonable. I've been allergic to implementing proper login sessions like this in Bridgy and Bridgy Fed, but not really for any good reason, and this is a pretty simple, low risk approach.

**Comment by jamietanna** [comment]
Thanks Ryan, this works nicely 👏🏽

**Comment by snarfed** [comment]
Done! It's stored in a session cookie now, lasts until you close your browser.
