### ISSUE TITLE
Fetch reposts' original post objects and render them in feeds

### ISSUE THREAD

**Issue by gRegorLove** [snarfed/bridgy-fed#419]
If possible, it would be nice to see the reposted content as well as the avatar/name/profile link of the original. Understand it may not be possible if Mastodon just sends the link of the original post.

Compare a (non-Mastodon) repost as [previewed in Monocle](https://monocle.p3k.io/preview?url=https%3A%2F%2Faaronparecki.com%2F2021%2F08%2F23%2F18%2Fchangelog) with how Mastodon reposts appears:

> [Tim Chambers ](https://indieweb.social/@tchambers) reposted
 [Tim's photo] [Tim Chambers](https://monocle.p3k.io/channel/tNgmSImKTPXM85o8QX7W6EJE/7123)
 [indieweb.social/@tchambers](https://indieweb.social/@tchambers)
 [shared this.](https://wandering.shop/users/janellecshane/statuses/109830923706594816)
 2/8/2023, 1:31:51 PM

**Comment by snarfed** [comment]
Oh ugh, thanks for the report, that's embarrassing. It should definitely include original full text etc. Will do.

**Comment by snarfed** [comment]
Aha, this is happening because we don't actually have the original post content. The AS2 `Announce` that we get in inbox delivery just has the original post's URL, not its contents or authors' details. We can still get them, we just need to fetch them, which is more work than I originally expected here. Still worthwhile though!

**Comment by snarfed** [comment]
Fwiw, here's the `Announce` for the example above:

```json
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "id": "https://indieweb.social/users/tchambers/statuses/109831252311304540/activity",
  "type": "Announce",
  "object": "https://wandering.shop/users/janellecshane/statuses/109830923706594816"
  "actor": {
    "id": "https://indieweb.social/users/tchambers",
    "name": "Tim Chambers",
    "..."
  },
  "published": "2023-02-08T21:31:51Z",
  "..."
}
```

**Comment by gRegorLove** [comment]
👍 Thought that might be the case.

**Comment by snarfed** [comment]
Fixed! Thanks again for reporting.

**Comment by gRegorLove** [comment]
This appears to be happening again on https://fed.brid.gy/web/gregorlove.com/feed

Regular notes appear to be missing author photo, too. I can create a separate issue for that if you prefer.

**Comment by snarfed** [comment]
Oh no! Thanks for the heads up, will look.

**Comment by snarfed** [comment]
Should be fixed now!
