### ISSUE TITLE
RSS feed missing details

### ISSUE THREAD

**Issue by aciccarello** [snarfed/bridgy-fed#429]
It looks like the RSS feed is missing some details. I'll switch to the atom feed for now but seemed like a bug considering it is in one feed file but not the other.

## RSS Feed item
<img width="703" alt="feed reader screenshot with text but no image or author" src="https://user-images.githubusercontent.com/11273838/219566017-a5ec03a6-806d-4e89-8067-29f37a2b0736.png">

## Atom Feed item
<img width="703" alt="feed reader screenshot showing image and author info" src="https://user-images.githubusercontent.com/11273838/219565800-44dc00d8-56cb-44ef-9475-18ba65cd27df.png">

**Comment by snarfed** [comment]
Confirmed that RSS is now also including the "Shared a post by ..." header for reposts, eg on https://monocle.p3k.io/preview?url=https%3A%2F%2Ffed.brid.gy%2Fuser%2Fsnarfed.org%2Ffeed%3Fformat%3Drss

**Comment by snarfed** [comment]
And images are now in too. Phew. Done, I think! Thanks again for reporting @aciccarello.
