### ISSUE TITLE
using a subdomains of the registered root domain

### ISSUE THREAD

**Issue by tomasparks** [snarfed/bridgy-fed#433]
I have my root domain registered @ tomasparks.name
but when I send a webmention with my subdomain as a source I get 

> <p>No user found for domain notes.tomasparks.name</p>

here is the source url https://notes.tomasparks.name/mastodon/20230224-0800.html

is there any way I can tell bridgy that they are owned by the same user?

**Comment by snarfed** [comment]
Hi! Other than redirecting one to the other, there's no automated way to do this right now. There are lots of web hosts that give users subdomains, so we start with the assumption that eg randomuser.wordpress.com is not the same as wordpress.com. I'm happy to set up a special case for your domain if you want though!

**Comment by snarfed** [comment]
Tentatively closing. Feel free to reopen or let me know if you want an exception!

**Comment by snarfed** [comment]
No worries! I'll just add an exception for your site. So your posts are on notes.tomasparks.name, but you want your fediverse handle to be @tomasparks.name, right?

**Comment by tomasparks** [comment]
> No worries! I'll just add an exception for your site. So your posts are on notes.tomasparks.name,

I have three subdomains at the moment

- gallery
- miniatures
- notes

> but you want your fediverse handle to be @tomasparks.name, right?
yes

**Comment by snarfed** [comment]
Done!
