### ISSUE TITLE
Support plume

### ISSUE THREAD

**Issue by swentel** [snarfed/bridgy-fed#44]
https://joinplu.me/

See comment on https://toot.cafe/@zack/101206779193111042 - I've asked him to jump in here with more details if he has them.

To give more context:

- page I tried to reply to is https://baptiste.gelez.xyz/~/FederationTesting/plume-and-the-indie-web/ 
- account: https://baptiste.gelez.xyz/@/0x1C3B00DA

I also confused myself this morning thinking that this account is from Pleroma, and maybe it is actually, cf https://edolas.world/@0x1C3B00DA

(note it's temporarily down, but should come back I guess)

**Comment by nekr0z** [comment]
Currently, Brid.gy seems to think Plume doesn't do ActivityPub, and tries OStatus?
https://fed.brid.gy/log?key=https%3A%2F%2Fevgenykuznetsov.org%2Fen%2Freactions%2F2021%2Fwagner-bridgy%2F+https%3A%2F%2Fblog.wagner.pp.ru%2F~%2FDiaryOfRussianHacker%2Ffirst-experience-with-plume%2F&start_time=1610295506

**Comment by snarfed** [comment]
https://joinplu.me/ says:

> Currently, Plume developers have less time and Plume is not actively maintained. New features may take time to be implemented. Could you consider similar purpose software: [WriteFreely](https://writefreely.org/), WordPress with [ActivityPub](https://wordpress.org/plugins/activitypub/) plugin and so on?

Sounds like it's abandoned. Closing!
