### ISSUE TITLE
Webmentions aren't being received for some replies

### ISSUE THREAD

**Issue by jamietanna** [snarfed/bridgy-fed#440]
It appears that some replies are being rejected by webmention.io with `no_link_found`

Some investigation:
https://chat.indieweb.org/dev/2023-03-09/1678348830552900
https://chat.indieweb.org/dev/2023-03-09/1678349222769000
https://chat.indieweb.org/dev/2023-03-09/1678349490081300

**Comment by snarfed** [comment]
Odd. Details from this example:

- source: https://fed.brid.gy/render?id=https%3A%2F%2Fhachyderm.io%2Fusers%2Fbyjp%2Fstatuses%2F109990940244547039%2Factivity
  - ...which 301 redirects to https://fed.brid.gy/render?id=https%3A%2F%2Fhachyderm.io%2Fusers%2Fbyjp%2Fstatuses%2F109990940244547039
- target: https://www.jvt.me/mf2/2023/03/shs0i/
- webmention.io status page: https://webmention.io/www.jvt.me/webmention/zbdmZxxGx1sI4n6djhx6
- BF log: https://fed.brid.gy/log?start_time=1678328560&key=https://hachyderm.io/users/byjp/statuses/109990940244547039/activity&module=

As mentioned in chat, the final source page has this link to the target URL.

```html
  <a class="u-in-reply-to" href="https://www.jvt.me/mf2/2023/03/shs0i/"></a>
```

@aaronpk my only guess is the redirect, but that should be pretty common, I'm sure wm.io supports source URL redirects, right?

**Comment by jamietanna** [comment]
Interestingly there are replies in the thread in 👆🏼 that I'm receiving perfectly fine

**Comment by snarfed** [comment]
Moving to https://github.com/aaronpk/webmention.io/issues/187

**Comment by snarfed** [comment]
Tentatively closing in favor of https://github.com/aaronpk/webmention.io/issues/187. Feel free to reopen if it turns out to be on this end after all!
