### ISSUE TITLE
Videos aren't present in h-feed for replies

### ISSUE THREAD

**Issue by jamietanna** [snarfed/bridgy-fed#441]
https://social.lol/@joehart/109994393527884635
https://fed.brid.gy/log?start_time=1678381252&key=https://social.lol/users/joehart/statuses/109994393527884635/activity&module=

**Comment by snarfed** [comment]
Thanks for reporting! Looks like this is a problem with videos, not images. Should be straightforward to fix.

**Comment by snarfed** [comment]
Should be fixed, tentatively closing. Thanks again!
