### ISSUE TITLE
Add a "notifications" feed

### ISSUE THREAD

**Issue by jamietanna** [snarfed/bridgy-fed#442]
Right now, if I were to scroll through my Bridgy Fed feed to try and find a mention / reply, it's mixed in with folks' new posts.

It'd be handy - especially with #440 - to be able to follow a "notifications" feed to see all the places I've had mentions / likes / replies / reposts.

**Comment by snarfed** [comment]
Yes! Definitely a good idea. This is what the user page dashboard feed has tried to do, but only casually, it doesn't have mf2 right now so it's not subscribable in a reader, and it also evidently regressed at some point to include your entire feed, not just notifs. I'll leave this open to track both of those.

**Comment by snarfed** [comment]
Done! User pages now have notifications in an `h-feed`. Docs: https://fed.brid.gy/docs#notifications

**Comment by jamietanna** [comment]
Thanks @snarfed 👏🏽 is there a link out from the user page? I can't seem to see one, not sure if it's one that can only appear when a social reader attempts to view the page?

**Comment by jamietanna** [comment]
Ie https://monocle.p3k.io/preview?url=https%3A%2F%2Ffed.brid.gy%2Fuser%2Fwww.jvt.me shows the feed including other folks' posts

**Comment by snarfed** [comment]
Sorry, I'm not sure what "link out" means? https://fed.brid.gy/user/www.jvt.me has the h-feed inside it, you can subscribe to that URL directly. And sorry, I've only suppressed other people's posts and non-notifs going forward, not retroactively.

**Comment by jamietanna** [comment]
Oh gotcha, that makes sense. Thanks 👏🏽

**Comment by jamietanna** [comment]
Should https://fed.brid.gy/log?start_time=1678835149&key=https://www.jvt.me/mf2/2023/03/mpqoh/&module= be visible in my notifications feed?

**Comment by snarfed** [comment]
Hah, good point. I do want your own activities on the user page dashboard, but you're right, they probably wouldn't be in a notifs feed. So, true, we probably want a separate feed for those. Reopening!

**Comment by snarfed** [comment]
Done! @jamietanna feel free to try: https://fed.brid.gy/web/www.jvt.me/notifications

**Comment by jamietanna** [comment]
Amazing thank you! Looks good 👏🏽

**Comment by jamietanna** [comment]
Happy to close unless you wanted to leave it open for anything else?

**Comment by snarfed** [comment]
Closing!

**Comment by snarfed** [comment]
@jamietanna I've tried to improve the notifs feed rendering a bit. Switched to just snippets, mostly avoiding images, and added undocumented support for a `quiet` query param that suppresses follows, likes, and reposts. I'd like to expose that in the UI but not sure how to do that cleanly yet.

**Comment by jamietanna** [comment]
Nice 😁 I'll see how that changes the rendering in Indiepass over the next few days. Lemme know if you'd like me to test anything
