### ISSUE TITLE
Post with hashtag doesn’t get linked?

### ISSUE THREAD

**Issue by EdwardHinkle** [snarfed/bridgy-fed#45]
I posted a reply to a Mastodon post and I included #IndieWeb in the text of my post. When I sent the post through Bridgy Fed, it’s plain text as opposed to the native Mastodon posts that have it linked.

See the posts and my reply in this thread:
https://cybre.space/@katastrophe/101661581248390741

Did I need to have a u-category on my hashtag or is this not supported yet on Bridgy Fed?

**Comment by snarfed** [comment]
hmm! i'm not sure, but i expect that's client side, not server side. which is a little confusing because mastodon is both for the other users, but not for you. bridgy fed can actually pass through some HTML from your posts, like linked text, and mastodon will accept and render it. i'll try to find an example.

**Comment by snarfed** [comment]
didn't find an easy example at hand, but feel free to add arbitrary `<a>`s to notes that you federate to mastodon, and it's possible they'll pass through.

**Comment by EdwardHinkle** [comment]
Aha!! You’re right. Upon further inspection, the first post in the thread is from cyber.space and that hashtag links to its own server’s copy of the hashtag. (Cyber.space/tag/indieweb), the second post in the thread is from vicious.play and that hashtag links to its own server (vicious.play/tag/indieweb).

So to match them I would need to add my own hyperlink to eddiehinkle.com/tag/indieweb

**Comment by EdwardHinkle** [comment]
So I think the real question is when I reply to a server (like cyber.space) how do I get my federated post to register with their server that I have a hashtag in my post

**Comment by EdwardHinkle** [comment]
If you look at the cyber.space Mastodon it has the post from vicious.play even though it’s a remote post. (https://cybre.space/tags/indieweb)

**Comment by EdwardHinkle** [comment]
So I think the real todo here (of which I can participate, not just asking you to do the work lol) is figuring out how remote Mastodon’s ping other servers when they have a hashtag

**Comment by EdwardHinkle** [comment]
Aha! I see a post from aaronpk has been catalogued on that server with that hashtag, so I suspect he has the answer!

**Comment by aaronpk** [comment]
You need to add a new property into the payload that describes the tag. For example:

```
"tag": [{
  "type": "Hashtag",
  "id": "https://aaronparecki.com/tag/indieweb",
  "name": "#indieweb"
}]
```

**Comment by EdwardHinkle** [comment]
@snarfed so the next question is how should Bridgy Fed handle this? Look for any hashtag in the text, or look for p-categories, or look for p-categories that also appear within the content with a #?

**Comment by EdwardHinkle** [comment]
I guess the tricky thing is it is looking for an Id that is a url, so maybe you need a hashtag inside of an href, and then you use the href as the id string

**Comment by snarfed** [comment]
hah, funny:

https://github.com/snarfed/granary/blob/427d743edcb25c4dd8f82bd1ef9ce1ecf43e8d89/granary/as2.py#L28

(nit: hopefully the `type: Hashtag` part isn't strictly necessary. the [AS 2.0 vocab spec](https://www.w3.org/TR/activitystreams-vocabulary/) has a specific example section for hashtags that shows basically this usage, but without `type`. the `Hashtag` value itself is nowhere in either the vocab spec or the [core spec](https://www.w3.org/TR/activitystreams-core/).)

the easy answer here is that indieweb source posts can include arbitrary links, including linking hashtags to search pages or anything else on their own site, and bridgy fed will pass them through, and AP servers like Mastodon i think maybe render them as is.

if you want target Mastodon servers to render them as searches within their own instance, like you describe here, then yes, `p-category` is probably best. i _think_ bridgy fed should already translate `p-category` to AS2 `tag`, so this might already work, but i'm not 100% sure. feel free to try!

**Comment by snarfed** [comment]
friendly ping @EdwardHinkle! feel free to try this with a test post with `p-category` and let me know if it works. or if this has dropped off your radar, feel free to close.

**Comment by EdwardHinkle** [comment]
It didn’t work with JUST a p-category. I still need to try BOTH a #tag AND p-category:tag

**Comment by EdwardHinkle** [comment]
I’ll try out using both and see if that works

**Comment by snarfed** [comment]
@EdwardHinkle interesting, i don't actually see your p-category attempt. no webmentions to `fed.brid.gy/webmention` during 4:20pm-5:30pm PDT yesterday. did your site maybe not send a wm?

**Comment by EdwardHinkle** [comment]
Oh, no I did that trial back in Feb. I just forgot to mention it here since I didn't get a chance to try the p-category with the hashtag in content

**Comment by EdwardHinkle** [comment]
Hmm okay, I just tried this again. https://eddiehinkle.com/2019/05/16/1/note/

The hashtag “#rentlife” exists in the text, the p-category rentlife is on the h-entry. But when I check the tags for the instance I log into that follows my website, it doesn’t seem to show my post under /tag/rentlife

**Comment by snarfed** [comment]
thanks for testing! here's the AS2 activity we sent to Mastodon, below, elided a bit. ([full thing is in the log](https://fed.brid.gy/log?start_time=1558018177&key=https%3A%2F%2Feddiehinkle.com%2F2019%2F05%2F16%2F1%2Fnote%2F+https%3A%2F%2Fmastodon.technology%2Finbox)).

it has a `tag` field with `Tag` objects that seem ok [based on the spec](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-tag). one difference from the [AS2 hashtag example](https://www.w3.org/TR/activitystreams-vocabulary/#microsyntaxes) is that the tags in the example both have `id`s. guess i could try that next.

```json
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "type": "Create",
  "object": {
    "type": "Note",
    "id": "https://fed.brid.gy/r/https://eddiehinkle.com/2019/05/16/1/note/",
    "url": "https://fed.brid.gy/r/https://eddiehinkle.com/2019/05/16/1/note/",
    "content": "Renting a house that is listed on the market for sale is ... not fun. Wife, baby, cat and I are all sitting in the car at the park... lol. #rentlife",
    "tag": [{
        "type": "Tag",
        "name": "rentlife"
      }, {
        "type": "Tag",
        "name": "family"
      }, {
        "type": "Tag",
        "name": "personal"
      }],
    "..."
  },
}
```

**Comment by EdwardHinkle** [comment]
Ohhh yeah interesting. Ids are supposed to be URLs? That means if we put the hashtag in an anchor link, you could use the href as the id. If you decide to go that route let me know and I’ll test one with an anchor link

**Comment by fancypantalons** [comment]
BTW, I noticed there hasn't been any movement on this, but I'm definitely experiencing this issue as well.  Let me know if there's anything I can do to help with it, as I keep pushing hashtags and it'd be nice if mastodon used them properly!

**Comment by fancypantalons** [comment]
So I've noticed a peculiarity in the behaviour, here.  So, here is an example of a create event where the hashtags are properly represented in Mastodon:

https://fed.brid.gy/log?start_time=1669167998&key=https://b-ark.ca/2022/11/22/review-circe.html%20https://social.scambi.org/inbox&module=

And here is a create event where the hashtags are *not* properly linked:

https://fed.brid.gy/log?start_time=1669229826&key=https://b-ark.ca/2022/11/23/i-kinda-wonder-what-it-must.html%20https://social.scambi.org/inbox&module=

The first major distinction, to me, is the latter is a Note while the former as an Article, and we know Masto converts those a bit differently.

In those Notes, I noticed BF is converting the note content into a "summary" and a "name" and that's it.  However, the [Mastodon API docs](https://docs.joinmastodon.org/spec/activitypub/) indicate that might be causing a problem:

>name - Used as status text, if content is not provided on a transformed Object type

And because BF is stripping the HTML on the name, Mastodon isn't getting the p-category microformat markup that's present in the original content.

My guess is that, like Articles, for Notes, BF should be sending a "content" element and *not* a "summary" element.

**Comment by snarfed** [comment]
@fancypantalons great sleuthing, thank you! That sounds very likely. My logic for converting mf2 HTML to Mastodon was originally based on Twitter, which uses just summary/name for articles instead of full text due to character limits. Mastodon's are much looser though, [eg this post from Bridgy Fed with 764 chars](https://indieweb.social/@snarfed.org@snarfed.org/109400600315316870) (only visible if you're logged into indieweb.social), so this change makes sense.

**Comment by fancypantalons** [comment]
So doing a bit of poking around, it looks like this is really an issue in the granary mf2->as1 mapping implementation.  

Should I open up an issue there?

Heck, I could probably throw together a PR if that's helpful (this issue is a nagging one for me as mastodon uses hashtags for discovery, which means my blog notes are basically invisible right now...)

**Comment by snarfed** [comment]
PRs are always welcome!

Having said that, I'm not sure about the conclusion here just yet. Looking at your two examples above, if you scroll down to the bottom of the logs, the final AS2 activities that BF sent to Mastodon inboxes both have the `tag` field populated. The note ([log](https://fed.brid.gy/log?start_time=1669229826&key=https://b-ark.ca/2022/11/23/i-kinda-wonder-what-it-must.html%20https://social.scambi.org/inbox&module=)) has one for `mbnov`, and the article ([log](https://fed.brid.gy/log?start_time=1669167998&key=https://b-ark.ca/2022/11/22/review-circe.html%20https://social.scambi.org/inbox&module=)) has one for `books`.

Also, the article does have both `content` (HTML) and `summary` (text), and they both look ok to me.

So, I'm not yet sure that BF/granary are doing something obviously wrong here.

**Comment by fancypantalons** [comment]
Hmm, so just to clarify, the issue I'm seeing is the article tags *are* being linked correctly, but the note tags aren't.

As you say, the article, which is working properly, has a name (text), content (html), and summary (text).

However the note only has a name (text) and a summary (text).

As a quoted from the Mastodon the name is "Used as status text, if content is not provided on a transformed Object type".

So the note, which isn't working properly, ends up using just the name for the toot content.  And I think that's why the tags in the note aren't being turned into proper hashtags with links, as the name is stripped of markup.

As an aside, I believe the summary is supposed to be used for content warnings, but... that's a whole other feature request. :)

**Comment by fancypantalons** [comment]
Damn.  Yup, you are 100% correct, I misread the JSON... hmm... I shall keep digging!

**Comment by fancypantalons** [comment]
So I have an alternative theory... but I'm not sure how to test it.

The article contains:  name, summary, and content

For the article the *summary* is being used by Mastodon in the rendered toot.  You can see that [https://indieweb.social/@brettk@b-ark.ca/109390593921616219](in the toot here).

I suspect that's because the summary is actually supposed to be used for content warnings... which... is a whole other feature request. :)  But the result is Mastodon is preferentially using the summary.

The summary *is* stripped of HTML and ends up looking like this:  

```
...blah blah blah... #books
```

The note, in contrast, contains:  name, and content.  No summary!

The content is *not* stripped of HTML, and it looks like this:  

```
...blah blah blah... <span class=\"category\"> #<a class=\"p-category\" href=\"/archives/category/mbnov/\">mbnov</a> </span>
```

In the note content, the "#" sits outside the anchor tag.  This is so that, when BF parses the p-category element, the tag name is "mbnov" and not "#mbnov", which I believe would be incorrect.

But looking at the Mastodon code, I think it is parsing the toot content, looking for patterns of the form "#<text>" and linking them accordingly.

So the article hashtag gets linked, because the tag is represented as "#books", while the note hashtag doesn't get linked because the tag isn't formatted in a way that Mastodon will pick up.

To test this, I'd want to change the note markup to place the "#" inside the anchor tag (so the text is formatted correctly for Mastodon), while hacking BF/Granary to remove the leading "#" before populating the Tag in the AS2.

So... thoughts on this essay? :)

**Comment by fancypantalons** [comment]
Alright, well, that idea didn't work.

Then I changed up the formatting so the p-category element is outside the main content, and the category link itself is embedded in the content.

The corresponding BF syndication [is here](https://fed.brid.gy/log?start_time=1669773209&key=https://b-ark.ca/2022/11/29/apologies-to-mastodon.html%20https://social.scambi.org/inbox&module=).

Pulling the content out, we now have:

```
<div class=\"categories\"><span class=\"category\"> <a href=\"/archives/category/indieweb/\">#indieweb</a> </span></div>
```

And it's still not rendering properly.

I'm honestly at a bit of a loss at this point...

**Comment by snarfed** [comment]
Ugh. Thank you for the sleuthing, and sorry it's been such a wild goose chase with no answer yet!

It's not a top priority for me personally right now, but if/when I do look myself, I'll definitely post here if I find anything new.

**Comment by gRegorLove** [comment]
Another data point, [this post](https://gregorlove.com/2022/11/hello-again-from-my-website/) with `p-category` has the `tag` in the create request, but hashtag didn't show up on Mastodon:

```json
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "type": "Create",
  "id": "https://fed.brid.gy/r/https://gregorlove.com/2022/11/hello-again-from-my-website/#bridgy-fed-create",
  "actor": {
    "id": "https://fed.brid.gy/gregorlove.com",
    "url": "https://fed.brid.gy/r/https://gregorlove.com/",
    "preferredUsername": "gregorlove.com"
  },
  "object": {
    "published": "2022-11-30 11:54-0800",
    "content": "<p>@artlung@xoxo.zone Hello again from my website! This time it should show up as a mention instead of a link.</p>",
    "url": "https://fed.brid.gy/r/https://gregorlove.com/2022/11/hello-again-from-my-website/",
    "@context": "https://www.w3.org/ns/activitystreams",
    "type": "Note",
    "tag": [
      {
        "type": "Tag",
        "name": "indieweb"
      }
    ],
    "id": "https://fed.brid.gy/r/https://gregorlove.com/2022/11/hello-again-from-my-website/",
    "to": [
      "https://www.w3.org/ns/activitystreams#Public"
    ]
  }
}
```

**Comment by gRegorLove** [comment]
Summarizing some sleuthing and discussion from #indieweb-dev:

Fetching the AS2 with `curl -H` for a [Mastodon post](https://hachyderm.io/users/liztai/statuses/109907766432901624):

```json
{
  "@context": [
    "https://www.w3.org/ns/activitystreams",
    {
      "ostatus": "http://ostatus.org#",
      "atomUri": "ostatus:atomUri",
      "inReplyToAtomUri": "ostatus:inReplyToAtomUri",
      "conversation": "ostatus:conversation",
      "sensitive": "as:sensitive",
      "toot": "http://joinmastodon.org/ns#",
      "votersCount": "toot:votersCount",
      "Hashtag": "as:Hashtag"
    }
  ],
  "id": "https://hachyderm.io/users/liztai/statuses/109907766432901624",
  "type": "Note",
  "summary": null,
  "inReplyTo": "https://hachyderm.io/users/lukzmu/statuses/109905124938988159",
  "published": "2023-02-22T09:50:24Z",
  "url": "https://hachyderm.io/@liztai/109907766432901624",
  "attributedTo": "https://hachyderm.io/users/liztai",
  "to": [
    "https://www.w3.org/ns/activitystreams#Public"
  ],
  "cc": [
    "https://hachyderm.io/users/liztai/followers",
    "https://hachyderm.io/users/lukzmu"
  ],
  "sensitive": false,
  "atomUri": "https://hachyderm.io/users/liztai/statuses/109907766432901624",
  "inReplyToAtomUri": "https://hachyderm.io/users/lukzmu/statuses/109905124938988159",
  "conversation": "tag:hachyderm.io,2023-02-21:objectId=28543079:objectType=Conversation",
  "content": "<p><span class=\"h-card\"><a href=\"https://hachyderm.io/@lukzmu\" class=\"u-url mention\">@<span>lukzmu</span></a></span> All I have to say is <a href=\"https://hachyderm.io/tags/IndieWeb\" class=\"mention hashtag\" rel=\"tag\">#<span>IndieWeb</span></a>. I will always have a place I can call my own with my website. My social media channels are just a way to distribute and amplify my content.</p>",
  "contentMap": {
    "en": "<p><span class=\"h-card\"><a href=\"https://hachyderm.io/@lukzmu\" class=\"u-url mention\">@<span>lukzmu</span></a></span> All I have to say is <a href=\"https://hachyderm.io/tags/IndieWeb\" class=\"mention hashtag\" rel=\"tag\">#<span>IndieWeb</span></a>. I will always have a place I can call my own with my website. My social media channels are just a way to distribute and amplify my content.</p>"
  },
  "attachment": [],
  "tag": [
    {
      "type": "Mention",
      "href": "https://hachyderm.io/users/lukzmu",
      "name": "@lukzmu"
    },
    {
      "type": "Hashtag",
      "href": "https://hachyderm.io/tags/indieweb",
      "name": "#indieweb"
    }
  ],
  "replies": {
    "id": "https://hachyderm.io/users/liztai/statuses/109907766432901624/replies",
    "type": "Collection",
    "first": {
      "type": "CollectionPage",
      "next": "https://hachyderm.io/users/liztai/statuses/109907766432901624/replies?only_other_accounts=true&page=true",
      "partOf": "https://hachyderm.io/users/liztai/statuses/109907766432901624/replies",
      "items": []
    }
  }
}
```

Note the `tag` property:

```json
    {
      "type": "Hashtag",
      "href": "https://hachyderm.io/tags/indieweb",
      "name": "#indieweb"
    }
```

The AS2 extension `Hashtag` appears to be from Eugen in Mastdon ([discussion](https://github.com/w3c/activitypub/issues/235)):

> I have added type: "Hashtag" to Mastodon because when I'm parsing the "tag" attribute and iterating over the items I'd like to know what the item is. A "Mention" type exists so there should be a "Hashtag" type as well.

It was proposed as an AS2 extension [here](https://www.w3.org/wiki/Activity_Streams_extensions#Hashtag_type) and [this issue](https://github.com/swicg/general/issues/6), but no further discussion since 2017-10 that I can see (did not check mailing list archives).

`Hashtag` appears to be an extension of AS2 `Link` [type](https://www.w3.org/TR/activitystreams-vocabulary/#dfn-link) since it has an `href` and not `id` property (`Object` type has `id`).

I'm leaning towards thinking (hoping) that BF only needs to add `"type": "Hashtag"` and ensure the hashtag starts with `#`.

**Comment by snarfed** [comment]
OK I don't know what to think. I tried what we thought would work, `type: Hashtag` with leading `#` in name. I also tried all other permutations of `type`, `id` vs `href`, and leading `#`. No dice. None of them resulted in "native" Mastodon hashtags.

Post links:
- https://indieweb.social/@snarfed.org@snarfed.org/109928754387053973
- https://indieweb.social/@snarfed.org@snarfed.org/109928765368984095

`tag` objects:

```json
[{
    "type": "Hashtag",
    "name": "type-hashtag",
    "href": "https://fed.brid.gy/#tag-type-hashtag",
}, {
    "type": "Tag",
    "name": "type-tag",
    "href": "https://fed.brid.gy/#tag-type-tag",
}, {
    "name": "no-type",
    "href": "https://fed.brid.gy/#tag-no-type",
}, {
    "type": "Hashtag",
    "name": "#type-hashtag",
    "href": "https://fed.brid.gy/#tag-type-#hashtag",
}, {
    "type": "Tag",
    "name": "#type-tag",
    "href": "https://fed.brid.gy/#tag-#type-tag",
}, {
    "name": "#no-type",
    "href": "https://fed.brid.gy/#tag-#no-type",
}]

[{
    "type": "Hashtag",
    "name": "type-hashtag",
    "id": "fed.brid.gy-tag-type-hashtag",
}, {
    "type": "Tag",
    "name": "type-tag",
    "id": "fed.brid.gy-tag-type-tag",
}, {
    "name": "no-type",
    "id": "fed.brid.gy-tag-no-type",
}, {
    "type": "Hashtag",
    "name": "#type-hashtag",
    "id": "fed.brid.gy-tag-type-#hashtag",
}, {
    "type": "Tag",
    "name": "#type-tag",
    "id": "fed.brid.gy-tag-#type-tag",
}, {
    "name": "#no-type",
    "id": "fed.brid.gy-tag-#no-type",
}]
```

**Comment by gRegorLove** [comment]
@snarfed Hm, did any tests include the same hashtag in the content? Maybe Mastodon is matching it, since they link the hashtags in the HTML view?

Like:

> Testing with #typehashtag

With `tag` object:
```json
{
    "type": "Hashtag",
    "name": "#typehashtag",
    "href": "https://fed.brid.gy/#tag-typehashtag",
}
```

I took out the hypen in the hashtag because I don't know if that's supported.

Also not sure if I'm supposed to see it there, but when I click those indieweb.social links, I don't see `tag` objects in the JSON.

**Comment by snarfed** [comment]
Good point! Added all tag names to the content and tried again, still nothing. https://indieweb.social/@snarfed.org@snarfed.org/109928901481785754

<img width="594" alt="image" src="https://user-images.githubusercontent.com/778068/221390704-c07b6d60-e072-44ef-bc39-883298e5ad14.png">

And yeah you'll only see it on indieweb.social if you're logged in. I'm constructing and sending these AP `Create` activities manually, so there's no way to fetch or see them in other instances. When you're logged out, the link above redirects you to a synthetic fragment URL on fed.brid.gy that serves the actor for @snarfed.org@@snarfed.org, which is more or less unrelated.

**Comment by gRegorLove** [comment]
BookWyrm recently added hashtags. See https://github.com/bookwyrm-social/bookwyrm/pull/2524 and [this comment](https://github.com/bookwyrm-social/bookwyrm/pull/2524#issuecomment-1438789816).

**Comment by snarfed** [comment]
Interesting! Notably, from https://github.com/bookwyrm-social/bookwyrm/pull/2524#issuecomment-1435733107 :

> Federation support from BookWyrm to Mastodon and takahe:
> Hashtag links get rewritten to point to the Mastodon/takahe hashtag page

I don't see the difference though. The JSON in your link https://github.com/bookwyrm-social/bookwyrm/pull/2524#issuecomment-1438789816 matches what you described above in https://github.com/snarfed/bridgy-fed/issues/45#issuecomment-1445257933, which I tested in https://indieweb.social/@snarfed.org@snarfed.org/109928901481785754.

The only possible difference I see is that the hashtag in their content is inside an `<a>` link. Maybe that's necessary?

**Comment by gRegorLove** [comment]
@snarfed Yeah, I should have included what @tantek said [in chat](https://chat.indieweb.org/dev/2023-03-13#t1678677344529000). It appears the content needs to have the `<a href>` with URL matching the href in the JSON. 

Weirdly, the URL comparison may not be case-sensitive? That AS2 from https://github.com/snarfed/bridgy-fed/issues/45#issuecomment-1444950494 has content:

```html
<a href=\"https://hachyderm.io/tags/IndieWeb\" class=\"mention hashtag\" rel=\"tag\">#<span>IndieWeb</span></a>
````

and has JSON tag:

```json
    {
      "type": "Hashtag",
      "href": "https://hachyderm.io/tags/indieweb",
      "name": "#indieweb"
    }
```

**Comment by snarfed** [comment]
Oh wow, it worked! Adding the `<a>` tag in content did the trick. [Here's my test post](https://indieweb.social/@snarfed.org@snarfed.org/110018105240426583), created with this AS2:

```json
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "type": "Create",
  "cc": ["as:Public"],
  "object": {
    "type": "Note",
    "id": "https://fed.brid.gy/r/https://snarfed.org/#2023-03-13-hashtag-test-a",
    "content": "testing hashtag <a href=\"https://snarfed.org/#foobar\">#foobar</a>",
    "tag": [{
      "type": "Hashtag",
      "href": "https://snarfed.org/#foobar",
      "name": "#foobar"
    }]
  }
}
```

**Comment by fancypantalons** [comment]
So does that just require the right markup on the source site or is there some BF work that needs to be done to bring it all together?

**Comment by snarfed** [comment]
@fancypantalons good q! I don't think source sites need new or different markup, `p-category` should be enough. More importantly, the UX options here are awkward. Mastodon requires hashtags in links in the content, but the content is obviously user-visible, so I'm reluctant to have BF change it programmatically much or at all.

Open to ideas here! @tantek is also [discussing this in chat right now.](https://chat.indieweb.org/dev/2023-03-14#t1678812979250300)

**Comment by snarfed** [comment]
(btw, note to myself, this issue should obviously track adding docs for whatever we conclude here.)

**Comment by snarfed** [comment]
Thank you @gRegorLove! I'll have something for you to try soon.

More experiment learnings:
* Both the tag object and content hrefs must be non-empty, fully qualified URLs.
* They don't need to match.
* Mastodon rewrites the content href to point to the local instance's search for the hashtag.
* However, it also generates a link preview for the _original_ content href, _unless_ it points to the sending instance. Ie for BF, if the content href is `https://fed.brid.gy/[anything]`, the link preview is suppressed. That's not really useful for users though, they're not going to link their hashtags on their site to BF. 😐

**Comment by gRegorLove** [comment]
@snarfed What about with `id` instead of `href`, since that works for @aaronpk? Screenshot: https://media.aaronpk.com/2023/03/14130405-4386.png

**Comment by snarfed** [comment]
Looks like it's working! Thanks for testing @gRegorLove! https://indieweb.social/@gregorlove.com@gregorlove.com/109864841025927677

**Comment by snarfed** [comment]
OK everyone, feel free to test! Here are the docs: https://fed.brid.gy/docs#hashtags

**Comment by fancypantalons** [comment]
Will this work if the hashtags are in the p-summary instead of the e-content?  For my long-form posts, I use a p-summary that contains the content that's syndicated out to Mastodon, and it's in that block where the hashtags are linked up.

**Comment by snarfed** [comment]
Somewhat, yes. As described in https://fed.brid.gy/docs#hashtags , they'll be invisible: Mastodon search will find them, but they won't be displayed in your post text. That still strictly comes from your original post's content; Bridgy Fed won't change it, nor will Mastodon afaik.

Relevant background discussion in https://github.com/snarfed/bridgy/issues/478

**Comment by fancypantalons** [comment]
Hmm... so... suppose I have this:

```html
<div class="h-entry">
  <p class="p-summary">
    This is a summary of my post, complete with a hashtag.  <a href="https://mysite.com/tag/throwback" class="p-category">#throwback</a>
  <p class="e-content">
    And here's the long-form content for that post.
  </p>
</div>
```

Brid.gy will send over the p-summary as the text for the post, in addition to a backlink.

For example, [this Mastodon post](https://indieweb.social/@brettk/109984592941074942) is a syndicated copy of [this article](https://b-ark.ca/2023/03/06/fictional-me-by-chat-gpt-2.html), and the Mastodon text comes from the p-summary block in that article.

I vaguely recall BF inherits most of that behaviour (minus the backlink, obviously).

Assuming that's right, I'm curious if, in the above example, "#throwback" will get properly sent over as a Hashtag in the AS2 and the text will be linked.

And if this isn't easy to answer I'm more than happy to just cobble something together and give it a shot!

**Comment by snarfed** [comment]
Ah! Looks like Bridgy (non-Fed) created that Mastodon post. You're right, it does prefer summary to content.

Bridgy Fed's behavior is similar but a bit different. (whee!) Under the hood, it doesn't have to choose a single piece of text to post, it federates full fledged AS2 objects. It tries to make those match your post as closely as possible. In this case, it would deliver a `Note` with both `summary` and `content`. [Mastodon interprets/abuses `summary` for their content warning UI](https://docs.joinmastodon.org/spec/activitypub/#payloads), so I think your text would end up as a content warning, and then show the content if you click through. I don't know if hashtags in summary/content warning work, but feel free to try!

**Comment by fancypantalons** [comment]
Ooooh yeah!  That does ring a bell now that you say it... ahh fun.  Thanks!

**Comment by snarfed** [comment]
Lots of discussion of this on AP Matrix chat over the last couple days. Notably https://matrix.to/#/!uHqAjmOtrLtidOiczC:matrix.org/$IghsBS-Ue20XTv4-nGifsqaNSf7YJNyMh2cvzylnwX8?via=matrix.org&via=mozilla.org&via=matrix.libreserver.org says that `@context` and `type: Hashtag` are important for Mastodon interop? eg:

```json
{"@context": [
    "https://www.w3.org/ns/activitystreams",
    {"Hashtag": "as:Hashtag"}
  ],
 "type": "Hashtag"
}
```

or

```json
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "type": "Hashtag"
}

**Comment by aciccarello** [comment]
It seems like the Mastodon 4.2 update might improve this support. Now tags that aren't in the content (or at the end of the content) appear below the post.

## Reply example

[Mastodon thread](https://mastodon.social/@TheRealPomax/111020232580944575), [Original Post](https://www.ciccarello.me/posts/2023/09/07/coopers-hawk-photo/)

<img width="574" alt="Screenshot of mastodon thread. A hashtag appears in a muted color below the reply text." src="https://github.com/snarfed/bridgy-fed/assets/11273838/62cab533-136d-4d02-b073-dca5f06e9acc">

## Photo post example

[Original Post](https://www.ciccarello.me/posts/2023/07/09/denver-puppy/)

<img width="574" alt="Mastodon photo post with text and photo shown above a list of hashtags" src="https://github.com/snarfed/bridgy-fed/assets/11273838/2c00bef1-3e13-4407-b470-25709bfc52fa">

**Comment by snarfed** [comment]
Yes! I suspect there's more to figure out though. Filing a new issue for 4.2 compatibility...
