### ISSUE TITLE
Post counts in Mastodon

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#458]
Our post counts in Mastodon are wrong. Often they're 0, sometimes they're 1, eg right now on https://indieweb.social/@snarfed.org@snarfed.org, sometimes higher, eg @gregorlove has reported 7. Does Mastodon get this from outbox? Actor objects? Somewhere else?

**Comment by gRegorLove** [comment]
Mine varies across instances

- indieweb.social: 7
- xoxo.zone: 7
- mastodon.social: 6
- mastodon.world: 6

**Comment by gRegorLove** [comment]
I'm seeing zero now too. Maybe I made a typo or maybe it's just a random number generator 🙃

**Comment by snarfed** [comment]
Looking beyond Mastodon, https://cawfee.club/users/$ARk1bGtBNWUbJZX2nI (@snarfed.org@snarfed.org on Pleroma) shows "Statuses: 1" and one visible post.

**Comment by snarfed** [comment]
Couldn't find any relevant info on how Mastodon calculates post counts in [web searches](https://www.google.com/search?q=mastodon+activitypub+profile+post+count#ip=1) or [their issues](https://github.com/mastodon/mastodon/issues?q=is%3Aissue+activitypub+profile+post+count).

**Comment by snarfed** [comment]
The examples above all have more realistic counts now. They definitely vary by remote instance, but I think that's normal, they're counting the posts they've actually seen. This may be working as expected, so I'm tentatively closing for now.
