### ISSUE TITLE
Mastodon @-mention didn't result in webmention

### ISSUE THREAD

**Issue by fluffy-critter** [snarfed/bridgy-fed#46]
Quite some time ago I set up fed.brid.gy on bessbuzz.biz, which produces an Atom feed with a WebSub hub. I have attempted to follow @beesbuzz.biz@beesbuzz.biz from multiple Mastodon accounts but each time I just see it as a “you requested to follow” but the request never gets granted. 

I’ve also tried sending webmentions to posts on mastodon using the instructions on fed.brid.gy but they never show up on the target posts.

As far as I can tell, all of my required atom, websub, and webmention discovery tags are set up correctly, and in particular I’ve been able to interact with other IndieWeb sites for quite some time now.

What steps can I take to figure out what’s going wrong? The troubleshooting steps on the instructions page don’t cover anything beyond a very narrow slice of the experience.

**Comment by fluffy-critter** [comment]
As a test I created [this entry](https://beesbuzz.biz/blog/chatter/6525-ActivityPub-test) which had an In-Reply-To link to [this toot](https://queer.party/@fluffy/101851467103569053). I ended up getting two replies, one from the http and one from the https version (which is annoying but not unexpected); they both came from the same fake https://fed.brid.gy/r/http://beesbuzz.biz/ user, but had different URLs:

https://fed.brid.gy/r/http://beesbuzz.biz/blog/chatter/6525-ActivityPub-test
https://fed.brid.gy/r/https://beesbuzz.biz/blog/chatter/6525-ActivityPub-test

On my instance they appear as the following toots:

https://queer.party/web/statuses/101852022941916960
https://queer.party/web/statuses/101852022734688958

So, okay, it seems that at least replies are working now, which is an improvement, although the way follows work could be a bit better, especially with sites that support both http and https. Some sort of ping consolidation would be nice to have; unfortunately for Reasons I can't simply only send webmentions from one or the other (although I have [an open issue](https://github.com/PlaidWeb/Pushl/issues/10) on my webmention conduit).

The queer.party profile for the bridged site is https://queer.party/web/accounts/78606, which shows 0 toots and 2 replies. It also still shows my follow relationship as "pending," rather than "following."

I know we've discussed the inability to send new posts in the past but per [this closed issue](https://github.com/snarfed/bridgy-fed/issues/33) it seems that the functionality has been added. I'm just not sure how to actually get it to work...

**Comment by snarfed** [comment]
thanks for the sleuthing and details @fluffy-critter, and sorry for the trouble!

looking at bridgy fed's logs, it's only ever received one ActivityPub `Follow` request to `/beesbuzz.biz/inbox`, from @fluffy@dragon.style at 2019-04-01 10:21:33 PDT. it replied by sending the AP `Accept` request below to https://dragon.style/users/fluffy/inbox, and Mastodon responded with HTTP 202, which it uses to mean it may or may not actually honor the request, depending on the signature and other requirements/heuristics that i don't always fully understand (and that sometimes change over time) ☹️.

```json
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "object": {
    "object": "https://fed.brid.gy/beesbuzz.biz",
    "type": "Follow",
    "actor": "https://dragon.style/users/fluffy"
  },
  "type": "Accept",
  "id": "tag:fed.brid.gy:accept/beesbuzz.biz/https://dragon.style/29f91e37-9580-4b84-bf42-11916220ac61",
  "actor": "https://fed.brid.gy/beesbuzz.biz"
}
```

(also, just fyi, you're not actually advertising a webmention endpoint on http://beesbuzz.biz/ or https://beesbuzz.biz/ right now, in either HTML or headers. some of bridgy fed's features will still work despite that, as you noticed, but it's not ideal.)

**Comment by fluffy-critter** [comment]
Yeah, I only advertise webmention endpoints on individual items, because I don't see the point to getting a ping/mention on a site. Previously I was advertising it on index pages as well but that just resulted in a lot of useless spam. I could reenable that if that makes bridgy fed work better though, but I'm at least able to receive replies to individual items; see the "responses" section at http://beesbuzz.biz/blog/chatter/6525-ActivityPub-test

Before I opened this ticket I tried unfollowing from @fluffy@queer.party and refollowing and still had the pending-follow thing happen. Just now I did that again and now it seems to be following correctly? Weird. And @fluffy@dragon.style got my latest blog entry on the timeline, too (see https://dragon.style/web/statuses/101853758066434482). Huh.

So, I guess whatever wasn't working before is working now? Weird.

Anyway, I guess this issue is resolved-ish, but I'll keep it open for now in case something weird happens in the next few days. Also I'd like an answer regarding the index-page webmention endpoint. :)

**Comment by fluffy-critter** [comment]
Okay so I ended up adding the webmention endpoint to my top-level site index, and then tried sending a mention to my site from queer.party. No mention came through, but the fed.brid.gy log showed:

```
Source | Target | Protocol | Status | Time (click for log)
-- | -- | -- | -- | --
queer.party/ac4a7684-4ca8-... | beesbuzz.biz | activitypub | error | 2019-04-02 01:05:46
```

Unfortunately the timestamp doesn't link to any error log.

I had restarted my edge server and verified that the `rel="webmention"` link was available before I sent the test ping (and this should have also invalidated any cache that talks to it), but is fed.brid.gy maybe caching webmention endpoints for some period of time?

Also I'm sorry for what my feed did to the logs when it apparently backfilled. :)

**Comment by snarfed** [comment]
thanks for the details! not sure what happened with the unhappy follows earlier.

> Also I'd like an answer regarding the index-page webmention endpoint. :)

bridgy fed sends webmentions to your home page for follows and unfollows. details on https://indieweb.org/follow#Implementations etc.

> Okay so I ended up adding the webmention endpoint to my top-level site index, and then tried sending a mention to my site from queer.party. 

looking at https://queer.party/@fluffy/101854077916187182 now. not sure what's up, i'll update when i know more.

**Comment by snarfed** [comment]
heh, i forgot, converting @-mentions on Mastodon to webmentions to your home page just isn't implemented yet. i'll keep this open as a feature request to implement it.

**Comment by fluffy-critter** [comment]
Ah, that makes sense. It does look like follow mentions do come through, at least, although webmention.io doesn’t support `u-follow-of` just yet.

**Comment by snarfed** [comment]
i've deployed this, so bridgy fed should now convert mastodon @-mentions to homepage webmentions. i tried @-mentioning my site in https://mastodon.technology/@snarfed/101936926634354766 , and mastodon (2.8.0) correctly shows that the activity includes a `Mention` tag of my site (below), and even cc's it, but mastodon didn't send the activity to bridgy fed. not sure why yet.

`curl -H 'Accept: application/activity+json' -v https://mastodon.technology/users/snarfed/statuses/101936926634354766`:
```json
{
  "@context": "...",
  "id": "https://mastodon.technology/users/snarfed/statuses/101936926634354766",
  "type": "Note",
  "summary": null,
  "inReplyTo": null,
  "published": "2019-04-16T17:01:01Z",
  "url": "https://mastodon.technology/@snarfed/101936926634354766",
  "attributedTo": "https://mastodon.technology/users/snarfed",
  "to": ["https://www.w3.org/ns/activitystreams#Public"],
  "cc": [
    "https://mastodon.technology/users/snarfed/followers",
    "https://fed.brid.gy/snarfed.org"
  ],
  "sensitive": false,
  "atomUri": "https://mastodon.technology/users/snarfed/statuses/101936926634354766",
  "conversation": "tag:mastodon.technology,2019-04-16:objectId=16360399:objectType=Conversation",
  "content": "<p>testing @-mentions with <a href=\"https://fed.brid.gy/\" rel=\"nofollow noopener\" target=\"_blank\"><span class=\"invisible\">https://</span><span class=\"\">fed.brid.gy/</span><span class=\"invisible\"></span></a>. hi <span class=\"h-card\"><a href=\"https://fed.brid.gy/r/https://snarfed.org/\" class=\"u-url mention\">@<span>snarfed.org</span></a></span>!</p>",
  "tag": [{
    "type": "Mention",
    "href": "https://fed.brid.gy/snarfed.org",
    "name": "@snarfed.org@snarfed.org"
  }],
  "..."
}
```

**Comment by snarfed** [comment]
maybe snarfed.org is just configured wrong for bridgy fed. [i tried again and @-mentioned some other users](https://mastodon.technology/@snarfed/101938547293295829), and it happily sent homepage wms for all three of them. yay. tentatively closing.
