### ISSUE TITLE
Write a FEDERATION.md file

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#477]
https://socialhub.activitypub.rocks/t/documenting-federation-behavior-in-a-semi-standard-way/453

https://github.com/gabek/fedidocs/issues/4

**Comment by snarfed** [comment]
[I'm not seeing much adoption of this in web searches.](https://www.google.com/search?q=%22federation.md%22) (Unscientific, I know.)

**Comment by silverpill** [comment]
I wrote a FEP draft for `FEDERATION.md`: https://codeberg.org/silverpill/feps/src/branch/main/67ff/fep-67ff.md
It contains an up to date list of services which adopted this convention. Bridgy Fed could be one of them :)

**Comment by snarfed** [comment]
Done! https://github.com/snarfed/bridgy-fed/blob/main/FEDERATION.md

**Comment by silverpill** [comment]
Good job! Adding Bridgy Fed to implementation list: https://codeberg.org/fediverse/fep/pulls/314
