### ISSUE TITLE
AP image attachments

### ISSUE THREAD

**Issue by fluffy-critter** [snarfed/bridgy-fed#48]
My site uses relative links wherever possible, when rendering HTML. As a result, the HTML for [this entry](https://beesbuzz.biz/comics/unity/ascent/3538-209-Rendezvous-with-Mama) gets `e-content` data with relative href/src/srcset like

```html
                <div id="preamble" class="body">
                    <p><div class="images"><img alt="" title="It has been a long day, and this morning's shower has lost its effect on Hira's appearance." src="/static/_img/54/eb7b/unity-209_1328681e22_960x512.jpg" width="960" height="512" srcset="/static/_img/54/eb7b/unity-209_1328681e22_960x512.jpg 1x, /static/_img/54/eb7b/unity-209_1328681e22_1920x1024.jpg 2x"></div> </p>
                </div>
```

Unfortunately this is being sent directly via ActivityPub, e.g. [this request](https://fed.brid.gy/log?start_time=1554271666&key=https%3A%2F%2Fbeesbuzz.biz%2Fcomics%2Funity%2Fascent%2F3538-209-Rendezvous-with-Mama+https%3A%2F%2Fqueer.party%2Finbox) with mf2 like:

```
    "content": [
      {
        "html": "<div class=\"body\" id=\"preamble\">\n                    <p></p><div class=\"images\"><img alt=\"\" height=\"512\" src=\"/_async/_img/54/eb7b/unity-209_1328681e22_960x512.jpg\" srcset=\"/_async/_img/54/eb7b/unity-209_1328681e22_960x512.jpg 1x, /_async/_img/54/eb7b/unity-209_1328681e22_1920x1024.jpg 2x\" title=\"It has been a long day, and this morning's shower has lost its effect on Hira's appearance.\" width=\"960\"/></div> <p></p>\n                </div>", 
        "value": ""
      }
    ], 
```

When this appears on Mastodon, image-only posts look like this:

<img width="327" alt="image" src="https://user-images.githubusercontent.com/347162/55456784-c7fcbf80-559c-11e9-9745-45408fe6b2b1.png">

I'm not finding any definitive answer about this on mf2 but my probably-bad assumption is that it would be up to the consumer (in this case, bridgy fed) to rewrite relative links, including `<img src>` and `<img srcset>`.

**Comment by fluffy-critter** [comment]
Although as a temporary workaround I tried making my templates emit absolute links and image-only posts still aren't showing their image content, so probably something else is going on too.

**Comment by fluffy-critter** [comment]
Okay yeah it looks like all the `<img>` content is getting stripped out anyway, argh...

<img width="748" alt="image" src="https://user-images.githubusercontent.com/347162/55457288-60477400-559e-11e9-8542-ca1baa12e1b1.png">

Once again it looks like Mastodon is getting in the way of this possibly working correctly anyway.

(But bridgy fed should still probably rewrite relative URLs.)

**Comment by fluffy-critter** [comment]
And, per [this conversation](https://queer.party/web/statuses/101861071623261488), it seems that the correct thing would be for bridgy fed to convert the `<img>` tags to attachments, which would at least make them appear on things that use the ActivityPub note mechanism.

**Comment by snarfed** [comment]
thanks! try marking images you want to attach in Mastodon with `class="u-photo"`? i think bridgy fed handles that.

**Comment by fluffy-critter** [comment]
Ngh, I GUESS I could add that to my templates...

**Comment by fluffy-critter** [comment]
Nope, it doesn't. [source page](http://beesbuzz.biz/comics/journal/2392-January-21-2019-Rub) [bridgy event](https://fed.brid.gy/log?start_time=1554305558&key=http%3A%2F%2Fbeesbuzz.biz%2Fcomics%2Fjournal%2F2392-January-21-2019-Rub+https%3A%2F%2Fqueer.party%2Finbox)

**Comment by fluffy-critter** [comment]
Okay, I added it, and while the image doesn't seem to be getting attached directly, at least now mastodon (or at least queer.party) is unfurling the destination URL which it wasn't doing before.

Unfortunately with my test ping I'm getting [no log found](https://fed.brid.gy/log?start_time=1554305802&key=http%3A%2F%2Fbeesbuzz.biz%2Fcomics%2Fjournal%2F2392-January-21-2019-Rub%3Ftest%3D1+https%3A%2F%2Fqueer.party%2Finbox) so I'm not sure what's actually different this time.

**Comment by fluffy-critter** [comment]
Okay, a [different test](https://queer.party/web/statuses/101863004773577925) worked. I guess this is acceptable, although it'd be nice if it used the 2x rendition from the srcset instead of the base image (but that's a huge pain to deal with).
