### ISSUE TITLE
Make it work on WordPress

### ISSUE THREAD

**Issue by danicotillas** [snarfed/bridgy-fed#50]
Hi @snarfed Congratulations for the work!!!
I´m trying to make IndieWeb work on my website comunicacionabierta.net since I just discovered. I think this is too good to be true... the problem is that I can´t make it work!!!
My server is a cloud one on Siteground - CentOS - and I don´t know exactly what´s my problem.
Mathias Pfefferle told me something about the webfinger but my knowledge is very limited.
Could you know what steps should I follow?
Thanks!

**Comment by snarfed** [comment]
hi daniel! thanks for the kind words.

setup instructions are at https://fed.brid.gy/#setup . have you followed them all? in particular, did you set up the redirects for `/.well-known/*`? right now those URLs all 404, eg https://comunicacionabierta.net/.well-known/webfinger , so those redirects aren't working yet.

**Comment by snarfed** [comment]
also, you're here because you want to federate your site with Mastodon, right? if you just want to do IndieWeb in general, definitely start on https://indieweb.org/ , and maybe https://indieweb.org/Getting_Started_on_WordPress , not here.

**Comment by snarfed** [comment]
@danicotillas any updates? let me know if you think there's a bridgy fed bug here to fix.

**Comment by danicotillas** [comment]
Hi @snarfed Thanks for your emails! I´ve been trying since but no success... I´m not a proficient programmer and definitely the instructions are a bit unclear for me. I think I did everything as required but still no chances to see it on mastodon.
I´m trying now on investigacionsocial.net. Don´t know if you can follow from there.
Thanks

**Comment by snarfed** [comment]
@danicotillas hey, you made progress! https://investigacionsocial.net/ has all the redirects working, and also has an Atom feed. great!

now you need a representative h-card. the easiest way is to just add `rel="me"` to your home page h-card's link. more details: https://indiewebify.me/validate-h-card/?url=https%3A%2F%2Finvestigacionsocial.net%2F

**Comment by danicotillas** [comment]
Thanks @snarfed !!!!!
I didn´t know about the existance of https://indiewebify.me/, it´s exactly what people like me need!!!
Just a question, in a site like investigacionsocial.net, which goal is to be a network of people publishing, is it possible that every profile is federated via IndieWeb and ActivityPub protocol? Could it be possible that every profile there is at the same time a profile for the Fediverse?
There are many chances I´m mixing Fediverse with IndieWeb with Bridgy but I´m still trying to understand everything properly to communicate properly.

Thanks for the effort!

**Comment by snarfed** [comment]
hey, you're welcome! indiewebify.me is definitely helpful.

> Just a question, in a site like investigacionsocial.net, which goal is to be a network of people publishing, is it possible that every profile is federated via IndieWeb and ActivityPub protocol? Could it be possible that every profile there is at the same time a profile for the Fediverse?

sadly bridgy fed can't do this right now. it expects a domain to represent just a single user on the fediverse. multiple users per domain is definitelys a good feature request, but it'd be a significant project and redesign, and not one i'd personally plan to implement anytime soon. i'm open to design proposals and PRs though!

**Comment by snarfed** [comment]
tentatively closing. feel free to reopen!
