### ISSUE TITLE
Atom Default Feed removed from Wordpress plugins

### ISSUE THREAD

**Issue by ngm** [snarfed/bridgy-fed#51]
The Atom Default Feed plugin mentioned in the docs (https://wordpress.org/plugins/atom-default-feed/) has been removed from Wordpress plugins.

> This plugin was closed on December 22, 2018 and is no longer available for download. Reason: Author Request.

**Comment by ngm** [comment]
You can still get the source for it here: https://plugins.svn.wordpress.org/atom-default-feed/trunk/atom-default-feed.php

**Comment by snarfed** [comment]
thanks for the heads up! I'll find another plugin to link to that's still maintained.

**Comment by snarfed** [comment]
couldn't find another plugin so i just switched to manual instructions. ah well.
