### ISSUE TITLE
Can't follow Bridgy Fed actor

### ISSUE THREAD

**Issue by silverpill** [snarfed/bridgy-fed#522]
Hello, I'm trying to follow `https://fed.brid.gy/snarfed.org`, but my `Follow` activity gets rejected with HTTP 502.
There was a problem with parsing of Accept header on my side, which has been fixed. Now Bridgy Fed seems to be fetching my actor, but still rejects the follow request.
Activity:
```json
{"@context":["https://www.w3.org/ns/activitystreams","https://w3id.org/security/v1","https://w3id.org/security/data-integrity/v1",{"MitraJcsRsaSignature2022":"mitra:MitraJcsRsaSignature2022","mitra":"http://jsonld.mitra.social#","proofPurpose":"sec:proofPurpose","proofValue":"sec:proofValue","sensitive":"as:sensitive","verificationMethod":"sec:verificationMethod"}],"actor":"https://mitra.social/users/silverpill","id":"https://mitra.social/objects/01886003-887b-0f60-573b-116b30ac0372","object":"https://fed.brid.gy/snarfed.org","to":["https://fed.brid.gy/snarfed.org"],"type":"Follow"}
```

Sent at 2023-05-28T01:40:24Z

**Comment by snarfed** [comment]
Hmm! Thanks for filing, and sorry for the trouble, I'll look.

**Comment by snarfed** [comment]
Ah, we're being overly strict about the `Content-Type`s we expect. Thanks again, fixed now. Feel free to try again!

**Comment by silverpill** [comment]
Thank you!
There's another issue. I tried to re-follow the actor and received this Accept activity from Bridgy Fed:

```json
{"@context":"https://www.w3.org/ns/activitystreams","actor":"https://fed.brid.gy/snarfed.org","id":"https://fed.brid.gy/user/snarfed.org/followers#accept-https://mitra.social/objects/01886328-2629-d9b6-7986-1c2ab6bd1d31","object":{"actor":"https://mitra.social/users/silverpill","object":"https://fed.brid.gy/snarfed.org","type":"Follow"},"type":"Accept"}
```

The `object` here doesn't have the `id` property. Is it possible to include it?

I could try to guess what the corresponding Follow activity was from `actor` and `object` properties, but that's not ideal.

**Comment by snarfed** [comment]
Hmm! `id` isn't required for "transient" activities like this, right? [From the spec](https://www.w3.org/TR/activitypub/#obj-id):

> ...all objects distributed by the ActivityPub protocol MUST have unique global identifiers, unless they are intentionally transient (short lived activities that are not intended to be able to be looked up, such as some kinds of chat messages or game notifications)

It does go on to say that transient activities should have `id` explicitly set to null, so I guess I should do that. Would that help here?

I could also generate a synthetic id, but it wouldn't be resolvable, since I don't currently store or serve `Accept`s, so I'm reluctant.

**Comment by snarfed** [comment]
Oh actually no, on closer reading of that section, null `id` is only required for "an anonymous object (a part of its parent context)," which I don't think this is.

**Comment by silverpill** [comment]
`Accept` might be transient, but in this case it embeds `Follow` activity, which is not transient.

**Comment by silverpill** [comment]
>I could also generate a synthetic id, but it wouldn't be resolvable, since I don't currently store or serve Accepts, so I'm reluctant.

I was referring to `Accept.object.id` property. Could you use ID of accepted `Follow` activity here?

**Comment by snarfed** [comment]
Oh! Sorry, yes, including the Follow id definitely makes sense, I'll do that.

**Comment by snarfed** [comment]
Done!

**Comment by silverpill** [comment]
Seems to be working now, thanks!
