### ISSUE TITLE
Something Wrong With It

### ISSUE THREAD

**Issue by Mirakelor** [snarfed/bridgy-fed#535]
I have added the .well-known redirects.But it seemed that it couldn't recognise %3A and %40. They seem to have no difference with the : and @.
![image](https://github.com/snarfed/bridgy-fed/assets/63326519/9c482099-36b9-4a7b-ac0a-d314d8d6a48d)

I really want to know how to fix it. Thank You🤨.

**Comment by snarfed** [comment]
Oops, definitely a bug. Our webfinger itself handles URL-encoded values ok, but the redirect check didn't. Thank you for filing! Fixed now, https://fed.brid.gy/web/monocle.js.org is now showing that your site is 500ing on the redirect.
