### ISSUE TITLE
'followers' URL does not work

### ISSUE THREAD

**Issue by angelortega** [snarfed/bridgy-fed#54]
Hi. I've found that the 'actor' URL contains the key 'followers' with an URL that when followed returns a 404 with the following additional info:

```
Error: Not Found
The requested URL /triptico.com/followers was not found on this server.

```
As far as I know, the ActivityPub spec recommends not to announce services that are not implemented. Or is it another kind of error? I'm sure fed.brid.gy keeps an internal list of followers because everything else works (i.e. posts are propagated to everyone that follows, so the follower list is somewhere inside).

On the other hand, I find your software useful and operative. Keep the good work.

Regards,
Ángel

**Comment by snarfed** [comment]
heh, true! the `followers`, `following`, and `outbox` URLs are all not implemented. technically ActivityPub only requires `outbox`, but we added the others in an attempt to interoperate with peertube, which requires them. details: https://github.com/snarfed/bridgy-fed/issues/40#issuecomment-447098466

thanks for the kind words!

**Comment by angelortega** [comment]
> heh, true! the followers, following, and outbox URLs are all not implemented. technically ActivityPub only requires outbox, but we added the others in an attempt to interoperate with peertube, which requires them. details: #40 (comment)

Understood, thanks!

Best regards,
Ángel
