### ISSUE TITLE
Why posts are only displayed to subscribers

### ISSUE THREAD

**Issue by flip-bs** [snarfed/bridgy-fed#55]
Hello,

Is there any technical (or non-technical) reasons that post can't be displayed in mastodon without following the ActivityPub account ?

Is BridgyFed sending post with the privacy status "follower only" like in mastodon ? can this be changed somewhere ? 

Thank's

**Comment by snarfed** [comment]
good question! activitypub delivery and visibility can definitely be subtle.

bridgy fed doesn't mark posts as follower only, and it ccs a special "public" audience, so they're definitely public. it can't deliver them to every existing Mastodon instance, though, so instances without any followers may need to fetch them on demand.

if you know more about activitypub delivery, I'm open to suggestions!

**Comment by snarfed** [comment]
tentatively closing. feel free to reopen!
