### ISSUE TITLE
Mastodon profile link verification (green check on rel-me links)

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#560]
[Mastodon supports bidirectional profile link verification with rel-me links.](https://docs.joinmastodon.org/user/profile/#verification) Verified links are rendered with green checks. This works for remote profiles as well as local ones; evidently [Mastodon instances verify links in remote profiles themselves](https://github.com/mastodon/mastodon/issues/20159#issuecomment-1307861787), distributed, the same way they verify links in local profiles.

<img style="float: right" width="376" alt="mastodon-search" src="https://github.com/snarfed/bridgy-fed/assets/778068/780a4cb0-5307-490f-bb36-7db8d95ba0bd">

@aaronpk [evidently tried this with his web site, but never quite got it to work.](https://chat.indieweb.org/dev/2023-06-23#t1687483479551500)

Background on how we originally got Mastodon profile links working in #323.

**Comment by snarfed** [comment]
My Bridgy Fed account @snarfed.org@snarfed.org has a profile link to https://snarfed.org/, which now has rel-me links back to both the AS2 actor id https://fed.brid.gy/snarfed.org and its url https://fed.brid.gy/r/https://snarfed.org/ . No green check on any Mastodon account anywhere yet. 🤷

**Comment by snarfed** [comment]
It's alive, it's alive!

**Comment by snarfed** [comment]
snarfed/granary@f608f3e63bb000d769a9e93b346f53a939637fbb

**Comment by snarfed** [comment]
Steps:

* Add a [`rel=me` link](https://indieweb.org/rel-me) on your site that points to `https://fed.brid.gy/r/https://[DOMAIN]/` for your domain, eg `https://fed.brid.gy/r/https://snarfed.org/`
* Click the 🔄 button on your Bridgy Fed user page to update your profile on all of your followers' instances.
* Log into any Mastodon instance where you have an account.
* Search for your Bridgy Fed handle, eg @snarfed.org@snarfed.org.
* Click on your fediverse user in the search results.
* Wait a minute or two (or ten 😐), then refresh the page. You should see a green check on the profile link for your web site.

Searching for your user when logged in triggers Mastodon instance to check verify your profile link(s) in the background. Each instance does this independently; verified links are not synched across instances.

**Comment by jamietanna** [comment]
Where's best to chat about this if I can't seem to get mine working? A new issue or on IndieWeb chat?

**Comment by snarfed** [comment]
Either! I'll ping you in chat now.

**Comment by snarfed** [comment]
Looking at this a bit again now. This is working for most users, but not for @www.jvt.me@www.jvt.me on any instance I looked at, including androiddev.social, indieweb.social, mas.to, mastodon.art, or mastodon.social. Given the consistency there, I suspect this is a bug with how BF handles www accounts, somehow.

**Comment by snarfed** [comment]
Hey @jamietanna, I know it sounds ridiculous, but I suspect the trailing slash on your site's rel-me. Could you change it to `<link rel=me href=https://fed.brid.gy/r/https://www.jvt.me>`, ie without trailing slash, and try again?

If that fixes it, I can look into how to make it work regardless of trailing slash.

**Comment by jamietanna** [comment]
@snarfed good shout, just pushed the changes, and site will hopefully be updated in ~10-15 minutes and will retry then :crossed_fingers:

**Comment by jamietanna** [comment]
Looks like it's worked :raised_hands:
