### ISSUE TITLE
Accepted but something was wrong

### ISSUE THREAD

**Issue by Mirakelor** [snarfed/bridgy-fed#579]
![image](https://github.com/snarfed/bridgy-fed/assets/63326519/59cb77a4-ff8a-40ef-bdf8-56a591863979)
![image](https://github.com/snarfed/bridgy-fed/assets/63326519/122d100d-b1d0-4529-b247-92cc47f19efb)
But......
![image](https://github.com/snarfed/bridgy-fed/assets/63326519/1d755704-c7d2-4144-b7f3-1e7380feed90)
Nothing is here...
It's on [Misskey](https://submarin.online)

---

![image](https://github.com/snarfed/bridgy-fed/assets/63326519/21dbf98b-07e2-4418-9dba-4ada748ba9b7)
Can't even find the account.
It's on [Dolphin](https://fuckc.cf)

---

![image](https://github.com/snarfed/bridgy-fed/assets/63326519/3054d6d4-992a-4663-812a-a239ecab9170)
It was on [Mastdon](https://best-friends.chat).I was trying to follow the account.But it failed to find it.

---

Thanks For Help❤️.

**Comment by Mirakelor** [comment]
Mastdon succeeded.
Misskey,dolphin are not supported.
Thanks.

**Comment by snarfed** [comment]
Thanks for filing and for all the details! We definitely hope to support all AP implementations eventually. #375 tracks Misskey support, and I've filed #1510 for Dolphin. Feel free to add details to both!
