### ISSUE TITLE
Error 400 when `<link rel="alternate">` uses a relative link

### ISSUE THREAD

**Issue by fluffy-critter** [snarfed/bridgy-fed#58]
Example:

```
$ curl -d source=https://beesbuzz.biz/blog/chatter/4128-More-ActivityPub-testing -d target=https://fed.brid.gy/ https://fed.brid.gy/webmention
<html>
 <head>
  <title>400 Bad Request</title>
 </head>
 <body>
  <h1>400 Bad Request</h1>
  The server could not comply with the request since it is either malformed or otherwise incorrect.<br /><br />
Bad URL feed: Invalid URL 'feed': No schema supplied. Perhaps you meant http://feed?


 </body>
</html>
```

The link that seems to be throwing it off in the source page is:

```
    <link rel="alternate" type="application/atom+xml" title="Atom feed" href="feed" />
```

which is a relative link to the Atom feed for that page (which should resolve to `https://beesbuzz.biz/blog/chatter/feed`).

It seems that whenever any error like this is encountered -- even if it's one that shouldn't have any impact on Bridgy Fed's operation -- it completely dies, preventing the ActivityPub post from happening for that page. I'm not finding any rhyme or reason to it, however.

Another example:

```
$ curl -d source=https://beesbuzz.biz/blog/1912-Slowcial-networking -d target=https://fed.brid.gy/ https://fed.brid.gy/webmention
<html>
 <head>
  <title>400 Bad Request</title>
 </head>
 <body>
  <h1>400 Bad Request</h1>
  The server could not comply with the request since it is either malformed or otherwise incorrect.<br /><br />
Target post https://platforms.fyi/ has no Atom link


 </body>
</html>
```

Maybe no ping would happen to the linked resource, but I still want, for example, my ActivityPub publish to happen.

**Comment by snarfed** [comment]
sorry for the trouble, and thanks for filing, and for all the details. agreed, looks like a bug. should be an easy fix,

**Comment by snarfed** [comment]
ok, relative atom hrefs are now fully qualified.

your example webmention here now fails with `501 Sorry, post activities are not supported yet.` since bridgy fed only supports replies to AP or OStatus sites, and your post is a reply to your own site. obviously not a great error message; i'll improve it too.

**Comment by fluffy-critter** [comment]
Well, there's more to it than that, I don't think that Bridgy Fed should be generating an outright failure for only partial failures - like, the main reason I use Bridgy Fed is to post notifications to my ActivityPub timeline. I don't really care about the other mention cases since I'm already able to send Webmentions, obviously.

**Comment by snarfed** [comment]
[discussed lots more on IRC.](https://chat.indieweb.org/dev/2019-09-23#t1569266086163700)

**Comment by fluffy-critter** [comment]
Summary of the discussion: I was abusing post types in ways that weren't actually interoperable. I've changed my templates to better fit the use case of `in-reply-to` and `like-of`, as such.
