### ISSUE TITLE
Returning 400: author https://fed.brid.gy/<domain> is on Bridgy Fed, which is not supported

### ISSUE THREAD

**Issue by tomasparks** [snarfed/bridgy-fed#597]
i am getting a 400 error message when I try to update my post

> I 2023-07-22 10:31:32.600852+00:00 Returning 400: author https://fed.brid.gy/tomasparks.name is on Bridgy Fed, which is not supported
>  E 2023-07-22 10:31:32.601256+00:00 <class '[werkzeug.exceptions.BadRequest](http://werkzeug.exceptions.badrequest/)'>: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

https://fed.brid.gy/log?path=%2F_ah%2Fqueue%2Fwebmention%2C%2Finbox&start_time=1690021892&key=https%3A%2F%2Fgallery.tomasparks.name%2Ftrips%2F2023%2F02%2F12%2F063545-MADV.html

**Comment by snarfed** [comment]
Uh oh. Sorry for the trouble, thanks for reporting, will look!

**Comment by snarfed** [comment]
Big refactoring recently, this subdomain bug (gallery.tomasparks.name vs tomasparks.name) evidently snuck Fixed now, will be deployed to prod in ~5m. Thanks again for reporting!
