### ISSUE TITLE
cant follow or post

### ISSUE THREAD

**Issue by tomasparks** [snarfed/bridgy-fed#599]
I can only update old post

follow:
> Source	https://notes.tomasparks.name/mastodon/20230624-195600.html
> Target	https://fed.brid.gy/
> Date: Jul 24, 11:48am
> Enqueued task projects/bridgy-federated/locations/us-central1/queues/webmention/tasks/90693072349722434171.
https://telegraph.p3k.io/webmention/17xdLB2vHveI9njP7E/details

post:
> Source	https://gallery.tomasparks.name/trips/2023/02/12/063533-MADV.html
> Target	https://fed.brid.gy/
> Date: Jul 24, 12:02pm
> Enqueued task projects/bridgy-federated/locations/us-central1/queues/webmention/tasks/94412877575333131171.

**Comment by snarfed** [comment]
Oh no, man, we really messed up subdomain support. I think I see the problem here, will fix. Sorry!

**Comment by tomasparks** [comment]
:)

**Comment by snarfed** [comment]
OK, it was both that and the the special case we added for your subdomains in #433, which is unusual and not as well tested or exercised. Hopefully fixed now though. @tomasparks feel free to try again!
