### ISSUE TITLE
disable gzip compression on home page

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#6]
[requested by @mblaney.](https://chat.indieweb.org/dev/2017-10-16#t1508120460584000) `/` is a [static file handler](https://cloud.google.com/appengine/docs/standard/python/config/appref#handlers_element), so the full serving path is google's. it currently always gzip-compresses the response and returns the `Content-Encoding: gzip` header.

oddly, i haven't found a way to ask it not to. [the HTTP spec says](https://tools.ietf.org/html/rfc7231#section-5.3.4) omitting `Accept-Encoding` says you're ok with anything, _but_ `Accept-Encoding: identity` should prevent it...but it doesn't.

also:
> Note: In the absence of a Content-Type header provided by your application, a default Content-Type: text/html header will be set, but the automatic gzip compression will not be applied.
* https://cloud.google.com/appengine/docs/standard/python/how-requests-are-handled#response_compression
* https://cloud.google.com/appengine/kb/#compression

...but that's obviously not happening. :/

**Comment by snarfed** [comment]
looks like it's this app engine bug: https://issuetracker.google.com/issues/37938470

**Comment by snarfed** [comment]
cc @swentel in case this is what you mentioned earlier today.

**Comment by swentel** [comment]
Ah right hehe. I managed to fix this on my side with this pull request: https://github.com/indieweb/mention-client-php/pull/35

So I'm ok with it at the moment.

**Comment by snarfed** [comment]
Google closed the App Engine bug ^ as won't fix, intended behavior, and I don't know that anyone here needs this any more. Tentatively closing.
