### ISSUE TITLE
Odd webmention source URL for a like?

### ISSUE THREAD

**Issue by gRegorLove** [snarfed/bridgy-fed#600]
There might be some oddities with the `/convert` URLs in webmentions. Tonight I received webmention:

```
source=https://fed.brid.gy/convert/activitypub/web/https:/xoxo.zone/users/artlung%23likes/591665
target=https://gregorlove.com/2023/07/weekend-roundup/
```

When I fetch the source I get a 301 to `https://ap.brid.gy/convert/web/https:/xoxo.zone/users/artlung#likes/591665?`

Is that meant to be `^^` instead of `#`?

The HTML source of that appears to be an h-card with no `id=likes`, and a meta-refresh to the profile:

HTML:
```html
<!DOCTYPE html>
<html>
<head><meta charset="utf-8">
<meta http-equiv="refresh" content="0;url=https://xoxo.zone/@artlung"></head>
<body class="">

  <span class="h-card">
    <data class="p-uid" value="https://xoxo.zone/users/artlung"></data>
    <a class="p-name u-url" href="https://xoxo.zone/@artlung">Joe Crawford</a>
    <span class="p-nickname">artlung</span>
    <img class="u-photo" src="https://xoxo-media.sfo2.cdn.digitaloceanspaces.com/accounts/avatars/107/406/944/287/698/280/original/3ed98f44a50a3716.jpeg" alt="" />
<img class="u-photo" src="https://xoxo-media.sfo2.cdn.digitaloceanspaces.com/accounts/headers/107/406/944/287/698/280/original/00533750f17a4e6b.png" alt="" />
  </span>

</body>
</html>
```

mf2:
```json
"type": [
    "h-card"
],
"properties": {
    "uid": [
        "https://xoxo.zone/users/artlung"
    ],
    "name": [
        "Joe Crawford"
    ],
    "nickname": [
        "artlung"
    ],
    "url": [
        "https://xoxo.zone/@artlung"
    ],
    "photo": [
        {
            "value": "https://xoxo-media.sfo2.cdn.digitaloceanspaces.com/accounts/avatars/107/406/944/287/698/280/original/3ed98f44a50a3716.jpeg",
            "alt": ""
        },
        {
            "value": "https://xoxo-media.sfo2.cdn.digitaloceanspaces.com/accounts/headers/107/406/944/287/698/280/original/00533750f17a4e6b.png",
            "alt": ""
        }
    ]
}
```

**Comment by snarfed** [comment]
Ugh, I can't catch a break on these wm source URLs. Thanks for the heads up. I switched from ^^ back to %23 the other day, https://github.com/snarfed/bridgy-fed/issues/581#issuecomment-1648664459 , because ^^ never actually solved the problem it was aiming at, https://github.com/pfefferle/wordpress-webmention/issues/359 , and it was confusing people. I'll fix this.

**Comment by gRegorLove** [comment]
@snarfed Is there something wrong on my end parsing the source URL? I wasn't sure because I saw the encoded `%2523` in the original, but when I fetch it, it seems to be ending up with the un-encoded `#`

**Comment by snarfed** [comment]
No, the redirected `Location` with the raw `#` was just a BF bug, and ideally it should have used the second, non-redirected URL as the source anyway.

**Comment by snarfed** [comment]
Should be fixed now, feel free to retry!

**Comment by gRegorLove** [comment]
Thanks! https://fed.brid.gy/convert/activitypub/web/https:/xoxo.zone/users/artlung%23likes/591665 looks right when I fetch in the browser now.

I think my webmention URL handling does have an issue. It appears to be un-encoding before fetching, so it still ends up with the Mastodon profile, but that's on my end.
