### ISSUE TITLE
Posts not completing - 500 error

### ISSUE THREAD

**Issue by TechLifeWeb** [snarfed/bridgy-fed#603]
We chatted about my posting issues for TechLifeWeb on the idieweb chat the other day but I thought I'd post here for easier tracking.  It seems like BF is seeing my new posts which is an improvement over the other day but now it is erroring. See this [BF Log FIle](https://fed.brid.gy/log?path=%2F_ah%2Fqueue%2Fwebmention%2C%2Finbox&start_time=1690469207&key=https%3A%2F%2Ftechlifeweb.com%2Fblog%2F2023%2F07%2F2023-07-27-post-56%2F%23bridgy-fed-create).  It gets in kind of a loop a little way down then finishes with a 500 Internal Server Error.

**Comment by snarfed** [comment]
https://botsin.space/@agora has an unusual bit of AS2 that BF choked on. Fix will be deployed within 5m, feel free to retry then!

**Comment by TechLifeWeb** [comment]
Looks like it's working, thanks! Seems Post counts are showing up on
Mastodon too which is cool.
