### ISSUE TITLE
Content in Atom feed isn't necessarily XHTML

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#624]
@aciccarello reports that Inoreader is failing to ingest our Atom:
![image](https://github.com/snarfed/bridgy-fed/assets/778068/a0e3b971-0007-437c-a98a-bb47e5bf97ee)

Here's validation output: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Ffed.brid.gy%2Fuser%2Fciccarello.me%2Ffeed%3Fformat%3Datom . I expect it's_probably [_XML parsing error: <unknown>:778:629: mismatched tag_](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Ffed.brid.gy%2Fuser%2Fciccarello.me%2Ffeed%3Fformat%3Datom#l778), due to us injecting HTML content from Mastodon directly into entries and claiming it's XHTML.

**Comment by snarfed** [comment]
Switched content from XHTML to HTML in CDATA. @aciccarello let me know if this made Inoreader happy!

**Comment by aciccarello** [comment]
I don't see any issues! Thanks for the fix. I'll probably check again tomorrow to make sure.
