### ISSUE TITLE
Repost of a Mastodon status does not show up

### ISSUE THREAD

**Issue by rretsiem** [snarfed/bridgy-fed#64]
Since posting to fed.brid.gy works fine, I tried to repost a status on Mastodon today from my site. I used Telegraph to send the request and got a “202” back, so everything seems fine.
However the repost/reblog does not appear on my account @renem.net@renem.net at Toots&amp;Replies. Also the repost wasn’t counted on the original status. Here is the log from fed.brid.gy for this repost-of action.
I don’t know if this is the right channel to ask, or better via IRC, so I try it here first, but feel free to close this here and point me to the right “support channel”. Thanks!

(Originally published at: https://renem.net/notes/github/2020-03-24-1/)

**Comment by snarfed** [comment]
thanks for the report, and sorry for the trouble! not sure what's up here, but I'll look soon.

**Comment by snarfed** [comment]
[here's the full log.](https://fed.brid.gy/log?key=https://renem.net/notes/reposts/2020-03-24-1/+https://social.tchncs.de/@kuketzblog/103877135239066914&start_time=1585046779) and here's the AP `Announce` request Bridgy Fed `POST`ed to https://social.tchncs.de/users/kuketzblog/inbox at 2020-03-24 10:46:23 UTC:

```json
{
  "id": "https://fed.brid.gy/r/https://renem.net/notes/reposts/2020-03-24-1/",
  "published": "2020-03-24T11:17:59+00:00",
  "summary": "An jeder Ecke wird gerade Zoom für Videokonferenzen empfohlen. Wer die Datenschutzerklärung gelesen und verstanden hat, wird Zoom vermutlich nicht nutzen wollen. Absolut gruselig. https://zoom.us/de-de/privacy.html - Mike Kuketz via Mastodon",
  "content": "<blockquote>\n<p>An jeder Ecke wird gerade Zoom für Videokonferenzen empfohlen. Wer die Datenschutzerklärung gelesen und verstanden hat, wird Zoom vermutlich nicht nutzen wollen. Absolut gruselig.\n<a href=\"https://zoom.us/de-de/privacy.html\">https://zoom.us/de-de/privacy.html</a> - <a href=\"https://social.tchncs.de/@kuketzblog\">Mike Kuketz via Mastodon</a></p>\n</blockquote>",
  "url": "https://fed.brid.gy/r/https://renem.net/notes/reposts/2020-03-24-1/",
  "actor": {
    "url": "https://fed.brid.gy/r/https://renem.net/about",
    "type": "Person",
    "name": "René",
    "preferredUsername": "renem.net",
    "id": "https://fed.brid.gy/renem.net"
  },
  "@context": "https://www.w3.org/ns/activitystreams",
  "type": "Announce",
  "object": "https://social.tchncs.de/users/kuketzblog/statuses/103877135239066914",
  "tag": [{
      "type": "Tag",
      "name": "datenschutz"
    }, {
      "type": "Tag",
      "name": "reposts"
    }],
  "cc": [
    "https://www.w3.org/ns/activitystreams#Public",
    "https://social.tchncs.de/users/kuketzblog",
    "https://social.tchncs.de/users/kuketzblog/followers"
  ]
}
```

**Comment by snarfed** [comment]
sadly, i don't know if i'll be able to debug this much more. Mastodon occasionally accepts posts from Bridgy Fed, and responds with HTTP 202, but then doesn't show them, and we don't know why. [other example issues here.](https://github.com/snarfed/bridgy-fed/issues?q=is%3Aissue+202)

sorry for the bad news. @rretsiem if you know the social.tchncs.de admin(s), feel free to ask them for any related server logs from around this time, 2020-03-24 10:46:23 UTC, they might be able to help!

**Comment by rretsiem** [comment]
Got an [answer to my question](https://social.tchncs.de/@milan/103940848640254938) for the logs from the admin ([@Milan](https://social.tchncs.de/@milan)) of the instance. But sadly he can’t help here. So I think it will be as mysterios as it was.

(Originally published at: https://github.com/snarfed/bridgy-fed/issues/64#issuecomment-605541812)

**Comment by snarfed** [comment]
thanks for following up! and sorry we don't have a better conclusion here. ah well.
