### ISSUE TITLE
Mastodon 4.2 hashtag compatibility

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#648]
Mastodon 4.2 recently improved/changed its hashtag support. Notably, it supposedly now supports hashtags that aren't explicitly in HTML links in `content`. Great!

@aciccarello reports that this worked retroactively in some of his older posts, https://github.com/snarfed/bridgy-fed/issues/45#issuecomment-1734325736 , but it seems like @tantek's recent attempts may not be fully working. Example: https://indieweb.social/@tantek.com@tantek.com/111123371912147974 , hashtags in content were rewritten to local instance tag search, like before, but they don't show up at the bottom of the post? Or are they not supposed to if they're explicitly in the post?

I don't personally plan to prioritize researching this right now, maybe later. I'd love for someone to dig in though!

**Comment by aciccarello** [comment]
That may be by design. I can't find the source but I read somewhere that the tags only appear in the bottom section if they are at the end of the post or only in the metadata. So inline hashtags are not repeated below.

**Comment by snarfed** [comment]
@tantek's recent post https://tantek.com/2023/277/b1/thoughtful-reading-writing-web correctly triggered Mastodon 4.2's new hashtags! eg https://indieweb.social/@tantek.com@tantek.com/111181125921137414

Tentatively closing. Feel free to reopen if necessary!
