### ISSUE TITLE
Only first link is checked

### ISSUE THREAD

**Issue by nekr0z** [snarfed/bridgy-fed#65]
[This log](https://fed.brid.gy/log?key=https%3A%2F%2Fevgenykuznetsov.org%2Fen%2Freactions%2F2020%2Fhydroxychloroquine-4%2F+https%3A%2F%2Fevgenykuznetsov.org%2Fen%2Freactions%2F2020%2F33-stats%2F&start_time=1591250515).

The note in question has three "in-reply-to" links, one for a normal page, one for a Fediverse page, and one for a twit.

Brid.gy does figure it out and sends the reply to the tweet properly. Brid.gy Fed only checks the first link, sees it's not Fediverse and gives up.

**Comment by snarfed** [comment]
ooh, sorry for the trouble, and thanks for filing! will fix.
