### ISSUE TITLE
Akkoma compatibility

### ISSUE THREAD

**Issue by snan** [snarfed/bridgy-fed#651]
This is more an Akkoma issue than a bridgy-fed issue but FYI:

I didn't find the bridgy post when searching for your blog URL on Akkoma but when I went through the source and dug out the rel alternate for that post that pointed directly to bridgy and searched for that, that worked.

I.e. searching for https://snarfed.org/2023-09-23_bridgy-fed-status-update-6 did not work, searching for https://fed.brid.gy/r/https://snarfed.org/2023-09-23_bridgy-fed-status-update-6 did work.

**Comment by snarfed** [comment]
Yup, that's sadly how Bridgy Fed works right now. Most fediverse servers require activity/object ids to be on the same domain that's sending them, hence the `fed.brid.gy/r/` wrapper.

There's actually a workaround, https://fed.brid.gy/docs#searchable , I just haven't gotten around to doing that on my own site. I should though, thanks for the nudge.

**Comment by snan** [comment]
No, you already have that rel alternate in there, which is how I found the 
post, by looking at the blog post's HTML source manually so I could copy 
it from there.

In other words, even with that alternate rel link it didn't work until I 
explicitly searched for the bridge-wrapped version.

**Comment by snarfed** [comment]
Hah yeah, I discovered that just now too, thanks. Sounds like Akkoma may just not support this then?

Akkoma seems to be having trouble with Bridgy Fed in multiple ways. Eg searches for users (ie WebFinger + AP actor lookup) seems unhappy. Also, I sent two replies to posts of yours just now, https://snarfed.org/2023-09-26_idiomdrottning and https://snarfed.org/2023-09-26_sandra-cw-inappropriately-named-term-indieweb-social , and your instance 500ed on the inbox delivery POSTs for both. Full logs linked on https://fed.brid.gy/web/snarfed.org

Related background: #374

**Comment by snarfed** [comment]
Reported 8 mos ago in https://akkoma.dev/AkkomaGang/akkoma/issues/438 , they debugged but I suspect they've now forgotten it 😢

**Comment by snan** [comment]
@***@***.*** shows up just fine with zero issues, @***@***.*** 
does not. 🤷🏻‍♀️

**Comment by FloatingGhost** [comment]
> Reported 8 mos ago in https://akkoma.dev/AkkomaGang/akkoma/issues/438 , they debugged but I suspect they've now forgotten it 😢

we attempted to debug, could not reproduce based on published data formats, and setting up a live instance to test proved incredibly hard so it was dropped

**Comment by snarfed** [comment]
Hi @FloatingGhost! Sorry for the trouble, thank you for looking! I'll update that issue and add one of the replies that @snan's instance 500ed on just now.

**Comment by snarfed** [comment]
> @snarfed.org@fed.brid.gy shows up just fine with zero issues, @snarfed.org@snarfed.org does not. 🤷🏻‍♀️

Sigh. @snarfed.org@snarfed.org serves WebFinger correctly, and points to a valid matching AP actor. My guess is that Akkoma is either 1) being very strict and only allowing the same domain that the actor is served from, or 2) not following or supporting WebFinger redirects.

**Comment by snarfed** [comment]
Merging into https://github.com/snarfed/bridgy-fed/issues/374
