### ISSUE TITLE
Project has no LICENSE

### ISSUE THREAD

**Issue by aschrijver** [snarfed/bridgy-fed#67]
I am creating a new _developer resources_ page for the [Feneas wiki research area](https://git.feneas.org/feneas/fediverse/-/wikis/Home) and noticed that your project has no LICENSE, which technically makes it proprietary and not open-source.

On the [ActivityPub watchlist](https://git.feneas.org/feneas/fediverse/-/wikis/watchlist-for-activitypub-apps) you are referred to as having `CC0` public domain license, but I will have to correct that, unless there is clarity on the actual license you adhere to.

**Comment by snarfed** [comment]
Hi! Thanks for your interest in Bridgy Fed. Our license notice is [near the top of the README file:](https://github.com/snarfed/bridgy-fed#readme)

> License: This project is placed in the public domain.

It's just public domain, not CC0 specifically, but sounds like that wasn't the concern here.

**Comment by aschrijver** [comment]
Thank you, I have updated in the page accordingly, which just had its initial commit:

- [Watchlist for ActivityPub developer resources](https://git.feneas.org/feneas/fediverse/-/wikis/Watchlist-for-ActivityPub-developer-resources)
