### ISSUE TITLE
Mastodon Translate link

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#681]
Bridged posts in Mastodon are now showing a _Translate_ link. Why? Can we suppress it?

We wouldn't want to suppress it if the fediverse user viewing it is using a different language than the post itself though, right? That implies that we'd need to determine the language of posts we bridge. Ugh.

https://indieweb.org/language says this is the `lang` HTML attr, which is element-scoped. Evidently at least some parsers expose this, eg php-mf2 puts it in a `lang` field at the top level of each item, eg https://pin13.net/mf2/?url=https://snarfed.org/ , but mf2py doesn't support it at all yet, eg https://python.microformats.io/?url=https%3A%2F%2Fsnarfed.org%2F&parser=html5lib . Sigh. (Background: https://microformats.org/wiki/microformats2-parsing-brainstorming#Parse_language_information )

@manton and @sknebel looked into this a bit, https://chat.indieweb.org/dev/2023-10-10#t1696968103063600 :
> manton From what I can tell, the only language set is using “contentMap” with “en” for the content… But that means duplicate the content text in every single JSON. Seems bloated. Anyone have experience with this? Maybe I’m missing something?
> &nbsp;&nbsp;  I’m seeing the same “Translate” links on Bridgy Fed posts too.
> sknebel manton: is that whats done in the messages your server gets?
> manton sknebel Yes, I’m looking at ActivityPub JSON from other Mastodon servers and it looks like this:
>   ```
>   "content": "Text here.",
>   "contentMap": {
>   "en": "Text here again."
>   }
>   ```
>   I also see some messages from PeerTube and it looks different:
>   ```
>   "language": {
>     "name": "English"
>     "identifier": "en",
>   }
>   ```
> sknebel seems thats what AS says, its default-language form looks different (based on json-ld) than the peertube version
> &nbsp;&nbsp; https://www.w3.org/TR/activitystreams-core/#naturalLanguageValues
> manton Ah, thanks. I was looking through activitystreams-vocabulary which only mentions contentMap.

**Comment by manton** [comment]
I also found this Mastodon issue that is related: https://github.com/mastodon/mastodon/issues/26249

**Comment by manton** [comment]
I might try adding `@language` as per activitystreams-core to see if Mastodon respects it. I'm not really sure if that's better than `contentMap`, though. I expect that very few ActivityPub implementations have any JSON-LD smarts at all.

**Comment by snarfed** [comment]
Confirmed, duplicating `content: ...` into `contentMap: {en: ...}` removes the Translate link. Thanks @manton!

I'll add that, and I'll leave this open to track doing this "right," ie fully supporting language metadata in AS1, mf2, Bluesky, etc. Looks like mf2py at least is close! https://github.com/microformats/mf2py/issues/150, https://github.com/microformats/mf2py/pull/203

**Comment by manton** [comment]
For completeness in this thread, I did end up adding `contentMap`, not `@language`.
