### ISSUE TITLE
For replies, don't send mentions to the original post's author

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#686]
Looks like we started doing unintentionally this as part of #633/#493. Should hopefully be an easy fix.

**Comment by srijan** [comment]
I'm trying out fed.brid.gy, and it looks like only mentions are sent, not replies.

See log: https://fed.brid.gy/log?start_time=1698309500&key=https%3A%2F%2Fmas.to%2Fusers%2Fsrijan%2Fstatuses%2F111300414574401571%2Factivity

The two webmentions sent were:

1. https://webmention.io/srijan.ch/webmention/w4uUzjaWbk8EHkjLoTnT - a "wm-property": "mention-of" to the post URL
2. https://webmention.io/srijan.ch/webmention/5wDV6GRGrtHeZM5yqplO - a mention to the homepage URL.

I expected the first one to be a in-reply-to instead of a mention-of.

**Comment by snarfed** [comment]
Hmm. Looking at the webmention source URL https://ap.brid.gy/convert/web/https:/mas.to/users/srijan/statuses/111300414574401571/activity (same for both webmentions), it 301 redirects to https://ap.brid.gy/convert/web/https://mas.to/users/srijan/statuses/111300414574401571 , which has this HTML with `u-in-reply-to` pointing to https://srijan.ch/notes/2023-10-26-001 near the bottom.

Not sure why webmention.io didn't catch that. cc @aaronpk

```html
<!DOCTYPE html>
<html>
<head><meta charset="utf-8">
<meta http-equiv="refresh" content="0;url=https://mas.to/@srijan/111300414574401571"></head>
<body class="">

<article class="h-entry">
  <span class="p-uid">https://mas.to/users/srijan/statuses/111300414574401571</span>
  
  <time class="dt-published" datetime="2023-10-26T08:39:08+00:00">2023-10-26T08:39:08+00:00</time>
  
  <span class="p-author h-card">
    <data class="p-uid" value="https://mas.to/users/srijan"></data>
    <a class="p-name u-url" href="https://mas.to/@srijan">Srijan Choudhary</a>
    <span class="p-nickname">srijan</span>
    <img class="u-photo" src="https://media.mas.to/masto-public/accounts/avatars/111/276/301/174/418/921/original/100dad9f447a27a3.jpeg" alt="" />
  </span>

  <a title="mas.to/@srijan/111300414574401571" class="u-url" href="https://mas.to/@srijan/111300414574401571">mas.to/@srijan/111300...</a>
  <div class="e-content p-name">
  
  <p><span class="h-card" translate="no"><a href="https://fed.brid.gy/r/https://srijan.ch" class="u-url mention">@<span>srijan.ch</span></a></span> Test reply from mastodon. Trial 3.</p>
<a class="u-mention" aria-hidden="true" href="https://srijan.ch/"></a>
  </div>

  <a class="u-in-reply-to" href="https://srijan.ch/notes/2023-10-26-001"></a>
</article>
</body>
</html>
```

**Comment by snarfed** [comment]
webmention.io uses XRay, right? XRay sees the `u-in-reply-to` fine: https://xray.p3k.app/parse?url=https://ap.brid.gy/convert/web/https:/mas.to/users/srijan/statuses/111300414574401571/activity&pretty=true

**Comment by srijan** [comment]
@snarfed - I tested this again today, and it looks like now I'm getting two webmentions of type reply - one to the post page and one to the author/home page.

Log: https://fed.brid.gy/log?start_time=1698690012&key=https%3A%2F%2Fmas.to%2Fusers%2Fsrijan%2Fstatuses%2F111325348389705706%2Factivity

**Comment by snarfed** [comment]
Yes! Sorry for the trouble, that happens with replies that also @-mention you. https://github.com/snarfed/bridgy-fed/issues/686 tracks de-duping those.

**Comment by snarfed** [comment]
Hopefully fixed now 🤞
