### ISSUE TITLE
Delete @realize.be@realize.be

### ISSUE THREAD

**Issue by swentel** [snarfed/bridgy-fed#69]
So I switched completely to swentel@realize.be using the activitypub module for Drupal (still need to importing my followers, but I have them, so that's ok). The typical actions like posting, replying, liking etc work, accept/follow or incoming replies back as well, which is great!

I've disabled the .htaccess redirect lines, however, even then a reply from mastodon on a post from my new handle triggered a webmention from fed.brid.gy too (besides an inbox request too from mastodon), which is interesting. It happened on https://realize.be/notes/2182 (the 'Wow that looks awesome!' comment). Not sure why that is exactly, but oh well. 

That said, you can simply remove my account :)
Or redirect urls back to my site, but I would definitely ignore all other requets (especially inbox)

Thanks for the service!

**Comment by snarfed** [comment]
congrats on the progress on your Drupal module! that's exciting to hear!

and...interesting indeed. Bridgy Fed is relatively stateless, it doesn't actually store accounts at all. it just responds to webmentions and AP requests. the only state it stores per user is their list of followers, and that's only used when it receives a webmention for a new post, which isn't what happened here.

in this case, bridgy fed got an AP `Create` request from mastodon.social, specifically a `POST` to `https://fed.brid.gy/realize.be/inbox` from 148.251.134.157, User-Agent `http.rb/4.4.1 (Mastodon/3.2.0; +https://mastodon.social/)`, with the body below. maybe mastodon cached your inbox URL or something related?

```json
{
  "@context": [
    "https://www.w3.org/ns/activitystreams",
    {
      "ostatus": "http://ostatus.org#",
      "atomUri": "ostatus:atomUri",
      "inReplyToAtomUri": "ostatus:inReplyToAtomUri",
      "conversation": "ostatus:conversation",
      "sensitive": "as:sensitive",
      "toot": "http://joinmastodon.org/ns#",
      "votersCount": "toot:votersCount"
    }
  ],
  "id": "https://mastodon.social/users/swentel/statuses/105009853277426090/activity",
  "type": "Create",
  "actor": "https://mastodon.social/users/swentel",
  "published": "2020-10-10T09:46:40Z",
  "to": [
    "https://www.w3.org/ns/activitystreams#Public"
  ],
  "cc": [
    "https://mastodon.social/users/swentel/followers",
    "https://realize.be/user/1/activitypub/swentel"
  ],
  "object": {
    "id": "https://mastodon.social/users/swentel/statuses/105009853277426090",
    "type": "Note",
    "summary": null,
    "inReplyTo": "https://realize.be/notes/2182",
    "published": "2020-10-10T09:46:40Z",
    "url": "https://mastodon.social/@swentel/105009853277426090",
    "attributedTo": "https://mastodon.social/users/swentel",
    "to": [
      "https://www.w3.org/ns/activitystreams#Public"
    ],
    "cc": [
      "https://mastodon.social/users/swentel/followers",
      "https://realize.be/user/1/activitypub/swentel"
    ],
    "sensitive": false,
    "atomUri": "https://mastodon.social/users/swentel/statuses/105009853277426090",
    "inReplyToAtomUri": "https://realize.be/notes/2182",
    "conversation": "tag:mastodon.social,2020-10-02:objectId=199134319:objectType=Conversation",
    "content": "<p><span class=\"h-card\"><a href=\"https://realize.be/user/1\" class=\"u-url mention\">@<span>swentel</span></a></span> Wow that looks awesome!</p>",
    "contentMap": {
      "en": "<p><span class=\"h-card\"><a href=\"https://realize.be/user/1\" class=\"u-url mention\">@<span>swentel</span></a></span> Wow that looks awesome!</p>"
    },
    "attachment": [],
    "tag": [
      {
        "type": "Mention",
        "href": "https://realize.be/user/1/activitypub/swentel",
        "name": "@swentel@realize.be"
      }
    ],
    "replies": {
      "id": "https://mastodon.social/users/swentel/statuses/105009853277426090/replies",
      "type": "Collection",
      "first": {
        "type": "CollectionPage",
        "next": "https://mastodon.social/users/swentel/statuses/105009853277426090/replies?only_other_accounts=true&page=true",
        "partOf": "https://mastodon.social/users/swentel/statuses/105009853277426090/replies",
        "items": []
      }
    }
  },
  "signature": {
    "type": "RsaSignature2017",
    "creator": "https://mastodon.social/users/swentel#main-key",
    "created": "2020-10-10T09:46:40Z",
    "signatureValue": "..."
  }
}
```

**Comment by swentel** [comment]
Actually, I figured it out by looking at the request. In cc, it says the followers of my mastodon user, and in fact, @realize.be@realize.be is following that user. I remember doing that command line when I was testing to connect my site in the very beginning with fed.brid.gy and debugging payloads for posts/replies etc, so it's totally normal.

I don't think I'll be able to undo that follow, because I need the original id of the follow request, which I don't have anymore :)

I know mastodon has the concept of a 'Move' activity, and also defines a property called 'alsoKnownAs' for the user. I'll try to read up if I can use the first option to send a command line request (I still have my private key) or whether the second option would make a difference.

**Comment by snarfed** [comment]
hi @swentel! any luck moving this account?

**Comment by swentel** [comment]
Hey @snarfed , haven't had time to look further at this yet, busy implementing more important functionality :)

That said, I might have found another approach: Mastodon sends out DELETE requests where actor and object are the same (the  id of a fediverse user) to notify other platforms that this user has been deleted. So I think ultimately, that's the best approach. The request is signed by the author that needs to be deleted (afaics, when you delete an account on mastodon, it's basically blocked, unless you're an admin, or ask an admin to take over that account).

I receive dozens of those requests every day in my inbox (I started to ignore them now), so it looks like it doesn't care whether you follow it on the local platform or not, and I assume that once it has arrived at a domain, that it's ok. (but I'd have to read the source for that to be honest).

**Comment by snarfed** [comment]
hah, yes! i see big spikes of those on bridgy fed regularly. i even temporarily had to start ignoring them to help scaling: dba533a14bd4f3509556163790ab27623d694b29

you have your private key now, right? feel free to try sending a `Delete` to see if that helps!

tentatively closing this for now, but feel free to reopen.
