### ISSUE TITLE
setting up with gitlab pages

### ISSUE THREAD

**Issue by vanangamudi** [snarfed/bridgy-fed#71]
is there any guide to set this up with gitlab pages?

**Comment by snarfed** [comment]
Hi! Sorry, no, there isn't as far as I know. Feel free to add instructions in a PR if you get it working though!

**Comment by snarfed** [comment]
tentatively closing. feel free to reopen!

**Comment by pinage404** [comment]
Hello,

I am trying to set up with GitLab pages

I tried with [GitLab Pages redirects](https://docs.gitlab.com/user/project/pages/redirects/)

I put this in [the `_redirects` file](https://gitlab.com/pinage404/git-gamble/-/blob/1305fcbc6dfe5927c647d7231f914d1a592f6406/docs/src/_redirects#L9)

```txt
/.well-known/host-meta* https://fed.brid.gy/.well-known/host-meta:splat 302
/.well-known/webfinger* https://fed.brid.gy/.well-known/webfinger:splat 302
```

But it seems not enougth, i get 404 page

https://git-gamble.is-cool.dev/.well-known/host-meta
https://git-gamble.is-cool.dev/.well-known/webfinger

Does anyone have a clue ?

Did someone succeed to set up Bridgy Fed with GitLab Pages ?

**Comment by pinage404** [comment]
It is blocked by this issue https://gitlab.com/gitlab-org/gitlab-pages/-/work_items/1125
