### ISSUE TITLE
Support RSS feeds as fediverse publishers?

### ISSUE THREAD

**Issue by skorokithakis** [snarfed/bridgy-fed#72]
I have a static website, and I've been wanting to expose the site's RSS feed as a fediverse publisher, so eg people can follow my site on Mastodon. Is this possible with Bridgy Fed right now? Could it be?

Thanks!

**Comment by snarfed** [comment]
Hey, sure! If you just want people in the fediverse to see your posts, you don't need Bridgy Fed at all. You just need an Atom Feed and maybe a couple other bits. Details: https://github.com/tootsuite/mastodon/issues/1441#issuecomment-302969948 . There's probably a better tutorial somewhere newer.

Bridgy Fed is for deeper integration, eg if you want to like/reply/boost toots from your web site, and vice versa.

**Comment by skorokithakis** [comment]
Ahh, great, thanks! Would you mind adding something to the guide, for people like me?

**Comment by snarfed** [comment]
Sure! Will do.
