### ISSUE TITLE
Can't reply to Mastodon, public key required?

### ISSUE THREAD

**Issue by nekr0z** [snarfed/bridgy-fed#73]
https://fed.brid.gy/log?key=https%3A%2F%2Fevgenykuznetsov.org%2Fen%2Freactions%2F2020%2Fopen-source-backup%2F+https%3A%2F%2Ffed.fab.industries%2F%40fabsh%2F105464589804490282&start_time=1609273046

**Comment by andrewshadura** [comment]
Same here, not sure what’s the reason.

**Comment by snarfed** [comment]
Ugh. Thanks for the report. I'm not sure either. @nekr0z's site has the webfinger redirect working right, eg https://evgenykuznetsov.org/.well-known/webfinger?resource=acct:evgenykuznetsov.org@evgenykuznetsov.org redirects to Bridgy Fed, which returns data that includes the public key, below. This hasn't changed recently.

Mastodon has a habit of changing its interop req'ts regularly, and I don't plan to spend as much time chasing each one own as I used to. If you all can find anything specific they changed or broke in 3.3.0, though, I'm happy to look more!

```json
  "magic_keys": [
    {
      "value": "data:application/magic-public-key,RSA.uJSw6A0Z-9rLqs0D4Bhu0atRvpZxQL-KF27KdGc5xQVuRtpZeZ2vbPgF0LLUsfeBvt2UjKCyOqtpd5VG8JSLEuSIKJppDU6OaBZj5-fSJM0azwk-_Gmvwhegyv6SroYIas2-sIMww4zPDtJM9i-NV_0cUj6ZAT-rs8M08leGCbE=.AQAB"
    }
  ],
  "links": [
    {
      "rel": "magic-public-key",
      "href": "data:application/magic-public-key,RSA.uJSw6A0Z-9rLqs0D4Bhu0atRvpZxQL-KF27KdGc5xQVuRtpZeZ2vbPgF0LLUsfeBvt2UjKCyOqtpd5VG8JSLEuSIKJppDU6OaBZj5-fSJM0azwk-_Gmvwhegyv6SroYIas2-sIMww4zPDtJM9i-NV_0cUj6ZAT-rs8M08leGCbE=.AQAB"
    },
    ...
```

**Comment by nekr0z** [comment]
@ThibG may have an idea...

**Comment by ThibG** [comment]
Sorry, we did indeed change stuff in 3.2.2 and 3.3.0, this wasn't meant as a new requirement, but a fix into edge cases that caused a security issue in Mastodon.

Basically, Mastodon requires actors to have an `acct:` URI, and when trying to get an `acct:` URI from an ActivityPub actor, it performs the webfinger query to `preferredUsername@domain` (so, for `https://fed.brid.gy/evgenykuznetsov.org`, the webfinger query would be done on `evgenkyuznetsov.org@fed.brid.gy`). In this case, this means `fed.brid.gy`'s webfinger endpoint needs to answer to `evgenykuznetsov.org@evgenykuznetsov.org` but also with `evgenykuznetsov.org@fed.brid.gy` (with the same document, or any document where the `subject` is `evgenykuznetsov.org@evgenykuznetsov.org` as it is how Mastodon detects redirects, an actual HTTP redirect to the document for `evgenykuznetsov.org@evgenykuznetsov.org` works too).

Before 3.2.2 and 3.3.0, the loopback check was missing in most circumstances, which allowed people to create “copies” of existing third-party accounts under an arbitrary `acct:` URI. This means up until now, resolving the account from its `id` (`https://fed.brid.gy/evgenykuznetsov.org`) failed but resolving it from its `acct:` URI succeeded, while now, both require `evgenykuznetsov.org@fed.brid.gy` to be resolvable and redirect to `evgenykuznetsov.org@evgenykuznetsov.org`.

I will try to improve Mastodon's generic error message with something more helpful in those cases.

**Comment by snarfed** [comment]
Thanks @ThibG! That's really helpful, and should be an easy fix on our end. Will do.

**Comment by snarfed** [comment]
Done! Should be fixed now. @nekr0z, @andrewshadura, feel free to try again.

**Comment by andrewshadura** [comment]
Thanks a lot, it works :slightly_smiling_face:

**Comment by nekr0z** [comment]
I confirm, fixed for me. Thanks, and happy New Year!
