### ISSUE TITLE
Bridgy Fed follower crashes ActivityPub Followers block in WordPress

### ISSUE THREAD

**Issue by cybeardjm** [snarfed/bridgy-fed#738]
I first reported the issue here: [https://github.com/Automattic/wordpress-activitypub/issues/571](https://github.com/Automattic/wordpress-activitypub/issues/571), but IMHO, the issue comes from how the username/URL is handled via the bridge.

In short:
1 - I created a blog and connected it to Bridgy Fed
2 - via IndieAuth I followed the author on 2 of my blogs who use the ActivityPub plugin for tests
3 - both of these blogs have a page where the "ActivityPub followers block" appear.
4 - for "no apparent reason" both of the pages started to crash in view or edit mode.
5 - it appears the way the "Bridgy Fed" follower is created, mainly its URL, generates bad information to the block when used.
6 - once the "Bridgy Fed" follower has been deleted from the list, the block works again and the page that contains it can be viewed or edited.

**Comment by snarfed** [comment]
Hmm! Sorry for the trouble. Looks like you're right, the WordPress ActivityPub plugin chokes on multiply valued `url` fields like Bridgy Fed has for your test blog. I'll follow up on https://github.com/Automattic/wordpress-activitypub/issues/571

**Comment by snarfed** [comment]
Tentatively closing here; let's track in the WP plugin issue.
