### ISSUE TITLE
Non-ASCII URLs seem to be a problem

### ISSUE THREAD

**Issue by nekr0z** [snarfed/bridgy-fed#74]
I'm not sure, since [this log](https://fed.brid.gy/log?key=https%3A%2F%2Fevgenykuznetsov.org%2Freactions%2F2021%2Fwagner-feed%2F+https%3A%2F%2Fblog.wagner.pp.ru%2F~%2F%25D0%2596%25D1%2583%25D1%2580%25D0%25BD%25D0%25B0%25D0%25BB%25D0%2592%25D0%25B8%25D1%2582%25D1%2583%25D1%2581%25D0%25B0%2F%25D0%25BF%25D0%25B5%25D1%2580%25D0%25B2%25D1%258B%25D0%25B9-%25D0%25BF%25D0%25BE%25D1%2581%25D1%2582&start_time=1610233832) doesn't even open for me.

**Comment by snarfed** [comment]
🙏 Will look!

**Comment by snarfed** [comment]
Looks like this isn't actually the unicode chars in the URL, but that Bridgy Fed may not be compatible with Plume. When it asks Plume for ActivityStreams 2 (as part of ActivityPub), Plume returns HTML instead:

```sh
$ curl -v -H 'Accept: application/activity+json; q=0.9, application/ld+json; profile="https://www.w3.org/ns/activitystreams"; q=0.8' 'https://blog.wagner.pp.ru/~/%D0%96%D1%83%D1%80%D0%BD%D0%B0%D0%BB%D0%92%D0%B8%D1%82%D1%83%D1%81%D0%B0/%D0%BF%D0%B5%D1%80%D0%B2%D1%8B%D0%B9-%D0%BF%D0%BE%D1%81%D1%82'
...
< HTTP/1.1 200 OK
< Content-Type: text/html; charset=utf-8
< Content-Length: 9203
< 
<!DOCTYPE html>
...
```

**Comment by nekr0z** [comment]
Yep, I've just mentioned that in #44 — sorry for the trouble.

Still, with ASCII-only URL I can at least view the log, while with non-ASCII it doesn't open, so I think the issue is still valid, if only for the log representation part.

**Comment by snarfed** [comment]
Ah! True, good point, wil look.

**Comment by snarfed** [comment]
Fixed! Example log: https://fed.brid.gy/log?key=%F0%9F%95%B8%F0%9F%92%8D&start_time=1615778418
