### ISSUE TITLE
Incomplete JSON-LD contexts

### ISSUE THREAD

**Issue by grishka** [snarfed/bridgy-fed#76]
Actors lack `"https://w3id.org/security/v1"` in their `@context`, which causes Smithereen (my ActivityPub project that more-or-less correctly implements JSON-LD) to fail while parsing them. Here's what it should look like:

```
{
  ...
  "@context": ["https://www.w3.org/ns/activitystreams", "https://w3id.org/security/v1"],
  ...
}
```

**Comment by snarfed** [comment]
Hi Gregory! Thanks for filing, and sorry for the trouble.

Could you elaborate on why this new context is needed? I don't think Bridgy Fed uses any terms beyond the existing AS2 context. I don't see https://w3id.org/security/v1 anywhere in https://w3c.github.io/activitypub/, and https://w3c.github.io/activitypub/#obj says:

>  ActivityPub defines some terms in addition to those provided by ActivityStreams. These terms are provided in the ActivityPub JSON-LD context at https://www.w3.org/ns/activitystreams. Implementers SHOULD include the ActivityPub context in their object definitions. Implementers MAY include additional context as appropriate.

**Comment by grishka** [comment]
That's where `publicKey` is defined.

**Comment by snarfed** [comment]
Ah, thanks! Great point. Ugh, this is a result of AP's horribly unspecified authz: https://w3c.github.io/activitypub/#authorization

Regardless, I'll add that context. Thanks again for filing.

**Comment by snarfed** [comment]
Done!
