### ISSUE TITLE
BridgyFed Profile Not Updating

### ISSUE THREAD

**Issue by tmichellemoore** [snarfed/bridgy-fed#778]
Hello @snarfed 
I am trying to setup BridgyFed because I want to use it for Bluesky when that feature goes live. So I have been trying to make it work for Mastodon. It worked for a few days. And then I wanted to update the profile. Once I did that, the picture disappeared and the profile didn’t update. I saw a related Issue here (https://github.com/snarfed/bridgy-fed/issues/614) and confirmed that the pin13 data is accurate. It also is correct on Indiewebify.me. I have tried various things like purging the cache on my site, checking the redirection. Can you point me in the right direction to fix it?

I am also having some issues with backfeeds on Brid.gy. I only mention just In case they are related.

Thank you,
Michelle

**Comment by snarfed** [comment]
Hey @tmichellemoore, sorry for the trouble! I saw this discussion in chat the other day. Not sure what's wrong yet, but I'll look soon.

**Comment by tmichellemoore** [comment]
Thank you! No rush.

**Comment by snarfed** [comment]
Oh also, feel free to send details about your Bridgy backfeed problems! Ideally on https://github.com/snarfed/bridgy/issues, since it's a separate service.

**Comment by tmichellemoore** [comment]
Ok. I will document my steps and a specific post and place it there. Thank you!

**Comment by snarfed** [comment]
Figured this out, it's a bug on our end. Thank you for reporting! Will fix.

**Comment by tmichellemoore** [comment]
Thank you!

**Comment by snarfed** [comment]
Fixed! I'm now seeing your profile picture on eg mastodon.social and indieweb.social. Apologies, thanks again for reporting!

**Comment by tmichellemoore** [comment]
Thank you!!
