### ISSUE TITLE
Old items expire when they probably shouldn't

### ISSUE THREAD

**Issue by fluffy-critter** [snarfed/bridgy-fed#78]
When I post a new item to my site, I use [Pushl](https://github.com/PlaidWeb/Pushl) to send notifications from items in my Atom feed, and all items have an implied fed.brid.gy mention in them to get them syndicated to `@beesbuzz.biz@beesbuzz.biz`.

Sometimes if I post an item to a section that doesn't get a lot of attention, Pushl sends out the mentions for all of the older items in that section as well (because Pushl doesn't maintain long-term state on mention sends). Per the Webmention spec this is totally allowed, as Webmention receivers are supposed to tolerate re-sends of old mentions and just use that as a signal that the content and outgoing mentions have changed.

However, it seems that fed.brid.gy is forgetting about older items, as these older items end up showing up as new in my Mastodon timeline:

<img width="345" alt="image" src="https://user-images.githubusercontent.com/347162/136610985-13632b90-d6c1-4957-bc0c-cf0a5788ac1a.png">

Similarly, if I tell Pushl to recrawl my entire site (to update legacy/lost backlinks etc.), Mastodon followers get flooded with new item notifications.

As a workaround I could change my site templates to only "mention" Bridgy Fed if they're sufficiently recent, but it seems like there are other reasons why Bridgy Fed might need to track items in perpetuity (for example, allowing replies to very old posts). In any case, this seems to indicate some overeager expiration policy in Bridgy Fed's data store.

**Comment by snarfed** [comment]
Bridgy Fed doesn't do a proper AP outbox, no, it's fire and forget. And thanks for the warning! I'll definitely limit it to `e-content`, and probably also on the plain text converted from the original HTML.

**Comment by fluffy-critter** [comment]
Awesome, thanks!
