### ISSUE TITLE
BridgyFed – Checkmark Not Showing After Adding Verification Link

### ISSUE THREAD

**Issue by tmichellemoore** [snarfed/bridgy-fed#784]
Hello @snarfed. I added the link to verify my website on Mastodon as the BridgyFed docs instructed - https://fed.brid.gy/docs#mastodon-link-verification. I am not 100% sure I added it correctly because it doesn't show the verification. This is what I added <a href="https://web.brid.gy/r/https://tmichellemoore.com/></a> Also, I broke the image again while doing this. But it is not showing on IndieWebify.me so that might be unrelated.

Originally Posted at https://tmichellemoore.com/blog/bridgyfed-image-not-showing-after-adding-verification-link/

**Comment by snarfed** [comment]
Ah, sorry! This is a bug in the docs. New users are on web.brid.gy, but older users like you are on fed.brid.gy instead. Try changing your link to https://fed.brid.gy/r/https://tmichellemoore.com/ and then follow the rest of the instructions again.

I'll update the docs. Thanks for reporting!

**Comment by tmichellemoore** [comment]
I changed the title of this issue to reflect the actual issue. Changing the link fix it. Thank you!

**Comment by tmichellemoore** [comment]
Well, the checkmark isn't there anymore. 
<img width="354" alt="image" src="https://github.com/snarfed/bridgy-fed/assets/7757648/abc73dcb-2bc9-4668-b7ed-845bc20c4b1d">

**Comment by snarfed** [comment]
I'm seeing it on mastodon.social! https://mastodon.social/@tmichellemoore.com@tmichellemoore.com

(If you're not logged in, you'll need to go to https://mastodon.social/ and search for @tmichellemoore.com@tmichellemoore.com .)

Bridgy Fed sends your profile updates to your followers' instances. If you look at your profile on an instance where you don't have a follower, it may not have the latest update, or may not verify your link as soon, or at all.

**Comment by tmichellemoore** [comment]
Hi @snarfed! I see it on the Mastodon mobile app. I don’t see it on my tablet Mastodon app or the web app. Thank you! I am just trying to take the steps to see if I want to federate or cross-post. I have one more step to see how to make the content show. Oh and to fix that image again. I will submit a ticket for that after I recheck my html.
