### ISSUE TITLE
Image Not Showing Again

### ISSUE THREAD

**Issue by tmichellemoore** [snarfed/bridgy-fed#786]
Hi @snarfed,
I am not sure what I did, but my photo has disappeared again in Mastodon. I thought I had found the issue with a missing quote after the image link. But that didn't fix it. Sorry about that. The good news is that I think I almost have it working like I want it. I just need to figure out how to make the link card not show something that I have linked to. But that's for another time.
https://tmichellemoore.com
Thank you!
Michelle

**Comment by snarfed** [comment]
Oof, sorry, this is another bug on our end! You're doing great QA recently, I feel like I should be paying you. 😁 

Deploying the fix now, should be live soon.

**Comment by tmichellemoore** [comment]
Lolol. Coincidentally, I just finished a week of being "QA Manager" ok not really. I am the project manager who has to figure out how to organize all of the user testers and figure out how to report the results to our sponsor. And then write the memo on why there were bugs or if we fixed them. Or how about this, the 20 enhancements reported as bugs. Thank you, @snarfed!

**Comment by snarfed** [comment]
Fixed! Thanks again for reporting!
