### ISSUE TITLE
Title is too long

### ISSUE THREAD

**Issue by silverpill** [snarfed/bridgy-fed#818]
Sometimes objects published by BridgyFed contain a `name` field with a very long string. Example:

https://fed.brid.gy/r/https://tantek.com/2024/035/t1/greshams-law-developers-users-jargon

The `name` here seems to be a plain-text copy of HTML in `content`.

**Comment by silverpill** [comment]
Yes, `name` doesn't seem to have a length limit, but this value comes from the original post at https://tantek.com right? I think this representation may not represent the intention of the author because the original post doesn't have a title

**Comment by snarfed** [comment]
Ah, good question! Definitely a good idea to try to faithfully represent the author's intent. In this case, the post's structured data comes from microformats2, and the post's content is inside a `<p class="p-name entry-title e-content entry-content article">`, which has the `p-name` mf2 class, which indicates an explicit intent for the whole content to be the name.

(@tantek has a bit of a reputation for exercising edge cases like this with markup etc on his site. Hi Tantek! 😁)

**Comment by silverpill** [comment]
Nevermind, I think it is actually the job of a consuming implementation.
