### ISSUE TITLE
Bluesky: update homepage

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#822]

**Comment by ch0ccyra1n** [comment]
Anything I can do to help with this?

**Comment by snarfed** [comment]
Thanks for offering! This needs both broad and deep knowledge of BF's functionality, so it may not be the best place to start contributing.

More importantly though, one of the biggest blockers to launch right now isn't this, or other issues here, but that Bluesky's federation beta test is currently limited to 10 users per federated server. Not sure what their timeline is for lifting that.

**Comment by ch0ccyra1n** [comment]
That's good to know. I suppose I was thinking moreso in terms of styling and such lol.

**Comment by snarfed** [comment]
Done!
