### ISSUE TITLE
Web: consider ignoring parsed u-url

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#829]
We hit an example recently where u-url was wrong: https://www.oh.mg/2024/02/crossing-the-street-and-getting-hit-by-a-car/ and https://www.oh.mg/2024/02/farscape-and-capitalism/ both have incorrect u-url of https://www.oh.mg/2024/02/ .

* https://pin13.net/mf2/?url=https://www.oh.mg/2024/02/crossing-the-street-and-getting-hit-by-a-car/
* https://pin13.net/mf2/?url=https://www.oh.mg/2024/02/farscape-and-capitalism/

What should we do about this? Should we ignore u-url and always use fetched url? But then we'd miss cases where u-url correctly points to a different canonical URL. Do those cases actually happen? Does consolidating them actually matter?

**Comment by snarfed** [comment]
Got another report of this: https://blimps.xyz/@KayOhtie/112453839615140876

**Comment by Ceralor** [comment]
Further chiming on this. It seems like any `u-url` links are added as profile links eg in Mastodon, like when someone defines multiple links in a bio config. It's very confusing seeing this _visual_ facet of the profile also be a problem for the _functional_ facet of it.

**Comment by snarfed** [comment]
Sorry this is confusing! [microformats](https://microformats.org/wiki/microformats2) like `u-url` do go in the HTML `class` attribute, but they're functional, not visual. `class` is for more than just CSS.

Bridgy Fed does add `u-url`(s) from your `h-card` as profile links in your generated fediverse profile. `u-url` is for the canonical URL of the current element, eg your web profile (probably your web site's home page) for your `h-card`, or the post's permalink for `h-entry`. This is often the current page, but not always, eg when you're rending your `h-card` somewhere other than your home page, or an `h-entry` in a feed.

If you're linking to your other profiles elsewhere, you'd generally use `rel=me`, not `u-url`.

**Comment by snarfed** [comment]
Plot twist! Turns out I was wrong about `h-card` `u-url` all along: https://chat.indieweb.org/microformats/2024-05-23#t1716482532021200 . Guess I got misled by what it means in `h-entry`, which is different. 🤷 No matter though, just more motivation to handle this on Bridgy Fed's end!
