### ISSUE TITLE
Bluesky: change fediverse handle format?

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#830]
I'm considering changing our Bluesky handle format.

Right now, we use subdomain labels liberally to convert fediverse addresses like `@user@example.com` to Bluesky handles like `user.example.com.ap.brid.gy`. This works, and it's simple, but it has drawbacks. We've been struggling to plan for how to scale handle verification, #744.

If I switch to the `-` character for the fediverse address part, eg `user-example-com.ap.brid.gy`, the resulting handles are more complicated, but I can switch to Bluesky's HTTPS handle verification method, and I'd only need a single wildcard DNS record and a single wildcard SSL cert.

I'm inclined to do it.

**Comment by andrewtj** [comment]
Just in case it's not on your radar, DNS names do have a 63-byte label length limit. (Label being the bit between dots.)

I'd guess it's unlikely that this would be a problem in practice but I don't have anything really substantive to support that feeling.

**Comment by snarfed** [comment]
Thanks, yes! 63 chars per label, 253 chars total.

I also need to look at allowed characters. For DNS it's just alphanumeric and `-`, right? WebFinger usernames may allow a few more, eg `.`s, which users would also need to translate to `-`s.

**Comment by snarfed** [comment]
Based on https://datatracker.ietf.org/doc/html/rfc7565#section-7 and https://datatracker.ietf.org/doc/html/rfc3986#section-2.3 , WebFinger usernames also allow `_` and `~`.

**Comment by andrewtj** [comment]
> I also need to look at allowed characters. For DNS it's just alphanumeric and -, right?

Kinda. DNS labels are arbitrary bytes but case insensitive to a-z. Hostname labels are alphanumeric and dash (for the most part). To enable internationalisation IDNA ([RFC 5890](https://datatracker.ietf.org/doc/html/rfc5890) and [RFC 5891](https://datatracker.ietf.org/doc/html/rfc5891)) then represents a normalised subset of unicode in a hostname label compatible format. If that's something you want to handle [dnspython](https://www.dnspython.org) has some helpers for marshalling names to and from IDNA.

**Comment by WisTex** [comment]
Some platforms support `-` and `_` in their handles (even though WebFinger may not allow a `-` in the username). Even domains can have a `-` in it.

You would need to account for this when you create the Bluesky version of the handle.

**Comment by snarfed** [comment]
Yup, absolutely true. Ugh.

I'm sure I (we) can come up with an encoding that can turn every fediverse handle into a single DNS compliant label, and it might still be worth it to avoid the DNS zone scaling issue...but UX-wise, it's getting uglier and uglier. Sigh.

**Comment by WisTex** [comment]
Would making it two levels help? (_i.e._ separating username and server)

`username.social-example-com.ap.brid.gy` for `username@social.example.com`

That would reduce the number of zones, although that may not matter depending on how you implemented creating the zones.

**Comment by snarfed** [comment]
Yeah I've considered various multi-level formats like that. The DNS scaling concern (more in #744) is mainly the number of records, regardless of how they're organized into zones.

The win of going fully flat under `ap.brid.gy`, as is proposed here, is that we can drop DNS entirely and use ATProto's [HTTPS-based handle resolution method](https://atproto.com/specs/handle#https-well-known-method) instead. That scales better in number of accounts, but SSL certs only support a single level of wildcards, ie `*.ap.brid.gy` but not `*.*.ap.brid.gy`, so the namespace would need to be flat. 🤷

**Comment by zooko** [comment]
Hi Ryan, nice to hear from you! :-)

**Comment by WisTex** [comment]
And with the number of subdomains, AutoSSL for each one will become a pain.

The tricky part will be handling domains and usernames with `-` in it.

**Comment by snarfed** [comment]
Given that this is only a win if it's entirely flat (https://github.com/snarfed/bridgy-fed/issues/830#issuecomment-1959990887), and that means we'd need to come up with a more complicated encoding to handle `-`, `_`, `~`, and similar characters, I'm now less inclined to do this. Sigh.

**Comment by snarfed** [comment]
Decided against this, sadly.
