### ISSUE TITLE
Opt out policies, and Opting out from Bridgy-Fed

### ISSUE THREAD

**Issue by Kio-td** [snarfed/bridgy-fed#834]
I do not want to have users from bluesky contacting my users. They chose bluesky, and i'm respecting their decision.

Additionally, opt-out services are something fedi _really_ does not appreciate. I'm sure you've already gotten a ton of messages basically admitting to that. My personal reason is that I do not want a single, controlled and corporate entity to have a copy of my user's data.

If you're looking to change to an opt-in model, a good start may be requiring to _ping_ the bot, and ask for a registration, rather than automatically registering everybody unless they're aware and capable of opting-out from the service.

Consent is important. For the same reason that I don't appreciate being forced to drink tea, or leave the 'please subscribe me to your mailing list' checkbox blank, is the same reason that I do not wish for my posts to be automatically sent to a service I have no intention to use.

Please permanently disable service for the following instances:
- Kitsunes.club
- Kitsunes.gay
- headmates.social

please reconsider making us drink your tea until we tell you to stop. Change to an opt-in model.

**Comment by snarfed** [comment]
Understood. I hear you; I'll opt out your instances.

Opt-out wasn't an easy call. [I wrote up the result of conversations I had with a number of people in the fediverse moderation community](https://snarfed.org/2024-01-19_moderate-people-not-code), I'd love to hear any thoughts you have on that.

Also, sincere suggestion, if you don't want corporate entities to have copies of your users' data, you might want to block GoogleBot and similar crawlers in your instances' `robots.txt` files.

**Comment by Kio-td** [comment]
> I'd love to hear any thoughts you have on that.
Personally, when I see something I want, I choose to have it. Especially when I am fully aware of what i am doing, and what I am choosing. Opt-in rates are low; this is a _good thing_. People who want to use your service have _chosen_ your service. People who don't, opted not to use it. 

>  ...if I could only follow 4% of people on other networks, they would be drastically less useful.
A fix. If they're not using #nobot, then send them a message. "Hi! X@bsky.social wants to get in touch with you. Would you like to opt in to using Bridgy-fed?" Simple, active request for consent. No need for a slam-dunk PR release to go ignored.

> Also, sincere suggestion, if you don't want corporate entities to have copies of your users' data, you might want to block GoogleBot and similar crawlers in your instances' robots.txt files.

The default for my users is to prevent indexing on the actual page for themselves. They have the ability choose crawling from external platforms. that's their choice and not mine.

**Comment by Kio-td** [comment]
There could be a few solutions to your problem. 
- force a message to be sent to the user, and for bridgy-sky to be actively listening for idunnoimcool_fedi@bridgy.fed, and then send a request for discovery.
- If users are hot-queried, then do a quick webfinger, and return a discovered user if it exists.
- require users on the bsky to get in touch with a discovery bot.

As for sending Fedi -> Bsky, it's just a matter of pinging a user not in the system yet; which is not hard to do.

**Comment by snarfed** [comment]
True! These are all interesting UX ideas.

I've been dissatisfied with the idea that realistically, the majority of people may likely never hear about Bridgy Fed, and therefore never get the chance to choose to opt in _or_ opt out. If the bridge was opt in, when someone wanted to interact with someone else across it, that would be more or less impossible, end of story.

I really like this angle of how to prompt people to opt in because it enables that use case. I'm all for letting people opt in or out before any follow attempt or other interaction takes place. Thank you for the conversation, I'll think through all this more!

**Comment by beardandbag** [comment]
I'm not sure you really hear what you've just said, @snarfed, so I'm going to play it back in bluntspeak a couple times.  I hope it's both educational and minimally painful.


> I've been dissatisfied with the idea that realistically, the majority of people may likely never hear about Bridgy Fed, and therefore never get the chance to choose to opt in or opt out. 

Reads as: "My idea is so great that everyone should have to listen to me tell them about it, whether they want it or not.  Even if they think they're happy with their experience, I know better than them."

It could have come out of the mouth of every spammer and every invasive web-advertisement author in the history of the Internet.  If you've been around long enough to write this bridge, you know that's a terrible idea.  A bridge may be a clever idea, but when people tell you you're building it upside-down, it might be a good idea to listen.  Which brings me to:

> Understood. I hear you... Opt-out wasn't an easy call

"I've heard what you said, about the bridge being upside-down, and I think my idea won't get the same visibility/traction/big-numbers it will if I do it in a way that respects people's privacy and safety."  People are coming out of the metaphorical woodwork to tell you what a bad idea opt-out is and why-- everything from loss of privacy to stalking and harassment to literal physical harm of marginalized folks.  Some are telling you politely and effectively, some... not so much.  But no matter the words they choose, **their feedback is a gift to you**.  You're being given every opportunity to get this right.  

Your statement that "it wasn't an easy call" tells us **you've listened and considered and affirmatively chosen to do this thing badly** and thereby micturate in everyone's metaphorical cereal.  That seems inadvisable for a number of moral and ethical reasons, but if that's not enough, even on a personal level- thinking about your own cereal.  Who'd want to hire you, if you demonstrate this kind of bad product-management in your free time?  Who'd want to socialize after work with the guy whose bridge got that guy beaten, this lady murdered by an ex, that other driven to suicide after a relentless harassment campaign?  After he was given dozens of explanations about why it will hurt people and how to do it without hurting them?

You gotta make your own choices.  I hope you take a moment to reflect on your position and your words and see that you have an off-ramp here.  I sincerely hope that you take it.

**Comment by mdartmann** [comment]
I agree opt-in is the policy for the reasons listed above. If you want a practical reason for opt-ins, it will be a logistical nightmare when a large amount of fedi admins storms to this repo for delisting requests.

That being said, regardless of what the result of this, please remove *.mae.lgbt, *.woem.cat (especially meow.woem.cat), *.meow.solutions, *.dartmann.net, *.maedartmann.name, 202.61.205.35, 152.53.14.{80,135,170}, 2a03:4000:5b:7a2::/64, 2a03:4000:6b:{82,84,e0}::/64 from this service.

**Comment by hobbes** [comment]
for your complete information, abusing the DM system to ask for consent is **not** the right thing to do. Please, pretty please, really hear us out !!!

**Comment by Kio-td** [comment]
> for your complete information, abusing the DM system to ask for consent is **not** the right thing to do. Please, pretty please, really hear us out !!!

this not not what i was suggesting. spamming users for consent is not okay and never has been.

asking a user once for consent once every 30 days, and accepting permanent rejection is fine

**Comment by Kio-td** [comment]
Before this ticket gets closed and locked
please do not use this issue to attack Ryan. He wanted to make something, a simple no has, does, and will suffice

asking to hear y'all out after you've spat in his face is asking for a lot

i am trying to help come to an agreement, and Snarfed is trying his best to make changes that respect your privacy, and ask for consent

**Comment by coreyreichle** [comment]
> True! These are all interesting UX ideas.
> 
> I've been dissatisfied with the idea that realistically, the majority of people may likely never hear about Bridgy Fed, and therefore never get the chance to choose to opt in _or_ opt out. If the bridge was opt in, when someone wanted to interact with someone else across it who'd never heard of it, and therefore hadn't opted in, it would be more or less impossible, end of story.
> 
> I really like this angle of how to prompt people to opt in in the moment, since it enables that use case. I'm all for letting people opt in or out before any follow attempt or other interaction takes place. Thank you for the conversation, I'll think through all this more!

You ever wonder that people wont hear about your bridge, because they have zero interest in their content being shared on bsky?  A known haven for the alt right?

**Comment by Kio-td** [comment]
what did I just say about attacking ryan

**Comment by Kio-td** [comment]
closing to hide this ticket

**Comment by hobbes** [comment]
@Kio-td I think that you are overreacting a bit: that last comment was not ad-hominem, and my last comment (or any comment of mine) was most certainly not a spat in the face of anyone, especially @snarfed 

No a simple no does not suffice, there is no way to convey any argument with a simple no. And noone will change his well thought out mind with a simple no. 

@snarfed faced an immense amount of backlash and has changed his mind and that's already a big thing. 

In your opinion, the proposed solution is fine. 

In my opinion, it's less bad than the previous opt-out policy, but it's still problematic for a number of reasons. And I have a right to say so, especially before he spends more time designing and implementing it, especially if I think that that solution will result in massive defederation of the bridge, especially if I think that it could result in a potential lot of work for fediverse instance admins.

Now you are also right: I made my point. As numerous others did. If you still can't hear it with that immense backlash, all those arguments, and all those tickets demanding opt-out, there's probably nothing more I can do. If you don't care about being defederated into irrelevance, imposing more work on other admins, and stress and danger on lots of human beings, so be it.

**Comment by Kio-td** [comment]
So essentially, from what I understand.
Opt-out is bad. already was, has, and will be.
passive opt in is okay.
implied opt in is okay.
so why can't he ask without processing your data? if you block the request-o-matic thats implied denial, if you say no, its denial, if you have nobot on your profile its a denial. there's a plethora of dropoff points --BEFORE-- the bridge ever connects you to bsky.

Your proposed solution is "throw it into the fire and give up". This is still someone's labor of love.

i dont like bsky. never have. But i will support someone's pet project, and offer advice, like, "change to an opt in model." Especially when countless admins have made it clear that my proposed solution would be preferred and accepted.

I was not saying that you specifically spat in his face, but if you take a look at the locked thread, feel free to search up "techbro" and read through all the wonderful comments people made about snarfed; so yes, i am going to say that the wider community essentially stuck gum in his hair and asked for another piece, and i have a right to say so, especially when the community effectively harrasses and belittles a man because he wanted to make something cool, and got misguided along the way.

**Comment by Kio-td** [comment]
...you just glossed over multiple ways of client-side denial, that is stateless and requires no configuartion or storage. Blocking the discovery bot, and using #nobot both do not require any sort of storage. and if you do not want to be bothered, then you might as well never visit a website again, because they, just like my proposal, use the exact same way of using active opt-in to ask if you want cookies, and they ask every single time until you confirm or deny. it'll act the same way as a website would.

there is no need for any blacklist. The proposal specifically calls for a whitelist.

**Comment by hobbes** [comment]
> ...you just glossed over multiple ways of client-side denial, that is stateless and requires no configuartion or storage. Blocking the discovery bot, and using #nobot both do not require any sort of storage. 

so again, you're asking the entire fediverse to socially or technically adapt to your pet project

> and if you do not want to be bothered, then you might as well never visit a website again, because they, just like my proposal, use the exact same way of using active opt-in to ask if you want cookies, and they ask every single time until you confirm or deny. it'll act the same way as a website would.

erf, do websites connect to and store something in your browser without you first connecting to it ? 

That's the point exactly: **you choose** to visit websites. Not the other way around. **You** initiate the connection. **You** can choose to never visit, or never visit again, without having any trace left on the website or your browser.

Besides, **if you choose to connect**, the cookie is stored **in your browser**, under your control. Not on the website. And even that is subject to precise regulation (and rightly so).

> there is no need for any blacklist. The proposal specifically calls for a whitelist.

If I understand it correctly, your proposal is to somehow send a message to the user asking for permission. For example a DM. And store the answer if the user agrees. But you also need to store a list of addresses for which you already asked and didn't receive an answer, or received a no answer. Otherwise you'll keep hammering them with DMs. 

So yes, you have a whitelist, but you also need a blacklist, and that's the problem. You need to keep a list of people who do not want to use your service. Which is both wrong and illegal.

**Comment by bkil** [comment]
@hobbes Had you read what others have answered before you, you would know that it was already suggested to store only hashes as a workaround (Bloom filters also come to mind as an approximation).

**Comment by hobbes** [comment]
@bkil sorry, can't find any reference to a hash in the conversation (and no, I haven't read each and every single comment in all issues on that project).

So ok, hashes. Good. Certainly better than nothing. However, that covers only half the requirement for anonymization: the original data cannot be recovered from the hash. But not the other half: given a list of addresses (for example from a hacked server, or a lost backup, or...), you can still determine which are in the list.

Really, it's good that you propose technical solutions, but I'm afraid that it's a more fundamental problem: if you have a possibility to say if someone is on the list, a malicious user has the exact same possibility. It's not a technical problem, it's a fundamental design problem. The design itself is problematic.

**Comment by snarfed** [comment]
#878 is a good place to discuss hashes and similar anonymized opt out ideas. As @hobbes mentions (and I did in https://github.com/snarfed/bridgy-fed/issues/878#issuecomment-1946953971), I'm not sure if it's truly possible, but I'd love to be proven wrong!

**Comment by snarfed** [comment]
Fortunately, with the new discoverable opt in idea https://github.com/snarfed/bridgy-fed/issues/835#issuecomment-1942046208, hopefully people who want to opt out anonymously won't need to at all.

**Comment by hobbes** [comment]
> Fortunately, with @Kio-td's DM-based discoverable opt in idea, [#835 (comment)](https://github.com/snarfed/bridgy-fed/issues/835#issuecomment-1942046208), hopefully people who want to opt out anonymously won't need to at all.

@snarfed unfortunately, you still need to somehow keep a list of addresses that you already DMed, so that you don't hammer them with multiple requests. After some times, that's the list of people who do not want to use your service. 

So it solves the discovery and preemptive opt-out problem, but not the fact that you keep a list of people who do not want to be bridged. Now I'll closely follow the discussion about hashes, because those have a way of finding clever solutions to unsolvable problems, but intuitively I'd say that it's impossible to really anonymize that list.

**Comment by snarfed** [comment]
(It would result in repeated ongoing inbox delivery requests, but they'd still be dwarfed by the fediverse's overall current volume of `Delete` activities, those seem to usually be the vast majority of overall activities delivered across the fediverse right now.)

**Comment by hobbes** [comment]
> I should go back and re-check some details of how domain-level blocks work in practice. Notably, if an instance blocks bksy.brid.gy, and Bridgy Fed tries to deliver a DM via AP inbox delivery, does that HTTP POST fail with a 4xx? Or succeed with a 202 and then get dropped?
> 
> If the former, Bridgy Fed doesn't need to store anything. It can retry the DM on each follow request, keep failing each time, and not need to store anything.

if there is a domain block, you don't need to store anything, the end user won't see anything and all is well.

My problem is more if there is no domain block: a user that does not answer will receive lots of DMs if you don't somehow know who you already sent to. So in that scenario you need to store the addresses of people who don't want to interface with the bridge, including those for which you don't have an answer.

**Comment by snarfed** [comment]
Right. I need to store who I've successfully delivered a DM to, and any responses. And you're also right that if one goal is that I can check if someone's on that list before I try to send them another prompt, but I also somehow can't otherwise check if someone's on that list for any other reason...that seems difficult or (more likely) impossible.

Follow-ups in https://github.com/snarfed/bridgy-fed/issues/878, definitely an interesting challenge!
