### ISSUE TITLE
opt in should be the default

### ISSUE THREAD

**Issue by fouroclockfarms** [snarfed/bridgy-fed#839]
Forcing unknowing users to link with corporate owned social media seems counter to what the fediverse is supposed to be. Opt-out as the default is going to force more work on mods and admins that they didn't sign up for Please be sure fouroclockfarms.club is blocked from this and consider changing the model to opt in despite whatever roadblocks you claim there are.

**Comment by snarfed** [comment]
Will do, and I hear you. #835 is a good place for followups.
