### ISSUE TITLE
Opt out is a piss-poor way of managing things

### ISSUE THREAD

**Issue by rocketdyke** [snarfed/bridgy-fed#840]
forcing opt-out will most likely get you defederated.

You need to opt-out my instance from this.

**Comment by snarfed** [comment]
I hear you. Happy to opt your instance out, just let me know which one it is.

**Comment by rocketdyke** [comment]
@snarfed 

you don't hear me at all.

since you'll have to guess what my server is, you're just going to have to opt-out all of them and figure out a way to opt-in the ones that want.

**Comment by rocketdyke** [comment]
@snarfed 

so, you don't plan to make this opt-out?

obviously you, as a high-and-mighty tech bro, know what is best for the entire federation.
