### ISSUE TITLE
Opting out, and the Hitchhiker's Guide to the Galaxy

### ISSUE THREAD

**Issue by timixretroplays** [snarfed/bridgy-fed#841]
The Hitchhiker's Guide to the Galaxy begins with an absurd story: A man's house is knocked down by the council to make room to build a road. He is lambasted by the council for being ignorant and difficult, and is told the plans to build this road have been made public, and available to read for a while, and that it is his fault that he's made no act at all to move his possessions out of the way, settle accounts, or even raise objections. It's revealed that the plans were in a locked filing cabinet, in a dark basement, in an unmarked part of a building, so that practically nobody would ever have discovered anything was going to happen to their houses before it happened.

Mastodon's monthly user base, as of October 2023, was 1.8 million ([source](https://mashable.com/article/mastodon-monthly-users)). What you have proposed is to knock down all 1.8 million houses in order to build your road, which is revolting. You could consult with home owners about your proposal. You could work with them to find a solution to your road that doesn't involve knocking their houses down. Invariably, some will _agree_ to have their houses knocked down so you can build your road. Those are the people you're building this road for - they want the road built so they can use it, and they are entirely free to do so if they so choose. You should seek these people out, gather their support, and crucially, only knock down the houses of people who have expressed to you that they want you to do so.

What percentage of people are telling you "yes, knock my house down" vs "no, don't knock my house down"? How would that percentage map to that figure of 1.8 million Mastodon users? From what I've read so far, I assume you're seeing far more of the latter, and so extrapolating out, the vast majority of people would tell you not to knock their houses down, _if only they knew they needed to do so_. Knowing this, with the switch yet to be flipped, you should simple back down and walk away, because the alternative is completely unconscionable. Altering course to an opt-in situation is the only ethical way forward for this project.

And if you've read through this, thinking "but I'm not doing anything as drastic as knocking down anybody's houses!", you have not only misread the room, you have missed the point entirely.

You do not have permission to bridge content I post on the Fediverse across to Bluesky, for any of my accounts, and it is your responsibility, not mine, to ensure this is honoured.

**Comment by scheeseman486** [comment]
Equating the creation of an API bridge between to social media protocols and eminent domain is a bit silly. Whose "house" is getting knocked down? Everyone's servers are able to continue existing and if there is a metaphorical highway it isn't this piece of software but the internet as a whole. Your premise is faulty, the comparisons you make are nonsense and nothing you said makes a coherent point about how an API bridge is somehow a threat.

It's not like it's impossible for a server using ActivityPub to be run by a literal nazi. If you want to be a part of a larger, open network then you'll have to moderate reactively. If you want a private social network of trusted servers then you're probably better off whitelisting. The protocol makes no difference.

**Comment by timixretroplays** [comment]
It doesn't make sense because I'm talking about data ownership and control, not moderation, the protocol, safety, or nazis?. To be clear, I don't have a technical issue with the bridge existing, but I and plenty of others are on Mastodon specifically to avoid contributing to or otherwise interacting with the big social sites like Facebook or Bluesky, and any project that will just attempt to connect 1.8 million people to them with an opt-out mechanism that almost none of them will ever see is going to be met with revulsion. This is a social issue, not a tech one.

**Comment by scheeseman486** [comment]
It's a tech one. You opted into a social network system that allows arbitrary third parties to hook into it's APIs, you opted to open it up to the web. If you don't wish to make those choices, there are other options available to you.

I don't want Chrome or Firefox to block websites because web hosts asked them to, that precedent would suck.

**Comment by timixretroplays** [comment]
No, yes, data ownership and control, yes, yes, and "probably not" is making an assumption about me as a person and not discussing the issue at hand. I think we're done here.

@snarfed, if I've interpreted correctly that you're switching to an opt-in strategy instead, feel free to close this issue. Sorry about the pile-on going on, I hope you get the opportunity to take some time out for yourself after this mess.

**Comment by scheeseman486** [comment]
Apologies, it was less of an assumption than it was poorly phrased rhetoric to make a general point about how things have changed and how some negative walled garden practices have been normalized from years of Facebook, Google and Discord slicing the internet into discreet chunks.

You don't have total control over the data you make available on the internet to the degree that you can legally compel services not to communicate with the ostensibly open protocol you opted into making available to anyone. You can ask them, they might be nice enough to comply, though at that point I wonder why not just blacklist it yourself like you would any other unwanted ActivityPub server? What makes this service different from any other Mastodon instance you don't want to have anything to do with?

**Comment by Sketch6307** [comment]
> It doesn't make sense because I'm talking about data ownership and control

You **do** have data ownership and control. That is provided, and can only possibly be provided, by the instance you use (i.e. by your visibility settings). If you make your content public, then yes, anyone can read it. And yes, that includes people (and platforms) you don't agree with.

That's the entire point of federation: multiple interoperable platforms that may not agree with each other.

If you want to live in a bubble you can absolutely do that, but the responsibility is not on those around you to build that bubble for you. You're expecting the opposite of eminent domain: turning a public space into a private one dedicated to the benefit of certain people.
