### ISSUE TITLE
opt-out

### ISSUE THREAD

**Issue by lyonsinbeta** [snarfed/bridgy-fed#842]
I would like my server to be opted out of this bridge because I do not consent to having my posts re-hosted on a for-profit website I have nothing to do with. Additionally, because I interact with a variety of accounts across servers I will need all of those servers also opted-out to ensure my posts and replies are not bridged.

My server is `mastodon.social.` Please opt-out my server, and all servers it federates with, and all servers they federate with, etc.

**Comment by snarfed** [comment]
=> #835
