### ISSUE TITLE
"Opt-out."

### ISSUE THREAD

**Issue by alexiswatson** [snarfed/bridgy-fed#849]
I reserve all rights for the content posted at https://kind.social/@alexiswatson, https://alexiswatson.dev, and elsewhere. As a member of the open source community, I am generally pretty lax about who I allow to repurpose what I create, whatever the form.

**You, however, do not have that permission.**

Note well that making this explicit is a courtesy. Copyright law does not require any kind of assertion of these rights. If you take someone's work, and post it someplace else without their permission, you are stealing their work. That your project will not deliver as much value as you'd like is entirely without consequence or merit.

I would further implore you to reconsider your present course.

All others reading this may freely repurpose and adapt this post for their own use as they see fit.

**Comment by Pawlicker** [comment]
> I reserve all rights for the content posted at https://kind.social/@alexiswatson, https://alexiswatson.dev, and elsewhere. As a member of the open source community, I am generally pretty lax about who I allow to repurpose what I create, whatever the form.
> 
> **You, however, do not have that permission.**
> 
> Note well that making this explicit is a courtesy. Copyright law does not require any kind of assertion of these rights. If you take someone's work, and post it someplace else without their permission, you are stealing their work. That your project will not deliver as much value as you'd like is entirely without consequence or merit.
> 
> I would further implore you to reconsider your present course.
> 
> All others reading this may freely repurpose and adapt this post for their own use as they see fit.

https://docs.joinmastodon.org/admin/config/#limited_federation_mode

**Comment by alexiswatson** [comment]
> You're talking absolute gibberish.
> 
> The license at https://github.com/alexiswatson/dotdev/blob/888e76d2c177cf697857a83e1699325c0ae4326d/LICENSE does not exclude snarfed, in fact, it's still the same as of writing this comment and based on how it is written, you cannot even retroactively remove rights to the existing content.

I'm referring to the use of content, which isn't even in that repo. He wants to fork and use my theme, fine. He wants to take my content posted to Fedi and post it to Bluesky without my consent? Answer's no.

**Comment by snarfed** [comment]
@alexiswatson done.

I'm working on a new opt in idea, https://github.com/snarfed/bridgy-fed/issues/835#issuecomment-1942046208, hopefully it can replace the original pure opt out. Apologies for not figuring it out sooner.

**Comment by alexiswatson** [comment]
@snarfed Thank you for being receptive to feedback, and for seeing to this specifically. 

As with others, I'm not inherently opposed to the notion of bridging, provided the concerns of those in #835 are addressed. I'll participate there as I'm able.
