### ISSUE TITLE
This whole project should be opt in, not opt out.

### ISSUE THREAD

**Issue by jameschip** [snarfed/bridgy-fed#850]
This bridge should be opt in by default, and not opt out.

The fact that users have to know about this in the first place, then make specific changes to their profiles to stop you from boosting their posts into another, possibly problematic, network without consent is backwards.

This bridge should *only* bridge posts from users that have a #bsyBridge tag in their profile, and not the other way around.

I know the temptation as a developer is to want your project to succeed and garner a lot of users, but by making this tool opt-out by default you don't end up with users; you end up with potential victims.

**Comment by Wurzelmann** [comment]
+1, doing this as an opt-out project just shows the developer has no concept of consent or no interest in it, don't know, which is worse.

**Comment by snarfed** [comment]
Understood. I'm working on a new opt in idea, https://github.com/snarfed/bridgy-fed/issues/835#issuecomment-1942046208, hopefully it can replace the original pure opt out. Apologies for not figuring it out sooner.
