### ISSUE TITLE
Why is this not opt in?

### ISSUE THREAD

**Issue by sotolf2** [snarfed/bridgy-fed#851]
So everyone will just have to know that you exist, or else you will just share all their stuff? That's kind of a really douchbag way of doing this...

**Comment by snarfed** [comment]
Understood. I'm working on a new opt in idea, https://github.com/snarfed/bridgy-fed/issues/835#issuecomment-1942046208, hopefully it can replace the original pure opt out. Apologies for not figuring it out sooner.
