### ISSUE TITLE
opt-out

### ISSUE THREAD

**Issue by sotolf2** [snarfed/bridgy-fed#852]
I reserve all rights for the content posted at https://alpha.polymaths.social/@sotolf, https://social.linux.pizza/@sotolf, and elsewhere. As a member of the open source community, I am generally pretty lax about who I allow to repurpose what I create, whatever the form.

You, however, do not have that permission.

Note well that making this explicit is a courtesy. Copyright law does not require any kind of assertion of these rights. If you take someone's work, and post it someplace else without their permission, you are stealing their work. That your project will not deliver as much value as you'd like is entirely without consequence or merit.

I would further implore you to reconsider your present course.

All others reading this may freely repurpose and adapt this post for their own use as they see fit.

**Comment by snarfed** [comment]
Done.

I'm working on a new opt in idea, https://github.com/snarfed/bridgy-fed/issues/835#issuecomment-1942046208, hopefully it can replace the original pure opt out. Apologies for not figuring it out sooner.
