### ISSUE TITLE
Instance opt out (and think about what you are doing)

### ISSUE THREAD

**Issue by papalouf** [snarfed/bridgy-fed#853]
Hello, as administrator of @mastodon.ptolemaios.fr instance and on my proper name (@BastienBoulbi@mastodon.ptolemaios.fr), I require you to opt out my instance and all its related accounts from your bluesky bridge. 

I strongly suggest you to rethink about your project and what it imply. Forcing your bluesky bridge in opt-out will expose you to be considered as in infraction against EU laws, particularly GDPR, for unlawful consent. 
I understand your idea and consent is the key to makes it trustful for many people. 

Please consider reversing your opt out mechanism and put in place an opt in mechanism.

**Comment by snarfed** [comment]
Understood. I've opted out @BastienBoulbi@mastodon.ptolemaios.fr. If you want your instance opted out, could you please DM me at https://indieweb.social/@snarfed from an admin account to confirm that you're the admin?

I'm working on a new opt in idea, https://github.com/snarfed/bridgy-fed/issues/835#issuecomment-1942046208, hopefully it can replace the original pure opt out. Apologies for not figuring it out sooner.
