### ISSUE TITLE
opt-out

### ISSUE THREAD

**Issue by sonologic** [snarfed/bridgy-fed#854]
opt-out for the entire instance `chasmcity.net`

And please reconsider 'opt-out'. It should be 'opt-in'. Why do you techbros always have to force your bad ideas on everyone? We're not interested in your nazi content bridge.

**Comment by snarfed** [comment]
Done, and understood.

I'm working on a new opt in idea, https://github.com/snarfed/bridgy-fed/issues/835#issuecomment-1942046208, hopefully it can replace the original pure opt out. Apologies for not figuring it out sooner.

**Comment by sonologic** [comment]
> Done, and understood.
> 
> I'm working on a new opt in idea, [#835 (comment)](https://github.com/snarfed/bridgy-fed/issues/835#issuecomment-1942046208), hopefully it can replace the original pure opt out. Apologies for not figuring it out sooner.

Can you please opt my instance out of ever receiving one of your push notifications too. I am not interested in bluesky, I am not interested in your service, I am not interested in you. Please leave me alone and don't force yourself upon me.
