### ISSUE TITLE
GDPR request

### ISSUE THREAD

**Issue by doppelgrau** [snarfed/bridgy-fed#855]
Hello,

I just wanted to inform you that I according with Article 21 GDPR I object that any data published with fediverse accounts (and any further accounts that might be successors) linked to my person is being used in the service you plan to offer.
In addition if you have already stored any information (including data you transferred to third parties) I want a copy according to Article 15 and that you afterwards delete them (Artikel 17).
If you need further information to identify these accounts please contact me and provide a private way to share the current accounts (still will object to any possible successor accounts).

Best regards

**Comment by fabiscafe** [comment]
Hm I'm actually interested in this topic in general when the fediverse comes into play. 

* https://blog.bloonface.com/2023/07/04/the-fediverse-is-a-privacy-nightmare/
* https://www.law.kuleuven.be/citip/blog/mastodon-angel-or-devil-in-disguise/

**Comment by doppelgrau** [comment]
In that case, probably best to open an own issue.

**Comment by snarfed** [comment]
@doppelgrau sure. I do need further information to identify these accounts; you can email them to me at github@ryanb.org or DM them to @snarfed@indieweb.social.

**Comment by snarfed** [comment]
Received the account in question. Bridgy Fed is not currently storing any data linked to it, and I've opted it out so that no future data will be stored or processed.
