### ISSUE TITLE
opt out

### ISSUE THREAD

**Issue by Alys** [snarfed/bridgy-fed#856]
I reserve all rights for the content posted at https://hachyderm.io/@lady_alys

I do not give you permission to copy, "bridge", or repurpose that content.

I should not need to make this explicit to you. Copyright law does not require any kind of assertion of these rights. If you take someone's work, and post it somewhere else without their permission, you are stealing their work.

I demand that you consider my account https://hachyderm.io/@lady_alys permanently opted out from your bridge.

All others reading this may freely repurpose and adapt this post for their own use as they see fit.

**Comment by snarfed** [comment]
Done, and understood.

I'm working on a new opt in idea, https://github.com/snarfed/bridgy-fed/issues/835#issuecomment-1942046208, hopefully it can replace the original pure opt out. Apologies for not figuring it out sooner.
