### ISSUE TITLE
your project should be opt in not opt out

### ISSUE THREAD

**Issue by Alys** [snarfed/bridgy-fed#857]
This project should be opt in, not opt out.

By making it opt out, you are apparently expecting that all Mastodon users who might object to this will hear about your bridge and have time to contact you before your bridge starts copying their content. This is clearly ludicrous and unfair.

You should not be forcing people to opt out from having their content appear on a platform that they have not chosen to use.

Copyright law does not require the copyright holder to assert their rights. Taking someone's work and posting it elsewhere without their permission is stealing.

**Comment by snarfed** [comment]
Understood.
