### ISSUE TITLE
either opt-in or federate properly

### ISSUE THREAD

**Issue by stevepatter** [snarfed/bridgy-fed#858]
This project (which should not exist) should be opt-in at both instance and user level. 

If BS wants to become federated and join the fediverse, it should entirely adopt the tried & tested fediverse protocols and join as a regular federated mastodon-style server. That way, we all benefit.

**Comment by Paavi20** [comment]
2nd that.

**Comment by snarfed** [comment]
Understood.

I'm working on a new opt in idea, https://github.com/snarfed/bridgy-fed/issues/835#issuecomment-1942046208, hopefully it can replace the original pure opt out. Apologies for not figuring it out sooner.
