### ISSUE TITLE
opt-out

### ISSUE THREAD

**Issue by tfunken** [snarfed/bridgy-fed#860]
This is an opt-out request for: all accounts on iceshrimp.social

**Comment by snarfed** [comment]
Sure. Can you please DM me at @snarfed@indieweb.social from an admin account on iceshrimp.social to confirm that you're an admin there? You're also welcome to block the bsky.brid.gy domain there.

**Comment by tfunken** [comment]
I already did when I opened this issue

**Comment by snarfed** [comment]
Thanks! Done.
