### ISSUE TITLE
opt out

### ISSUE THREAD

**Issue by flippthebunny** [snarfed/bridgy-fed#861]
stop this right now

**Comment by snarfed** [comment]
Feel free to post your fediverse handle here or DM it to @snarfed@indieweb.social, I'll happily opt you out.

I'm also working on a new opt in idea, https://github.com/snarfed/bridgy-fed/issues/835#issuecomment-1942046208, hopefully it can replace the original pure opt out. Apologies for not figuring it out sooner.

**Comment by redpyre-Dev** [comment]
no u
