### ISSUE TITLE
opt-out

### ISSUE THREAD

**Issue by ghost** [snarfed/bridgy-fed#862]
Opt-out mastodon.cute.camp, instance wide. And as previously said numerous time by others, think at what you are doing.

**Comment by snarfed** [comment]
Sure. Can you please DM me at @snarfed@indieweb.social from an admin account to confirm that you're an admin? You're also welcome to block the bsky.brid.gy domain there.

I'm also working on a new opt in idea, https://github.com/snarfed/bridgy-fed/issues/835#issuecomment-1942046208, hopefully it can replace the original pure opt out. Apologies for not figuring it out sooner.

**Comment by snarfed** [comment]
Done.
