### ISSUE TITLE
opt-out

### ISSUE THREAD

**Issue by cangeeq** [snarfed/bridgy-fed#863]
Please opt-out @jrm@space.space / https://spacey.space/@jrm

fwiw, I think default opt-out was a terrible idea (on almost everything, but particularly in this case), opting out via hashtag in bio is a terrible idea (pollutes intent of field, doesn't scale, not standardized), and I'm skeptical the individual request methods (github, email) will behonoured.

But I'm giving it a shot anyways.

Thanks.

**Comment by snarfed** [comment]
Done, and understood.

I'm working on a new opt in idea, https://github.com/snarfed/bridgy-fed/issues/835#issuecomment-1942046208, hopefully it can replace the original pure opt out. Apologies for not figuring it out sooner.
