### ISSUE TITLE
This should be opt-in, not opt-out

### ISSUE THREAD

**Issue by Paavi20** [snarfed/bridgy-fed#864]
The absence of opt-out doesn't qualify as consent and acting as a quasi federation from Fediverse to commercial platforms you're acting against the will of both many administrators and users of those federated instances. This is also against the GDPR and privacy policies of most instances.

**Comment by snarfed** [comment]
Understood.

I'm working on a new opt in idea, https://github.com/snarfed/bridgy-fed/issues/835#issuecomment-1942046208, hopefully it can replace the original pure opt out. Apologies for not figuring it out sooner.
