### ISSUE TITLE
opt-out, and reconsider this project

### ISSUE THREAD

**Issue by CdRGit** [snarfed/bridgy-fed#865]
choosing to use issues to opt out to ensure this is heard, @catgirlQueer@tech.lgbt / https://tech.lgbt/@catgirlQueer

also, reconsider this entire project, there's a reason you're getting so much backlash, opt-out is not consent.

**Comment by outlaw-dame** [comment]
Federation as it currently stands is not consent. Ask any new person, better yet check most instances TOS do they all explicitly tell users they are signing on to potentially have their content duplicated by instances they do not know about? Do they know these instances. Federation is opt-out not opt-in, the everyday user believes they are opting into explicitly having their account and content on the instance they sign up on. How is this any different?

**Comment by CdRGit** [comment]
there is a big difference between federation within platforms that implement the same protocol and duplicating content to a different platform

**Comment by outlaw-dame** [comment]
You failed to address any of the points I made. What is the big difference? Especially, if none of the points I brought up are addressed. You are saying lack of consent is okay in one situation and no okay in another, that is disingenuous. If you are for consent then you should be for consent not when it is convenient for you. People should be fully informed and aware so they can make the best decision for them as possible.

**Comment by MagicLike** [comment]
> You failed to address any of the points I made. What is the big difference? Especially, if none of the points I brought up are addressed. You are saying lack of consent is okay in one situation and no okay in another, that is disingenuous. If you are for consent then you should be for consent not when it is convenient for you. People should be fully informed and aware so they can make the best decision for them as possible.

Please just read #835 and reconsider your view. There are so many different reasons for making this bridge opt-in, so far that it could even be illegal to run.

**Comment by nixfemby** [comment]
> Federation as it currently stands is not consent. Ask any new person, better yet check most instances TOS do they all explicitly tell users they are signing on to potentially have their content duplicated by instances they do not know about? Do they know these instances. Federation is opt-out not opt-in, the everyday user believes they are opting into explicitly having their account and content on the instance they sign up on. How is this any different?

In the case of Mastodon, you're agreeing to the privacy policy which does explicitly state this, yes. 

Obviously signing up to any instance does not automatically mean you agree to the bridge, its privacy policy or even that of Bluesky. With an opt-out approach you're actually forcing this onto every new user without any clear option to disable it, except for an obscure hashtag, unless you force every single admin and fedi software developer to take  it into account.

**Comment by outlaw-dame** [comment]
That is a slick response, do the instances? The service provider, does it explicitly state this? If the government came due to a law violation they are not coming for Eugen, they are focusing on the service provider. Does each instance explicitly state this? Does it make it very clear to users?

**Comment by lullis** [comment]
> federation with activitypub-compliant servers ensures that all features (report-forwarding, blocks, delete requests, visibility) is (usually) correctly handled

This is absolutely not true. There is nothing about the protocol that enforces any of the features provided by the applications.

**Comment by snarfed** [comment]
@CdRGit I've opted you out.

I'm working on a new opt in idea, https://github.com/snarfed/bridgy-fed/issues/835#issuecomment-1942046208, hopefully it can replace the original pure opt out. Apologies for not figuring it out sooner.
