### ISSUE TITLE
opt-out

### ISSUE THREAD

**Issue by appcreatorguy** [snarfed/bridgy-fed#866]
please take this as a formal request from the account @alphacerium@tech.lgbt to opt-out from having any data associated with this account pass through the bridge.

Choosing to make this bridge opt-out is a terrible idea and not a valid form of consent, a violation of users privacy (and probably GDPR) and I strongly suggest you reconsider your approach to a bridge. 

The idea is commendable. However, opt-out is not the way.

**Comment by snarfed** [comment]
Done, and understood.

I'm working on a new opt in idea, https://github.com/snarfed/bridgy-fed/issues/835#issuecomment-1942046208, hopefully it can replace the original pure opt out. Apologies for not figuring it out sooner.
