### ISSUE TITLE
opt-out

### ISSUE THREAD

**Issue by Nours42** [snarfed/bridgy-fed#868]
please take this as a formal request from the accounts
- @[Nours@g33ks.coffee (mailto:Nours@g33ks.coffee)
- @[gobelin_nounours@ludosphere.fr] (mailto:gobelin_nounours@ludosphere.fr)
- @[gobelin_nounours@imaginair.es] (mailto:gobelin_nounours@imaginair.es)
to opt-out from having any data associated with this accounts pass through the bridge.

building this bridge is, for me, a developmental error. We're here because we found peace and goodwill.  Opening our doors to Bluesky is the opposite of what needs to be done to keep us peaceful and caring.  I know it's a form of closing off the world, but this world is ugly and violent.  Please leave it out of the fediverse

**Comment by snarfed** [comment]
Done, and understood.

I'm working on a new opt in idea, https://github.com/snarfed/bridgy-fed/issues/835#issuecomment-1942046208, hopefully it can replace the original pure opt out. Apologies for not figuring it out sooner.
