### ISSUE TITLE
opt-out

### ISSUE THREAD

**Issue by Berinkton** [snarfed/bridgy-fed#871]
Please take this as a formal request from the account

@[berinkton@social.linux.pizza](https://social.linux.pizza/@Berinkton)
to opt-out from having any data associated with this account pass through the bridge.

I joined the Mastodon Fediverse because i saw it as a good alternative to the corporate Social Media Platforms
that already exist.
I do not want my publicly accessible content that i post on any Fediverse Platform to be transferred
to any Corporate non federated Platform. This Bridge should be opt-in or at least should have a better and more clear way to
opt-out. Please reconsider your approach for user participation with this project. I personally don't like how this opt-out method of integration is forced upon all users.

I request a reply that my wish to opt-out is acknowledged.
If i do not get a reply within 14 days and/or see any sign that my data was shared through the bridge,
i will take legal action.

**Comment by snarfed** [comment]
Done, and understood.

I'm working on a new opt in idea, https://github.com/snarfed/bridgy-fed/issues/835#issuecomment-1942046208, hopefully it can replace the original pure opt out. Apologies for not figuring it out sooner.
