### ISSUE TITLE
Pre-emptive domain blocks

### ISSUE THREAD

**Issue by coreyreichle** [snarfed/bridgy-fed#872]
Is there an already existent AP account, so that people can premptivley seek out the domain, as an individual user (Not instance operator), in order to block it?

Is the single domain the only domain bridging will be done from?

And no, I'm not going to RTFM this time, because frankly, I didn't ask to share my data with a for-profit data harvester, and YOU made that choice for me.

**Comment by Varpie** [comment]
From what I read of the code, this doesn't correctly implement ActivityPub, so I don't think there is.

**Comment by snarfed** [comment]
@coreyreichle the domain to block is `bsky.brid.gy`. the Bluesky <=> fediverse bridge hasn't launched yet, so sorry, no, there aren't any live bridged accounts in the fediverse yet.

**Comment by coreyreichle** [comment]
Can you add a webfinger end point, so people can search for the user, such as @domain@bsky.grd.gy, so people can search for this account, then block the domain, for information self-defense since otherwise.

Then, it can be published right now, and can start to demonstrate good will.
