### ISSUE TITLE
GDPR request

### ISSUE THREAD

**Issue by Varpie** [snarfed/bridgy-fed#873]
As an EU resident, I would like to request confirmation as to whether or not personal data concerning `@varpie@peculiar.florist` is being processed, and if so, know
- the purposes of the processing (it is not a legitimate interest as defined by GDPR, and certainly not something I have freely given my consent to...)
- what personal data is being processed
- from which sources, and to whom it has been delivered

I would also like any such data to be removed, and for any processing to cease immediately.

You can consider this a request to opt out of any processing of `@varpie@peculiar.florist`'s data by this tool (even though I should not have to, opt out is a stupid decision, opt in is the way to go for a tool that abuses federation protocols).

Also, the so-called "GDPR lawyers" you mention in #836 are a scam. Out of the 3 explanations given on https://brid.gy/about#gdpr, only one (the fact that it is only publicly available data) is valid.
- [Recital 18](https://gdpr-info.eu/recitals/no-18/) says _This Regulation does not apply to the processing of personal data by **a natural person** in the course of a purely personal or household activity and thus with no connection to a professional or commercial activity_, a natural person is a human being, not a scraping tool. It also says _this Regulation applies to controllers or processors which provide the means for processing personal data for such personal or household activities_, which this tool is (so it definitely applies).
- The third point says _The vast majority of Bridgy's user data is from or for personal web sites_, which is really 2 points, justified by a single argument, the use of [article 2b](https://gdpr-info.eu/art-2-gdpr/). This article does not look at where the data comes from, so using it to say it's OK because the user data is from personal websites is bullshit, and your claim that the "vast majority" is for personal websites still doesn't apply here because you have no control over who uses the tool, so no guarantee that the users aren't corporations harvesting data. And once again, the tool isn't a natural person, so its use is invalidated by recital 18 seen above.

**Comment by SchizoidLifter** [comment]
EU citizens should have all privileges revoked followed by forced labor for 5 years

**Comment by Animaly0** [comment]
man, that’s literally our rights as citizen of the EU, what are you even saying…

**Comment by snarfed** [comment]
@Varpie understood. Bridgy Fed is not storing and has not processed any data for @varpie@peculiar.florist. I've opted it out of any future storage and processing.

I'm working on a new opt in idea, https://github.com/snarfed/bridgy-fed/issues/835#issuecomment-1942046208, hopefully it can replace the original pure opt out. Apologies for not figuring it out sooner.

**Comment by Alys** [comment]
> EU citizens should have all privileges revoked followed by forced labor for 5 years

@SchizoidLifter Advocating slavery ("forced labor") is despicable. Advocating it for a whole group of people, as you've done here, seems racist, which is also unacceptable. If you meant this as a "joke", that doesn't make it any better; slavery and targeting specific groups of people are not suitable topics for jokes.

I won't be replying further in this issue because I have no desire to get drawn into a debate. I'm merely calling out your comment as inappropriate because I feel that to say nothing would be implicit approval.
