### ISSUE TITLE
opt out

### ISSUE THREAD

**Issue by redpyre-Dev** [snarfed/bridgy-fed#874]
thing bad

**Comment by redpyre-Dev** [comment]
(this is satire btw, so many people here really need to get a grip and unclench)

**Comment by snarfed** [comment]
Sure. Let me know your fediverse address, either here or in a DM to @snarfed@indieweb.social, and I'll opt you out.

**Comment by snarfed** [comment]
You can also block the bsky.brid.gy domain as a user or an admin, that has the same effect as opt out, and you won't need to give me any information.
