### ISSUE TITLE
opt out for tilde.zone

### ISSUE THREAD

**Issue by coreyreichle** [snarfed/bridgy-fed#875]
As a user on tilde.zone, I'm requesting opt-out for the domain.

**Comment by gentleAmateur** [comment]
The domain owner would need to request that.

**Comment by coreyreichle** [comment]
Typically, I'd agree.  However, since there's no way for me to preemptively block the domain today, since it's not a proper AP service... I would like my domain opted out until such a time I can block the domain individually.

**Comment by ajloveslily14** [comment]
You're insane if you think some random user can make decisions behalf of the owner. Seriously who do you think you are? Get a grip on reality.

**Comment by snarfed** [comment]
@coreyreichle the bridge implements standard ActivityPub. Its domain is bsky.brid.gy, you're welcome to block that domain for your account, and an admin can block it for your instance as a whole. I'm also happy to opt out your account or the instance in the bridge too, but as others have mentioned here, I'd need an admin to ask me to do that.
