### ISSUE TITLE
Link to basics of law 101

### ISSUE THREAD

**Issue by tangenital-theory** [snarfed/bridgy-fed#876]
Hi. It seems like a lot of people here have a very strong grasp on how national and international law works.

Can we add a link in the readme that points to a beginner-level course in understanding US and International law? I mean, a free course is ideal, but I do think you should have some money backing up legal claims you make over the internet, so if you know a good paid resource, I highly encourage that instead.

Also shoutout to snarfed for making something cool. Just remember it's the vocal minority who shit their pants and are asking for a diaper change. I wouldn't fault you for liberal use of the block and report buttons.

Peace and Love

**Comment by snarfed** [comment]
Thanks for the kind words. I get the idea, and I appreciate it, but I think it's a bit beyond the scope of this specific project's docs or readme.
