### ISSUE TITLE
Federate me (harder) please

### ISSUE THREAD

**Issue by Cyberes** [snarfed/bridgy-fed#879]
Very cool, despite what the nay-sayers are screeching about. Thanks for your hard work.
https://mast.evulid.cc

**Comment by jenbanim** [comment]
Mastodon users when the posts they made publicly visible are visible to the public
![image](https://github.com/snarfed/bridgy-fed/assets/40228062/f9c394a3-55d9-4798-803c-46e021e56817)

**Comment by Subversionary** [comment]
> Mastodon users when the posts they made publicly visible are visible to the public

Mastodon users when you actually make use of federation and not treat it as alternative twitter

**Comment by Cyberes** [comment]
Turns out these kinds of people enjoy moaning about publicly accessible data being publicly accessible:
https://github.com/matrix-org/matrix-viewer/issues/47

**Comment by Subversionary** [comment]
> Turns out these kinds of people enjoy moaning about publicly accessible data being publicly accessible

Reminds me of discool/dsccool/tracr drama where people were scared shitless of a discord crawler archiving their posts in public discord servers, claiming violation of privacy.
Matrix/Mastodon posts are even more openly available than discord, funnily enough.

**Comment by Cyberes** [comment]
Yeah, things started falling apart the moment we let the idiots with low IQ on the internet.

**Comment by snarfed** [comment]
Thanks. Let's stay civil and constructive though, please.
