### ISSUE TITLE
Only allows full web sites (domains)

### ISSUE THREAD

**Issue by Quinn64** [snarfed/bridgy-fed#882]
Whenever trying to add a [Movim](https://github.com/movim/movim) blog, it subscribes to the login page instead of the user's public blog.

For example, if I want to subscribe to Timothée's blog ( https://mov.im/blog/edhelas%40movim.eu ) from Mastodon, when I feed it to https://fed.brid.gy it ends up generating a feed based on https://mov.im instead and provides the address @mov.im@web.brid.gy

**Comment by snarfed** [comment]
Done!
