### ISSUE TITLE
Incorrect content-type?

### ISSUE THREAD

**Issue by silverpill** [snarfed/bridgy-fed#895]
How to reproduce:

```
curl -v -H 'Accept: application/ld+json; profile="https://www.w3.org/ns/activitystreams"' https://fed.brid.gy/r/https://snarfed.org/2024-02-19_terence-eden-but-the-one-thing-i-cant-figu-mastodon
```

The response contains `Content-Type` header with `application/ld+json` value. I personally think it's okay but in the aftermath of [GHSA-jhrq-qvrm-qr36](https://github.com/mastodon/mastodon/security/advisories/GHSA-jhrq-qvrm-qr36) other implementations may choose to reject all media types except `application/ld+json; profile="https://www.w3.org/ns/activitystreams"` and `application/activity+json`.

**Comment by snarfed** [comment]
Good point! Thanks for filing. I'll add the profile.

**Comment by snarfed** [comment]
Done! Thanks again for the nudge.
