### ISSUE TITLE
support Friendica

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#9]
their current released ostatus support is incomplete. @annando is rewriting it in the `new-ostatus` branch in his fork: https://github.com/annando/friendica/tree/new-ostatus

more discussion in friendica/friendica#3696.

**Comment by annando** [comment]
The changes are already in the current master of Friendica.

**Comment by annando** [comment]
There are currently no known OStatus issues. It is working fine with GNU Social, Pleroma and Mastodon.

**Comment by snarfed** [comment]
thanks for the update!

**Comment by snarfed** [comment]
Looks like Friendica now supports ActivityPub. I [tried liking](https://snarfed.org/2023-01-17_hubuppro-collective) [this post](https://friendica.hubup.pro/display/174591b4-1563-a455-e2af-046050971897) on https://friendica.hubup.pro/ (running Friendica 2022.12) via BF, and when BF tried to fetch https://friendica.hubup.pro/display/174591b4-1563-a455-e2af-046050971897 (the post URL) with AS2 conneg headers, it returned HTTP 503 Temporarily Unavailable. Looks like that was from Cloudflare, checking that my request wasn't a bot.

Not a good sign for at least that instance's federation support. I'll try again on another instance that's not on Cloudflare.

**Comment by snarfed** [comment]
Success! I [successfully liked](https://snarfed.org/2023-01-17_libranet-de-starr-wulfe-libranet-de) [this post](https://libranet.de/display/0b6b25a8-1563-aaff-1011-9d6756275890) on libranet.de, running Friendica 2023.01. [Bridgy Fed log.](https://fed.brid.gy/log?start_time=1673978568&key=https://snarfed.org/2023-01-17_libranet-de-starr-wulfe-libranet-de%20https://libranet.de/objects/0b6b25a8-1563-aaff-1011-9d6756275890&module=) I'm going to tentatively declare success here.

**Comment by snarfed** [comment]
Reopening, following Friendica accounts doesn't seem to be working: https://github.com/friendica/friendica/issues/12965

**Comment by bkil** [comment]
Maybe not related to your present issue, but HTTP 503 may be related to this, that should be solved by implementing retries with exponential backoff in your backend:

* https://github.com/friendica/friendica/issues/10131
* https://github.com/friendica/friendica/blob/develop/doc/Install.md#user-content-your-worker-never-or-rarely-runs

**Comment by snarfed** [comment]
Thanks! But the current failure is no longer an HTTP 503. It's accepting async with 202, and then failing during later background processing. Details in https://github.com/friendica/friendica/issues/12965

**Comment by snarfed** [comment]
Tried again after #442, looks like it's working now!
