### ISSUE TITLE
AT protocol support

### ISSUE THREAD

**Issue by sysadminpower2019** [snarfed/bridgy-fed#904]
Hello

Now that bsky has finally opened up federation is there a roadmap for @protocol support for bridgyfed?

**Comment by snarfed** [comment]
Yes! The original roadmap is in #381. My current plan is to finish and ship web <=> Bluesky support first. Off the top of my head, here are a few things remaining:
* #744
* #830 
* #826 
* #823 
* #822
* #688

After that, I can work on finishing fediverse <=> Bluesky. #880 is probably the biggest blocker there.

**Comment by snarfed** [comment]
Status update here: right now, Bluesky's current federation beta test has a quota of 10 users per federated server, so I still can't open up even just web <=> Bluesky bridging to everyone quite yet.

I'm also still debugging bits of Bridgy Fed's support too, but hopefully soon I'll at least be able to ask a few people to beta test on my end.

**Comment by sysadminpower2019** [comment]
let me know i'd be super happy to betatest

**Comment by snarfed** [comment]
Damn, accidentally deleted a comment here with a small todo list, and evidently there's no way to undelete deleted comments. Argh.

**Comment by snarfed** [comment]
Added a set of manual tests in https://github.com/snarfed/bridgy-fed/issues/904#issuecomment-1981163614 that I'm currently working through. No need for help yet, analyzing and debugging is still the long pole for these tests, not just doing them. Making progress though.

**Comment by snarfed** [comment]
Reconsidered! I've merged that list of tests and other todos into #381, and I'm closing this in favor of continuing to track the ATProto/Bluesky launch there. Feel free to subscribe there!
