### ISSUE TITLE
Can Bridgy Fed bridge user content from Bluesky without permission?

### ISSUE THREAD

**Issue by vyv03354** [snarfed/bridgy-fed#907]
Almost all recent discussions are about bridging from Mastodon to Bluesky (if I understand correctly). How about the opposite direction?

Unlike Mastodon, Bluesky specifies the protocol by name in [their ToS](https://bsky.social/about/support/tos#user-content):
> c. Bluesky’s Use of User Content: User Content is only used only in connection with: (a) providing Bluesky Social and Content, including by sharing User Content throughout Bluesky Social and **the AT Protocol** as well as developing and improving our current and future offerings; and (b) promoting and marketing Bluesky and Bluesky Social.

(emphasis mine)

Will discoverable opt-in (#880) also cover that? (Tip: Bluesky does not support DM at the moment.)

**Comment by snarfed** [comment]
Hi! It's a good question. The short answer is, I don't know yet. We've been discussing details in #880, including the fact that Bluesky doesn't have DMs yet: https://github.com/snarfed/bridgy-fed/issues/880#issuecomment-1963162833 . Do you have any thoughts on how you'd do it there?

(Btw, if you want to understand someone's real goals and expectations, ToSes aren't often the most useful or understandable place to start. That specific section of Bluesky's ToS describes what _they_ do with user data, not how they restrict what other people can do. I've been talking with them regularly for almost a year now, in person and on calls as well as online, and they've always been encouraging and supportive of this and other third party bridges.)

**Comment by snarfed** [comment]
Merging into #880.
