### ISSUE TITLE
Web sign-up: detect native AP servers

### ISSUE THREAD

**Issue by sysadminpower2019** [snarfed/bridgy-fed#911]
Hello,

So castopod should be available via ActivityPub but when i try to use the bridgy-fed website it gives me an error. 
Couldn't connect to ......: 400 Bad Request: Couldn't find a representative h-card (http://microformats.org/wiki/representative-hcard-parsing) on .....

**Comment by snarfed** [comment]
Hi! If you want to use Bridgy Fed from the fediverse, you don't need to use the https://fed.brid.gy/ web site, you can follow a site directly from the fediverse: https://fed.brid.gy/docs#fediverse-follow

Otherwise, let me know specifically what you're hoping to do, and I can try to help.

**Comment by qazmlp** [comment]
I think they were trying to use Bridgy Fed (web.brid.gy that is) to bring a Castopod podcast into the Fediverse, but Castopod is ActivityPub-native software and doesn't expose an hCard, so Bridgy isn't necessary and also doesn't work for that.

Maybe it would be helpful to detect an existing AP actor at the URL and direct users to subscribe to it instead, where available.

**Comment by snarfed** [comment]
Ah, good guess! And good suggestion. I guess I'd just point them to https://fed.brid.gy/docs#fediverse-follow

**Comment by snarfed** [comment]
Related to https://github.com/snarfed/bridgy-fed/issues/348 , arguably the same if we expand it a bit.

**Comment by sysadminpower2019** [comment]
my thought was you had to submit the site to have it be 'activated'
for my other site that has AP support, it said if i wanted to use my 'real domain' 
I had to make some DNS changes which in any case didn't it seems

**Comment by snarfed** [comment]
Related to #1025

**Comment by snarfed** [comment]
This may subsume #348?

**Comment by snarfed** [comment]
Yeah I think this is the same as #348.

Specifically, in `Web.get_or_create`, we'd fetch `host-meta`, look for a webfinger endpoint, and fail if it exists.
