### ISSUE TITLE
Broken link on Followers page

### ISSUE THREAD

**Issue by gRegorLove** [snarfed/bridgy-fed#934]
The latest follower on [my page](https://fed.brid.gy/web/gregorlove.com/followers) has a broken link, looks like JSON:

`<a class="follower col-xs-10 col-sm-10 col-lg-6" href="{&#39;displayName&#39;: &#39;Twitter&#39;, &#39;value&#39;: &#39;https://techhub.social/@giflian&#39;}">`

The other follower links appear OK.

**Comment by snarfed** [comment]
Oof, thanks! Will look.

**Comment by snarfed** [comment]
Fixed, thanks for reporting!
