### ISSUE TITLE
ATProto => ActivityPub link previews

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#958]
They're partially making it over, but not all the way. Example [Bluesky post](https://bsky.app/profile/snarfed.bsky.social/post/3kq6zy5it5k2i) and [bridged fediverse post](https://indieweb.social/@snarfed.bsky.social@atproto.brid.gy/112276989431123686).

<img width="619" alt="image" src="https://github.com/snarfed/bridgy-fed/assets/778068/c1d1fb67-873e-46af-8f9e-7a12192023df">

---

Bluesky record, pruned:
```json
{
  "cid" : "bafyreicxnk4ipbjh5g3rikqa3hlmzee4dl3mdgahif7n3aezwdixggsaau",
  "uri" : "at://did:plc:3ljmtyyjqcjee2kpewgsifvb/app.bsky.feed.post/3kq6zy5it5k2i",
  "value" : {
    "$type" : "app.bsky.feed.post",
    "createdAt" : "2024-04-15T19:54:10.898Z",
    "embed" : {
      "$type" : "app.bsky.embed.external",
      "external" : {
        "description" : "",
        "thumb" : {
          "$type" : "blob",
          "mimeType" : "image/jpeg",
          "ref" : {"$link" : "bafkreiemenxtcacg5p4m4ck6iofqgcqyfulhbwq5lsatrwgd4kvvbtxjz4"},
          "size" : 377240
        },
        "title" : "Adeline Software International - Wikipedia",
        "uri" : "https://en.wikipedia.org/wiki/Adeline_Software_International"
      }
    },
    "text" : "and now with a link"
  }
}
```

AS1:
```json
{
  "objectType": "note",
  "id": "at://did:plc:3ljmtyyjqcjee2kpewgsifvb/app.bsky.feed.post/3kq6zy5it5k2i",
  "url": "https://bsky.app/profile/did:plc:3ljmtyyjqcjee2kpewgsifvb/post/3kq6zy5it5k2i",
  "content": "and now with a link",
  "attachments": [{
      "objectType": "link",
      "url": "https://en.wikipedia.org/wiki/Adeline_Software_International",
      "displayName": "Adeline Software International - Wikipedia",
      "image": "https://morel.us-east.host.bsky.network/xrpc/com.atproto.sync.getBlob?did=did:plc:3ljmtyyjqcjee2kpewgsifvb&cid=bafkreiemenxtcacg5p4m4ck6iofqgcqyfulhbwq5lsatrwgd4kvvbtxjz4"
    }]
}
```

AS2:
```json
{
  "type": "Note",
  "id": "https://atproto.brid.gy/convert/ap/at://did:plc:3ljmtyyjqcjee2kpewgsifvb/app.bsky.feed.post/3kq6zy5it5k2i",
  "url": "https://fed.brid.gy/r/https://bsky.app/profile/did:plc:3ljmtyyjqcjee2kpewgsifvb/post/3kq6zy5it5k2i",
  "content": "and now with a link",
  "attachment": [{
      "url": "https://en.wikipedia.org/wiki/Adeline_Software_International",
      "image": "https://morel.us-east.host.bsky.network/xrpc/com.atproto.sync.getBlob?did=did:plc:3ljmtyyjqcjee2kpewgsifvb&cid=bafkreiemenxtcacg5p4m4ck6iofqgcqyfulhbwq5lsatrwgd4kvvbtxjz4",
      "name": "Adeline Software International - Wikipedia"
    }],
  },
}
```

**Comment by qazmlp** [comment]
You'll want to put the image URL in the attachment's `icon` or `icon`.`url` property, according to [this code](https://github.com/mastodon/mastodon/blob/0622107449e72d35b22afeeba2f0ba983e914803/app/lib/activitypub/parser/media_attachment_parser.rb#L24).

**Comment by snarfed** [comment]
I'm actually surprised that fediverse servers, or at least Mastodon, use anything in `attachments` for link previews at all, if it even does? Mastodon famously refetches links itself to generate previews instead of trusting a remote server: https://github.com/mastodon/mastodon/issues/4486 , https://github.com/mastodon/mastodon/issues/23662

**Comment by qazmlp** [comment]
It's an edge case of a fallback, yeah. Mastodon does not *actually* support link attachments outside the `content` at all, but if it receives an attachment that it doesn't support, it will reliably render that as some form of clickable placeholder.
(The app is a little better about telling you what's behind there, in my experience.)

Thinking about it, the semantic intention of `icon` is most likely "file icon" or "favicon".
(I don't know how it renders in practice. I think you can also colour in that rectangle with a [Blurhash](https://docs.joinmastodon.org/spec/activitypub/#blurhash).)

I noticed that Akkoma can apparently show some kind of summary text when it can't show the attachment preview, but I can't read its source code well enough to know how to make use of that.

I think it's fair to say that "links as attachments" just isn't something that's widely supported by Fediverse apps, even if in my opinion it should be, and could be a way to not overwhelm the link destination.

**Comment by qazmlp** [comment]
It breaks very badly in some third-party clients, though:
<details><summary>Elk.zone - tall image</summary>

![image](https://github.com/snarfed/bridgy-fed/assets/17500283/d37192d2-65f7-4111-b4b4-721b787a7b03)

</details> 

I can't even click through there, even though technically the information is provided by Mastodon:
![image](https://github.com/snarfed/bridgy-fed/assets/17500283/935b4d65-44a1-446f-93e3-91b1f8a5ff6b)

**Comment by snarfed** [comment]
> It breaks very badly in some third-party clients, though:

Right, and it breaks in Mastodon itself too, eg the screenshot in the original description here.

The AS2 attachment here was converted automatically by granary from the embed facet in the Bluesky post. I wasn't intentionally trying to generate a link preview in the fediverse; I expected Mastodon and most others to fetch the link and generate the preview themselves, like they usually do.

Regardless, you're right, `type: Link`: should hopefully fix this. 🤞

**Comment by qazmlp** [comment]
> Regardless, you're right, `type: Link` should hopefully fix this. 🤞

Unfortunately not at first, since I don't think anything actually supports that kind of attachment.
It would make it decently easy for Mastodon et al to add support for it, though, as then there'd be a clear intent.

The only way to make links work reliably and render correctly, currently, is to insert them into the post content for (almost all?) fediverse apps, unfortunately, since they follow Twitter's data model in that regard.

**Comment by snarfed** [comment]
Looking at this again, I'm inclined to just remove these attachments altogether and let fediverse servers generate their own link previews, since that's the happier and more common path in the fediverse.

**Comment by snarfed** [comment]
Reopening this, @bnewbold inspired me to try again to see if I can get fedi servers to render link previews that are separate from post text. I never actually tried with `type: Link`. I should!

**Comment by bnewbold** [comment]
to clarify, what i was reporting was that sometimes there is a bsky post with no URL in the text and only a card/embed. In those cases, it feels like the URL from the embed should be appended to the end of the post text (with a `<br>` or two?), so that the link preview will render. Otherwise there is just the post text commenting on the referenced content, but no URL or link preview at all on the AP side.

**Comment by snarfed** [comment]
Right! I get it. I generally try pretty hard to not modify users' original post text at all, so I first plan to try to get the AS2 equivalent of a `Link` attachment without its URL in the post text working. If that doesn't work, I can consider appending the URL to the post text.

**Comment by snarfed** [comment]
Tried again just now with the AS2 below, `type: Link` with `icon`, but no dice, Mastodon still renders it as "Preview not available." It is at least clickable and linked to the `url`, and shows the `name` on hover, but still.

![image](https://github.com/snarfed/bridgy-fed/assets/778068/066accb6-b897-4c58-a97d-cb402f94aa9e)

**Comment by snarfed** [comment]
I went the HTML-link-in-content route. Example: https://indieweb.social/@snarfed.bsky.social@bsky.brid.gy/112645157258479340 . Should be deployed in ~10m.
