### ISSUE TITLE
ActivityPub: do we need to do anything for instances that limit us?

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#972]
When a fediverse instance blocks us, users there can't see the `@bsky.brid.gy@bsky.brid.gy` user, so they can't follow or DM it to opt in. We'll document that in #823.

When a fediverse instance _[limits](https://docs.joinmastodon.org/admin/moderation/#limit-server)_ us, though, like eg social.coop does right now, users there _can_ see and follow/DM `@bsky.brid.gy@bsky.brid.gy`, at least after clicking through a warning.

We should document this too. Otherwise, does everything work ok? Do we need to do anything else?

<img width="575" alt="image" src="https://github.com/snarfed/bridgy-fed/assets/778068/6786cec8-08ed-4491-935e-0e7353f63a0e">

**Comment by qazmlp** [comment]
Users there won't be able to receive the initial DM (I think they may be able to find it after following, but not easily), but they will be able to receive subsequent DMs from that account once following.

I hadn't thought of this. It's necessary to send all service-DMs from the opt-in account in that case, if you want them to go through reliably, if there are any. It would be good to document that users on such instances will only be able to receive service DMs when using the follow-to-opt-in method, not when opting in by sending a DM.

Beyond that, I don't think you really can do much more, as the limits an instance has set aren't reliably detectable from outside. (The moderation list may be hidden or the instance may be invisibly moderated, or the instance may have this same behaviour without implementing the `domain_blocks` API.)

**Comment by snarfed** [comment]
> Users there won't be able to receive the initial DM...but they will be able to receive subsequent DMs from that account once following

Interesting! Do you actually know that for a fact, especially the first part? Any chance you have a link to background or docs or tests people have done? I don't disbelieve you, I just haven't been able to find much, eg https://www.google.com/search?q=Mastodon+server+limit+silence+%22dms%22

**Comment by qazmlp** [comment]
> > Users there won't be able to receive the initial DM...but they will be able to receive subsequent DMs from that account once following
> 
> Interesting! Do you actually know that for a fact, especially the first part? Any chance you have a link to background or docs or tests people have done? I don't disbelieve you, I just haven't been able to find much, eg https://www.google.com/search?q=Mastodon+server+limit+silence+%22dms%22

Hm… actually I'll have to think about where I heard that. But I can check the source code for this, should take just a few minutes now that I know how it's structured.

**Comment by qazmlp** [comment]
Oh interesting, I think they just changed this/are changing this!
https://github.com/mastodon/mastodon/pull/29366

Judging from the source code, "silenced" @-mentions mentions will now appear in this notification request area.

**Comment by qazmlp** [comment]
I should caution that this is definitely app-specific behaviour and there will be some fedi accounts who won't receive DMs at all without following the sender. It may not be a large fraction, but it's common enough to document the possibility, I think.

**Comment by snarfed** [comment]
Mentioned all this in the new doc updates! #823, 0e5be92
