### ISSUE TITLE
Add link to original AP profile to bridge accounts on Bsky

### ISSUE THREAD

**Issue by qazmlp** [snarfed/bridgy-fed#976]
Maybe this is implemented already, in which case it's not working if the bio is so long that it gets cut off.

The bridge may have to truncate the bio itself to make it fit Bsky's constraints, until/unless Bsky raises its display limits for accounts hosted elsewhere.

**Comment by snarfed** [comment]
Yes! Great point. We do this sometimes, in some places, eg see `@genco.me@bsky.brid.gy` on the fediverse, screenshot below, but it's inconsistent. Fortunately, I know why, shouldn't be a difficult fix.

<img width="649" alt="image" src="https://github.com/snarfed/bridgy-fed/assets/778068/2cb92711-ef5f-403b-81d6-e43445e56a05">

**Comment by snarfed** [comment]
First pass at this is done! Still a bit awkward, too much vertical whitespace, and needs links, but it's a start.

<img width="638" alt="image" src="https://github.com/snarfed/bridgy-fed/assets/778068/ab20ee43-9542-43b5-83e6-50e617722f30">

**Comment by snarfed** [comment]
Bluesky profile descriptions don't have facets, so we can't link arbitrary text. I think the best we can do right now is include URLs, and they'll get auto-linked. Sigh. More details: https://github.com/bluesky-social/atproto/discussions/2504

**Comment by snarfed** [comment]
Also the truncation should break at word boundaries. As an example, we cut off a URL in https://bsky.app/profile/did:plc:whco57z2rz6jvi3wv3o56jdi, which is awkward.

**Comment by snarfed** [comment]
OK, I think I'm happy with where this is right now. Examples:

https://bsky.app/profile/snarfed.indieweb.social.ap.brid.gy

> [bridged from [indieweb.social/@snarfed](https://indieweb.social/@snarfed) on the fediverse by [fed.brid.gy](https://fed.brid.gy/) ]

![image](https://github.com/snarfed/bridgy-fed/assets/778068/aabd57cd-e6fe-4a48-9c6b-726734a46e65)

https://indieweb.social/@snarfed.bsky.social@bsky.brid.gy

> [[bridged](https://fed.brid.gy/bsky/snarfed.bsky.social) from [snarfed.bsky.social](https://bsky.app/profile/snarfed.bsky.social) on Bluesky by [Bridgy Fed](https://fed.brid.gy/)]

![image](https://github.com/snarfed/bridgy-fed/assets/778068/ee7bd8e0-32c3-4622-b47f-26b79758649b)

**Comment by snarfed** [comment]
Now to update existing users' profiles. Running this now:

```py
import pages

users = (
  ActivityPub.query(ActivityPub.enabled_protocols == 'atproto',
                    ActivityPub.status == None).fetch()
  + ATProto.query(ATProto.enabled_protocols == 'activitypub',
                  ATProto.status == None).fetch())

logging.getLogger().setLevel(logging.ERROR)

for i, user in enumerate(users):
  print(i, user.key.id(), user.handle)
  pages.update_profile(user, user)
```

**Comment by snarfed** [comment]
Argh, scratch that, I still need to prevent the "bridged from" snippet from getting truncated.

**Comment by snarfed** [comment]
OK, done with that, restarting the backfill now.

**Comment by qazmlp** [comment]
Worked on my profile, thank you!

**Comment by snarfed** [comment]
Done in snarfed/granary@85b9e19b363cd83cc20279593d2fe4ad5b6ac96f. Not going to bother re-backfilling all of those profiles; they'll refresh on their own eventually.
