### ISSUE TITLE
ActivityPub => ATProto hashtags

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#980]
Not working yet. Example: https://indieweb.social/@laurenshof/112359491459258562 => https://bsky.app/profile/laurenshof.indieweb.social.ap.brid.gy/post/3krdoh7rypeb2

**Comment by snarfed** [comment]
AS2:

```
{
  "type": "Create",
  "id": "https://indieweb.social/users/laurenshof/statuses/112359491459258562/activity",
  "actor": "https://indieweb.social/users/laurenshof",
  "published": "2024-04-30T09:36:19Z",
  "object": {
    "type": "Note",
    "id": "https://indieweb.social/users/laurenshof/statuses/112359491459258562",
    "url": "https://indieweb.social/@laurenshof/112359491459258562",
    "published": "2024-04-30T09:36:19Z",
    "attributedTo": "https://indieweb.social/users/laurenshof",
    "content": "<p>test post for <a href=\"https://indieweb.social/tags/atproto\" class=\"mention hashtag\" rel=\"tag\">#<span>atproto</span></a> atproto</p>",
    "attachment": [],
    "tag": [{
      "type": "Hashtag",
      "href": "https://indieweb.social/tags/atproto",
      "name": "#atproto"
    }],
  }
  ...
}
```

...converted to AS1: 
```
{
  "objectType": "activity",
  "verb": "post",
  "id": "https://indieweb.social/users/laurenshof/statuses/112359491459258562/activity",
  "actor": {
    "id": "https://indieweb.social/users/laurenshof",
    ...
  },
  "published": "2024-04-30T09:36:19Z",
  "object": {
    "objectType": "note",
    "id": "https://indieweb.social/users/laurenshof/statuses/112359491459258562",
    "url": "https://indieweb.social/@laurenshof/112359491459258562",
    "author": {"id": "https://indieweb.social/users/laurenshof"}
    "published": "2024-04-30T09:36:19Z",
    "content": "<p>test post for <a href=\"https://indieweb.social/tags/atproto\" class=\"mention hashtag\" rel=\"tag\">#<span>atproto</span></a> atproto</p>",
    "tags": [{
      "href": "https://indieweb.social/tags/atproto",
      "displayName": "#atproto"
    }],
  }
}
```

...converted to ATProto:

```
{
  "$type": "app.bsky.feed.post",
  "createdAt": "2024-04-30T09:36:19.000Z",
  "text": "test post for #atproto atproto"
}
```

**Comment by snarfed** [comment]
Woo, fixed!
- Original: https://indieweb.social/@snarfed/112367193538259739
- Bridged: https://bsky.app/profile/snarfed.indieweb.social.ap.brid.gy/post/3krh3x6wpkkv2

**Comment by austinhuang0131** [comment]
Are you sure it works?

* Original: https://mstdn.party/@austin/112405359754338066
* Bridged: https://bsky.app/profile/austin.mstdn.party.ap.brid.gy/post/3kry2ce73slk2

**Comment by snarfed** [comment]
@austinhuang0131 looks like you're hitting https://github.com/snarfed/bridgy-fed/issues/1010

**Comment by austinhuang0131** [comment]
It *is* in post text though...

```
$ curl https://mstdn.party/users/austin/statuses/112405359754338066 -H "Accept: application/activity+json" | jq
{
  "@context": [
    "https://www.w3.org/ns/activitystreams",
    {
      "ostatus": "http://ostatus.org#",
      "atomUri": "ostatus:atomUri",
      "inReplyToAtomUri": "ostatus:inReplyToAtomUri",
      "conversation": "ostatus:conversation",
      "sensitive": "as:sensitive",
      "toot": "http://joinmastodon.org/ns#",
      "votersCount": "toot:votersCount",
      "blurhash": "toot:blurhash",
      "focalPoint": {
        "@container": "@list",
        "@id": "toot:focalPoint"
      },
      "Hashtag": "as:Hashtag"
    }
  ],
  "id": "https://mstdn.party/users/austin/statuses/112405359754338066",
  "type": "Note",
  "summary": null,
  "inReplyTo": null,
  "published": "2024-05-08T12:01:14Z",
  "url": "https://mstdn.party/@austin/112405359754338066",
  "attributedTo": "https://mstdn.party/users/austin",
  "to": [
    "https://www.w3.org/ns/activitystreams#Public"
  ],
  "cc": [
    "https://mstdn.party/users/austin/followers"
  ],
  "sensitive": false,
  "atomUri": "https://mstdn.party/users/austin/statuses/112405359754338066",
  "inReplyToAtomUri": null,
  "conversation": "tag:mstdn.party,2024-05-08:objectId=132625052:objectType=Conversation",                                                               
  "content": "<p>&quot;Would u like to buy a refurbished computer&quot;</p><p><a href=\"https://mstdn.party/tags/PostIt\" class=\"mention hashtag\" rel= \"tag\">#<span>PostIt</span></a></p>",                                       
  "contentMap": {
    "en": "<p>&quot;Would u like to buy a refurbished computer&quot;</p><p><a href=\"https://mstdn.party/tags/PostIt\" class=\"mention hashtag\" rel=\"t ag\">#<span>PostIt</span></a></p>"                                           
  },
  "attachment": [
    {
      "type": "Document",
      "mediaType": "image/jpeg",
      "url": "https://files.mstdn.party/media_attachments/files/112/392/526/847/942/213/original/e86f7d3a18db9788.jpg",                                  
      "name": "A monkey with a speech bubble is drawn on a post-it placed on a wall. The speech bubble says \"Would u like to buy a refurbished computer \".",                                                                        
      "blurhash": "UDHoE_DhuPVXbEo#VsbbB-w_VZRjxGW=V@oz",
      "width": 2163,
      "height": 3834
    }
  ],
  "tag": [
    {
      "type": "Hashtag",
      "href": "https://mstdn.party/tags/postit",
      "name": "#postit"
    }
  ],
  "replies": {
    "id": "https://mstdn.party/users/austin/statuses/112405359754338066/replies",                                                                       
    "type": "Collection",
    "first": {
      "type": "CollectionPage",
      "next": "https://mstdn.party/users/austin/statuses/112405359754338066/replies?only_other_accounts=true&page=true",                                
      "partOf": "https://mstdn.party/users/austin/statuses/112405359754338066/replies",                                                                 
      "items": []
    }
  }
}
```

**Comment by snarfed** [comment]
Good point!

I haven't looked into this deeply yet. I'll follow up in #1010.

**Comment by snarfed** [comment]
Reopening, these seem to be unreliable. Eg here's one that didn't work: https://mastodon.online/@emarktaylor/112480973885137226 => https://bsky.app/profile/emarktaylor.mastodon.online.ap.brid.gy/post/3kszmvscesxh2

...and here's one with two, one worked, one didn't 🤪: https://mastodon.online/@emarktaylor/112480873556819998 => https://bsky.app/profile/emarktaylor.mastodon.online.ap.brid.gy/post/3kszlfj5l2wf2

**Comment by qazmlp** [comment]
> Reopening, these seem to be unreliable. Eg here's one that didn't work: https://mastodon.online/@emarktaylor/112480973885137226 => https://bsky.app/profile/emarktaylor.mastodon.online.ap.brid.gy/post/3kszmvscesxh2
> 
> ...and here's one with two, one worked, one didn't 🤪: https://mastodon.online/@emarktaylor/112480873556819998 => https://bsky.app/profile/emarktaylor.mastodon.online.ap.brid.gy/post/3kszlfj5l2wf2

I think it's case-sensitivity. Mastodon apparently sends hashtags according to its database rather than the post content.

**Comment by hybridhavoc** [comment]
That's interesting. For testing I made [this post](https://fed.brid.gy/log?path=%2Fqueue%2Fwebmention%2C%2Finbox&start_time=1716389852&key=https%3A%2F%2Fdarkfriend.social%2Fusers%2Fhybridhavoc%2Fstatuses%2F112485324245512138%2Factivity). [Mastodon](https://darkfriend.social/@hybridhavoc/112485324245512138). [Bluesky](https://bsky.app/profile/hybridhavoc.darkfriend.social.ap.brid.gy/post/3kt3kntggbts2).

Neither registered as camel-cased in the JSON, even though the TuneTuesday tag is camel-cased on my Mastodon instance (I updated it myself long ago). 

Made [another post](https://fed.brid.gy/log?path=%2Fqueue%2Fwebmention%2C%2Finbox&start_time=1716390218&key=https%3A%2F%2Fdarkfriend.social%2Fusers%2Fhybridhavoc%2Fstatuses%2F112485348620544910%2Factivity). [Mastodon](https://darkfriend.social/@hybridhavoc/112485348620544910). [Bluesky](https://bsky.app/profile/hybridhavoc.darkfriend.social.ap.brid.gy/post/3kt3kyqq5pfd2).

This time the tunetuesday hashtag looks good, but not the storysong one.

Posted [one final one](https://fed.brid.gy/log?path=%2Fqueue%2Fwebmention%2C%2Finbox&start_time=1716390429&key=https%3A%2F%2Fdarkfriend.social%2Fusers%2Fhybridhavoc%2Fstatuses%2F112485362481453943%2Factivity). [Mastodon](https://darkfriend.social/@hybridhavoc/112485362481453943). [Bluesky](https://bsky.app/profile/hybridhavoc.darkfriend.social.ap.brid.gy/post/3kt3l72f7fsj2).

Does seem like the case sensitive thing is an issue, but it's kinda bothersome that it doesn't necessarily match what is on the OP's server. In the second post I think maybe the presence of the period directly following the storysong hashtag kept it from being processed properly? Just speculation there.

**Comment by TheLastBoyScoutUK** [comment]
Found this issue because I'm having the same issue with hashtags. Looks like it could indeed be case related.

**Working**
https://fed.brid.gy/r/https://bsky.app/profile/did:plc:o66bj7shwur23ic7zpermpiw/post/3kt3hyskm4k24 => https://bsky.app/profile/hallenbeck.thelastboyscout.uk/post/3kt3hyskm4k24

**Not Working**
https://mastodon.social/@hallenbeck/112487404523932742 => https://bsky.app/profile/hallenbeck.mastodon.social.ap.brid.gy/post/3kt4i7hn3dw62

**Comment by snarfed** [comment]
Thanks for the examples, all! Looks like case sensitivity was definitely one root cause here, punctuation on either end of the hashtag in the post text was another, and occasionally hashtags at the beginning or end of the post text was another. I think I've fixed all of those. Example: https://indieweb.social/@snarfed/112554052674489553 => https://bsky.app/profile/snarfed.indieweb.social.ap.brid.gy/post/3ku23dhx4bho2

Sadly AS2 dropped AS1's `startIndex` and `length` from tags, which makes this harder. (Combining `startIndex` and `length` with HTML `content` was also problematic, I get it, but still. 😕) Without those, processing AS2 hashtags requires searching post text for the hashtag string, which will always be a tricky balance between false negatives and false positives, and I don't know that I'll ever get it to 100% perfect. For example, in the example above, the `#g` hashtag didn't make it across because it's terminated by the 🫖 emoji. The AS2 `tag` object is fine, but my regex for searching post text doesn't currently handle emoji termination. Sigh.

That's pretty unusual though, so I'm tentatively marking this as fixed for now. Feel free to reopen or open new issues for other real world problems you all see. And thanks again for all the sleuthing!
