### ISSUE TITLE
ActivityPub => ATProto: handle usernames with _ and ~ chars

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#982]
This is a fun one. First user with an underscore in their username signed up just now, https://me.dm/@punkscience_ns , @punkscience. (Hi Darryl! Sorry for the trouble!)

We translated the fediverse address `@punkscience_ns@me.dm` to the bridged Bluesky handle `punkscience_ns.me.dm.ap.brid.gy` and created the DNS TXT record `_atproto.punkscience_ns.me.dm.ap.brid.gy`, which is serving fine. PLC directory has it in https://web.plc.directory/did/did:plc:di27vbfe6wutukod4g36kovz.

However, [ATProto handles don't allow the underscore character](https://atproto.com/specs/handle). 🤦 (Also see https://github.com/swicg/activitypub-webfinger/issues/9) So, I guess we need to translate underscores to maybe dashes, and hope we don't hit a collision between eg `x_y` and `x-y` on the same instance.

**Comment by snarfed** [comment]
Also need to handle tildes (`~`). Probably even less common, but theoretically possible.

Related: #744, #830

**Comment by snarfed** [comment]
Got another one: https://mastodon.social/users/_dmh , @dmhowcroft. (Sorry Dave!)

**Comment by dmhowcroft** [comment]
Thanks! Looking forward to seeing it resolved :)

**Comment by snarfed** [comment]
And https://darmstadt.social/users/ceol_agus_ol, `did:plc:xry5u23qftlcaysecxbhuv4m`.

**Comment by snarfed** [comment]
https://mastodon.social/users/carb_uncle, `did:plc:oegzpinpvkhf5sv5oj4f7mq7`

**Comment by snarfed** [comment]
Implemented and deployed. Next, fixing these users ^ manually.

**Comment by snarfed** [comment]
Woo, first profile I've seen this work on! https://wetdry.world/@mary_ext => https://bsky.app/profile/mary-ext.wetdry.world.ap.brid.gy

**Comment by qazmlp** [comment]
What happens now if there's a collision? Is the second user not bridged or do they just not get a friendly handle?

**Comment by snarfed** [comment]
They're not bridged.

I honestly couldn't predict if we hit that collision in a week, or a quarter, or five years, or never. I suspect closer to five years. We'll cross that bridge when we come to it.

**Comment by snarfed** [comment]
Need to do a bit more here: ATProto handles can't begin or end with `-`. https://mastodon.gamedev.place/users/_DenisProdan_ and https://warpday.net/users/98ftq556kb (`@hirata_@warpday.net`) failed this.

**Comment by dmhowcroft** [comment]
Is my underscore-initial username bridged to ATP now?

**Comment by snarfed** [comment]
@dmhowcroft sadly no, sorry, and honestly I don't yet have a plan to support usernames that begin or end with underscores or dashes.

**Comment by snarfed** [comment]
OK, I think we're set here. `_` and `~` are converted to `-` except if they're at the beginning or end, where they're not supported, and that's now documented. I've filed #1005 for that.

**Comment by mackuba** [comment]
@snarfed since Mastodon accounts can now assign a custom Bluesky username when bridged, is there a way for a Mastodon account that starts with _ to bridge this way, using a custom username?

**Comment by snarfed** [comment]
@mackuba good idea! The catch is that they'd need to specify their custom domain handle when they initially bridge their account, instead of afterward like right now. Still doable though!

**Comment by snarfed** [comment]
Not a high priority for me personally right now, but it's probably doable by anyone. PRs are always welcome!

**Comment by mackuba** [comment]
> [@mackuba](https://github.com/mackuba) good idea! The catch is that they'd need to specify their custom domain handle when they initially bridge their account, instead of afterward like right now. Still doable though!

Is it possible to do this now with this new bridge settings UI you've launched recently, by any chance?

**Comment by snarfed** [comment]
Hmm! Maybe! Not yet, but you're right that the web UI makes it a bit easier to build.

**Comment by quillmatiq** [comment]
@snarfed maybe we can do this if the user chooses a custom domain on the UI first?

1. user toggles bridging
2. leave alert next to toggle: "not bridging bc [...]. set a custom domain to start bridging"
3. user sets custom domain
4. profit

**Comment by mackuba** [comment]
@anujahooja 🙏🏻
