### ISSUE TITLE
Post with multiple images doesn't bridge all the images

### ISSUE THREAD

**Issue by TomCasavant** [snarfed/bridgy-fed#989]
https://tomkahe.com/@pokemon/112372668561541081
https://bsky.app/profile/pokemon.tomkahe.com.ap.brid.gy/post/3krjjqfvpzjw2

I'll probably un-bridge that account for now because I didn't realize Bluesky doesn't support polls yet, but it looks like it's only sending 1 of the 2 images from the status (this might also be because it's an image and a video so it's not two of the same type of media, I'm not certain)

**Comment by qazmlp** [comment]
Bluesky doesn't support videos / custom GIFs as of yet, it's most likely failing on that currently.

**Comment by snarfed** [comment]
Right! I'll add this to the docs.

**Comment by TomCasavant** [comment]
> @TomCasavant out of curiosity, if the video can't make it over to Bluesky, would you prefer that the post is bridged without it, ie the current behavior? Or that the post isn't bridged at all?

I think personally I'd prefer to bridge the post even if there's media missing, but I could see how that could get confusing for users on both sides of the bridge



Also, this may be worthy of a separate issue. But that same post has hashtags associated with it on the mastodon side, I've got a slightly customized mastodon server that doesn't show hashtags at the end of a post in the text body- I'm not sure if you're parsing those from the ActivityPub tags or from the text itself but they don't appear to be in the bluesky post
