### ISSUE TITLE
Bluesky -> ActivityPub: quote posts are bridged without what they’re quoting

### ISSUE THREAD

**Issue by goeo-** [snarfed/bridgy-fed#991]
Probably best to add a link to what it’s quoting, and if the quoted account is bridged, a same-platform one?

**Comment by snarfed** [comment]
Yup! This is #461, merging in there. I haven't prioritized these at all, but I guess I should eventually.

**Comment by goeo-** [comment]
i thought i had searched the existing issues, my bad :/
