### ISSUE TITLE
Bluesky and AP: URLs bridged are truncated and don't work

### ISSUE THREAD

**Issue by laril** [snarfed/bridgy-fed#993]
All the urls bridged from Bluesky to the Fediverse seem to get truncated, and aren't recognized as urls. 

![image](https://github.com/snarfed/bridgy-fed/assets/1693738/c4f0de02-9f9f-4ea5-bfb8-db8bccdf84d5)

original:
![image](https://github.com/snarfed/bridgy-fed/assets/1693738/2f8ac3e4-5361-43b8-a3a4-dbfbf45a256f)

**Comment by snarfed** [comment]
Yes! True, known issue, sorry for the trouble. This is https://github.com/snarfed/granary/issues/675 . Will fix eventually!

**Comment by snarfed** [comment]
I'm hearing reports that this is true in the other direction too...

**Comment by GrahamDo** [comment]
I'm getting it too (not truncated, in my case, just not clickable).

Here's an example, as requested.

I posted this on Mastodon earlier: https://mastodon.africa/@GrahamDowns/112404608454218580

Here's how it appeared on BS: https://bsky.app/profile/GrahamDowns.mastodon.africa.ap.brid.gy/post/3krxpnthrpsd2

The full URL shows on BS, and it's not clickable.

**Comment by snarfed** [comment]
Fixed! Example: https://indieweb.social/@snarfed/112464466850570968 => https://bsky.app/profile/snarfed.indieweb.social.ap.brid.gy/post/3ksscak7mas62

**Comment by GrahamDo** [comment]
👏👏
