### ISSUE TITLE
Many fediverse servers can't discover @bsky.brid.gy@bsky.brid.gy

### ISSUE THREAD

**Issue by snarfed** [snarfed/bridgy-fed#995]
Getting a few reports of this, Pleroma and Akkoma, not sure what's going on yet. I see the remote instance fetch @bsky.brid.gy@bsky.brid.gy's Webfinger, and BF returns it ok, but then the remote instance never fetches the AP actor id. cc @deadsuperhero , https://sironi.tk/notice/AhUW5sJtgOzkGdRYG0

**Comment by snarfed** [comment]
Interestingly @deadsuperhero says their same Akkoma instance can see @snarfed.org@snarfed.org fine, which is also served by BF. Odd.

**Comment by TomCasavant** [comment]
I don't know if it's related but I was trying to follow the brid.gy account from my postmarks instance and for some reason it was failing to verify my signature. 
I opened an issue with postmarks https://github.com/ckolderup/postmarks/issues/191, since I expect that's where the issue is, but it might be relevant.

**Comment by snarfed** [comment]
@TomCasavant thanks! Different issue, I'll reply there.

**Comment by snarfed** [comment]
Merging #998 in here. Evidently this affects other servers too: Friendica, Hubzilla, micro.blog, Wordpress/Friends. Ugh. 

@manton, @pfefferle, any thoughts here? Details above

**Comment by qazmlp** [comment]
I noticed a few things:

In WebFinger, `acct:bsky.brid.gy@bsky.brid.gy` is aliased to `"https://fed.brid.gy/"`, which doesn't seem right to me since the actors aren't strictly equivalent.

At `https://bsky.brid.gy/bsky.brid.gy`, the `@context` includes `https://w3id.org/security/v1`.
I'm not certain about this, but it may cause some JSON-LD transformers to error out?
https://json-ld.org/playground/ does seem to handle it fine, though.

`https://bsky.brid.gy/bsky.brid.gy/outbox` errors out with `"error":"User bsky.brid.gy not found"`.

(`https://fed.brid.gy/r/https://snarfed.org/` has similar JSON-LD to `https://fed.brid.gy/snarfed.org` but is missing some parts lie the shared inbox? But that's definitely unrelated.)

**Comment by snarfed** [comment]
Thanks for looking! Useful pionts, but I doubt any are the cause here. None of these should be fatal or block fediverse instances from loading and using the actor. [`aliases` in Webfinger just "identify the same entity;"](https://www.rfc-editor.org/rfc/rfc7033#section-4.4.2) they're not necessarily AS2 actors, and afaik fediverse instances generally don't look at aliases at all. And I haven't seen these failing servers fetch the actor at all, or outbox, so I doubt they're hitting the others.

**Comment by qazmlp** [comment]
I found the issue! (for Akkoma)

Akkoma [prefers XRD](https://akkoma.dev/AkkomaGang/akkoma/src/commit/21a81e111165bd29ef953d5e51c682f3dd94dfb4/lib/pleroma/web/web_finger.ex#L202) and [when reading XRD expects strictly `type="application/activity+json"`](https://akkoma.dev/AkkomaGang/akkoma/src/commit/21a81e111165bd29ef953d5e51c682f3dd94dfb4/lib/pleroma/web/web_finger.ex#L113) as opposed to [strictly `type: "application/ld+json; profile=\"https://www.w3.org/ns/activitystreams\""` when reading JSON](https://akkoma.dev/AkkomaGang/akkoma/src/commit/21a81e111165bd29ef953d5e51c682f3dd94dfb4/lib/pleroma/web/web_finger.ex#L134).

Bridgy serves the latter `type` in both cases, so it doesn't find it.

**Comment by snarfed** [comment]
Whoa, awesome sleuthing! And very easy fix. Will do.

**Comment by snarfed** [comment]
I take it back, this is fixable on our end, but not as easily as I thought. And unfortunate because afaict BF isn't doing anything wrong, I don't know that XRD vs JRD should affect the expected type of ActivityPub actor `self` links in Webfinger.

I can still look into making this change. In the meantime, @qazmlp would you mind filing an Akkoma bug?

**Comment by qazmlp** [comment]
> I can still look into making this change. In the meantime, @qazmlp would you mind filing an Akkoma bug?

Sure, though I think it would be entirely valid to have either `type` each for two `rel=self` entries in each representation.

**Comment by qazmlp** [comment]
(The bug is almost certainly upstream in Pleroma… I have to look a bit while software is actively developed right now.)

**Comment by qazmlp** [comment]
> (The bug is almost certainly upstream in Pleroma… I have to look a bit which software is actively developed right now.)

The Pleroma issue tracker at https://git.pleroma.social/pleroma/pleroma/-/issues doesn't allow sign-ups with (at least) Gmail addresses and I don't have a domain on hand under this identity. Looks like I can't file this one without jumping through a lot of hoops 😓

> > Sure, will do, though I think it would be entirely valid to have either `type` each for one of two `rel=self` entries in each representation.
> 
> Oh, good idea! That would definitely be easier on our end.

It may still be good to file it there eventually since the discrepancy is definitely odd.
To me, it feels like it's probably grown behaviour based on what other instances that support XRD/JRD do.

**Comment by snarfed** [comment]
I've added a second `self` link with `application/activity+json`. @qazmlp, @deadsuperhero, mind testing when you get a chance?

**Comment by snarfed** [comment]
Great! Also @manton reports that it's visible in micro.blog now too. Promising!

**Comment by ObjectInSpace** [comment]
I'm on an akkoma server and my bluesky account (which is following ap@brid.gy) wasn't showing up... until just recently. Thanks for that! I still am not seeing actual content in my feeds though. I'll try re-following.

**Comment by snarfed** [comment]
@ObjectInSpace thanks! [BF bridges posts going forward, but not necessarily historical ones.](https://fed.brid.gy/docs#posts-forward)

This post is about whether you can see `@bsky.brid.gy@bsky.brid.gy` from some fediverse servers like Akkoma though. Could you see if that account is visible for you?

**Comment by ObjectInSpace** [comment]
I can search for @bsky.brid.gy@bsky.brid.gy and read the profile and request to follow, but it says that the follow request is pending. The same is true if I search for my bluesky handle on the fediverse side. I'm following ap@brid.gy from bluesky but my fedi handle is not yet findable on bluesky and new content doesn't appear from either direction on either page.

**Comment by snarfed** [comment]
@ObjectInSpace what are your fediverse and bluesky accounts?

**Comment by ObjectInSpace** [comment]
Scratch that, if I go into the profile for my bluesky account from the fediverse side, I can see new posts and can boost them, etc.

**Comment by ObjectInSpace** [comment]
I can see a boost from drew@akkomane.social of my post from prism.bsky.social reposted in my bluesky notifications, as well as a reply I sent from akkoma, and I'm able to follow drew@akkomane.social from there. So it seems like it is just the search that is not working. More worrying is that my reply from prism@bsky.social does not appear on akkomane. Not yet, at least.

**Comment by ObjectInSpace** [comment]
Hm I posted a second post from bluesky and it is not appearing on fed when I pull up the bluesky feed from fedi. Same if I post from fedi and pull up the account from bluesky. Not sure why the first one showed up but the second one hasn't.

**Comment by snarfed** [comment]
Sounds like this may be the [Bluesky polling delay](https://fed.brid.gy/docs#bluesky-delay). We're working on improving this in #978.

**Comment by ObjectInSpace** [comment]
Yeah my bluesky posts did eventually show up fedi-side, they were just delayed. Editting/consolidating comments to be less spammy. My handles are drew@akkomane.social and prism@bsky.social if they are still helpful.

**Comment by snarfed** [comment]
Got a confirmation that Pleroma can now see the bot user too: https://sironi.tk/notice/AhbtQ7x9AqiRF7UoaW . Tentatively closing.
