### ISSUE TITLE
Vivaldi's instance has strange namespace issues

### ISSUE THREAD

**Issue by StarrWulfe** [snarfed/bridgy-fed#996]
My handle `@starrwulfe@social.vivaldi.net` can also be `@starrwulfe@vivaldi.net` due to some strange quirk where Vivialdi has our emails, and shared hosting defaulting to vivaldi.net but somehow the mastodon instance can webfinger and be both?  I dunno. 

The instance itself is at https://social.vivaldi.net. Of course Bridgy already has pegged `https://fed.brid.gy/ap/starrwulfe.vivaldi.net` to a regular web instance that needs to be repeated via RSS. And there's nothing showing under `https://fed.brid.gy/bsky/starrwulfe.**_social_**.vivaldi.net` at all. 

Please investigate as I suspect anyone using Vivaldi's instance won't be able to use the bridge until it's rectified.

**Comment by snarfed** [comment]
Hmm! https://fed.brid.gy/ap/@starrwulfe@social.vivaldi.net is the user page URL you want. Looks ok to me...?

**Comment by StarrWulfe** [comment]
Hmm I didn't see it before, but yep! 

Knowing me I probably typed it wrong the first 11tybillion times. 😅
