### ISSUE TITLE
Missing Bluesky ap.brid.gy follows

### ISSUE THREAD

**Issue by StarrWulfe** [snarfed/bridgy-fed#997]
I followed `@ap.brid.gy` from my bluesky handle `@starrwulfe.xyz` around 6 hours ago and still no show at https://fed.brid.gy/bsky/starrwulfe.xyz. 

- Are there any time outs?
- Is there a way to reset and re-follow?
- Can a confirmation mention/DM be made for those doing a follow so we know the backend is up and ready?

(These also apply to the AP side as well if possible.)

**Comment by robinmaypanpan** [comment]
I'm having the same problem.

**Comment by snarfed** [comment]
Sorry all! I'll look.

**Comment by TheHCJ** [comment]
I am having this issue with @hcj.vibes.cool

**Comment by snarfed** [comment]
Yup, sorry all, there are a number of missing Bluesky accounts that followed ap.brid.gy but haven't been bridged. I'll work on those.

**Comment by snarfed** [comment]
I did a first pass at backfilling all of these missing accounts.

**Comment by StarrWulfe** [comment]
I'm up and running since this time yesterday actually. Feel free to close
whenever it's complete on your end.

**Comment by snarfed** [comment]
Thanks! Spot checked some of the missing accounts here and they're up and running too. Tentatively closing.
