### ISSUE TITLE
AP opt-in can't be found from Friedica, Hubzilla, micro.blog, Akkoma and Wordpress/Friends servers.

### ISSUE THREAD

**Issue by StarrWulfe** [snarfed/bridgy-fed#998]
Just as it says on the title.

Tested with my instances at

- starrwulfe@zotum.net -- Hubzilla
- starrwulfe@abc.starrwulfe,xyz -- micro.blog
- starrwulfe@fe.disroot.org -- Akkoma
- starrwulfe@libranet.de and starrwulfe@opensocial.space -- Friendica

Let me know if there's other ways.

**Comment by snarfed** [comment]
Yeah this is #995. Details there; we don't know what's going on yet. Odd since those instances can see other BF-served users like @snarfed.org@snarfed.org.

**Comment by snarfed** [comment]
Merged into #995.
